--201212/201301报表合并_联营，租赁、招商
SELECT T1.LOCATION 门店编码,
       T1.LOCATION_NAME 门店名称,
       T1.MONTH 月份,
       T1.DEPT 大类,
       SUM(DECODE(零售类型编码,
                  1,
                  销售数量,
                  6,
                  销售数量,
                  11,
                  销售数量,
                  NULL)) 正常销售数量,
       SUM(DECODE(零售类型编码,
                  1,
                  销售金额,
                  6,
                  销售金额,
                  11,
                  销售金额,
                  NULL)) 正常销售金额,
       -----------
       SUM(DECODE(零售类型编码,
                  2,
                  销售数量,
                  3,
                  销售数量,
                  4,
                  销售数量,
                  5,
                  销售数量,
                  8,
                  销售数量,
                  12,
                  销售数量,
                  13,
                  销售数量,
                  15,
                  销售数量,
                  16,
                  销售数量,
                  17,
                  销售数量,
                  19,
                  销售数量,
                  22,
                  销售数量,
                  23,
                  销售数量,
                  24,
                  销售数量,
                  26,
                  销售数量,
                  27,
                  销售数量,
                  28,
                  销售数量,
                  29,
                  销售数量,
                  30,
                  销售数量,
                  31,
                  销售数量,
                  32,
                  销售数量,
                  33,
                  销售数量,
                  34,
                  销售数量,
                  35,
                  销售数量,
                  36,
                  销售数量,
                  38,
                  销售数量,
                  39,
                  销售数量,
                  40,
                  销售数量,
                  NULL)) 促销销售数量,
       SUM(DECODE(零售类型编码,
                  2,
                  销售金额,
                  3,
                  销售金额,
                  4,
                  销售金额,
                  5,
                  销售金额,
                  8,
                  销售金额,
                  12,
                  销售金额,
                  13,
                  销售金额,
                  15,
                  销售金额,
                  16,
                  销售金额,
                  17,
                  销售金额,
                  19,
                  销售金额,
                  22,
                  销售金额,
                  23,
                  销售金额,
                  24,
                  销售金额,
                  26,
                  销售金额,
                  27,
                  销售金额,
                  28,
                  销售金额,
                  29,
                  销售金额,
                  30,
                  销售金额,
                  31,
                  销售金额,
                  32,
                  销售金额,
                  33,
                  销售金额,
                  34,
                  销售金额,
                  35,
                  销售金额,
                  36,
                  销售金额,
                  38,
                  销售金额,
                  39,
                  销售金额,
                  40,
                  销售金额,
                  NULL)) 促销销售金额,
       -----------
       SUM(DECODE(零售类型编码,
                  9,
                  销售数量,
                  21,
                  销售数量,
                  25,
                  销售数量,
                  NULL)) 折价销售数量,
       SUM(DECODE(零售类型编码,
                  9,
                  销售金额,
                  21,
                  销售金额,
                  25,
                  销售金额,
                  NULL)) 折价销售金额,
       -----------
       SUM(DECODE(零售类型编码, 10, 销售数量, NULL)) 大宗销售数量,
       SUM(DECODE(零售类型编码, 10, 销售金额, NULL)) 大宗销售金额,
       -----------
       SUM(DECODE(零售类型编码, 20, 销售数量, NULL)) DM销售数量,
       SUM(DECODE(零售类型编码, 20, 销售金额, NULL)) DM销售金额
  FROM (SELECT TL.INTEGRATION_ID LOCATION,
               TL.ORG_NAME LOCATION_NAME,
               A.MN_WID MONTH,
               PROD.PROD_DP_NUM DEPT,
               R.RETAIL_TYPE_ID 零售类型编码,
               R.RETAIL_TYPE_DESC 零售类型,
               IL.BUSINESS_MODE,
               SUM(A.SLS_QTY) 销售数量,
               SUM(A.SLS_AMT_LCL) 销售金额
          FROM RADM.W_RTL_SLS_IT_LC_MN_A     A,
               RADM.W_INT_ORG_D              ORG,
               RADM.W_INT_ORG_D_TL           TL,
               RADM.BBG_RA_RETAIL_TYPE_D     R,
               RADM.BBG_RA_ITEM_LOC_D        IL,
               RABATCHER.W_PRODUCT_D_RTL_TMP PROD
         WHERE A.ORG_WID = ORG.ROW_WID
           AND ORG.ORG_NUM = TL.INTEGRATION_ID
           AND R.ROW_WID = A.BBG_RETAIL_TYPE_WID
           AND A.BBG_ITEM_LOC_WID = IL.ROW_WID
           AND A.PROD_WID = PROD.PROD_IT_WID
           AND IL.BUSINESS_MODE IN ('LY','ZL','ZS') --经营属性
           AND A.MN_WID IN (201212, 201301)
         GROUP BY TL.INTEGRATION_ID,
                  TL.ORG_NAME,
                  A.MN_WID,
                  PROD.PROD_DP_NUM,
                  R.RETAIL_TYPE_ID,
                  R.RETAIL_TYPE_DESC,
                  IL.BUSINESS_MODE) T1
 GROUP BY T1.LOCATION, T1.LOCATION_NAME, T1.MONTH, T1.DEPT
 ORDER BY T1.LOCATION, T1.MONTH, T1.DEPT;
