--创建RADM.BBG_RA_INV_REF_V取数据
CREATE OR REPLACE VIEW RADM.BBG_RA_INV_REF_V AS
SELECT INV.ITEM,
       INV.ORG_NUM,
       INV.DAY_DT,
       SUM(INV.SUPP_INV_QTY) SUPP_INV_QTY,
       SUM(INV.SUPP_INV_COST) SUPP_INV_COST,
       SUM(INV.SLS_COST_LCL) SLS_COST_LCL
  FROM RADM.BBG_RA_INV_REF INV
 GROUP BY INV.ITEM, INV.ORG_NUM, INV.DAY_DT;
--检查RADM.BBG_RA_INV_REF是否有重复数据
SELECT T.ITEM,T.ORG_NUM,T.DAY_DT,T.SUPPLIER,COUNT(*)
FROM RADM.BBG_RA_INV_REF T GROUP BY T.ITEM,T.ORG_NUM,T.DAY_DT,T.SUPPLIER HAVING COUNT(*)>1;
--修改W_PRODUCT_D_RTL_TMP的SRC_EFF_FROM_DT
UPDATE RABATCHER.W_PRODUCT_D_RTL_TMP P SET P.SRC_EFF_FROM_DT=DATE'2012-01-01';
SELECT * FROM RABATCHER.W_PRODUCT_D_RTL_TMP;
--修改RABATCHER.W_INT_ORG_DH_RTL_TMP的EFFECTIVE_FROM_DT
UPDATE RABATCHER.W_INT_ORG_DH_RTL_TMP O SET O.EFFECTIVE_FROM_DT=DATE'2012-01-01' WHERE O.CURRENT_FLG='Y';
--核对导入数据
--BBG_RA_INV_REF_V
SELECT SUM(T.SUPP_INV_QTY) SUPP_INV_QTY, SUM(T.SUPP_INV_COST) SUPP_INV_COST
  FROM RADM.BBG_RA_INV_REF_V T;
--W_RTL_INV_IT_LC_DY_FS
SELECT SUM(T.INV_SOH_QTY) INV_SOH_QTY,
       SUM(T.INV_SOH_COST_AMT_LCL) INV_SOH_COST_AMT_LCL
  FROM RADM.W_RTL_INV_IT_LC_DY_FS T;
--W_RTL_INV_IT_LC_DY_TMP
SELECT SUM(T.INV_SOH_QTY), SUM(T.INV_SOH_COST_AMT_LCL) INV_SOH_COST_AMT_LCL
  FROM RABATCHER.W_RTL_INV_IT_LC_DY_TMP T;
	
--从RABATCHER.W_RTL_INV_IT_LC_DY_TMP插入RADM.W_RTL_INV_IT_LC_DY_F
SELECT RADM.W_RTL_INV_IT_LC_DY_F_SEQ.NEXTVAL ROW_WID,
       A.PROD_IT_WID PROD_WID,
       A.PROD_SCD1_WID PROD_SCD1_WID,
       A.ORG_WID ORG_WID,
       A.ORG_LC_WID ORG_DH_WID,
       A.ORG_SCD1_WID ORG_SCD1_WID,
       '1' || TO_CHAR(TRUNC(A.DAY_DT, 'MONTH'), 'YYYYMMDD') || '000' FROM_DT_WID,
       '1' || TO_CHAR(TRUNC(LAST_DAY(A.DAY_DT)), 'YYYYMMDD') || '000' TO_DT_WID,
       A.CLEARANCE_FLG CLEARANCE_FLG,
       A.INV_REPL_FLG INV_REPL_FLG,
       A.INV_REPL_METHOD_TYPE INV_REPL_METHOD_TYPE,
       A.INV_REPL_INCREMENT_PCT INV_REPL_INCREMENT_PCT,
       A.INV_SOH_QTY INV_SOH_QTY,
       A.INV_ON_ORD_QTY INV_ON_ORD_QTY,
       A.INV_IN_TRAN_QTY INV_IN_TRAN_QTY,
       A.INV_MAX_SOH_QTY INV_MAX_SOH_QTY,
       A.INV_MIN_SOH_QTY INV_MIN_SOH_QTY,
       A.INV_UNIT_RTL_AMT_LCL INV_UNIT_RTL_AMT_LCL,
       A.INV_SOH_RTL_AMT_LCL INV_SOH_RTL_AMT_LCL,
       A.INV_ON_ORD_RTL_AMT_LCL INV_ON_ORD_RTL_AMT_LCL,
       A.INV_IN_TRAN_RTL_AMT_LCL INV_IN_TRAN_RTL_AMT_LCL,
       A.INV_MAX_SOH_RTL_AMT_LCL INV_MAX_SOH_RTL_AMT_LCL,
       A.INV_MIN_SOH_RTL_AMT_LCL INV_MIN_SOH_RTL_AMT_LCL,
       A.INV_AVG_COST_AMT_LCL INV_AVG_COST_AMT_LCL,
       A.INV_UNIT_COST_AMT_LCL INV_UNIT_COST_AMT_LCL,
       A.INV_SOH_COST_AMT_LCL INV_SOH_COST_AMT_LCL,
       A.INV_ON_ORD_COST_AMT_LCL INV_ON_ORD_COST_AMT_LCL,
       A.INV_IN_TRAN_COST_AMT_LCL INV_IN_TRAN_COST_AMT_LCL,
       A.INV_MAX_SOH_COST_AMT_LCL INV_MAX_SOH_COST_AMT_LCL,
       A.INV_MIN_SOH_COST_AMT_LCL INV_MIN_SOH_COST_AMT_LCL,
       A.DM_RECD_STATUS DM_RECD_STATUS,
       A.DOC_CURR_CODE DOC_CURR_CODE,
       A.LOC_CURR_CODE LOC_CURR_CODE,
       A.LOC_EXCHANGE_RATE LOC_EXCHANGE_RATE,
       A.GLOBAL1_EXCHANGE_RATE GLOBAL1_EXCHANGE_RATE,
       A.GLOBAL2_EXCHANGE_RATE GLOBAL2_EXCHANGE_RATE,
       A.GLOBAL3_EXCHANGE_RATE GLOBAL3_EXCHANGE_RATE,
       A.CREATED_BY_ID CREATED_BY_ID,
       A.CHANGED_BY_ID CHANGED_BY_ID,
       A.CREATED_ON_DT CREATED_ON_DT,
       A.CHANGED_ON_DT CHANGED_ON_DT,
       A.AUX1_CHANGED_ON_DT AUX1_CHANGED_ON_DT,
       A.AUX2_CHANGED_ON_DT AUX2_CHANGED_ON_DT,
       A.AUX3_CHANGED_ON_DT AUX3_CHANGED_ON_DT,
       A.AUX4_CHANGED_ON_DT AUX4_CHANGED_ON_DT,
       A.DELETE_FLG DELETE_FLG,
       SYSDATE W_INSERT_DT,
       SYSDATE W_UPDATE_DT,
       A.DATASOURCE_NUM_ID DATASOURCE_NUM_ID,
       A.ETL_THREAD_VAL ETL_THREAD_VAL,
       A.ETL_THREAD_VAL ETL_THREAD_VAL,
       A.PROD_IT_NUM || '~' || A.ORG_NUM || '~' ||
       TO_CHAR(A.DAY_DT, 'DD-MON-YY', 'NLS_DATE_LANGUAGE=American') INTEGRATION_ID,
       A.TENANT_ID TENANT_ID,
       A.X_CUSTOM X_CUSTOM,
       A.BBG_ITEM_LOC_WID BBG_ITEM_LOC_WID,
       A.BBG_REFERENCE_DO1 BBG_REFERENCE_DO1,
       A.BBG_REFERENCE_DO2 BBG_REFERENCE_DO2,
       A.BBG_REFERENCE_DO3 BBG_REFERENCE_DO3,
       A.BBG_REFERENCE_DO4 BBG_REFERENCE_DO4,
       A.BBG_REFERENCE_DO5 BBG_REFERENCE_DO5,
       A.BBG_REFERENCE_FO1 BBG_REFERENCE_FO1,
       A.BBG_REFERENCE_FO2 BBG_REFERENCE_FO2,
       A.BBG_REFERENCE_FO3 BBG_REFERENCE_FO3,
       A.BBG_REFERENCE_FO4 BBG_REFERENCE_FO4,
       A.BBG_REFERENCE_FO5 BBG_REFERENCE_FO5,
       A.BBG_REFERENCE_FO6 BBG_REFERENCE_FO6,
       A.BBG_REFERENCE_FO7 BBG_REFERENCE_FO7,
       A.BBG_REFERENCE_FO8 BBG_REFERENCE_FO8,
       A.BBG_REFERENCE_FO9 BBG_REFERENCE_FO9,
       A.BBG_REFERENCE_FO10 BBG_REFERENCE_FO10
  FROM RABATCHER.W_RTL_INV_IT_LC_DY_TMP A;
	
SELECT * FROM RABATCHER.W_RTL_INV_IT_LC_DY_TMP T WHERE T.ORG_WID=32 AND T.PROD_IT_WID=274777;
SELECT * FROM RADM.W_RTL_INV_IT_LC_DY_F;
select t.day_dt,trunc(t.day_dt, 'month'),TRUNC(LAST_DAY(T.DAY_DT)) from RABATCHER.W_RTL_INV_IT_LC_DY_TMP T;
	
--在BBG_RA_INV_REF中，但是RMS.ITEM_LOC没记录。原因，因为关联了RMS.ITEM_LOC.CLEAR_IND(是否清仓)，而目前没有使用
SELECT *
  FROM RADM.BBG_RA_INV_REF_V V
 WHERE NOT EXISTS (SELECT 1
          FROM RADM.W_RTL_INV_IT_LC_DY_FS F
         WHERE V.ITEM = F.PROD_IT_NUM
           AND V.ORG_NUM = F.ORG_NUM
           AND V.DAY_DT = F.DAY_DT);
--not in RABATCHER.W_RTL_INV_IT_LC_DY_TMP
SELECT *
  FROM RADM.BBG_RA_INV_REF_V V
 WHERE NOT EXISTS (SELECT 1
          FROM RABATCHER.W_RTL_INV_IT_LC_DY_TMP F
         WHERE V.ITEM = F.PROD_IT_NUM
           AND V.ORG_NUM = F.ORG_NUM
           AND V.DAY_DT = F.DAY_DT);

SELECT T.ITEM,T.ORG_NUM,T.DAY_DT,COUNT(*)
FROM RADM.BBG_RA_INV_REF T GROUP BY T.ITEM,T.ORG_NUM,T.DAY_DT HAVING COUNT(*)>1;

SELECT * FROM RADM.BBG_RA_INV_REF T WHERE T.ITEM=800000002 AND T.ORG_NUM=120022 AND T.DAY_DT=DATE'2013-05-01' /*AND T.SUPPLIER=37000187*/;
--
SELECT * FROM RADM.BBG_RA_INV_REF_V T WHERE T.ITEM=800000148 AND T.ORG_NUM=118011;
SELECT * FROM RADM.W_RTL_INV_IT_LC_DY_FS T WHERE T.PROD_IT_NUM=800000148 AND T.ORG_NUM=118011;
SELECT * FROM RABATCHER.W_RTL_INV_IT_LC_DY_TMP T WHERE T.PROD_IT_NUM=800000148 AND T.ORG_NUM=118011;
SELECT * FROM RADM.BBG_RA_ITEM_LOC_D T WHERE T.ITEM=800261235 AND T.LOC=120027;
SELECT * FROM RABATCHER.W_PRODUCT_D_RTL_TMP T WHERE T.PROD_IT_NUM='800261235';

SELECT DISTINCT T.ETL_THREAD_VAL FROM RADM.W_RTL_INV_IT_LC_DY_FS T;

SELECT *
  FROM ALL_ALL_TABLES T
 WHERE T.owner = 'RADM'
   AND T.table_name LIKE '%INV%';
W_RTL_INV_IT_LC_DY_F;
W_RTL_INV_IT_LC_DY_FS;
BBG_RA_SUPP_INV_IT_LC_DY_F;
W_RTL_INV_IT_LC_MN_AVG2_FV;
BBG_RA_INV_OUT_IT_LC_DY_F;


--每日库存EOH数量
select distinct 0 as c1, D1.c2 as c2, D1.c1 as c3, D1.c3 as c4
  from (select sum(T959964.INV_SOH_QTY) as c1,
               TRUNC(T960506.MCAL_DAY_DT) as c2,
               T960506.ROW_WID as c3
          from W_MCAL_DAY_DV         T960506 /* Dim_W_MCAL_DAY_D_Retail_Gregorian_Calendar */,
               W_RTL_INV_SC_DY_CUR_A T959964 /* Fact_W_RTL_INV_SC_DY_CUR_A */
         where (T959964.DT_WID = T960506.ROW_WID and
               T960506.MCAL_CAL_WID = 1.0 and '2010' < T960506.CAL_YEAR and
               TRUNC(T960506.MCAL_DAY_DT) between
               TO_DATE('2014-04-01', 'YYYY-MM-DD') and
               TO_DATE('2014-04-22', 'YYYY-MM-DD'))
         group by T960506.ROW_WID, TRUNC(T960506.MCAL_DAY_DT)) D1
 order by c2;

--一个商品每日EOH数量
select distinct 0 as c1, D1.c2 as c2, D1.c1 as c3, D1.c3 as c4
  from (select sum(T966082.INV_SOH_QTY) as c1,
               TRUNC(T960506.MCAL_DAY_DT) as c2,
               T960506.ROW_WID as c3
          from W_MCAL_DAY_DV T960506 /* Dim_W_MCAL_DAY_D_Retail_Gregorian_Calendar */,
               (SELECT T.*
                  FROM W_PRODUCT_D T, W_PRODUCT_ATTR_D A
                 WHERE T.SCD1_WID = A.SCD1_WID
                   AND A.PRODUCT_ATTR12_NAME = A.PRODUCT_ATTR11_NAME) T14449,
               W_RTL_INV_IT_DY_A T966082 /* Fact_W_RTL_INV_IT_DY_A */
         where (T14449.ROW_WID = T966082.PROD_WID and
               T14449.PROD_NUM = '800187952' and
               T960506.ROW_WID = T966082.DT_WID and
               T960506.MCAL_CAL_WID = 1.0 and '2010' < T960506.CAL_YEAR and
               TRUNC(T960506.MCAL_DAY_DT) between
               TO_DATE('2014-04-01', 'YYYY-MM-DD') and
               TO_DATE('2014-04-22', 'YYYY-MM-DD'))
         group by T960506.ROW_WID, TRUNC(T960506.MCAL_DAY_DT)) D1
 order by c2;

--一个商品一个地点每日EOH数量
select distinct 0 as c1, D1.c2 as c2, D1.c1 as c3, D1.c3 as c4
  from (select sum(T963640.INV_SOH_QTY) as c1,
               TRUNC(T960506.MCAL_DAY_DT) as c2,
               T960506.ROW_WID as c3
          from W_INT_ORG_DH T964333 /* Dim_W_INT_ORG_DH_Retail_As_Was */,
               W_INT_ORG_D T964463 /* Dim_W_INT_ORG_D_Retail_As_Was */,
               W_MCAL_DAY_DV T960506 /* Dim_W_MCAL_DAY_D_Retail_Gregorian_Calendar */,
               (SELECT T.*
                  FROM W_PRODUCT_D T, W_PRODUCT_ATTR_D A
                 WHERE T.SCD1_WID = A.SCD1_WID
                   AND A.PRODUCT_ATTR12_NAME = A.PRODUCT_ATTR11_NAME) T14449,
               W_RTL_INV_IT_LC_DY_FV T963640 /* Fact_W_RTL_INV_IT_LC_DY_F */
         where (T963640.ORG_DH_WID = T964333.ROW_WID and
               T960506.ROW_WID = T963640.DT_WID and
               T14449.ROW_WID = T963640.PROD_WID and
               T14449.PROD_NUM = '800187952' and T960506.MCAL_CAL_WID = 1.0 and
               T963640.ORG_WID = T964463.ROW_WID and
               T964333.SCD1_WID = T964463.SCD1_WID and
               cast(T964463.ORG_NUM as INTEGER) = 120033 and
               '2010' < T960506.CAL_YEAR and
               TRUNC(T960506.MCAL_DAY_DT) between
               TO_DATE('2014-04-01', 'YYYY-MM-DD') and
               TO_DATE('2014-04-22', 'YYYY-MM-DD'))
         group by T960506.ROW_WID, TRUNC(T960506.MCAL_DAY_DT)) D1
 order by c2;
 
 SELECT * FROM RADM.W_RTL_INV_IT_LC_DY_F T WHERE T.PROD_WID=301934 AND T.ORG_WID=44;
 SELECT * FROM RADM.W_PRODUCT_D T WHERE T.PROD_NUM='800187952';
 SELECT * FROM RADM.W_INT_ORG_D T WHERE T.ORG_NUM='120033';
