SELECT * FROM TABLE_CHECK_DIMENSION

TRUNCATE TABLE TABLE_CHECK_DIMENSION

SELECT * FROM TABLE_CHECK_FACT

CREATE TABLE TABLE_CHECK_FACT (RUN_DATE DATE,TABLE_NAME VARCHAR2(60),T_COUNT INT,SUM1 INT,SUM2 INT,SUM3 INT,SUM4 INT)


DECLARE
  JOBNO NUMBER;
BEGIN
  DBMS_JOB.SUBMIT (JOB => JOBNO,
                   WHAT => 'CHECK_FACT;',
                   NEXT_DATE =>SYSDATE,
                   INTERVAL => 'SYSDATE+1');
  COMMIT;
END;


SELECT * FROM ALL_JOBS;
