--1.
CREATE OR REPLACE VIEW RADM.BBG_RA_ITEM_LOC_D_CHECK AS
SELECT U.ROW_WID,
       U.ITEM,
       U.LOC,
       U.EFFECTIVE_FROM_DT,
       U.EFFECTIVE_TO_DT,
       NVL(U.LAG_EFFECTIVE_FROM_DT, U.EFFECTIVE_FROM_DT) LAG_EFFECTIVE_FROM_DT,
       NVL(U.LEAD_EFFECTIVE_TO_DT, U.EFFECTIVE_TO_DT) LEAD_EFFECTIVE_TO_DT,
       U.CURRENT_FLG
  FROM (SELECT T.ROW_WID,
               T.ITEM,
               T.LOC,
               T.EFFECTIVE_FROM_DT,
               T.EFFECTIVE_TO_DT,
               TO_DATE(LAG(TO_NUMBER(TO_CHAR(T.EFFECTIVE_TO_DT, 'YYYYMMDD')))
                       OVER(PARTITION BY T.ITEM, T.LOC ORDER BY T.EFFECTIVE_FROM_DT,T.ROW_WID),
                       'YYYYMMDD') + 1 LAG_EFFECTIVE_FROM_DT,
               TO_DATE(LEAD(TO_NUMBER(TO_CHAR(T.EFFECTIVE_FROM_DT,
                                              'YYYYMMDD')))
                       OVER(PARTITION BY T.ITEM, T.LOC ORDER BY T.EFFECTIVE_FROM_DT,T.ROW_WID),
                       'YYYYMMDD') - 1 LEAD_EFFECTIVE_TO_DT,
               T.CURRENT_FLG
          FROM RADM.BBG_RA_ITEM_LOC_D T
         WHERE 1 = 1) U
 WHERE 1 = 1
 ORDER BY U.ITEM, U.LOC, U.EFFECTIVE_FROM_DT,U.ROW_WID;

--2.
DROP TABLE RADM.BBG_RA_ITEM_LOC_D_DT_TMP;
CREATE TABLE RADM.BBG_RA_ITEM_LOC_D_DT_TMP AS
SELECT *
  FROM RADM.BBG_RA_ITEM_LOC_D_CHECK T
 WHERE T.EFFECTIVE_TO_DT <> T.LEAD_EFFECTIVE_TO_DT;

--3.按EFFECTIVE_TO_DT排序，第一条的EFFECTIVE_FROM_DT如果大于EFFECTIVE_TO_DT，则修改成EFFECTIVE_TO_DT - 1
UPDATE RADM.BBG_RA_ITEM_LOC_D A
   SET A.EFFECTIVE_FROM_DT = A.EFFECTIVE_TO_DT - 1
 WHERE EXISTS (SELECT 1
          FROM (SELECT *
                  FROM (SELECT T.ROW_WID,
                               T.ITEM,
                               T.LOC,
                               T.EFFECTIVE_FROM_DT,
                               T.EFFECTIVE_TO_DT,
                               RANK() OVER(PARTITION BY T.ITEM, T.LOC ORDER BY T.EFFECTIVE_TO_DT) RO
                          FROM RADM.BBG_RA_ITEM_LOC_D T
                         WHERE LENGTH(T.ITEM) = 13) U
                 WHERE U.RO = 1
                   AND U.EFFECTIVE_TO_DT < U.EFFECTIVE_FROM_DT) B
         WHERE A.ROW_WID = B.ROW_WID);

--4.
SELECT B.ITEM, B.LOC, B.EFFECTIVE_FROM_DT, COUNT(1)
  FROM (SELECT A.ITEM, A.LOC, A.EFFECTIVE_FROM_DT
          FROM RADM.BBG_RA_ITEM_LOC_D A) B
 GROUP BY B.ITEM, B.LOC, B.EFFECTIVE_FROM_DT
HAVING COUNT(1) > 1;

--5.按照EFFECTIVE_FROM_DT排序，如果日期有相同的，则修改一条。
UPDATE RADM.BBG_RA_ITEM_LOC_D B
   SET B.EFFECTIVE_FROM_DT =
       (SELECT D.NEW_EFFECTIVE_FROM_DT
          FROM (SELECT A.ROW_WID,
                       A.ITEM,
                       A.LOC,
                       A.EFFECTIVE_FROM_DT,
                       A.EFFECTIVE_TO_DT,
                       LEAD(A.EFFECTIVE_FROM_DT) OVER(PARTITION BY A.ITEM, A.LOC ORDER BY A.EFFECTIVE_FROM_DT, A.ROW_WID) NEXT_EFFECTIVE_FROM_DT,
                       A.EFFECTIVE_FROM_DT - 1 NEW_EFFECTIVE_FROM_DT,
                       A.CURRENT_FLG
                  FROM RADM.BBG_RA_ITEM_LOC_D A
                 WHERE A.ITEM = '2400072022511'
                 ORDER BY A.LOC, A.EFFECTIVE_FROM_DT, A.ROW_WID) D
         WHERE B.ROW_WID = D.ROW_WID
           AND B.EFFECTIVE_FROM_DT = D.NEXT_EFFECTIVE_FROM_DT)
 WHERE LENGTH(B.ITEM) = 13
   AND B.CURRENT_FLG <> 'Y'
   AND EXISTS
 (SELECT 1
          FROM (SELECT A.ROW_WID,
                       A.ITEM,
                       A.LOC,
                       A.EFFECTIVE_FROM_DT,
                       A.EFFECTIVE_TO_DT,
                       LEAD(A.EFFECTIVE_FROM_DT) OVER(PARTITION BY A.ITEM, A.LOC ORDER BY A.EFFECTIVE_FROM_DT, A.ROW_WID) NEXT_EFFECTIVE_FROM_DT,
                       A.EFFECTIVE_FROM_DT - 1 NEW_EFFECTIVE_FROM_DT,
                       A.CURRENT_FLG
                  FROM RADM.BBG_RA_ITEM_LOC_D A
                 WHERE A.ITEM = '2400072022511'
                 ORDER BY A.LOC, A.EFFECTIVE_FROM_DT, A.ROW_WID) C
         WHERE B.ROW_WID = C.ROW_WID
           AND B.EFFECTIVE_FROM_DT = C.NEXT_EFFECTIVE_FROM_DT);

--6.
UPDATE RADM.BBG_RA_ITEM_LOC_D A
   SET A.EFFECTIVE_TO_DT =
       (SELECT C.LEAD_EFFECTIVE_TO_DT FROM RADM.BBG_RA_ITEM_LOC_D_DT_TMP C
         WHERE A.ROW_WID = C.ROW_WID
           AND A.EFFECTIVE_TO_DT <> C.LEAD_EFFECTIVE_TO_DT
					 AND C.CURRENT_FLG='N')
 WHERE A.CURRENT_FLG = 'N'
   AND EXISTS
 (SELECT 1
          FROM RADM.BBG_RA_ITEM_LOC_D_DT_TMP B
         WHERE A.ROW_WID = B.ROW_WID
           AND A.EFFECTIVE_TO_DT <> B.LEAD_EFFECTIVE_TO_DT
					 AND B.CURRENT_FLG='N');

--7.





--TMP
SELECT * FROM RADM.BBG_RA_ITEM_LOC_D_DT_TMP T WHERE T.CURRENT_FLG='Y' ORDER BY T.ITEM,T.LOC,T.ROW_WID;
/*
2400070071761 
2400071025470 
2400072013671 
2400072021852 
2400072021889 
2400072021932 
2400072022510 
2400072022511 
*/

SELECT A.ROW_WID,
       A.ITEM,
       A.LOC,
       A.EFFECTIVE_FROM_DT,
       A.EFFECTIVE_TO_DT,
       A.CURRENT_FLG
  FROM RADM.BBG_RA_ITEM_LOC_D A
 WHERE A.ITEM = '2400072012983'
 AND A.LOC=130032
 ORDER BY A.ROW_WID FOR UPDATE;

SELECT A.ROW_WID,
       A.ITEM,
       A.LOC,
       A.EFFECTIVE_FROM_DT,
       A.EFFECTIVE_TO_DT,
       LEAD(A.EFFECTIVE_FROM_DT) OVER(PARTITION BY A.ITEM, A.LOC ORDER BY A.EFFECTIVE_FROM_DT, A.ROW_WID) NEXT_EFFECTIVE_FROM_DT,
       A.EFFECTIVE_FROM_DT - 1 NEW_EFFECTIVE_FROM_DT,
       A.CURRENT_FLG
  FROM RADM.BBG_RA_ITEM_LOC_D A
 WHERE A.ITEM = '2400071025470'
 ORDER BY A.LOC,A.EFFECTIVE_FROM_DT,A.ROW_WID;




SELECT B.ITEM, B.LOC, B.EFFECTIVE_FROM_DT, COUNT(1)
  FROM (SELECT A.ITEM, A.LOC, A.EFFECTIVE_FROM_DT
          FROM RADM.BBG_RA_ITEM_LOC_D A) B
 GROUP BY B.ITEM, B.LOC, B.EFFECTIVE_FROM_DT
HAVING COUNT(1) > 1;

SELECT DISTINCT C.ITEM
  FROM (SELECT B.ITEM, B.LOC, B.EFFECTIVE_FROM_DT, COUNT(1)
          FROM (SELECT A.ITEM, A.LOC, A.EFFECTIVE_FROM_DT
                  FROM RADM.BBG_RA_ITEM_LOC_D A) B
         GROUP BY B.ITEM, B.LOC, B.EFFECTIVE_FROM_DT
        HAVING COUNT(1) > 1) C;


SELECT A.ROW_WID,
       A.ITEM,
       A.LOC,
       A.EFFECTIVE_FROM_DT,
       A.EFFECTIVE_TO_DT,
       A.CURRENT_FLG,
       LEAD(A.EFFECTIVE_FROM_DT) OVER(PARTITION BY A.ITEM, A.LOC ORDER BY A.ROW_WID) NEXT_EFFECTIVE_FROM_DT,
       LEAD(A.EFFECTIVE_FROM_DT) OVER(PARTITION BY A.ITEM, A.LOC ORDER BY A.ROW_WID) - 1 NEW_EFFECTIVE_FROM_DT
  FROM RADM.BBG_RA_ITEM_LOC_D A
 WHERE A.ITEM = '2400072021852'
   AND A.LOC = '139065'
	 ORDER BY A.ROW_WID;

select * from BBG_RA_ITEM_LOC_D_DT_TMP t;
SELECT *
  FROM RADM.BBG_RA_ITEM_LOC_D T
 WHERE T.ITEM = '2400070071761'
   AND T.LOC = '120015'
 ORDER BY T.EFFECTIVE_FROM_DT, T.ROW_WID;

SELECT *
  FROM RADM.BBG_RA_ITEM_LOC_D_CHECK T
 WHERE T.EFFECTIVE_TO_DT <> T.LEAD_EFFECTIVE_TO_DT;
 
 SELECT COUNT(1)
  FROM RADM.BBG_RA_ITEM_LOC_D_CHECK T
 WHERE T.EFFECTIVE_TO_DT <> T.LEAD_EFFECTIVE_TO_DT;

SELECT * FROM RADM.BBG_RA_ITEM_LOC_D_EFF_FROM T WHERE LENGTH(T.ITEM)=13;
SELECT * FROM RADM.BBG_RA_ITEM_LOC_D_EFF_FROM T WHERE T.ITEM='2400071010028' AND T.LOC='130004';
SELECT * FROM RADM.BBG_RA_ITEM_LOC_D T WHERE T.ITEM='2400071010028' AND T.LOC='130004' ORDER BY T.EFFECTIVE_FROM_DT;
--14402757
SELECT *
  FROM RADM.BBG_RA_ITEM_LOC_D_CHECK T
 WHERE T.EFFECTIVE_FROM_DT <> T.LAG_EFFECTIVE_FROM_DT
    OR T.EFFECTIVE_TO_DT <> T.LEAD_EFFECTIVE_TO_DT;

SELECT T.EFFECTIVE_FROM_DT,
       TO_NUMBER(TO_CHAR(T.EFFECTIVE_FROM_DT, 'YYYYMMDD')),
       TO_NUMBER(TO_CHAR(T.EFFECTIVE_TO_DT, 'YYYYMMDD'))
  FROM RADM.BBG_RA_ITEM_LOC_D T;

SELECT T.ITEM, T.LOC, COUNT(1)
  FROM RADM.BBG_RA_ITEM_LOC_D T
 GROUP BY T.ITEM, T.LOC
 ORDER BY 3 DESC;


SELECT U.ROW_WID,
       U.ITEM,
       U.LOC,
       U.EFFECTIVE_FROM_DT,
       U.EFFECTIVE_TO_DT,
       NVL(U.LAG_EFFECTIVE_FROM_DT, U.EFFECTIVE_FROM_DT) LAG_EFFECTIVE_FROM_DT,
       NVL(U.LEAD_EFFECTIVE_TO_DT, U.EFFECTIVE_TO_DT) LEAD_EFFECTIVE_TO_DT,
       U.CURRENT_FLG,
       U.RO
  FROM (SELECT T.ROW_WID,
               T.ITEM,
               T.LOC,
               T.EFFECTIVE_FROM_DT,
               T.EFFECTIVE_TO_DT,
               TO_DATE(LAG(TO_NUMBER(TO_CHAR(T.EFFECTIVE_TO_DT, 'YYYYMMDD')))
                       OVER(PARTITION BY T.ITEM, T.LOC ORDER BY T.ROW_WID),
                       'YYYYMMDD') + 1 LAG_EFFECTIVE_FROM_DT,
               TO_DATE(LEAD(TO_NUMBER(TO_CHAR(T.EFFECTIVE_FROM_DT,
                                              'YYYYMMDD')))
                       OVER(PARTITION BY T.ITEM, T.LOC ORDER BY T.ROW_WID),
                       'YYYYMMDD') - 1 LEAD_EFFECTIVE_TO_DT,
               T.CURRENT_FLG,
               RANK() OVER(PARTITION BY T.ITEM, T.LOC ORDER BY T.ROW_WID) RO
          FROM RADM.BBG_RA_ITEM_LOC_D T
         WHERE T.ITEM = 800034931
           AND T.LOC = 120030
         ORDER BY T.ITEM, T.LOC, T.ROW_WID) U
 WHERE 1 = 1;
