--1.add etl_thread_val(number(10)) column on W_RTL_PRICE_IT_LC_DY_F
select * from W_RTL_PRICE_IT_LC_DY_F;

--1.1.update etl_thread_val
ALTER TABLE RADM.W_RTL_PRICE_IT_LC_DY_F NOLOGGING;
ALTER SESSION ENABLE PARALLEL DML;
UPDATE /*+PARALLEL(16)*/ RADM.W_RTL_PRICE_IT_LC_DY_F T
   SET T.ETL_THREAD_VAL = SUBSTR(T.INTEGRATION_ID,
                                 INSTR(T.INTEGRATION_ID, '~', 1, 2) - 1,
                                 1)
 WHERE T.ETL_THREAD_VAL IS NULL;
COMMIT;
ALTER TABLE RADM.W_RTL_PRICE_IT_LC_DY_F LOGGING;
ALTER SESSION DISABLE PARALLEL DML;

--2.test sql
UPDATE RADM.W_RTL_PRICE_IT_LC_DY_F T
   SET (T.ORG_DH_WID, T.BBG_REFERENCE_FO10, T.TO_DT_WID, T.W_UPDATE_DT) =
       (SELECT S.ORG_DH_WID,
               S.BBG_REFERENCE_FO10,
               S.TO_DT_WID,
               S.W_UPDATE_DT
          FROM (SELECT W_RTL_PRICE_IT_LC_DY_TMP.PROD_IT_WID PROD_WID,
                       W_RTL_PRICE_IT_LC_DY_TMP.ORG_WID ORG_WID,
                       W_RTL_PRICE_IT_LC_DY_TMP.ORG_LC_WID ORG_DH_WID,
                       W_RTL_PRICE_IT_LC_DY_TMP.DT_WID FROM_DT_WID,
                       TO_NUMBER('120161102000') TO_DT_WID,
                       SYSDATE W_UPDATE_DT,
                       W_RTL_PRICE_IT_LC_DY_TMP.BBG_REFERENCE_FO10 BBG_REFERENCE_FO10
                  FROM RABATCHER.W_RTL_PRICE_IT_LC_DY_TMP W_RTL_PRICE_IT_LC_DY_TMP
                 WHERE (1 = 1)
                   AND (W_RTL_PRICE_IT_LC_DY_TMP.ETL_THREAD_VAL = 1)) S
         WHERE (1 = 1)
           AND T.PROD_WID = S.PROD_WID
           AND T.ORG_WID = S.ORG_WID
           AND S.FROM_DT_WID > T.FROM_DT_WID
           AND T.TO_DT_WID = TO_NUMBER('999999999999999'))
 WHERE (PROD_WID, ORG_WID) IN
       (SELECT PROD_WID, ORG_WID
          FROM (SELECT W_RTL_PRICE_IT_LC_DY_TMP.PROD_IT_WID PROD_WID,
                       W_RTL_PRICE_IT_LC_DY_TMP.ORG_WID ORG_WID,
                       W_RTL_PRICE_IT_LC_DY_TMP.ORG_LC_WID ORG_DH_WID,
                       W_RTL_PRICE_IT_LC_DY_TMP.DT_WID FROM_DT_WID,
                       TO_NUMBER('120161102000') TO_DT_WID,
                       SYSDATE W_UPDATE_DT,
                       W_RTL_PRICE_IT_LC_DY_TMP.BBG_REFERENCE_FO10 BBG_REFERENCE_FO10
                  FROM RABATCHER.W_RTL_PRICE_IT_LC_DY_TMP W_RTL_PRICE_IT_LC_DY_TMP
                 WHERE (1 = 1)
                   AND (W_RTL_PRICE_IT_LC_DY_TMP.ETL_THREAD_VAL = 1)) S
         WHERE (1 = 1)
           AND T.PROD_WID = S.PROD_WID
           AND T.ORG_WID = S.ORG_WID
           AND S.FROM_DT_WID > T.FROM_DT_WID
           AND T.TO_DT_WID = TO_NUMBER('999999999999999'))
   AND T.ETL_THREAD_VAL = 1
   AND T.TO_DT_WID = TO_NUMBER('999999999999999');

--3.
W_RTL_PRICE_IT_LC_DY_FV
--4.

--5.

--6.

select * from W_RTL_PRICE_IT_LC_DY_F t WHERE T.FROM_DT_WID = 120161102000;
SELECT DISTINCT T.ORG_NUM, T.ETL_THREAD_VAL
  FROM RABATCHER.W_RTL_PRICE_IT_LC_DY_TMP T
 ORDER BY 2, 1;
