CREATE OR REPLACE PACKAGE BBG_RA2CSMB_PACKAGE AS

  FUNCTION F_BBG_RA2CSMB(O_ERROR_MESSAGE IN OUT VARCHAR2) RETURN BOOLEAN;

END BBG_RA2CSMB_PACKAGE;
/
CREATE OR REPLACE PACKAGE BODY BBG_RA2CSMB_PACKAGE AS

  FUNCTION F_BBG_RA2CSMB(O_ERROR_MESSAGE IN OUT VARCHAR2) RETURN BOOLEAN IS
  BEGIN
    BEGIN
      BBG_RA2CSMB();
    END;
    RETURN TRUE;
  EXCEPTION
    WHEN OTHERS THEN
      O_ERROR_MESSAGE := SQLERRM;
      RETURN FALSE;
  END;

END;
/
