--每日移出移入内存清单表BBG_RA_INMEMORY_LIST
INSERT INTO RADM.BBG_RA_INMEMORY_LIST
  SELECT T.table_name
    FROM ALL_ALL_TABLES T
   WHERE T.owner = 'RADM'
     /*AND (T.table_name LIKE 'W_RTL_SLS%A' OR
         T.table_name LIKE 'BBG_RA_SLS%A')*/
     AND T.inmemory = 'ENABLED'
     AND T.num_rows > 0
     AND NOT EXISTS (SELECT 1
            FROM RADM.BBG_RA_INMEMORY_LIST L
           WHERE T.table_name = L.TABLE_NAME)
   ORDER BY T.table_name;

--NOINMEMORY
SELECT 'execute immediate ''ALTER TABLE RADM.' || L.TABLE_NAME ||
       ' NO INMEMORY'';'
  FROM RADM.BBG_RA_INMEMORY_LIST L
 ORDER BY L.TABLE_NAME;

--INMEMORY
SELECT 'execute immediate ''ALTER TABLE RADM.' || L.TABLE_NAME ||
       ' INMEMORY PRIORITY CRITICAL MEMCOMPRESS FOR CAPACITY HIGH'';'
  FROM RADM.BBG_RA_INMEMORY_LIST L
 ORDER BY L.TABLE_NAME;
