SELECT *
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F T
 WHERE T.DT_WID = 120130508000;
SELECT *
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F T
 WHERE T.DT_WID = 120130507000;
 
SELECT DISTINCT T.BBG_REFERENCE_FO10 FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F T;
/*16张表
 W_RTL_SLS_CL_DY_CUR_A
 W_RTL_SLS_CL_LC_DY_A
 W_RTL_SLS_CL_LC_DY_CUR_A
 W_RTL_SLS_DP_DY_CUR_A
 W_RTL_SLS_DP_LC_DY_A
 W_RTL_SLS_DP_LC_DY_CUR_A
 W_RTL_SLS_IT_DY_A
 W_RTL_SLS_IT_DY_SN_A
 W_RTL_SLS_IT_LC_DY_A
 W_RTL_SLS_IT_LC_DY_SN_A
 W_RTL_SLS_LC_DY_A
 W_RTL_SLS_SC_DY_A
 W_RTL_SLS_SC_DY_CUR_A
 W_RTL_SLS_SC_LC_DY_A
 W_RTL_SLS_SC_LC_DY_CUR_A
 W_RTL_SLS_TRX_IT_LC_DY_F
 */
 
--update all table
CREATE OR REPLACE PROCEDURE JIN_UPDATE_SLS_PROFIT_AMT_LCL(DTWID IN INT) AS
BEGIN
  UPDATE RADM.W_RTL_SLS_CL_DY_CUR_A T
     SET T.SLS_PROFIT_AMT_LCL = T.SLS_PROFIT_AMT_LCL + T.RET_PROFIT_AMT_LCL,
         T.BBG_REFERENCE_FO10 = T.SLS_PROFIT_AMT_LCL,
         T.W_UPDATE_DT        = SYSDATE
   WHERE T.DT_WID = DTWID
     AND T.BBG_REFERENCE_FO10 IS NULL;
  COMMIT;
  UPDATE RADM.W_RTL_SLS_CL_LC_DY_A T
     SET T.SLS_PROFIT_AMT_LCL = T.SLS_PROFIT_AMT_LCL + T.RET_PROFIT_AMT_LCL,
         T.BBG_REFERENCE_FO10 = T.SLS_PROFIT_AMT_LCL,
         T.W_UPDATE_DT        = SYSDATE
   WHERE T.DT_WID = DTWID
     AND T.BBG_REFERENCE_FO10 IS NULL;
  COMMIT;
  UPDATE RADM.W_RTL_SLS_CL_LC_DY_CUR_A T
     SET T.SLS_PROFIT_AMT_LCL = T.SLS_PROFIT_AMT_LCL + T.RET_PROFIT_AMT_LCL,
         T.BBG_REFERENCE_FO10 = T.SLS_PROFIT_AMT_LCL,
         T.W_UPDATE_DT        = SYSDATE
   WHERE T.DT_WID = DTWID
     AND T.BBG_REFERENCE_FO10 IS NULL;
  COMMIT;
  UPDATE RADM.W_RTL_SLS_DP_DY_CUR_A T
     SET T.SLS_PROFIT_AMT_LCL = T.SLS_PROFIT_AMT_LCL + T.RET_PROFIT_AMT_LCL,
         T.BBG_REFERENCE_FO10 = T.SLS_PROFIT_AMT_LCL,
         T.W_UPDATE_DT        = SYSDATE
   WHERE T.DT_WID = DTWID
     AND T.BBG_REFERENCE_FO10 IS NULL;
  COMMIT;
  UPDATE RADM.W_RTL_SLS_DP_LC_DY_A T
     SET T.SLS_PROFIT_AMT_LCL = T.SLS_PROFIT_AMT_LCL + T.RET_PROFIT_AMT_LCL,
         T.BBG_REFERENCE_FO10 = T.SLS_PROFIT_AMT_LCL,
         T.W_UPDATE_DT        = SYSDATE
   WHERE T.DT_WID = DTWID
     AND T.BBG_REFERENCE_FO10 IS NULL;
  COMMIT;
  UPDATE RADM.W_RTL_SLS_DP_LC_DY_CUR_A T
     SET T.SLS_PROFIT_AMT_LCL = T.SLS_PROFIT_AMT_LCL + T.RET_PROFIT_AMT_LCL,
         T.BBG_REFERENCE_FO10 = T.SLS_PROFIT_AMT_LCL,
         T.W_UPDATE_DT        = SYSDATE
   WHERE T.DT_WID = DTWID
     AND T.BBG_REFERENCE_FO10 IS NULL;
  COMMIT;
  UPDATE RADM.W_RTL_SLS_IT_DY_A T
     SET T.SLS_PROFIT_AMT_LCL = T.SLS_PROFIT_AMT_LCL + T.RET_PROFIT_AMT_LCL,
         T.BBG_REFERENCE_FO10 = T.SLS_PROFIT_AMT_LCL,
         T.W_UPDATE_DT        = SYSDATE
   WHERE T.DT_WID = DTWID
     AND T.BBG_REFERENCE_FO10 IS NULL;
  UPDATE RADM.W_RTL_SLS_IT_DY_SN_A T
     SET T.SLS_PROFIT_AMT_LCL = T.SLS_PROFIT_AMT_LCL + T.RET_PROFIT_AMT_LCL,
         T.BBG_REFERENCE_FO10 = T.SLS_PROFIT_AMT_LCL,
         T.W_UPDATE_DT        = SYSDATE
   WHERE T.DT_WID = DTWID
     AND T.BBG_REFERENCE_FO10 IS NULL;
  COMMIT;
  UPDATE RADM.W_RTL_SLS_IT_LC_DY_A T
     SET T.SLS_PROFIT_AMT_LCL = T.SLS_PROFIT_AMT_LCL + T.RET_PROFIT_AMT_LCL,
         T.BBG_REFERENCE_FO10 = T.SLS_PROFIT_AMT_LCL,
         T.W_UPDATE_DT        = SYSDATE
   WHERE T.DT_WID = DTWID
     AND T.BBG_REFERENCE_FO10 IS NULL;
  COMMIT;
  UPDATE RADM.W_RTL_SLS_IT_LC_DY_SN_A T
     SET T.SLS_PROFIT_AMT_LCL = T.SLS_PROFIT_AMT_LCL + T.RET_PROFIT_AMT_LCL,
         T.BBG_REFERENCE_FO10 = T.SLS_PROFIT_AMT_LCL,
         T.W_UPDATE_DT        = SYSDATE
   WHERE T.DT_WID = DTWID
     AND T.BBG_REFERENCE_FO10 IS NULL;
  COMMIT;
  UPDATE RADM.W_RTL_SLS_LC_DY_A T
     SET T.SLS_PROFIT_AMT_LCL = T.SLS_PROFIT_AMT_LCL + T.RET_PROFIT_AMT_LCL,
         T.BBG_REFERENCE_FO10 = T.SLS_PROFIT_AMT_LCL,
         T.W_UPDATE_DT        = SYSDATE
   WHERE T.DT_WID = DTWID
     AND T.BBG_REFERENCE_FO10 IS NULL;
  COMMIT;
  UPDATE RADM.W_RTL_SLS_SC_DY_A T
     SET T.SLS_PROFIT_AMT_LCL = T.SLS_PROFIT_AMT_LCL + T.RET_PROFIT_AMT_LCL,
         T.BBG_REFERENCE_FO10 = T.SLS_PROFIT_AMT_LCL,
         T.W_UPDATE_DT        = SYSDATE
   WHERE T.DT_WID = DTWID;
  COMMIT;
  UPDATE RADM.W_RTL_SLS_SC_DY_CUR_A T
     SET T.SLS_PROFIT_AMT_LCL = T.SLS_PROFIT_AMT_LCL + T.RET_PROFIT_AMT_LCL,
         T.BBG_REFERENCE_FO10 = T.SLS_PROFIT_AMT_LCL,
         T.W_UPDATE_DT        = SYSDATE
   WHERE T.DT_WID = DTWID
     AND T.BBG_REFERENCE_FO10 IS NULL;
  COMMIT;
  UPDATE RADM.W_RTL_SLS_SC_LC_DY_A T
     SET T.SLS_PROFIT_AMT_LCL = T.SLS_PROFIT_AMT_LCL + T.RET_PROFIT_AMT_LCL,
         T.BBG_REFERENCE_FO10 = T.SLS_PROFIT_AMT_LCL,
         T.W_UPDATE_DT        = SYSDATE
   WHERE T.DT_WID = DTWID
     AND T.BBG_REFERENCE_FO10 IS NULL;
  COMMIT;
  UPDATE RADM.W_RTL_SLS_SC_LC_DY_CUR_A T
     SET T.SLS_PROFIT_AMT_LCL = T.SLS_PROFIT_AMT_LCL + T.RET_PROFIT_AMT_LCL,
         T.BBG_REFERENCE_FO10 = T.SLS_PROFIT_AMT_LCL,
         T.W_UPDATE_DT        = SYSDATE
   WHERE T.DT_WID = DTWID
     AND T.BBG_REFERENCE_FO10 IS NULL;
  COMMIT;
  UPDATE RADM.W_RTL_SLS_TRX_IT_LC_DY_F T
     SET T.SLS_PROFIT_AMT_LCL = T.SLS_PROFIT_AMT_LCL + T.RET_PROFIT_AMT_LCL,
         T.BBG_REFERENCE_FO10 = T.SLS_PROFIT_AMT_LCL,
         T.W_UPDATE_DT        = SYSDATE
   WHERE T.DT_WID = DTWID
     AND T.BBG_REFERENCE_FO10 IS NULL;
  COMMIT;
END;


--调用JIN_UPDATE_SLS_PROFIT_AMT_CLC
CREATE OR REPLACE PROCEDURE RADM.JIN_UPDATE_MONTH AS
BEGIN
  begin
    -- Call the procedure
    jin_update_sls_profit_amt_lcl(dtwid => 120130501000);
  end;
  begin
    -- Call the procedure
    jin_update_sls_profit_amt_lcl(dtwid => 120130502000);
  end;
  begin
    -- Call the procedure
    jin_update_sls_profit_amt_lcl(dtwid => 120130503000);
  end;
	  begin
    -- Call the procedure
    jin_update_sls_profit_amt_lcl(dtwid => 120130504000);
  end;
	  begin
    -- Call the procedure
    jin_update_sls_profit_amt_lcl(dtwid => 120130505000);
  end;
	  begin
    -- Call the procedure
    jin_update_sls_profit_amt_lcl(dtwid => 120130506000);
  end;
	  begin
    -- Call the procedure
    jin_update_sls_profit_amt_lcl(dtwid => 120130507000);
  end;
END;


--参数名和列名一样，全表被更新，修复回来。。。。
/*
 W_RTL_SLS_CL_DY_CUR_A
 W_RTL_SLS_CL_LC_DY_A
 W_RTL_SLS_CL_LC_DY_CUR_A
 W_RTL_SLS_DP_DY_CUR_A
 W_RTL_SLS_DP_LC_DY_A
 W_RTL_SLS_DP_LC_DY_CUR_A
 W_RTL_SLS_IT_DY_A
 W_RTL_SLS_IT_DY_SN_A
 W_RTL_SLS_IT_LC_DY_A
 W_RTL_SLS_IT_LC_DY_SN_A
 W_RTL_SLS_LC_DY_A
 W_RTL_SLS_SC_DY_A
 W_RTL_SLS_SC_DY_CUR_A
 W_RTL_SLS_SC_LC_DY_A
 W_RTL_SLS_SC_LC_DY_CUR_A
 W_RTL_SLS_TRX_IT_LC_DY_F
 */
SELECT COUNT(*) FROM RADM.W_RTL_SLS_CL_DY_CUR_A T WHERE T.BBG_REFERENCE_FO10 IS NOT NULL;





