--2016.3.23日执行时间：3597秒
--插入记录数：1673085条
insert into RABATCHER.W_RTL_NPROF_IT_LC_DY_TMP T
  (ORG_WID,
   ORG_LC_WID,
   ORG_DS_WID,
   ORG_RG_WID,
   ORG_AR_WID,
   ORG_CH_WID,
   ORG_NUM,
   ORG_DS_NUM,
   ORG_RG_NUM,
   ORG_AR_NUM,
   ORG_CH_NUM,
   ORG_SCD1_WID,
   DT_WID,
   DAY_DT,
   WK_WID,
   WK_NUM,
   PR_WID,
   PR_NUM,
   QT_WID,
   QT_NUM,
   SUPPLIER_WID,
   SUPPLIER_NUM,
   PROD_WID,
   PROD_SCD1_WID,
   PROD_SC_WID,
   PROD_CL_WID,
   PROD_DP_WID,
   PROD_GP_WID,
   PROD_DV_WID,
   PROD_IT_NUM,
   PROD_SC_NUM,
   PROD_CL_NUM,
   PROD_DP_NUM,
   PROD_GP_NUM,
   PROD_DV_NUM,
   BASE_PROF_AMT_LCL,
   NET_PROF_AMT_LCL,
   NET_NET_PROF_AMT_LCL,
   DEAD_NET_PROF_AMT_LCL,
   DM_RECD_STATUS,
   DOC_CURR_CODE,
   LOC_CURR_CODE,
   LOC_EXCHANGE_RATE,
   GLOBAL1_EXCHANGE_RATE,
   GLOBAL2_EXCHANGE_RATE,
   GLOBAL3_EXCHANGE_RATE,
   CREATED_BY_ID,
   CHANGED_BY_ID,
   CREATED_ON_DT,
   CHANGED_ON_DT,
   AUX1_CHANGED_ON_DT,
   AUX2_CHANGED_ON_DT,
   AUX3_CHANGED_ON_DT,
   AUX4_CHANGED_ON_DT,
   DELETE_FLG,
   DATASOURCE_NUM_ID,
   TENANT_ID,
   X_CUSTOM,
   BBG_ITEM_LOC_WID,
   BBG_ITEM_LOC_SUPP_WID,
   BBG_REFERENCE_DO1,
   BBG_REFERENCE_DO2,
   BBG_REFERENCE_DO3,
   BBG_REFERENCE_DO4,
   BBG_REFERENCE_DO5,
   BBG_REFERENCE_FO1,
   BBG_REFERENCE_FO3,
   BBG_REFERENCE_FO4,
   BBG_REFERENCE_FO5,
   BBG_REFERENCE_FO6,
   BBG_REFERENCE_FO7,
   BBG_REFERENCE_FO8,
   BBG_REFERENCE_FO9,
   BBG_REFERENCE_FO10
   
   )
  select W_INT_ORG_D_RTL_TMP.ORG_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_LC_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_DS_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_RG_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_AR_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_CH_WID,
         W_INT_ORG_D_RTL_TMP.ORG_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_DS_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_RG_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_AR_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_CH_NUM,
         W_INT_ORG_D_RTL_TMP.ORG_SCD1_WID,
         W_MCAL_DAY_D.ROW_WID,
         W_MCAL_DAY_D.MCAL_DAY_DT,
         W_MCAL_WEEK_D.ROW_WID,
         W_MCAL_WEEK_D.MCAL_YEAR || W_MCAL_WEEK_D.MCAL_WEEK,
         W_MCAL_DAY_D.MCAL_PERIOD_WID,
         W_MCAL_DAY_D.MCAL_YEAR || W_MCAL_DAY_D.MCAL_PERIOD,
         W_MCAL_DAY_D.MCAL_QTR_WID,
         W_MCAL_DAY_D.MCAL_YEAR || W_MCAL_DAY_D.MCAL_QTR,
         W_PARTY_ORG_D.ROW_WID,
         W_PARTY_ORG_D.SUPPLIER_NUM,
         W_RTL_NCOST_IT_LC_DY_F.PROD_WID,
         W_PRODUCT_D_RTL_TMP.PROD_SCD1_WID,
         W_PRODUCT_D_RTL_TMP.PROD_SC_WID,
         W_PRODUCT_D_RTL_TMP.PROD_CL_WID,
         W_PRODUCT_D_RTL_TMP.PROD_DP_WID,
         W_PRODUCT_D_RTL_TMP.PROD_GP_WID,
         W_PRODUCT_D_RTL_TMP.PROD_DV_WID,
         W_PRODUCT_D_RTL_TMP.PROD_IT_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_SC_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_CL_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_DP_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_GP_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_DV_NUM,
         sum(W_RTL_SLS_TRX_IT_LC_DY_TMP.SLS_AMT_LCL -
             nvl(W_RTL_SLS_TRX_IT_LC_DY_TMP.SLS_TAX_AMT_LCL, 0) -
             W_RTL_NCOST_IT_LC_DY_F.BASE_COST_AMT_LCL *
             W_RTL_SLS_TRX_IT_LC_DY_TMP.SLS_QTY),
         sum(W_RTL_SLS_TRX_IT_LC_DY_TMP.SLS_AMT_LCL -
             nvl(W_RTL_SLS_TRX_IT_LC_DY_TMP.SLS_TAX_AMT_LCL, 0) -
             W_RTL_NCOST_IT_LC_DY_F.NET_COST_AMT_LCL *
             W_RTL_SLS_TRX_IT_LC_DY_TMP.SLS_QTY),
         sum(W_RTL_SLS_TRX_IT_LC_DY_TMP.SLS_AMT_LCL -
             nvl(W_RTL_SLS_TRX_IT_LC_DY_TMP.SLS_TAX_AMT_LCL, 0) -
             W_RTL_NCOST_IT_LC_DY_F.NET_NET_COST_AMT_LCL *
             W_RTL_SLS_TRX_IT_LC_DY_TMP.SLS_QTY),
         sum(W_RTL_SLS_TRX_IT_LC_DY_TMP.SLS_AMT_LCL -
             nvl(W_RTL_SLS_TRX_IT_LC_DY_TMP.SLS_TAX_AMT_LCL, 0) -
             W_RTL_NCOST_IT_LC_DY_F.DEAD_NET_COST_AMT_LCL *
             W_RTL_SLS_TRX_IT_LC_DY_TMP.SLS_QTY),
         W_RTL_NCOST_IT_LC_DY_F.DM_RECD_STATUS,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.DOC_CURR_CODE,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.LOC_CURR_CODE,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.LOC_EXCHANGE_RATE,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.GLOBAL1_EXCHANGE_RATE,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.GLOBAL2_EXCHANGE_RATE,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.GLOBAL3_EXCHANGE_RATE,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.CREATED_BY_ID,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.CHANGED_BY_ID,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.CREATED_ON_DT,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.CHANGED_ON_DT,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.AUX1_CHANGED_ON_DT,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.AUX2_CHANGED_ON_DT,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.AUX3_CHANGED_ON_DT,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.AUX4_CHANGED_ON_DT,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.DELETE_FLG,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.DATASOURCE_NUM_ID,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.TENANT_ID,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.X_CUSTOM,
         W_RTL_NCOST_IT_LC_DY_F.BBG_ITEM_LOC_WID,
         W_RTL_NCOST_IT_LC_DY_F.BBG_ITEM_LOC_SUPP_WID,
         W_RTL_NCOST_IT_LC_DY_F.BBG_REFERENCE_DO1,
         W_RTL_NCOST_IT_LC_DY_F.BBG_REFERENCE_DO2,
         W_RTL_NCOST_IT_LC_DY_F.BBG_REFERENCE_DO3,
         W_RTL_NCOST_IT_LC_DY_F.BBG_REFERENCE_DO4,
         W_RTL_NCOST_IT_LC_DY_F.BBG_REFERENCE_DO5,
         SUM(W_RTL_SLS_TRX_IT_LC_DY_TMP.SLS_AMT_LCL -
             nvl(W_RTL_SLS_TRX_IT_LC_DY_TMP.SLS_TAX_AMT_LCL, 0) -
             W_RTL_NCOST_IT_LC_DY_F.BBG_REFERENCE_FO1 *
             W_RTL_SLS_TRX_IT_LC_DY_TMP.SLS_QTY),
         W_RTL_SLS_TRX_IT_LC_DY_TMP.BBG_REFERENCE_FO3,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.BBG_REFERENCE_FO4,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.BBG_REFERENCE_FO5,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.BBG_REFERENCE_FO6,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.BBG_REFERENCE_FO7,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.BBG_REFERENCE_FO8,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.BBG_REFERENCE_FO9,
         W_RTL_SLS_TRX_IT_LC_DY_TMP.BBG_REFERENCE_FO10
  
    from RABATCHER.W_INT_ORG_D_RTL_TMP        W_INT_ORG_D_RTL_TMP,
         RABATCHER.W_PRODUCT_D_RTL_TMP        W_PRODUCT_D_RTL_TMP,
         RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP W_RTL_SLS_TRX_IT_LC_DY_TMP,
         RADM.W_RTL_NCOST_IT_LC_DY_F          W_RTL_NCOST_IT_LC_DY_F,
         RADM.W_MCAL_DAY_D                    W_MCAL_DAY_D,
         RADM.W_MCAL_CONTEXT_G                W_MCAL_CONTEXT_G,
         RADM.W_MCAL_WEEK_D                   W_MCAL_WEEK_D,
         RADM.W_PARTY_ORG_D                   W_PARTY_ORG_D,
         RABATCHER.W_INT_ORG_DH_RTL_TMP       W_INT_ORG_DH_RTL_TMP
   where (1 = 1)
     And (W_MCAL_DAY_D.MCAL_DAY_DT BETWEEN
         W_INT_ORG_D_RTL_TMP.EFFECTIVE_FROM_DT AND
         W_INT_ORG_D_RTL_TMP.EFFECTIVE_TO_DT)
     AND (W_RTL_SLS_TRX_IT_LC_DY_TMP.ORG_WID = W_INT_ORG_D_RTL_TMP.ORG_WID)
     AND ((W_RTL_NCOST_IT_LC_DY_F.ORG_WID =
         W_RTL_SLS_TRX_IT_LC_DY_TMP.ORG_WID) AND
         (W_RTL_SLS_TRX_IT_LC_DY_TMP.PROD_IT_WID =
         W_RTL_NCOST_IT_LC_DY_F.PROD_WID))
     AND (W_PRODUCT_D_RTL_TMP.PROD_IT_NUM =
         W_RTL_SLS_TRX_IT_LC_DY_TMP.PROD_IT_NUM)
     AND (W_RTL_NCOST_IT_LC_DY_F.FROM_DT_WID = W_MCAL_DAY_D.ROW_WID)
     AND (W_MCAL_DAY_D.MCAL_DAY_DT BETWEEN
         W_PRODUCT_D_RTL_TMP.SRC_EFF_FROM_DT AND
         W_PRODUCT_D_RTL_TMP.SRC_EFF_TO_DT)
     AND (W_MCAL_DAY_D.MCAL_DAY_DT BETWEEN W_MCAL_WEEK_D.MCAL_WEEK_START_DT AND
         W_MCAL_WEEK_D.MCAL_WEEK_END_DT)
     AND (W_MCAL_CONTEXT_G.DATASOURCE_NUM_ID =
         W_RTL_NCOST_IT_LC_DY_F.DATASOURCE_NUM_ID)
     AND (W_MCAL_CONTEXT_G.MCAL_CAL_WID = W_MCAL_DAY_D.MCAL_CAL_WID)
     AND (W_MCAL_DAY_D.MCAL_DAY_DT BETWEEN W_PARTY_ORG_D.EFFECTIVE_FROM_DT AND
         W_PARTY_ORG_D.EFFECTIVE_TO_DT)
     AND (W_PARTY_ORG_D.ROW_WID = W_RTL_NCOST_IT_LC_DY_F.SUPPLIER_WID)
     AND (W_MCAL_DAY_D.MCAL_DAY_DT BETWEEN
         W_INT_ORG_DH_RTL_TMP.EFFECTIVE_FROM_DT AND
         W_INT_ORG_DH_RTL_TMP.EFFECTIVE_TO_DT)
     AND (W_RTL_SLS_TRX_IT_LC_DY_TMP.ORG_LC_WID =
         W_INT_ORG_DH_RTL_TMP.ORG_LC_WID)
     And (W_MCAL_CONTEXT_G.ORG_ID = '1')
     And (W_MCAL_CONTEXT_G.CALENDAR_ID = 'Retail Calendar~41')
     And (W_PARTY_ORG_D.SUPPLIER_FLG = 'Y')
   Group By W_INT_ORG_D_RTL_TMP.ORG_WID,
            W_INT_ORG_DH_RTL_TMP.ORG_LC_WID,
            W_INT_ORG_DH_RTL_TMP.ORG_DS_WID,
            W_INT_ORG_DH_RTL_TMP.ORG_RG_WID,
            W_INT_ORG_DH_RTL_TMP.ORG_AR_WID,
            W_INT_ORG_DH_RTL_TMP.ORG_CH_WID,
            W_INT_ORG_D_RTL_TMP.ORG_NUM,
            W_INT_ORG_DH_RTL_TMP.ORG_DS_NUM,
            W_INT_ORG_DH_RTL_TMP.ORG_RG_NUM,
            W_INT_ORG_DH_RTL_TMP.ORG_AR_NUM,
            W_INT_ORG_DH_RTL_TMP.ORG_CH_NUM,
            W_INT_ORG_D_RTL_TMP.ORG_SCD1_WID,
            W_MCAL_DAY_D.ROW_WID,
            W_MCAL_DAY_D.MCAL_DAY_DT,
            W_MCAL_WEEK_D.ROW_WID,
            W_MCAL_WEEK_D.MCAL_YEAR || W_MCAL_WEEK_D.MCAL_WEEK,
            W_MCAL_DAY_D.MCAL_PERIOD_WID,
            W_MCAL_DAY_D.MCAL_YEAR || W_MCAL_DAY_D.MCAL_PERIOD,
            W_MCAL_DAY_D.MCAL_QTR_WID,
            W_MCAL_DAY_D.MCAL_YEAR || W_MCAL_DAY_D.MCAL_QTR,
            W_PARTY_ORG_D.ROW_WID,
            W_PARTY_ORG_D.SUPPLIER_NUM,
            W_RTL_NCOST_IT_LC_DY_F.PROD_WID,
            W_PRODUCT_D_RTL_TMP.PROD_SCD1_WID,
            W_PRODUCT_D_RTL_TMP.PROD_SC_WID,
            W_PRODUCT_D_RTL_TMP.PROD_CL_WID,
            W_PRODUCT_D_RTL_TMP.PROD_DP_WID,
            W_PRODUCT_D_RTL_TMP.PROD_GP_WID,
            W_PRODUCT_D_RTL_TMP.PROD_DV_WID,
            W_PRODUCT_D_RTL_TMP.PROD_IT_NUM,
            W_PRODUCT_D_RTL_TMP.PROD_SC_NUM,
            W_PRODUCT_D_RTL_TMP.PROD_CL_NUM,
            W_PRODUCT_D_RTL_TMP.PROD_DP_NUM,
            W_PRODUCT_D_RTL_TMP.PROD_GP_NUM,
            W_PRODUCT_D_RTL_TMP.PROD_DV_NUM,
            W_RTL_NCOST_IT_LC_DY_F.DM_RECD_STATUS,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.DOC_CURR_CODE,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.LOC_CURR_CODE,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.LOC_EXCHANGE_RATE,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.GLOBAL1_EXCHANGE_RATE,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.GLOBAL2_EXCHANGE_RATE,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.GLOBAL3_EXCHANGE_RATE,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.CREATED_BY_ID,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.CHANGED_BY_ID,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.CREATED_ON_DT,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.CHANGED_ON_DT,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.AUX1_CHANGED_ON_DT,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.AUX2_CHANGED_ON_DT,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.AUX3_CHANGED_ON_DT,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.AUX4_CHANGED_ON_DT,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.DELETE_FLG,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.DATASOURCE_NUM_ID,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.TENANT_ID,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.X_CUSTOM,
            W_RTL_NCOST_IT_LC_DY_F.BBG_ITEM_LOC_WID,
            W_RTL_NCOST_IT_LC_DY_F.BBG_ITEM_LOC_SUPP_WID,
            W_RTL_NCOST_IT_LC_DY_F.BBG_REFERENCE_DO1,
            W_RTL_NCOST_IT_LC_DY_F.BBG_REFERENCE_DO2,
            W_RTL_NCOST_IT_LC_DY_F.BBG_REFERENCE_DO3,
            W_RTL_NCOST_IT_LC_DY_F.BBG_REFERENCE_DO4,
            W_RTL_NCOST_IT_LC_DY_F.BBG_REFERENCE_DO5,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.BBG_REFERENCE_FO3,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.BBG_REFERENCE_FO4,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.BBG_REFERENCE_FO5,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.BBG_REFERENCE_FO6,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.BBG_REFERENCE_FO7,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.BBG_REFERENCE_FO8,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.BBG_REFERENCE_FO9,
            W_RTL_SLS_TRX_IT_LC_DY_TMP.BBG_REFERENCE_FO10;
