--2015-7-8 6:17:18
--÷¥–– ±º‰:6195√Î

merge /*+ APPEND */
into RADM.W_RTL_BCOST_IT_DY_A T
using (Select /*+ APPEND */
        W_RTL_BCOST_IT_DY_TMP.PROD_IT_WID PROD_WID,
        W_RTL_BCOST_IT_DY_TMP.PROD_SCD1_WID PROD_SCD1_WID,
        W_RTL_BCOST_IT_DY_TMP.DT_WID DT_WID,
        W_RTL_BCOST_IT_DY_TMP.SUPPLIER_WID SUPPLIER_WID,
        W_RTL_BCOST_IT_DY_TMP.BASE_COST_AMT_LCL BASE_COST_AMT_LCL,
        W_RTL_BCOST_IT_DY_TMP.BASE_COST_AMT BASE_COST_AMT,
        W_RTL_BCOST_IT_DY_TMP.BASE_COST_AMT_GLOBAL1 BASE_COST_AMT_GLOBAL1,
        W_RTL_BCOST_IT_DY_TMP.BASE_COST_AMT_GLOBAL2 BASE_COST_AMT_GLOBAL2,
        W_RTL_BCOST_IT_DY_TMP.BASE_COST_AMT_GLOBAL3 BASE_COST_AMT_GLOBAL3,
        W_RTL_BCOST_IT_DY_TMP.DATASOURCE_NUM_ID DATASOURCE_NUM_ID,
        W_RTL_BCOST_IT_DY_TMP.DELETE_FLG DELETE_FLG,
        100 ETL_PROC_WID,
        W_RTL_BCOST_IT_DY_TMP.PROD_IT_NUM || '~' ||
        W_RTL_BCOST_IT_DY_TMP.DAY_DT || '~' ||
        W_RTL_BCOST_IT_DY_TMP.SUPPLIER_NUM INTEGRATION_ID,
        W_RTL_BCOST_IT_DY_TMP.TENANT_ID TENANT_ID,
        SYSDATE W_INSERT_DT,
        SYSDATE W_UPDATE_DT,
        W_RTL_BCOST_IT_DY_TMP.X_CUSTOM X_CUSTOM,
        W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_DO1 BBG_REFERENCE_DO1,
        W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_DO2 BBG_REFERENCE_DO2,
        W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_DO3 BBG_REFERENCE_DO3,
        W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_DO4 BBG_REFERENCE_DO4,
        W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_DO5 BBG_REFERENCE_DO5,
        W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO1 BBG_REFERENCE_FO1,
        W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO2 BBG_REFERENCE_FO2,
        W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO3 BBG_REFERENCE_FO3,
        W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO4 BBG_REFERENCE_FO4,
        W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO5 BBG_REFERENCE_FO5,
        W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO6 BBG_REFERENCE_FO6,
        W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO7 BBG_REFERENCE_FO7,
        W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO8 BBG_REFERENCE_FO8,
        W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO9 BBG_REFERENCE_FO9,
        W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO10 BBG_REFERENCE_FO10
       
         From RABATCHER.W_RTL_BCOST_IT_DY_TMP W_RTL_BCOST_IT_DY_TMP
        Where (1 = 1)
       
       ) S
on (T.PROD_WID = S.PROD_WID and T.PROD_SCD1_WID = S.PROD_SCD1_WID and T.DT_WID = S.DT_WID and T.SUPPLIER_WID = S.SUPPLIER_WID)
when matched then
  update
     set T.BASE_COST_AMT_LCL     = S.BASE_COST_AMT_LCL,
         T.BASE_COST_AMT         = S.BASE_COST_AMT,
         T.BASE_COST_AMT_GLOBAL1 = S.BASE_COST_AMT_GLOBAL1,
         T.BASE_COST_AMT_GLOBAL2 = S.BASE_COST_AMT_GLOBAL2,
         T.BASE_COST_AMT_GLOBAL3 = S.BASE_COST_AMT_GLOBAL3,
         T.DATASOURCE_NUM_ID     = S.DATASOURCE_NUM_ID,
         T.DELETE_FLG            = S.DELETE_FLG,
         T.ETL_PROC_WID          = S.ETL_PROC_WID,
         T.INTEGRATION_ID        = S.INTEGRATION_ID,
         T.TENANT_ID             = S.TENANT_ID,
         T.W_UPDATE_DT           = S.W_UPDATE_DT,
         T.X_CUSTOM              = S.X_CUSTOM,
         T.BBG_REFERENCE_DO1     = S.BBG_REFERENCE_DO1,
         T.BBG_REFERENCE_DO2     = S.BBG_REFERENCE_DO2,
         T.BBG_REFERENCE_DO3     = S.BBG_REFERENCE_DO3,
         T.BBG_REFERENCE_DO4     = S.BBG_REFERENCE_DO4,
         T.BBG_REFERENCE_DO5     = S.BBG_REFERENCE_DO5,
         T.BBG_REFERENCE_FO1     = S.BBG_REFERENCE_FO1,
         T.BBG_REFERENCE_FO2     = S.BBG_REFERENCE_FO2,
         T.BBG_REFERENCE_FO3     = S.BBG_REFERENCE_FO3,
         T.BBG_REFERENCE_FO4     = S.BBG_REFERENCE_FO4,
         T.BBG_REFERENCE_FO5     = S.BBG_REFERENCE_FO5,
         T.BBG_REFERENCE_FO6     = S.BBG_REFERENCE_FO6,
         T.BBG_REFERENCE_FO7     = S.BBG_REFERENCE_FO7,
         T.BBG_REFERENCE_FO8     = S.BBG_REFERENCE_FO8,
         T.BBG_REFERENCE_FO9     = S.BBG_REFERENCE_FO9,
         T.BBG_REFERENCE_FO10    = S.BBG_REFERENCE_FO10
  

when not matched then
  insert
    (
     
     T.ROW_WID,
     T.PROD_WID,
     T.PROD_SCD1_WID,
     T.DT_WID,
     T.SUPPLIER_WID,
     T.BASE_COST_AMT_LCL,
     T.BASE_COST_AMT,
     T.BASE_COST_AMT_GLOBAL1,
     T.BASE_COST_AMT_GLOBAL2,
     T.BASE_COST_AMT_GLOBAL3,
     T.DATASOURCE_NUM_ID,
     T.DELETE_FLG,
     T.ETL_PROC_WID,
     T.INTEGRATION_ID,
     T.TENANT_ID,
     T.W_INSERT_DT,
     T.W_UPDATE_DT,
     T.X_CUSTOM,
     T.BBG_REFERENCE_DO1,
     T.BBG_REFERENCE_DO2,
     T.BBG_REFERENCE_DO3,
     T.BBG_REFERENCE_DO4,
     T.BBG_REFERENCE_DO5,
     T.BBG_REFERENCE_FO1,
     T.BBG_REFERENCE_FO2,
     T.BBG_REFERENCE_FO3,
     T.BBG_REFERENCE_FO4,
     T.BBG_REFERENCE_FO5,
     T.BBG_REFERENCE_FO6,
     T.BBG_REFERENCE_FO7,
     T.BBG_REFERENCE_FO8,
     T.BBG_REFERENCE_FO9,
     T.BBG_REFERENCE_FO10
     
     )
  values
    (
     
     RADM.W_RTL_BCOST_IT_DY_A_SEQ.NEXTVAL,
     S.PROD_WID,
     S.PROD_SCD1_WID,
     S.DT_WID,
     S.SUPPLIER_WID,
     S.BASE_COST_AMT_LCL,
     S.BASE_COST_AMT,
     S.BASE_COST_AMT_GLOBAL1,
     S.BASE_COST_AMT_GLOBAL2,
     S.BASE_COST_AMT_GLOBAL3,
     S.DATASOURCE_NUM_ID,
     S.DELETE_FLG,
     S.ETL_PROC_WID,
     S.INTEGRATION_ID,
     S.TENANT_ID,
     S.W_INSERT_DT,
     S.W_UPDATE_DT,
     S.X_CUSTOM,
     S.BBG_REFERENCE_DO1,
     S.BBG_REFERENCE_DO2,
     S.BBG_REFERENCE_DO3,
     S.BBG_REFERENCE_DO4,
     S.BBG_REFERENCE_DO5,
     S.BBG_REFERENCE_FO1,
     S.BBG_REFERENCE_FO2,
     S.BBG_REFERENCE_FO3,
     S.BBG_REFERENCE_FO4,
     S.BBG_REFERENCE_FO5,
     S.BBG_REFERENCE_FO6,
     S.BBG_REFERENCE_FO7,
     S.BBG_REFERENCE_FO8,
     S.BBG_REFERENCE_FO9,
     S.BBG_REFERENCE_FO10
     
     )
