--PROD
SELECT T.ROW_WID,
       T.PROD_NUM,
       T.SCD1_WID,
       T.PROD_CAT5_WID,
       T.PROD_CAT5,
       T.PROD_CAT5_WID_AS_WAS,
       T.PROD_CAT5_AS_WAS,
       T.EFFECTIVE_FROM_DT,
       T.EFFECTIVE_TO_DT
  FROM RADM.W_PRODUCT_D T
 WHERE T.PROD_NUM = '100375571'
 ORDER BY T.EFFECTIVE_FROM_DT;
 
SELECT * FROM RABATCHER.W_PRODUCT_D_RTL_TMP T WHERE T.PROD_IT_NUM='100375571'; 
 
--SLS
SELECT /*+PARALLEL(32)*/ * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F T WHERE T.PROD_SCD1_WID=697932 ORDER BY T.DT_WID;
SELECT /*+PARALLEL(32)*/ * FROM RADM.W_RTL_SLS_IT_LC_DY_A T WHERE T.PROD_SCD1_WID=697932 ORDER BY T.DT_WID;


/*
W_PRODUCT_D_V:

SELECT T.*
  FROM W_PRODUCT_D T, W_PRODUCT_ATTR_D A
 WHERE T.SCD1_WID = A.SCD1_WID
   AND A.PRODUCT_ATTR12_NAME = A.PRODUCT_ATTR11_NAME
   
Fact_W_RTL_SLS_IT_LC_DY_A(PROD_WID,PROD_SCD1_WID)
1.Dim_W_PRODUCT_D_As_Is:SCD1_WID

2.Dim_W_PRODUCT_D_PIT:SCD1_WID

3.Dim_W_PRODUCT_D:PROD_WID
*/
