--商品重新分类ROLE_ID
SELECT * FROM RAINY_ROLE WHERE ROLE_EXT LIKE '%RECL%';
--拥有重分类的岗位
SELECT * FROM RAINY_POSITION RP WHERE EXISTS(SELECT 1 FROM RAINY_POSITION_ROLE RPR WHERE RP.POSITION_ID=RPR.POSITION_ID AND RPR.ROLE_ID='115');
SELECT * FROM RAINY_POSITION RP WHERE EXISTS(SELECT 1 FROM RAINY_POSITION_ROLE RPR WHERE RP.POSITION_ID=RPR.POSITION_ID AND RPR.ROLE_ID='116');
SELECT * FROM RAINY_POSITION RP WHERE EXISTS(SELECT 1 FROM RAINY_POSITION_ROLE RPR WHERE RP.POSITION_ID=RPR.POSITION_ID AND RPR.ROLE_ID='139');
--拥有重分类的用户
SELECT * FROM RAINY_USER RU WHERE EXISTS(SELECT 1 FROM RAINY_POSITION_ROLE RPR,RAINY_USER_POSITION RUP WHERE RU.USER_ID=RUP.USER_ID AND RUP.POSITION_ID=RPR.POSITION_ID AND RPR.ROLE_ID=115);
SELECT * FROM RAINY_USER RU WHERE EXISTS(SELECT 1 FROM RAINY_POSITION_ROLE RPR,RAINY_USER_POSITION RUP WHERE RU.USER_ID=RUP.USER_ID AND RUP.POSITION_ID=RPR.POSITION_ID AND RPR.ROLE_ID=116);
SELECT * FROM RAINY_USER RU WHERE EXISTS(SELECT 1 FROM RAINY_POSITION_ROLE RPR,RAINY_USER_POSITION RUP WHERE RU.USER_ID=RUP.USER_ID AND RUP.POSITION_ID=RPR.POSITION_ID AND RPR.ROLE_ID=139);

--重分类权限全部去掉.ROLE_ID=139的全部去掉.
--所有用户去掉商品重新分类权限
SELECT 'revoke ' || 'RECLS' || ' from ' || DRP.GRANTEE || ';'
  FROM DBA_ROLE_PRIVS DRP
  WHERE DRP.GRANTED_ROLE= 'RECLS';

--岗位去掉商品重新分类权限
DELETE RAINY_POSITION_ROLE WHERE ROLE_ID=139;


