SELECT * 
FROM RAINY_POSITION_ROLE
WHERE ROLE_ID IN (147,151)
AND POSITION_ID IN (8,9,10,11,12,122,123,124,125);




--移除原职位权限
--查询出来的语句在sys用户下执行
SELECT 'revoke ' || rr.role_ext || ' from ' || ru.user_id || ';'
  FROM rainy_role          rr ,
       rainy_user          ru ,
       rainy_user_position rup ,
       rainy_position_role rpr 
 WHERE rr.appl = 'RMS'
   AND rup.user_id = ru.user_id
   AND rup.position_id = rpr.position_id
   AND rpr.role_id = rr.role_id
   AND RPR.ROLE_ID IN (147,151)
   AND RPR.POSITION_ID IN (8,9,10,11,12,122,123,124,125);
   

   
DELETE RAINY_POSITION_ROLE
WHERE ROLE_ID IN (147,151)
AND POSITION_ID IN (8,9,10,11,12,122,123,124,125);

INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(8,147);
INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(9,147);
INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(10,147);
INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(11,147);
INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(12,147);
INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(122,147);
INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(123,147);
INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(124,147);
INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(125,147);

INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(8,151);
INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(9,151);
INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(10,151);
INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(11,151);
INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(12,151);
INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(122,151);
INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(123,151);
INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(124,151);
INSERT INTO RAINY_POSITION_ROLE(POSITION_ID,ROLE_ID) VALUES(125,151);


