--2016-5-13 3:06:07,执行6108秒，插入40953条记录。
--2016-4-25 2:39:22,执行1399秒，插入34755条记录。

/* DETECTION_STRATEGY = NOT_EXISTS */
insert into RABATCHER.BBG_RA_SUPP_INV_IT_LC_DY_TMP PARTITION FOR
  (1) T
  (ORG_WID,
   ORG_LC_WID,
   ORG_DS_WID,
   ORG_RG_WID,
   ORG_AR_WID,
   ORG_CH_WID,
   ORG_NUM,
   ORG_DS_NUM,
   ORG_RG_NUM,
   ORG_AR_NUM,
   ORG_CH_NUM,
   ORG_SCD1_WID,
   PROD_IT_WID,
   PROD_SCD1_WID,
   PROD_SC_WID,
   PROD_CL_WID,
   PROD_DP_WID,
   PROD_GP_WID,
   PROD_DV_WID,
   PROD_IT_NUM,
   PROD_SC_NUM,
   PROD_CL_NUM,
   PROD_DP_NUM,
   PROD_GP_NUM,
   PROD_DV_NUM,
   DT_WID,
   DAY_DT,
   WK_WID,
   WK_NUM,
   PR_WID,
   PR_NUM,
   QT_WID,
   QT_NUM,
   SUPPLIER_WID,
   SUPPLIER_NUM,
   SUPP_INV_QTY,
   SUPP_INV_COST,
   DOC_CURR_CODE,
   LOC_CURR_CODE,
   LOC_EXCHANGE_RATE,
   GLOBAL1_EXCHANGE_RATE,
   GLOBAL2_EXCHANGE_RATE,
   GLOBAL3_EXCHANGE_RATE,
   CREATED_BY_ID,
   CHANGED_BY_ID,
   CREATED_ON_DT,
   CHANGED_ON_DT,
   AUX1_CHANGED_ON_DT,
   AUX2_CHANGED_ON_DT,
   AUX3_CHANGED_ON_DT,
   AUX4_CHANGED_ON_DT,
   DELETE_FLG,
   DATASOURCE_NUM_ID,
   TENANT_ID,
   X_CUSTOM,
   ETL_THREAD_VAL,
   BBG_ITEM_LOC_WID,
   BBG_ITEM_LOC_SUPP_WID,
   BBG_REFERENCE_DO1,
   BBG_REFERENCE_DO2,
   BBG_REFERENCE_DO3,
   BBG_REFERENCE_DO4,
   BBG_REFERENCE_DO5,
   BBG_REFERENCE_FO1,
   BBG_REFERENCE_FO2,
   BBG_REFERENCE_FO3,
   BBG_REFERENCE_FO4,
   BBG_REFERENCE_FO5,
   BBG_REFERENCE_FO6,
   BBG_REFERENCE_FO7,
   BBG_REFERENCE_FO8,
   BBG_REFERENCE_FO9,
   BBG_REFERENCE_FO10,
   ETL_PROC_WID)
  select W_INT_ORG_D_RTL_TMP.ORG_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_LC_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_DS_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_RG_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_AR_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_CH_WID,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.ORG_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_DS_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_RG_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_AR_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_CH_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_SCD1_WID,
         W_PRODUCT_D_RTL_TMP.PROD_IT_WID,
         W_PRODUCT_D_RTL_TMP.PROD_SCD1_WID,
         W_PRODUCT_D_RTL_TMP.PROD_SC_WID,
         W_PRODUCT_D_RTL_TMP.PROD_CL_WID,
         W_PRODUCT_D_RTL_TMP.PROD_DP_WID,
         W_PRODUCT_D_RTL_TMP.PROD_GP_WID,
         W_PRODUCT_D_RTL_TMP.PROD_DV_WID,
         W_PRODUCT_D_RTL_TMP.PROD_IT_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_SC_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_CL_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_DP_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_GP_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_DV_NUM,
         W_MCAL_DAY_D.ROW_WID,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.DAY_DT,
         W_MCAL_WEEK_D.ROW_WID,
         W_MCAL_WEEK_D.MCAL_YEAR || W_MCAL_WEEK_D.MCAL_WEEK,
         W_MCAL_DAY_D.MCAL_PERIOD_WID,
         W_MCAL_DAY_D.MCAL_YEAR || W_MCAL_DAY_D.MCAL_PERIOD,
         W_MCAL_DAY_D.MCAL_QTR_WID,
         W_MCAL_DAY_D.MCAL_YEAR || W_MCAL_DAY_D.MCAL_QTR,
         W_PARTY_ORG_D.ROW_WID,
         TO_CHAR(STG_BBG_RA_SUP_INV_IT_LC_DY_FS.SUPPLIER_NUM),
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.SUPP_INV_QTY,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.SUPP_INV_COST,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.DOC_CURR_CODE,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.LOC_CURR_CODE,
         1.0,
         1.0,
         1.0,
         1.0,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.CREATED_BY_ID,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.CHANGED_BY_ID,
         SYSDATE,
         SYSDATE,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.AUX1_CHANGED_ON_DT,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.AUX2_CHANGED_ON_DT,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.AUX3_CHANGED_ON_DT,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.AUX4_CHANGED_ON_DT,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.DELETE_FLG,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.DATASOURCE_NUM_ID,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.TENANT_ID,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.X_CUSTOM,
         1,
         BBG_RA_ITEM_LOC_D.ROW_WID,
         NVL(BBG_RA_ITEM_LOC_SUPP_D.ROW_WID, -1),
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.BBG_REFERENCE_DO1,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.BBG_REFERENCE_DO2,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.BBG_REFERENCE_DO3,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.BBG_REFERENCE_DO4,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.BBG_REFERENCE_DO5,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.BBG_REFERENCE_FO1,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.BBG_REFERENCE_FO2,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.BBG_REFERENCE_FO3,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.BBG_REFERENCE_FO4,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.BBG_REFERENCE_FO5,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.BBG_REFERENCE_FO6,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.BBG_REFERENCE_FO7,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.BBG_REFERENCE_FO8,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.BBG_REFERENCE_FO9,
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.BBG_REFERENCE_FO10,
         (CASE
           WHEN 100 = 0 THEN
            1
           ELSE
            100
         END)
    from RADM.W_MCAL_DAY_D               W_MCAL_DAY_D,
         RADM.W_MCAL_WEEK_D              W_MCAL_WEEK_D,
         RABATCHER.W_INT_ORG_DH_RTL_TMP  W_INT_ORG_DH_RTL_TMP,
         RABATCHER.W_PRODUCT_D_RTL_TMP   W_PRODUCT_D_RTL_TMP,
         RABATCHER.W_INT_ORG_D_RTL_TMP   W_INT_ORG_D_RTL_TMP,
         RADM.W_PARTY_ORG_D              W_PARTY_ORG_D,
         RADM.BBG_RA_ITEM_LOC_D          BBG_RA_ITEM_LOC_D,
         RADM.BBG_RA_ITEM_LOC_SUPP_D     BBG_RA_ITEM_LOC_SUPP_D,
         RADM.BBG_RA_SUP_INV_IT_LC_DY_FS STG_BBG_RA_SUP_INV_IT_LC_DY_FS
   where (1 = 1)
     And (W_MCAL_DAY_D.MCAL_DAY_DT = STG_BBG_RA_SUP_INV_IT_LC_DY_FS.DAY_DT)
     AND ((W_MCAL_DAY_D.MCAL_DAY_DT BETWEEN
         W_MCAL_WEEK_D.MCAL_WEEK_START_DT AND
         W_MCAL_WEEK_D.MCAL_WEEK_END_DT) AND
         W_MCAL_DAY_D.MCAL_CAL_WID = W_MCAL_WEEK_D.MCAL_CAL_WID)
     AND ((W_INT_ORG_DH_RTL_TMP.ORG_NUM =
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.ORG_NUM) AND
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.DAY_DT BETWEEN
         W_INT_ORG_DH_RTL_TMP.EFFECTIVE_FROM_DT AND
         W_INT_ORG_DH_RTL_TMP.EFFECTIVE_TO_DT)
     AND ((W_PRODUCT_D_RTL_TMP.PROD_IT_NUM =
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.PROD_IT_NUM) AND
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.DAY_DT BETWEEN
         W_PRODUCT_D_RTL_TMP.SRC_EFF_FROM_DT AND
         W_PRODUCT_D_RTL_TMP.SRC_EFF_TO_DT)
     AND (BBG_RA_ITEM_LOC_D.ITEM =
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.PROD_IT_NUM AND
         BBG_RA_ITEM_LOC_D.LOC = STG_BBG_RA_SUP_INV_IT_LC_DY_FS.ORG_NUM and
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.DAY_DT between
         BBG_RA_ITEM_LOC_D.EFFECTIVE_FROM_DT and
         BBG_RA_ITEM_LOC_D.EFFECTIVE_TO_DT)
     AND ((W_INT_ORG_D_RTL_TMP.ORG_NUM =
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.ORG_NUM) AND
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.DAY_DT BETWEEN
         W_INT_ORG_D_RTL_TMP.EFFECTIVE_FROM_DT AND
         W_INT_ORG_D_RTL_TMP.EFFECTIVE_TO_DT)
     AND ((W_PARTY_ORG_D.SUPPLIER_NUM =
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.SUPPLIER_NUM) AND
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.DAY_DT BETWEEN
         W_PARTY_ORG_D.EFFECTIVE_FROM_DT AND W_PARTY_ORG_D.EFFECTIVE_TO_DT)
     AND (BBG_RA_ITEM_LOC_SUPP_D.ITEM(+) =
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.PROD_IT_NUM AND
         BBG_RA_ITEM_LOC_SUPP_D.LOC(+) =
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.ORG_NUM AND
         BBG_RA_ITEM_LOC_SUPP_D.SUPPLIER(+) =
         STG_BBG_RA_SUP_INV_IT_LC_DY_FS.SUPPLIER_NUM and
         (STG_BBG_RA_SUP_INV_IT_LC_DY_FS.DAY_DT between
         BBG_RA_ITEM_LOC_SUPP_D.EFFECTIVE_FROM_DT(+) and
         BBG_RA_ITEM_LOC_SUPP_D.EFFECTIVE_TO_DT(+)))
     And (STG_BBG_RA_SUP_INV_IT_LC_DY_FS.ETL_THREAD_VAL = 1)
