--2016-03-28执行时常：5792秒。插入行数：421092行。
--可以提交。
/* DETECTION_STRATEGY = NOT_EXISTS */
insert into RABATCHER.BBG_RA_CUST_IT_LC_DY_TMP T
  (ORG_WID,
   ORG_SCD1_WID,
   PROD_IT_WID,
   PROD_SCD1_WID,
   ORG_LC_WID,
   ORG_DS_WID,
   ORG_RG_WID,
   ORG_AR_WID,
   ORG_CH_WID,
   PROD_DV_WID,
   PROD_GP_WID,
   PROD_DP_WID,
   PROD_CL_WID,
   PROD_SC_WID,
   DT_WID,
   WK_WID,
   PR_WID,
   QT_WID,
   DAY_DT,
   WK_NUM,
   PR_NUM,
   QT_NUM,
   ORG_NUM,
   ORG_DS_NUM,
   ORG_RG_NUM,
   ORG_AR_NUM,
   ORG_CH_NUM,
   PROD_IT_NUM,
   PROD_SC_NUM,
   PROD_CL_NUM,
   PROD_DP_NUM,
   PROD_GP_NUM,
   PROD_DV_NUM,
   DATASOURCE_NUM_ID,
   INTEGRATION_ID,
   W_INSERT_DT,
   W_UPDATE_DT,
   BBG_ITEM_LOC_WID,
   BBG_CUSTOMER_COUNT,
   BBG_SERVICE_SATISFACTION
   
   )
  select W_INT_ORG_D_RTL_TMP.ORG_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_SCD1_WID,
         W_PRODUCT_D_RTL_TMP.PROD_IT_WID,
         W_PRODUCT_D_RTL_TMP.PROD_SCD1_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_LC_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_DS_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_RG_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_AR_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_CH_WID,
         W_PRODUCT_D_RTL_TMP.PROD_DV_WID,
         W_PRODUCT_D_RTL_TMP.PROD_GP_WID,
         W_PRODUCT_D_RTL_TMP.PROD_DP_WID,
         W_PRODUCT_D_RTL_TMP.PROD_CL_WID,
         W_PRODUCT_D_RTL_TMP.PROD_SC_WID,
         W_MCAL_DAY_D.ROW_WID,
         W_MCAL_WEEK_D.ROW_WID,
         W_MCAL_DAY_D.MCAL_PERIOD_WID,
         W_MCAL_DAY_D.MCAL_QTR_WID,
         BBG_RA_CUST_IT_LC_DY_FS.DAY_DT,
         W_MCAL_WEEK_D.MCAL_YEAR || W_MCAL_WEEK_D.MCAL_WEEK,
         W_MCAL_DAY_D.MCAL_YEAR || W_MCAL_DAY_D.MCAL_PERIOD,
         W_MCAL_DAY_D.MCAL_YEAR || W_MCAL_DAY_D.MCAL_QTR,
         BBG_RA_CUST_IT_LC_DY_FS.ORG_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_DS_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_RG_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_AR_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_CH_NUM,
         BBG_RA_CUST_IT_LC_DY_FS.PROD_IT_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_SC_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_CL_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_DP_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_GP_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_DV_NUM,
         1,
         W_PRODUCT_D_RTL_TMP.PROD_IT_NUM || '~' ||
         W_INT_ORG_DH_RTL_TMP.ORG_NUM || '~' || W_MCAL_DAY_D.MCAL_DAY_DT,
         SYSDATE,
         SYSDATE,
         BBG_RA_ITEM_LOC_D.ROW_WID,
         BBG_RA_CUST_IT_LC_DY_FS.BBG_CUSTOMER_COUNT,
         BBG_RA_CUST_IT_LC_DY_FS.BBG_SERVICE_SATISFACTION
  
    from RADM.BBG_RA_CUST_IT_LC_DY_FS   BBG_RA_CUST_IT_LC_DY_FS,
         RADM.W_MCAL_DAY_D              W_MCAL_DAY_D,
         RADM.W_MCAL_WEEK_D             W_MCAL_WEEK_D,
         RABATCHER.W_INT_ORG_D_RTL_TMP  W_INT_ORG_D_RTL_TMP,
         RABATCHER.W_INT_ORG_DH_RTL_TMP W_INT_ORG_DH_RTL_TMP,
         RABATCHER.W_PRODUCT_D_RTL_TMP  W_PRODUCT_D_RTL_TMP,
         RADM.BBG_RA_ITEM_LOC_D         BBG_RA_ITEM_LOC_D
   where (1 = 1)
     And (BBG_RA_CUST_IT_LC_DY_FS.DAY_DT = W_MCAL_DAY_D.MCAL_DAY_DT)
     AND ((((W_MCAL_DAY_D.MCAL_DAY_DT BETWEEN
         W_MCAL_WEEK_D.MCAL_WEEK_START_DT AND
         W_MCAL_WEEK_D.MCAL_WEEK_END_DT)) AND
         W_MCAL_DAY_D.DATASOURCE_NUM_ID = W_MCAL_WEEK_D.DATASOURCE_NUM_ID))
     AND (BBG_RA_CUST_IT_LC_DY_FS.ORG_NUM = W_INT_ORG_D_RTL_TMP.ORG_NUM AND
         (BBG_RA_CUST_IT_LC_DY_FS.DAY_DT BETWEEN
         W_INT_ORG_D_RTL_TMP.EFFECTIVE_FROM_DT AND
         W_INT_ORG_D_RTL_TMP.EFFECTIVE_TO_DT))
     AND (BBG_RA_CUST_IT_LC_DY_FS.ORG_NUM = W_INT_ORG_DH_RTL_TMP.ORG_NUM AND
         (BBG_RA_CUST_IT_LC_DY_FS.DAY_DT BETWEEN
         W_INT_ORG_DH_RTL_TMP.EFFECTIVE_FROM_DT AND
         W_INT_ORG_DH_RTL_TMP.EFFECTIVE_TO_DT))
     AND (BBG_RA_CUST_IT_LC_DY_FS.PROD_IT_NUM =
         W_PRODUCT_D_RTL_TMP.PROD_IT_NUM AND
         (BBG_RA_CUST_IT_LC_DY_FS.DAY_DT BETWEEN
         W_PRODUCT_D_RTL_TMP.SRC_EFF_FROM_DT AND
         W_PRODUCT_D_RTL_TMP.SRC_EFF_TO_DT))
     AND (BBG_RA_CUST_IT_LC_DY_FS.PROD_IT_NUM = BBG_RA_ITEM_LOC_D.ITEM AND
         BBG_RA_CUST_IT_LC_DY_FS.ORG_NUM = BBG_RA_ITEM_LOC_D.LOC and
         (BBG_RA_CUST_IT_LC_DY_FS.DAY_DT between
         BBG_RA_ITEM_LOC_D.EFFECTIVE_FROM_DT and
         BBG_RA_ITEM_LOC_D.EFFECTIVE_TO_DT))
