
--1.
DROP TABLE RADM.YJ_TMP;
CREATE TABLE RADM.YJ_TMP AS
  SELECT /*+PARALLEL(16)*/
  DISTINCT A.SLS_TRX_ID
    FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F A
   WHERE A.HYK_NO IS NULL
     AND EXISTS (SELECT /*+PARALLEL(16)*/
           1
            FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F B
           WHERE A.SLS_TRX_ID = B.SLS_TRX_ID
             AND B.HYK_NO IS NOT NULL
             AND B.DT_WID = &DTWID)
     AND A.DT_WID = &DTWID;
		 
--2.		 
DROP TABLE RADM.YJ_TMP1;
CREATE TABLE RADM.YJ_TMP1 AS
SELECT A.SLS_TRX_ID, MAX(A.HYK_NO) HYK_NO
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F A
 WHERE A.HYK_NO IS NOT NULL
   AND A.DT_WID = &DTWID
   AND EXISTS
 (SELECT 1 FROM RADM.YJ_TMP B WHERE A.SLS_TRX_ID = B.SLS_TRX_ID)
 GROUP BY A.SLS_TRX_ID;
		 
--3.
UPDATE /*+PARALLEL(16)*/ RADM.W_RTL_SLS_TRX_IT_LC_DY_F A
   SET A.HYK_NO =
       (SELECT /*+PARALLEL(16)*/
         B.HYK_NO
          FROM RADM.YJ_TMP1 B
         WHERE A.SLS_TRX_ID = B.SLS_TRX_ID)
 WHERE A.DT_WID = &DTWID
   AND A.HYK_NO IS NULL
   AND EXISTS
 (SELECT 1 FROM RADM.YJ_TMP1 C WHERE A.SLS_TRX_ID = C.SLS_TRX_ID);
COMMIT;
	 
--4.
UPDATE /*+PARALLEL(A,12)*/ RADM.W_RTL_SLS_TRX_IT_LC_DY_F A
   SET A.VIP_SLS_QTY                 = A.SLS_QTY,
       A.VIP_SLS_AMT_LCL             = A.SLS_AMT_LCL,
       A.VIP_SLS_PROFIT_AMT_LCL      = A.SLS_PROFIT_AMT_LCL,
       A.VIP_SLS_MANUAL_MKDN_AMT_LCL = A.SLS_MANUAL_MKDN_AMT_LCL,
       A.VIP_SLS_MANUAL_MKUP_AMT_LCL = A.SLS_MANUAL_MKUP_AMT_LCL,
       A.VIP_SLS_TAX_AMT_LCL         = A.SLS_TAX_AMT_LCL,
       A.VIP_SLS_EMP_DISC_AMT_LCL    = A.SLS_EMP_DISC_AMT_LCL,
       A.VIP_SLS_MANUAL_COUNT        = A.SLS_MANUAL_COUNT,
       A.VIP_SLS_SCAN_COUNT          = A.SLS_SCAN_COUNT,
       A.VIP_RET_QTY                 = A.RET_QTY,
       A.VIP_RET_AMT_LCL             = A.RET_AMT_LCL,
       A.VIP_RET_PROFIT_AMT_LCL      = A.RET_PROFIT_AMT_LCL,
       A.VIP_RET_MANUAL_MKDN_AMT_LCL = A.RET_MANUAL_MKDN_AMT_LCL,
       A.VIP_RET_MANUAL_MKUP_AMT_LCL = A.RET_MANUAL_MKUP_AMT_LCL,
       A.VIP_RET_TAX_AMT_LCL         = A.RET_TAX_AMT_LCL,
       A.VIP_RET_EMP_DISC_AMT_LCL    = A.RET_EMP_DISC_AMT_LCL,
       A.VIP_RET_MANUAL_COUNT        = A.RET_MANUAL_COUNT,
       A.VIP_RET_SCAN_COUNT          = A.RET_SCAN_COUNT
 WHERE A.DT_WID = &DTWID
   AND EXISTS
 (SELECT 1 FROM RADM.YJ_TMP1 B WHERE A.SLS_TRX_ID = B.SLS_TRX_ID)
   AND A.VIP_SLS_QTY <> A.SLS_QTY;
COMMIT;
