--1.
DROP MATERIALIZED VIEW RA_RMS.BBG_JL_ITEM_LOC_MV;

CREATE MATERIALIZED VIEW RA_RMS.BBG_JL_ITEM_LOC_MV REFRESH  START
  WITH SYSDATE NEXT TRUNC(SYSDATE) + 1 + 0.5 / 24 AS
  SELECT ITEM,
         LOC,
         SRC_EFF_FROM_DT,
         NBB,
         NBO,
         --SALE_TYPE,
         STANDARD_GROSS_MARGIN,
         PROMO_GROSS_MARGIN,
         BUSINESS_MODE,
         ZC_IND,
         BBG_ZG_IND,
         HERO_ITEM_IND,
         --START_DATE,
         --END_DATE,
         NEW_ITEM_FLAG,
         --REF_NO1,
         REF_NO2/*,
         REF_NO3,
         REF_NO4*/
    FROM BBG_RA_ITEM_LOC_JL_V@RMS_JL;

--1.1
CREATE INDEX RA_RMS.IDXBBG_JL_ITEM_LOC_MV  
   ON BBG_JL_ITEM_LOC_MV (ITEM,LOC,SRC_EFF_FROM_DT);


--2.ÐÞ¸ÄRMS.BBG_RA_ITEM_LOC_JL_VÊÓÍ¼
SELECT * FROM RMS.BBG_RA_ITEM_LOC_JL_V;

--2.1B±í
SELECT TRIM(A.ITEM) ITEM,
       TRIM(A.LOC) LOC,
       A.SRC_EFF_FROM_DT SRC_EFF_FROM_DT,
       TRIM(A.NBB) NBB,
       TRIM(A.NBO) NBO,
       '' SALE_TYPE,
       TRIM(A.STANDARD_GROSS_MARGIN) STANDARD_GROSS_MARGIN,
       TRIM(A.PROMO_GROSS_MARGIN) PROMO_GROSS_MARGIN,
       TRIM(A.BUSINESS_MODE) BUSINESS_MODE,
       TRIM(A.ZC_IND) ZC_IND,
       TRIM(A.BBG_ZG_IND) BBG_ZG_IND,
       TRIM(A.HERO_ITEM_IND) HERO_ITEM_IND,
       '' START_DATE,
       '' END_DATE,
       TRIM(A.NEW_ITEM_FLAG) NEW_ITEM_FLAG,
       '' REF_NO1,
       TRIM(A.REF_NO2) REF_NO2,
       '' REF_NO3,
       '' REF_NO4,
       RANK() OVER(PARTITION BY A.ITEM, A.LOC ORDER BY DECODE(A.BUSINESS_MODE, 'JX', 1, 'DX', 2, 'LY', 3), A.ZC_IND) RANK_NO
  FROM RA_RMS.BBG_JL_ITEM_LOC_MV A
 WHERE EXISTS
 (SELECT 1
          FROM (SELECT B.ITEM, B.LOC, MAX(B.SRC_EFF_FROM_DT) SRC_EFF_FROM_DT
                  FROM RA_RMS.BBG_JL_ITEM_LOC_MV B
                 GROUP BY B.ITEM, B.LOC) C
         WHERE A.ITEM = C.ITEM
           AND A.LOC = C.LOC
           AND A.SRC_EFF_FROM_DT = C.SRC_EFF_FROM_DT)
