SELECT * FROM cmx_doc_ceie_header;
SELECT * FROM APPS.CUX_DOC_CEIE_HEADERS_V6@RMS_EBS;

SELECT * FROM APPS.CUX_DOC_CEIE_HEADERS_V6;

SELECT * FROM dba_SYNONYMS T WHERE T.SYNONYM_NAME='CMX_DOC_CEIE_HEADER';
