--********************************************************************************************
--接口定义
--********************************************************************************************
--商品资料接口
SELECT * FROM BBG_RA_PRODUCT_JL_V@RA_JL;
--商品地点接口
SELECT * FROM BBG_RA_ITEM_LOC_JL_V@RA_JL;
--销售接口
SELECT * FROM BBG_RA_SLS_TRX_JL_V@RA_JL;
--供应商销售接口
SELECT * FROM BBG_RA_SUPP_SLS_JL_V@RA_JL;

--*********************************************************************************************

--RA中创建金力商品资料视图
CREATE OR REPLACE VIEW BBG_RA_PRODUCT_JL_REF_V AS
  SELECT * FROM BBG_RA_PRODUCT_JL_V@RA_JL;
--检查商品资料是否重复
SELECT * FROM BBG_RA_PRODUCT_JL_REF_V T WHERE EXISTS(SELECT 1 FROM W_PRODUCT_D D WHERE D.PROD_NUM=T.PROD_NUM);
--C_ODI_PARAM
SELECT * FROM RADM.C_ODI_PARAM T;
--ITEM_LEVEL EX
SELECT *
  FROM RADM.W_PRODUCT_ATTR_D T
 WHERE T.PRODUCT_ATTR13_NAME = '900024471';
SELECT *
  FROM RADM.W_PRODUCT_ATTR_D T
 WHERE T.PRODUCT_ATTR14_NAME = '800024471';
SELECT *
  FROM RADM.W_PRODUCT_ATTR_D T
 WHERE T.PRODUCT_ATTR15_NAME = '800024471';
--ITEM_LEVEL=1
SELECT * FROM RADM.W_PRODUCT_D T WHERE T.INTEGRATION_ID = '900024471';
--ITEM_LEVEL=2
SELECT * FROM RADM.W_PRODUCT_D T WHERE T.INTEGRATION_ID = '800024471';
--ITEM_LEVEL=3
SELECT * FROM RADM.W_PRODUCT_D T WHERE T.INTEGRATION_ID = '2000233553609';
SELECT * FROM RADM.W_PRODUCT_D T WHERE T.INTEGRATION_ID = '6930946900314';

SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F F WHERE F.PROD_WID = 464339;
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F F WHERE F.PROD_WID = 274237;
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F F WHERE F.PROD_WID = 20700;
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F F WHERE F.PROD_WID = 197795;
--------------------------------------------------------------------------------
SELECT * FROM RADM.W_PRODUCT_DS;
SELECT * FROM RADM.W_PRODUCT_ATTR_DS;
SELECT * FROM RADM.W_PRODUCT_DS_TL;
SELECT * FROM RADM.W_PRODUCT_TYPE_D;
SELECT * FROM ALL_ALL_TABLES T WHERE T.table_name = 'W_PRODUCT_TYPE_D';

CREATE TABLE RA_RMS.W_RTL_ITEM_D_TMP_BAK AS
SELECT * FROM RA_RMS.W_RTL_ITEM_D_TMP;


SELECT * FROM RADM.W_PRODUCT_ATTR_D T WHERE T.PRODUCT_ATTR11_NAME = 1;


SELECT * FROM RADM.W_PRODUCT_D T WHERE T.ROW_WID = 274237;


SELECT DISTINCT T.PRODUCT_ATTR5_NAME
  FROM RADM.W_PRODUCT_ATTR_D T;
	SELECT distinct t.bbg_item_place_of_origin FROM RADM.W_PRODUCT_D t;
	
