/*
table list:
W_RTL_SLS_TRX_IT_LC_DY_F 
W_RTL_SLS_CL_DY_CUR_A
W_RTL_SLS_CL_LC_DY_A
W_RTL_SLS_CL_LC_DY_CUR_A
W_RTL_SLS_DP_DY_CUR_A
W_RTL_SLS_DP_LC_DY_A
W_RTL_SLS_DP_LC_DY_CUR_A
W_RTL_SLS_IT_DY_A
W_RTL_SLS_IT_DY_SN_A
W_RTL_SLS_IT_LC_DY_A
W_RTL_SLS_IT_LC_DY_SN_A
W_RTL_SLS_LC_DY_A
W_RTL_SLS_SC_DY_A
W_RTL_SLS_SC_DY_CUR_A
W_RTL_SLS_SC_LC_DY_A
W_RTL_SLS_SC_LC_DY_CUR_A
*/
--
DELETE RADM.W_RTL_SLS_TRX_IT_LC_DY_F T
 WHERE T.DT_WID BETWEEN &BDTWID AND &EDTWID
   AND T.BBG_SERVICE_SATISFACTION = 3.5;
COMMIT;
--
DELETE RADM.W_RTL_SLS_CL_DY_CUR_A T
 WHERE T.DT_WID BETWEEN &BDTWID AND &EDTWID
   AND EXISTS
 (SELECT 1
          FROM RADM.W_PROD_CAT_DH C
         WHERE T.PROD_DH_WID = C.ROW_WID
           AND C.LVL6ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;
--
DELETE W_RTL_SLS_CL_LC_DY_A T
 WHERE T.DT_WID BETWEEN &BDTWID AND &EDTWID
   AND EXISTS
 (SELECT 1
          FROM RADM.W_PROD_CAT_DH C
         WHERE T.PROD_DH_WID = C.ROW_WID
           AND C.LVL6ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;
--           
DELETE W_RTL_SLS_CL_LC_DY_CUR_A T
 WHERE T.DT_WID BETWEEN &BDTWID AND &EDTWID
   AND EXISTS
 (SELECT 1
          FROM RADM.W_PROD_CAT_DH C
         WHERE T.PROD_DH_WID = C.ROW_WID
           AND C.LVL6ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;
--
DELETE W_RTL_SLS_DP_DY_CUR_A T
 WHERE T.DT_WID BETWEEN &BDTWID AND &EDTWID
   AND EXISTS
 (SELECT 1
          FROM RADM.W_PROD_CAT_DH C
         WHERE T.PROD_DH_WID = C.ROW_WID
           AND C.LVL6ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;
--
DELETE W_RTL_SLS_DP_LC_DY_A T
 WHERE T.DT_WID BETWEEN &BDTWID AND &EDTWID
   AND EXISTS
 (SELECT 1
          FROM RADM.W_PROD_CAT_DH C
         WHERE T.PROD_DH_WID = C.ROW_WID
           AND C.LVL6ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;
--
DELETE W_RTL_SLS_DP_LC_DY_CUR_A T
 WHERE T.DT_WID BETWEEN &BDTWID AND &EDTWID
   AND EXISTS
 (SELECT 1
          FROM RADM.W_PROD_CAT_DH C
         WHERE T.PROD_DH_WID = C.ROW_WID
           AND C.LVL6ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;
--
DELETE W_RTL_SLS_IT_DY_A T
 WHERE T.DT_WID BETWEEN &BDTWID AND &EDTWID
   AND EXISTS
 (SELECT 1
          FROM RABATCHER.W_PRODUCT_D_RTL_TMP P
         WHERE T.PROD_WID = P.PROD_IT_WID
           AND P.PROD_DP_NUM IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;
--
DELETE W_RTL_SLS_IT_DY_SN_A T
 WHERE T.DT_WID BETWEEN &BDTWID AND &EDTWID
   AND EXISTS
 (SELECT 1
          FROM RABATCHER.W_PRODUCT_D_RTL_TMP P
         WHERE T.PROD_WID = P.PROD_IT_WID
           AND P.PROD_DP_NUM IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;
--
DELETE W_RTL_SLS_IT_LC_DY_A T
 WHERE T.DT_WID BETWEEN &BDTWID AND &EDTWID
   AND EXISTS
 (SELECT 1
          FROM RABATCHER.W_PRODUCT_D_RTL_TMP P
         WHERE T.PROD_WID = P.PROD_IT_WID
           AND P.PROD_DP_NUM IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;
--
DELETE W_RTL_SLS_IT_LC_DY_SN_A T
 WHERE T.DT_WID BETWEEN &BDTWID AND &EDTWID
   AND EXISTS
 (SELECT 1
          FROM RABATCHER.W_PRODUCT_D_RTL_TMP P
         WHERE T.PROD_WID = P.PROD_IT_WID
           AND P.PROD_DP_NUM IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;
--
DELETE W_RTL_SLS_SC_DY_A T
 WHERE T.DT_WID BETWEEN &BDTWID AND &EDTWID
   AND EXISTS
 (SELECT 1
          FROM RADM.W_PROD_CAT_DH C
         WHERE T.PROD_DH_WID = C.ROW_WID
           AND C.LVL6ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;
--           
DELETE W_RTL_SLS_SC_DY_CUR_A T
 WHERE T.DT_WID BETWEEN &BDTWID AND &EDTWID
   AND EXISTS
 (SELECT 1
          FROM RADM.W_PROD_CAT_DH C
         WHERE T.PROD_DH_WID = C.ROW_WID
           AND C.LVL6ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;
--           
DELETE W_RTL_SLS_SC_LC_DY_A T
 WHERE T.DT_WID BETWEEN &BDTWID AND &EDTWID
   AND EXISTS
 (SELECT 1
          FROM RADM.W_PROD_CAT_DH C
         WHERE T.PROD_DH_WID = C.ROW_WID
           AND C.LVL6ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;
--           
DELETE W_RTL_SLS_SC_LC_DY_CUR_A T
 WHERE T.DT_WID BETWEEN &BDTWID AND &EDTWID
   AND EXISTS
 (SELECT 1
          FROM RADM.W_PROD_CAT_DH C
         WHERE T.PROD_DH_WID = C.ROW_WID
           AND C.LVL6ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;

--
DELETE W_RTL_SLS_LC_DY_A T WHERE T.DT_WID BETWEEN &BDTWID AND &EDTWID;
COMMIT;

--W_RTL_SLS_LC_DY_A
--MERGE
--TARGET:W_RTL_SLS_LC_DY_A
--SOURCE:W_RTL_SLS_IT_LC_DY_A
MERGE /*+ APPEND */
INTO RADM.W_RTL_SLS_LC_DY_A T
USING (SELECT A.ORG_WID,
              MAX(A.ORG_DH_WID) ORG_DH_WID,
              MAX(A.ORG_SCD1_WID) ORG_SCD1_WID,
              A.DT_WID,
              A.RTL_TYPE_WID,
              A.VOUCHER_FLG,
              SUM(A.SLS_QTY) SLS_QTY,
              SUM(A.SLS_AMT_LCL) SLS_AMT_LCL,
              SUM(A.SLS_PROFIT_AMT_LCL) SLS_PROFIT_AMT_LCL,
              SUM(A.SLS_MANUAL_MKDN_AMT_LCL) SLS_MANUAL_MKDN_AMT_LCL,
              SUM(A.SLS_MANUAL_MKUP_AMT_LCL) SLS_MANUAL_MKUP_AMT_LCL,
              SUM(A.SLS_TAX_AMT_LCL) SLS_TAX_AMT_LCL,
              SUM(A.SLS_EMP_DISC_AMT_LCL) SLS_EMP_DISC_AMT_LCL,
              0 SLS_TRX_COUNT,
              SUM(A.RET_QTY) RET_QTY,
              SUM(A.RET_AMT_LCL) RET_AMT_LCL,
              SUM(A.RET_PROFIT_AMT_LCL) RET_PROFIT_AMT_LCL,
              SUM(A.RET_MANUAL_MKDN_AMT_LCL) RET_MANUAL_MKDN_AMT_LCL,
              SUM(A.RET_MANUAL_MKUP_AMT_LCL) RET_MANUAL_MKUP_AMT_LCL,
              SUM(A.RET_TAX_AMT_LCL) RET_TAX_AMT_LCL,
              SUM(A.RET_EMP_DISC_AMT_LCL) RET_EMP_DISC_AMT_LCL,
              0 RET_TRX_COUNT,
              MAX(A.DATASOURCE_NUM_ID) DATASOURCE_NUM_ID,
              MAX(A.DELETE_FLG) DELETE_FLG,
              MAX(A.DOC_CURR_CODE) DOC_CURR_CODE,
              MAX(A.ETL_PROC_WID) ETL_PROC_WID,
              MAX(A.GLOBAL1_EXCHANGE_RATE) GLOBAL1_EXCHANGE_RATE,
              MAX(A.GLOBAL2_EXCHANGE_RATE) GLOBAL2_EXCHANGE_RATE,
              MAX(A.GLOBAL3_EXCHANGE_RATE) GLOBAL3_EXCHANGE_RATE,
              MAX(SUBSTR(A.INTEGRATION_ID,
                         INSTR(A.INTEGRATION_ID, '~', 1, 1) + 1,
                         6) || '~' ||
                  SUBSTR(A.INTEGRATION_ID,
                         INSTR(A.INTEGRATION_ID, '~', 1, 2) + 1,
                         INSTR(A.INTEGRATION_ID, '~', 1, 3) -
                         INSTR(A.INTEGRATION_ID, '~', 1, 2) - 1) || '~' ||
                  A.RTL_TYPE_CODE || '~' || A.VOUCHER_FLG) INTEGRATION_ID,
              MAX(A.LOC_CURR_CODE) LOC_CURR_CODE,
              MAX(A.LOC_EXCHANGE_RATE) LOC_EXCHANGE_RATE,
              MAX(A.TENANT_ID) TENANT_ID,
              SYSDATE W_INSERT_DT,
              SYSDATE W_UPDATE_DT,
              MAX(A.X_CUSTOM) X_CUSTOM,
              A.BBG_RETAIL_TYPE_WID,
              MAX(A.BBG_CUSTOMER_COUNT) BBG_CUSTOMER_COUNT,
              MAX(A.BBG_SERVICE_SATISFACTION) BBG_SERVICE_SATISFACTION,
              MAX(A.BBG_REFERENCE_DO1) BBG_REFERENCE_DO1,
              MAX(A.BBG_REFERENCE_DO2) BBG_REFERENCE_DO2,
              MAX(A.BBG_REFERENCE_DO3) BBG_REFERENCE_DO3,
              MAX(A.BBG_REFERENCE_DO4) BBG_REFERENCE_DO4,
              MAX(A.BBG_REFERENCE_DO5) BBG_REFERENCE_DO5,
              SUM(A.BBG_REFERENCE_FO1) BBG_REFERENCE_FO1,
              SUM(A.BBG_REFERENCE_FO2) BBG_REFERENCE_FO2,
              MAX(A.BBG_REFERENCE_FO3) BBG_REFERENCE_FO3,
              MAX(A.BBG_REFERENCE_FO4) BBG_REFERENCE_FO4,
              MAX(A.BBG_REFERENCE_FO5) BBG_REFERENCE_FO5,
              MAX(A.BBG_REFERENCE_FO6) BBG_REFERENCE_FO6,
              MAX(A.BBG_REFERENCE_FO7) BBG_REFERENCE_FO7,
              MAX(A.BBG_REFERENCE_FO8) BBG_REFERENCE_FO8,
              MAX(A.BBG_REFERENCE_FO9) BBG_REFERENCE_FO9,
              MAX(A.BBG_REFERENCE_FO10) BBG_REFERENCE_FO10
         FROM RADM.W_RTL_SLS_IT_LC_DY_A A
        WHERE A.DT_WID BETWEEN &BDTWID AND &EDTWID
        GROUP BY A.ORG_WID,
                 A.DT_WID,
                 A.RTL_TYPE_WID,
                 A.VOUCHER_FLG,
                 A.BBG_RETAIL_TYPE_WID) S
ON (T.ORG_WID = S.ORG_WID and T.ORG_DH_WID = S.ORG_DH_WID and T.ORG_SCD1_WID = S.ORG_SCD1_WID and T.DT_WID = S.DT_WID and T.RTL_TYPE_WID = S.RTL_TYPE_WID and T.VOUCHER_FLG = S.VOUCHER_FLG and T.ETL_PROC_WID = S.ETL_PROC_WID and T.BBG_RETAIL_TYPE_WID = S.BBG_RETAIL_TYPE_WID)
when matched then
  update
     set T.DATASOURCE_NUM_ID        = S.DATASOURCE_NUM_ID,
         T.DELETE_FLG               = S.DELETE_FLG,
         T.DOC_CURR_CODE            = S.DOC_CURR_CODE,
         T.GLOBAL1_EXCHANGE_RATE    = S.GLOBAL1_EXCHANGE_RATE,
         T.GLOBAL2_EXCHANGE_RATE    = S.GLOBAL2_EXCHANGE_RATE,
         T.GLOBAL3_EXCHANGE_RATE    = S.GLOBAL3_EXCHANGE_RATE,
         T.INTEGRATION_ID           = S.INTEGRATION_ID,
         T.LOC_CURR_CODE            = S.LOC_CURR_CODE,
         T.LOC_EXCHANGE_RATE        = S.LOC_EXCHANGE_RATE,
         T.TENANT_ID                = S.TENANT_ID,
         T.W_INSERT_DT              = S.W_INSERT_DT,
         T.W_UPDATE_DT              = S.W_UPDATE_DT,
         T.X_CUSTOM                 = S.X_CUSTOM,
         T.BBG_CUSTOMER_COUNT       = S.BBG_CUSTOMER_COUNT,
         T.BBG_SERVICE_SATISFACTION = S.BBG_SERVICE_SATISFACTION,
         T.BBG_REFERENCE_DO1        = S.BBG_REFERENCE_DO1,
         T.BBG_REFERENCE_DO2        = S.BBG_REFERENCE_DO2,
         T.BBG_REFERENCE_DO3        = S.BBG_REFERENCE_DO3,
         T.BBG_REFERENCE_DO4        = S.BBG_REFERENCE_DO4,
         T.BBG_REFERENCE_DO5        = S.BBG_REFERENCE_DO5,
         T.BBG_REFERENCE_FO1        = S.BBG_REFERENCE_FO1,
         T.BBG_REFERENCE_FO2        = S.BBG_REFERENCE_FO2,
         T.BBG_REFERENCE_FO3        = S.BBG_REFERENCE_FO3,
         T.BBG_REFERENCE_FO4        = S.BBG_REFERENCE_FO4,
         T.BBG_REFERENCE_FO5        = S.BBG_REFERENCE_FO5,
         T.BBG_REFERENCE_FO6        = S.BBG_REFERENCE_FO6,
         T.BBG_REFERENCE_FO7        = S.BBG_REFERENCE_FO7,
         T.BBG_REFERENCE_FO8        = S.BBG_REFERENCE_FO8,
         T.BBG_REFERENCE_FO9        = S.BBG_REFERENCE_FO9,
         T.BBG_REFERENCE_FO10       = S.BBG_REFERENCE_FO10,
         T.SLS_QTY                  = S.SLS_QTY,
         T.SLS_AMT_LCL              = S.SLS_AMT_LCL,
         T.SLS_PROFIT_AMT_LCL       = S.SLS_PROFIT_AMT_LCL,
         T.SLS_MANUAL_MKDN_AMT_LCL  = S.SLS_MANUAL_MKDN_AMT_LCL,
         T.SLS_MANUAL_MKUP_AMT_LCL  = S.SLS_MANUAL_MKUP_AMT_LCL,
         T.SLS_TAX_AMT_LCL          = S.SLS_TAX_AMT_LCL,
         T.SLS_EMP_DISC_AMT_LCL     = S.SLS_EMP_DISC_AMT_LCL,
         T.SLS_TRX_COUNT            = S.SLS_TRX_COUNT,
         T.RET_QTY                  = S.RET_QTY,
         T.RET_AMT_LCL              = S.RET_AMT_LCL,
         T.RET_PROFIT_AMT_LCL       = S.RET_PROFIT_AMT_LCL,
         T.RET_MANUAL_MKDN_AMT_LCL  = S.RET_MANUAL_MKDN_AMT_LCL,
         T.RET_MANUAL_MKUP_AMT_LCL  = S.RET_MANUAL_MKUP_AMT_LCL,
         T.RET_TAX_AMT_LCL          = S.RET_TAX_AMT_LCL,
         T.RET_EMP_DISC_AMT_LCL     = S.RET_EMP_DISC_AMT_LCL,
         T.RET_TRX_COUNT            = S.RET_TRX_COUNT
when not matched then
  insert
    (T.ROW_WID,
     T.ORG_WID,
     T.ORG_DH_WID,
     T.ORG_SCD1_WID,
     T.DT_WID,
     T.RTL_TYPE_WID,
     T.VOUCHER_FLG,
     T.SLS_QTY,
     T.SLS_AMT_LCL,
     T.SLS_PROFIT_AMT_LCL,
     T.SLS_MANUAL_MKDN_AMT_LCL,
     T.SLS_MANUAL_MKUP_AMT_LCL,
     T.SLS_TAX_AMT_LCL,
     T.SLS_EMP_DISC_AMT_LCL,
     T.SLS_TRX_COUNT,
     T.RET_QTY,
     T.RET_AMT_LCL,
     T.RET_PROFIT_AMT_LCL,
     T.RET_MANUAL_MKDN_AMT_LCL,
     T.RET_MANUAL_MKUP_AMT_LCL,
     T.RET_TAX_AMT_LCL,
     T.RET_EMP_DISC_AMT_LCL,
     T.RET_TRX_COUNT,
     T.DATASOURCE_NUM_ID,
     T.DELETE_FLG,
     T.DOC_CURR_CODE,
     T.ETL_PROC_WID,
     T.GLOBAL1_EXCHANGE_RATE,
     T.GLOBAL2_EXCHANGE_RATE,
     T.GLOBAL3_EXCHANGE_RATE,
     T.INTEGRATION_ID,
     T.LOC_CURR_CODE,
     T.LOC_EXCHANGE_RATE,
     T.TENANT_ID,
     T.W_INSERT_DT,
     T.W_UPDATE_DT,
     T.X_CUSTOM,
     T.BBG_RETAIL_TYPE_WID,
     T.BBG_CUSTOMER_COUNT,
     T.BBG_SERVICE_SATISFACTION,
     T.BBG_REFERENCE_DO1,
     T.BBG_REFERENCE_DO2,
     T.BBG_REFERENCE_DO3,
     T.BBG_REFERENCE_DO4,
     T.BBG_REFERENCE_DO5,
     T.BBG_REFERENCE_FO1,
     T.BBG_REFERENCE_FO2,
     T.BBG_REFERENCE_FO3,
     T.BBG_REFERENCE_FO4,
     T.BBG_REFERENCE_FO5,
     T.BBG_REFERENCE_FO6,
     T.BBG_REFERENCE_FO7,
     T.BBG_REFERENCE_FO8,
     T.BBG_REFERENCE_FO9,
     T.BBG_REFERENCE_FO10)
  values
    (RADM.W_RTL_SLS_LC_DY_A_SEQ.NEXTVAL,
     S.ORG_WID,
     S.ORG_DH_WID,
     S.ORG_SCD1_WID,
     S.DT_WID,
     S.RTL_TYPE_WID,
     S.VOUCHER_FLG,
     S.SLS_QTY,
     S.SLS_AMT_LCL,
     S.SLS_PROFIT_AMT_LCL,
     S.SLS_MANUAL_MKDN_AMT_LCL,
     S.SLS_MANUAL_MKUP_AMT_LCL,
     S.SLS_TAX_AMT_LCL,
     S.SLS_EMP_DISC_AMT_LCL,
     S.SLS_TRX_COUNT,
     S.RET_QTY,
     S.RET_AMT_LCL,
     S.RET_PROFIT_AMT_LCL,
     S.RET_MANUAL_MKDN_AMT_LCL,
     S.RET_MANUAL_MKUP_AMT_LCL,
     S.RET_TAX_AMT_LCL,
     S.RET_EMP_DISC_AMT_LCL,
     S.RET_TRX_COUNT,
     S.DATASOURCE_NUM_ID,
     S.DELETE_FLG,
     S.DOC_CURR_CODE,
     S.ETL_PROC_WID,
     S.GLOBAL1_EXCHANGE_RATE,
     S.GLOBAL2_EXCHANGE_RATE,
     S.GLOBAL3_EXCHANGE_RATE,
     S.INTEGRATION_ID,
     S.LOC_CURR_CODE,
     S.LOC_EXCHANGE_RATE,
     S.TENANT_ID,
     S.W_INSERT_DT,
     S.W_UPDATE_DT,
     S.X_CUSTOM,
     S.BBG_RETAIL_TYPE_WID,
     S.BBG_CUSTOMER_COUNT,
     S.BBG_SERVICE_SATISFACTION,
     S.BBG_REFERENCE_DO1,
     S.BBG_REFERENCE_DO2,
     S.BBG_REFERENCE_DO3,
     S.BBG_REFERENCE_DO4,
     S.BBG_REFERENCE_DO5,
     S.BBG_REFERENCE_FO1,
     S.BBG_REFERENCE_FO2,
     S.BBG_REFERENCE_FO3,
     S.BBG_REFERENCE_FO4,
     S.BBG_REFERENCE_FO5,
     S.BBG_REFERENCE_FO6,
     S.BBG_REFERENCE_FO7,
     S.BBG_REFERENCE_FO8,
     S.BBG_REFERENCE_FO9,
     S.BBG_REFERENCE_FO10);
COMMIT;
