--例子
SELECT /*+PARALEL(BBG_RA_ITEM_LOC_D,20)*/
 ROW_WID,
 ITEM,
 LOC,
 EFFECTIVE_FROM_DT,
 EFFECTIVE_TO_DT,
 LAG(Effective_TO_DT) Over(Partition By Item, Loc Order By Effective_TO_DT) + 1 NEW_EFFECTIVE_FROM_DT
  FROM BBG_RA_ITEM_LOC_D
 WHERE ITEM = 2400071025437
   AND LOC = 139122;

--创建视图   
CREATE MATERIALIZED VIEW BBG_RA_ITEM_D_CHECK_TMP AS
SELECT "ROW_WID","ITEM","LOC","EFFECTIVE_FROM_DT","EFFECTIVE_TO_DT","NEW_EFFECTIVE_FROM_DT"
  FROM (SELECT /*+PARALEL(BBG_RA_ITEM_LOC_D,20)*/
         ROW_WID,
         ITEM,
         LOC,
         EFFECTIVE_FROM_DT,
         EFFECTIVE_TO_DT,
         LAG(Effective_TO_DT) Over(Partition By Item, Loc Order By Effective_TO_DT) + 1 NEW_EFFECTIVE_FROM_DT
          FROM BBG_RA_ITEM_LOC_D)
 WHERE EFFECTIVE_FROM_DT <> NEW_EFFECTIVE_FROM_DT;

DROP MATERIALIZED VIEW RADM.BBG_RA_ITEM_D_CHECK_TMP;



--修复语句
UPDATE RADM.BBG_RA_ITEM_LOC_D T
   SET T.EFFECTIVE_FROM_DT =
       (SELECT A.NEW_EFFECTIVE_FROM_DT
          FROM RADM.BBG_RA_ITEM_D_CHECK_TMP A
         WHERE T.ROW_WID = A.ROW_WID
           AND T.EFFECTIVE_FROM_DT <> A.NEW_EFFECTIVE_FROM_DT)
					 AND EXISTS(SELECT 1 FROM RADM.BBG_RA_ITEM_D_CHECK_TMP B WHERE T.ROW_WID=B.ROW_WID);

SELECT * FROM RADM.BBG_RA_ITEM_LOC_D T WHERE T.ROW_WID = 66668188;
