SELECT * FROM CMX_CONTRACT_RESULT;--合同费用结果表
SELECT * FROM CMX_FUND_RESULT;--销售补差结果表

SELECT * FROM CMX_CODE_DETAIL T WHERE T.CODE_TYPE='CTRSRTP';
SELECT * FROM CMX_CODE_DETAIL T WHERE T.CODE_TYPE='CKIN';

SELECT DISTINCT FUND_TYPE FROM cmx_fund_result;
SELECT * FROM CMX_CODE_DETAIL T WHERE T.CODE='PR';
SELECT * FROM CMX_CODE_DETAIL T WHERE T.CODE_TYPE='XPRT';

SELECT * FROM cmx_fund_result t where t.fund_method is not null;
select * from cmx_contract_options;

SELECT COUNT(*) FROM CMX_CONTRACT_RESULT;
SELECT COUNT(*) FROM CMX_FUND_RESULT;
