--1.CREATE TABLE
CREATE TABLE RADM.BBG_RA_CUST_TMP_201608 AS SELECT * FROM BBG_RA_CUST_IT_LC_DY_F WHERE 1=2;

--2.drop index
--2.1.BBG_RA_CUST_IT_LC_DY_F
ALTER TABLE BBG_RA_CUST_IT_LC_DY_F
  DROP CONSTRAINT PK_BBG_RA_CUST_IT_LC_DY_F CASCADE;
  
DROP INDEX PK_BBG_RA_CUST_IT_LC_DY_F;  
--2.2.BBG_RA_CUST_IT_LC_DY_F_HIST
ALTER TABLE BBG_RA_CUST_IT_LC_DY_F_HIST
  DROP CONSTRAINT PK_BBG_RA_CUST_IT_LC_DY_F_HIST CASCADE;
  
DROP INDEX PK_BBG_RA_CUST_IT_LC_DY_F_HIST;  

--3.EXCHANGE PARTITION
ALTER TABLE RADM.BBG_RA_CUST_IT_LC_DY_F EXCHANGE PARTITION BBG_RA_CUST_IT_LC_DY_F_201608 WITH TABLE BBG_RA_CUST_TMP_201608;
ALTER TABLE RADM.BBG_RA_CUST_IT_LC_DY_F_HIST EXCHANGE PARTITION BBGRA_CUST_IT_LC_DY_F_H_201608 WITH TABLE BBG_RA_CUST_TMP_201608;

--4.CREATE INDEX
--4.1.BBG_RA_CUST_IT_LC_DY_F
CREATE UNIQUE INDEX RADM.PK_BBG_RA_CUST_IT_LC_DY_F ON RADM.BBG_RA_CUST_IT_LC_DY_F
(PROD_WID, ORG_WID, DT_WID, BBG_ITEM_LOC_WID)
NOLOGGING
TABLESPACE DM_FACT_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL 10
INVISIBLE;
  
ALTER TABLE BBG_RA_CUST_IT_LC_DY_F
  ADD CONSTRAINT PK_BBG_RA_CUST_IT_LC_DY_F PRIMARY KEY (PROD_WID, ORG_WID, DT_WID, BBG_ITEM_LOC_WID)
  USING INDEX 
  TABLESPACE DM_FACT_INDEX
  PCTFREE 10
  INITRANS 12
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
	
ALTER INDEX PK_BBG_RA_CUST_IT_LC_DY_F LOGGING;
ALTER INDEX PK_BBG_RA_CUST_IT_LC_DY_F PARALLEL 1;

--4.2.BBG_RA_CUST_IT_LC_DY_F_HIST
CREATE UNIQUE INDEX RADM.PK_BBG_RA_CUST_IT_LC_DY_F_HIST ON RADM.BBG_RA_CUST_IT_LC_DY_F_HIST
(PROD_WID, ORG_WID, DT_WID, BBG_ITEM_LOC_WID)
NOLOGGING
TABLESPACE DM_FACT_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL 10
INVISIBLE;
  
ALTER TABLE BBG_RA_CUST_IT_LC_DY_F_HIST
  ADD CONSTRAINT PK_BBG_RA_CUST_IT_LC_DY_F_HIST PRIMARY KEY (PROD_WID, ORG_WID, DT_WID, BBG_ITEM_LOC_WID)
  USING INDEX 
  TABLESPACE DM_FACT_INDEX
  PCTFREE 10
  INITRANS 12
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
	
ALTER INDEX PK_BBG_RA_CUST_IT_LC_DY_F_HIST LOGGING;
ALTER INDEX PK_BBG_RA_CUST_IT_LC_DY_F_HIST PARALLEL 1;

--5.DBMS_STATS
BEGIN
  DBMS_STATS.GATHER_TABLE_STATS(OWNNAME          => 'RADM',
                                TABNAME          => 'BBG_RA_CUST_IT_LC_DY_F',
                                GRANULARITY      => 'ALL',
                                DEGREE           => 8,
                                ESTIMATE_PERCENT => SYS.DBMS_STATS.AUTO_SAMPLE_SIZE,
                                CASCADE          => TRUE);
  DBMS_STATS.GATHER_TABLE_STATS(OWNNAME          => 'RADM',
                                TABNAME          => 'BBG_RA_CUST_IT_LC_DY_F_HIST',
                                GRANULARITY      => 'ALL',
                                DEGREE           => 8,
                                ESTIMATE_PERCENT => SYS.DBMS_STATS.AUTO_SAMPLE_SIZE,
                                CASCADE          => TRUE);
END;
/
