--1.CREATE TABLE
CREATE TABLE RADM.BBG_RA_SLS_TMP_201608 AS SELECT * FROM BBG_RA_SLS_IT_LC_DY_A WHERE 1=2;

--2.DROP INDEX
--2.1.BBG_RA_SLS_IT_LC_DY_A
ALTER TABLE BBG_RA_SLS_IT_LC_DY_A
  DROP CONSTRAINT PK_BBG_RA_SLS_IT_LC_DY_A CASCADE;
  
DROP INDEX PK_BBG_RA_SLS_IT_LC_DY_A; 

--2.2.BBG_RA_SLS_IT_LC_DY_A_HIST
ALTER TABLE BBG_RA_SLS_IT_LC_DY_A_HIST
  DROP CONSTRAINT PK_BBG_RA_SLS_IT_LC_DY_A_HIST CASCADE;
  
DROP INDEX PK_BBG_RA_SLS_IT_LC_DY_A_HIST; 

--3.EXCHANGE PARTITION
ALTER TABLE RADM.BBG_RA_SLS_IT_LC_DY_A EXCHANGE PARTITION BBG_RA_SLS_IT_LC_DY_A_201608 WITH TABLE BBG_RA_SLS_TMP_201608;
ALTER TABLE RADM.BBG_RA_SLS_IT_LC_DY_A_HIST EXCHANGE PARTITION BBG_RA_SLS_IT_LC_DY_A_201608 WITH TABLE BBG_RA_SLS_TMP_201608;

--4.CREATE INDEX
--4.1.BBG_RA_SLS_IT_LC_DY_A
CREATE UNIQUE INDEX RADM.PK_BBG_RA_SLS_IT_LC_DY_A ON RADM.BBG_RA_SLS_IT_LC_DY_A
(PROD_WID, ORG_WID, DT_WID, SUPPLIER_WID)
NOLOGGING
TABLESPACE DM_FACT_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL 10
INVISIBLE;
  
ALTER TABLE BBG_RA_SLS_IT_LC_DY_A
  ADD CONSTRAINT PK_BBG_RA_SLS_IT_LC_DY_A PRIMARY KEY (PROD_WID, ORG_WID, DT_WID, SUPPLIER_WID)
  USING INDEX 
  TABLESPACE DM_FACT_INDEX
  PCTFREE 10
  INITRANS 12
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
	
ALTER INDEX PK_BBG_RA_SLS_IT_LC_DY_A LOGGING;
ALTER INDEX PK_BBG_RA_SLS_IT_LC_DY_A PARALLEL 1;

--4.2.BBG_RA_SLS_IT_LC_DY_A_HIST
CREATE UNIQUE INDEX RADM.PK_BBG_RA_SLS_IT_LC_DY_A_HIST ON RADM.BBG_RA_SLS_IT_LC_DY_A_HIST
(PROD_WID, ORG_WID, DT_WID, SUPPLIER_WID)
NOLOGGING
TABLESPACE DM_FACT_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL 10
INVISIBLE;
  
ALTER TABLE BBG_RA_SLS_IT_LC_DY_A_HIST
  ADD CONSTRAINT PK_BBG_RA_SLS_IT_LC_DY_A_HIST PRIMARY KEY (PROD_WID, ORG_WID, DT_WID, SUPPLIER_WID)
  USING INDEX 
  TABLESPACE DM_FACT_INDEX
  PCTFREE 10
  INITRANS 12
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
	
ALTER INDEX PK_BBG_RA_SLS_IT_LC_DY_A_HIST LOGGING;
ALTER INDEX PK_BBG_RA_SLS_IT_LC_DY_A_HIST PARALLEL 1;

--5.DBMS_STATS
BEGIN
  DBMS_STATS.GATHER_TABLE_STATS(OWNNAME => 'RADM',
                                TABNAME => 'BBG_RA_SLS_IT_LC_DY_A',
                                GRANULARITY      => 'ALL',
                                DEGREE           => 8,
                                ESTIMATE_PERCENT => SYS.DBMS_STATS.AUTO_SAMPLE_SIZE,
                                CASCADE          => TRUE);
  DBMS_STATS.GATHER_TABLE_STATS(OWNNAME => 'RADM',
                                TABNAME => 'BBG_RA_SLS_IT_LC_DY_A_HIST',
                                GRANULARITY      => 'ALL',
                                DEGREE           => 8,
                                ESTIMATE_PERCENT => SYS.DBMS_STATS.AUTO_SAMPLE_SIZE,
                                CASCADE          => TRUE);
END;
/
