--1.CREATE TABLE
CREATE TABLE RADM.W_RTL_NCOST_TMP_201608 AS SELECT * FROM W_RTL_NCOST_IT_DY_A WHERE 1=2;

--2.DROP INDEX
--2.1.W_RTL_NCOST_IT_DY_A
ALTER TABLE W_RTL_NCOST_IT_DY_A
  DROP CONSTRAINT PK_W_RTL_NCOST_IT_DY_A CASCADE;
  
DROP INDEX PK_W_RTL_NCOST_IT_DY_A;  
--2.2.

--2.EXCHANGE PARTITION
ALTER TABLE RADM.W_RTL_NCOST_IT_DY_A EXCHANGE PARTITION W_RTL_NCOST_IT_DY_A_201608 WITH TABLE W_RTL_NCOST_TMP_201608;
ALTER TABLE RADM.W_RTL_NCOST_IT_DY_A_HIST EXCHANGE PARTITION W_RTL_NCOST_IT_DY_A_201608 WITH TABLE W_RTL_NCOST_TMP_201608;

--3.CREATE INDEX
CREATE UNIQUE INDEX RADM.PK_W_RTL_NCOST_IT_DY_A ON RADM.W_RTL_NCOST_IT_DY_A
(PROD_WID, SUPPLIER_WID, DT_WID)
NOLOGGING
TABLESPACE DM_FACT_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL 10
INVISIBLE;
  
ALTER TABLE W_RTL_NCOST_IT_DY_A
  ADD CONSTRAINT PK_W_RTL_NCOST_IT_DY_A PRIMARY KEY (PROD_WID, SUPPLIER_WID, DT_WID)
  USING INDEX 
  TABLESPACE DM_FACT_INDEX
  PCTFREE 10
  INITRANS 12
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
	
ALTER INDEX PK_W_RTL_NCOST_IT_DY_A LOGGING;
ALTER INDEX PK_W_RTL_NCOST_IT_DY_A PARALLEL 1;

--4.DBMS_STATS
BEGIN
  DBMS_STATS.GATHER_TABLE_STATS(OWNNAME          => 'RADM',
                                TABNAME          => 'W_RTL_NCOST_IT_DY_A',
                                GRANULARITY      => 'ALL',
                                DEGREE           => 8,
                                ESTIMATE_PERCENT => SYS.DBMS_STATS.AUTO_SAMPLE_SIZE,
                                CASCADE          => TRUE);
  DBMS_STATS.GATHER_TABLE_STATS(OWNNAME          => 'RADM',
                                TABNAME          => 'W_RTL_NCOST_IT_DY_A_HIST',
                                GRANULARITY      => 'ALL',
                                DEGREE           => 8,
                                ESTIMATE_PERCENT => SYS.DBMS_STATS.AUTO_SAMPLE_SIZE,
                                CASCADE          => TRUE);
END;
/
