--商品库存
--G表
SELECT * FROM RADM.W_RTL_INV_IT_LC_G;
--F视图
SELECT * FROM RADM.W_RTL_INV_IT_LC_DY_FV F WHERE F.DT_WID = 120150114000;

--
SELECT /*+PARALLEL(F,20)*/ *
  FROM RADM.W_RTL_INV_IT_LC_G G
 WHERE G.PROD_SCD1_WID = 654833
   AND G.ORG_SCD1_WID = 96;
--
SELECT /*+PARALLEL(F,20)*/ *
  FROM RADM.W_RTL_INV_IT_LC_DY_FV F
 WHERE F.DT_WID = 120150115000
   AND F.PROD_SCD1_WID = 654833
   AND F.ORG_SCD1_WID = 96;
--
SELECT T.ROW_WID, T.SCD1_WID, T.PROD_NUM
  FROM RADM.W_PRODUCT_D T
 WHERE T.SCD1_WID = 654833;

SELECT T.ROW_WID, T.SCD1_WID, T.ORG_NUM
  FROM RADM.W_INT_ORG_D T
 WHERE T.SCD1_WID = 96;
 
SELECT *
  FROM RADM.W_RTL_INV_IT_LC_DY_FS T
 WHERE T.PROD_IT_NUM = '800041767'
 AND T.ORG_NUM='120008';

SELECT /*+PARALLEL(G,20) PARALLEL(F,20)*/
 F.PROD_SCD1_WID,
 F.ORG_SCD1_WID,
 G.PROD_IT_NUM,
 G.ORG_NUM,
 F.INV_SOH_QTY   F_INV_SOH_QTY,
 G.INV_SOH_QTY   G_INV_SOH_QTY
  FROM RADM.W_RTL_INV_IT_LC_G G, RADM.W_RTL_INV_IT_LC_DY_FV F
 WHERE G.PROD_SCD1_WID(+) = F.PROD_SCD1_WID
   AND G.ORG_SCD1_WID(+) = F.ORG_SCD1_WID
   AND F.DT_WID = 120150115000
   AND NVL(F.INV_SOH_QTY, 0) <> NVL(G.INV_SOH_QTY, 0);
