/*
供应商库存数据都是从BBG_RA_SUPP_INV_IT_LC_G聚合出来的,但是每天的供应商库存是增量传入RA.
BBG_RA_SUPP_INV_FV_SRC,
BBG_RA_SUP_INV_IT_LC_DY_FS,
BBG_RA_SUPP_INV_IT_LC_DY_TMP
以上为增量表
BBG_RA_SUPP_INV_IT_LC_G为全量表
*/

SELECT SUM(T.SUPP_INV_QTY), SUM(T.SUPP_INV_COST)
  FROM RADM.BBG_RA_SUPP_INV_IT_DY_A T
 WHERE T.DT_WID = 120141209000;

SELECT SUM(T.SUPP_INV_QTY), SUM(T.SUPP_INV_COST)
  FROM BBG_RA_SUP_INV_IT_LC_DY_FS T
 WHERE T.DAY_DT = DATE '2014-12-09';

SELECT SUM(T.SUPP_INV_QTY), SUM(T.SUPP_INV_COST)
  FROM BBG_RA_SUPP_INV_IT_LC_DY_TMP T
 WHERE T.DT_WID = 120141209000;

SELECT SUM(T.SUPP_INV_QTY), SUM(T.SUPP_INV_COST)
  FROM BBG_RA_SUPP_INV_IT_LC_G T;

--RMS 
SELECT T.ITEM,
       T.LOC,
       T.SUPPLIER,
       SUM(T.SOH) SUPP_INV_QTY,
       SUM(T.WAC * T.SOH) SUPP_INV_COST
  FROM (SELECT A.ITEM, A.LOC, A.SUPPLIER, A.SOH, A.WAC
          FROM RMS.CMX_SUPP_INV A
        UNION ALL
        SELECT B.ITEM, B.LOC, B.SUPPLIER, B.SOH, B.WAC
          FROM RMS.CMX_SUPP_INV_HIST B) T
 WHERE NOT EXISTS (SELECT 1
          FROM WH W
         WHERE W.REDIST_WH_IND = 'Y'
           AND W.WH = T.LOC)
 GROUP BY T.ITEM, T.LOC, T.SUPPLIER;

--RA
SELECT G.PROD_IT_NUM,
       G.ORG_NUM,
       G.SUPPLIER_NUM,
       SUM(G.SUPP_INV_QTY) SUPP_INV_QTY,
       SUM(G.SUPP_INV_COST) SUPP_INV_COST
  FROM RADM.BBG_RA_SUPP_INV_IT_LC_G G
 GROUP BY G.PROD_IT_NUM, G.ORG_NUM, G.SUPPLIER_NUM;

--CHECK
CREATE TABLE RADM.JIN_SUPP_INV_RA_RMS_DIF_TMP AS
  SELECT *
    FROM (SELECT T.ITEM,
                 T.LOC,
                 T.SUPPLIER,
                 SUM(T.SOH) RMS_SUPP_INV_QTY,
                 SUM(T.WAC * T.SOH) RMS_SUPP_INV_COST
            FROM (SELECT A.ITEM, A.LOC, A.SUPPLIER, A.SOH, A.WAC
                    FROM RMS.CMX_SUPP_INV@RA_RMS_DBLINK A
                  UNION ALL
                  SELECT B.ITEM, B.LOC, B.SUPPLIER, B.SOH, B.WAC
                    FROM RMS.CMX_SUPP_INV_HIST@RA_RMS_DBLINK B) T
           WHERE NOT EXISTS (SELECT 1
                    FROM WH@RA_RMS_DBLINK W
                   WHERE W.REDIST_WH_IND = 'Y'
                     AND W.WH = T.LOC)
           GROUP BY T.ITEM, T.LOC, T.SUPPLIER) RMS,
         (SELECT G.PROD_IT_NUM,
                 G.ORG_NUM,
                 G.SUPPLIER_NUM,
                 SUM(G.SUPP_INV_QTY) RA_SUPP_INV_QTY,
                 SUM(G.SUPP_INV_COST) RA_SUPP_INV_COST
            FROM RADM.BBG_RA_SUPP_INV_IT_LC_G G
           GROUP BY G.PROD_IT_NUM, G.ORG_NUM, G.SUPPLIER_NUM) RA
   WHERE RMS.ITEM = RA.PROD_IT_NUM
     AND RMS.LOC = RA.ORG_NUM
     AND RMS.SUPPLIER = RA.SUPPLIER_NUM
     AND (ROUND(RMS.RMS_SUPP_INV_QTY, 4) <> ROUND(RA.RA_SUPP_INV_QTY, 4) OR
         ROUND(RMS.RMS_SUPP_INV_COST, 4) <> ROUND(RA.RA_SUPP_INV_COST, 4));

--DETAIL
--RADM
SELECT *
  FROM RADM.BBG_RA_SUPP_INV_IT_LC_G G
 WHERE G.PROD_IT_NUM = '800362027'
   AND G.ORG_NUM = '120148'
   AND G.SUPPLIER_NUM = '12000447';
--RMS
SELECT *
  FROM RMS.CMX_SUPP_INV@RA_RMS_DBLINK I
 WHERE I.ITEM = '800362027'
   AND I.LOC = '120148'
   AND I.SUPPLIER = '12000447';

--*******************************************************************************************************************  
--*******************************************************************************************************************
--商品库存核查
--*******************************************************************************************************************
--*******************************************************************************************************************
/*
W_RTL_INV_IT_LC_DY_TMP
W_RTL_INV_IT_LC_DY_F
W_RTL_INV_IT_LC_G
ITEM_LOC_SOH_HIST
*/

SELECT T.DAY_DT,
       SUM(T.INV_SOH_QTY) INV_SOH_QTY,
       SUM(T.INV_SOH_COST_AMT_LCL) INV_SOH_COST_AMT_LCL
  FROM RABATCHER.W_RTL_INV_IT_LC_DY_TMP T
 GROUP BY T.DAY_DT;

SELECT T.DT_WID,
       SUM(T.INV_SOH_QTY) INV_SOH_QTY,
       SUM(T.INV_SOH_COST_AMT_LCL) INV_SOH_COST_AMT_LCL
  FROM RADM.W_RTL_INV_IT_LC_DY_FV T
 WHERE T.DT_WID = 120141214000
 GROUP BY T.DT_WID;

SELECT SUM(T.INV_SOH_QTY) INV_SOH_QTY,
       SUM(T.INV_SOH_COST_AMT_LCL) INV_SOH_COST_AMT_LCL
  FROM RADM.W_RTL_INV_IT_LC_G T;

SELECT T.SOH_BAK_DATE,
       SUM(T.STOCK_ON_HAND),
       SUM(T.STOCK_ON_HAND * T.AV_COST)
  FROM ITEM_LOC_SOH_HIST@RA_RMS_DBLINK T
 WHERE T.SOH_BAK_DATE = DATE '2014-12-14'
 GROUP BY T.SOH_BAK_DATE;

--
SELECT T.ITEM, T.LOC, T.STOCK_ON_HAND, T.STOCK_ON_HAND * T.AV_COST COST
  FROM ITEM_LOC_SOH_HIST@RA_RMS_DBLINK T
 WHERE T.SOH_BAK_DATE = DATE '2014-12-14';

SELECT T.,
       SUM(T.INV_SOH_QTY) INV_SOH_QTY,
       SUM(T.INV_SOH_COST_AMT_LCL) INV_SOH_COST_AMT_LCL
  FROM RADM.W_RTL_INV_IT_LC_DY_FV T
 WHERE T.DT_WID = 120141214000
 GROUP BY T.DT_WID;

