--1.
SELECT * FROM RADM.BBG_RA_10STORE_LOC_DAILY_VIEW;
SELECT * FROM RADM.BBG_RA_10STORE_LOC_MONTH_VIEW;
SELECT * FROM RADM.BBG_RA_10STORE_DP_DAILY_VIEW;
--2.
CREATE OR REPLACE VIEW RMS.BBG_RA_10STORE_LOC_DAILY_VIEW AS
SELECT * FROM RADM.BBG_RA_10STORE_LOC_DAILY_VIEW@RMS_RA;

CREATE OR REPLACE VIEW RMS.BBG_RA_10STORE_LOC_MONTH_VIEW AS
SELECT * FROM RADM.BBG_RA_10STORE_LOC_MONTH_VIEW@RMS_RA;

CREATE OR REPLACE VIEW RMS.BBG_RA_10STORE_DP_DAILY_VIEW AS
SELECT * FROM RADM.BBG_RA_10STORE_DP_DAILY_VIEW@RMS_RA;

--3.
SELECT * FROM RMS.BBG_RA_10STORE_LOC_DAILY_VIEW;
SELECT * FROM RMS.BBG_RA_10STORE_LOC_MONTH_VIEW;
SELECT * FROM RMS.BBG_RA_10STORE_DP_DAILY_VIEW;


