ksh      slsslwcurrrcplp.ksh
ksh      wfslsidplp.ksh
ksh      wfslsilwplp.ksh
ksh      wfslsiwplp.ksh
ksh      wfslssldcurrplp.ksh
ksh      wfslssldcurrrcplp.ksh
ksh      wfslssldplp.ksh
ksh      wfslsslwcurrplp.ksh
ksh      wfslsslwcurrrcplp.ksh
ksh      wfslsslwplp.ksh
