

#!/bin/ksh

. $MMHOME/etc/ra.env


SCEN_NAME="SDE_RETAILSOURCELOADCONTROLSEEDDATA"
SYSDATE=`date +%Y%m%d`


startscen.sh $SCEN_NAME $VERSION $CONTEXT_INSTALL RA_BI.RA_SRC_BASE_HOME=$MMHOME GLOBAL.GET_ODI_HOME=$ODI_HOME GLOBAL.SYSTEM_DATE=$SYSDATE

