Delete W_RTL_PARTITION_MAP_G
where TABLE_NAME = 'W_RTL_ITEM_GRP1_DS'
and PARTITION_NAME = 'PART_ITEMLIST'
and FUNCTION_NAME = 'ITEMLIST';

Insert into W_RTL_PARTITION_MAP_G (TABLE_NAME,PARTITION_NAME,FUNCTION_NAME,FROM_VALUE,TO_VALUE,OWNER_NAME) values ('W_RTL_ITEM_GRP1_DS','PART_ITEMLIST','ITEMLIST',null,null,null);

Delete W_RTL_PARTITION_MAP_G
where TABLE_NAME = 'W_RTL_ITEM_GRP1_DS'
and PARTITION_NAME = 'PART_ITEMUDA'
and FUNCTION_NAME = 'ITEMUDA';

Insert into W_RTL_PARTITION_MAP_G (TABLE_NAME,PARTITION_NAME,FUNCTION_NAME,FROM_VALUE,TO_VALUE,OWNER_NAME) values ('W_RTL_ITEM_GRP1_DS','PART_ITEMUDA','ITEMUDA',null,null,null);

Delete W_RTL_PARTITION_MAP_G
where TABLE_NAME = 'W_RTL_ITEM_GRP1_DS'
and PARTITION_NAME = 'PART_ITEMDIFF'
and FUNCTION_NAME = 'ITEMDIFF';

Insert into W_RTL_PARTITION_MAP_G (TABLE_NAME,PARTITION_NAME,FUNCTION_NAME,FROM_VALUE,TO_VALUE,OWNER_NAME) values ('W_RTL_ITEM_GRP1_DS','PART_ITEMDIFF','ITEMDIFF',null,null,null);

Delete W_RTL_PARTITION_MAP_G
where TABLE_NAME = 'W_RTL_ITEM_GRP2_DS'
and PARTITION_NAME = 'PART_ITEM_PACK'
and FUNCTION_NAME = 'PACK';

Insert into W_RTL_PARTITION_MAP_G (TABLE_NAME,PARTITION_NAME,FUNCTION_NAME,FROM_VALUE,TO_VALUE,OWNER_NAME) values ('W_RTL_ITEM_GRP2_DS','PART_ITEM_PACK','PACK',null,null,null);

Commit;