/* Formatted on 2016/8/9 5:56:07 (QP5 v5.256.13226.35510) */
MERGE /*+ APPEND PARALLEL(8)*/
INTO RADM.BBG_RA_CUST_IT_LC_DY_F T
USING (SELECT /*+ APPEND PARALLEL(8)*/
        BBG_RA_CUST_IT_LC_DY_TMP.PROD_IT_WID              PROD_WID,
        BBG_RA_CUST_IT_LC_DY_TMP.PROD_SCD1_WID            PROD_SCD1_WID,
        BBG_RA_CUST_IT_LC_DY_TMP.ORG_WID                  ORG_WID,
        BBG_RA_CUST_IT_LC_DY_TMP.ORG_LC_WID               ORG_DH_WID,
        BBG_RA_CUST_IT_LC_DY_TMP.ORG_SCD1_WID             ORG_SCD1_WID,
        BBG_RA_CUST_IT_LC_DY_TMP.DT_WID                   DT_WID,
        BBG_RA_CUST_IT_LC_DY_TMP.BBG_ITEM_LOC_WID         BBG_ITEM_LOC_WID,
        BBG_RA_CUST_IT_LC_DY_TMP.BBG_CUSTOMER_COUNT       BBG_CUSTOMER_COUNT,
        BBG_RA_CUST_IT_LC_DY_TMP.BBG_SERVICE_SATISFACTION BBG_SERVICE_SATISFACTION,
        BBG_RA_CUST_IT_LC_DY_TMP.DATASOURCE_NUM_ID        DATASOURCE_NUM_ID,
        BBG_RA_CUST_IT_LC_DY_TMP.INTEGRATION_ID           INTEGRATION_ID,
        BBG_RA_CUST_IT_LC_DY_TMP.W_INSERT_DT              W_INSERT_DT,
        BBG_RA_CUST_IT_LC_DY_TMP.W_UPDATE_DT              W_UPDATE_DT
         FROM RABATCHER.BBG_RA_CUST_IT_LC_DY_TMP BBG_RA_CUST_IT_LC_DY_TMP
        WHERE (1 = 1)) S
ON (T.PROD_WID = S.PROD_WID AND T.ORG_WID = S.ORG_WID AND T.DT_WID = S.DT_WID AND T.BBG_ITEM_LOC_WID = S.BBG_ITEM_LOC_WID)
WHEN MATCHED THEN
  UPDATE
     SET T.PROD_SCD1_WID            = S.PROD_SCD1_WID,
         T.ORG_DH_WID               = S.ORG_DH_WID,
         T.ORG_SCD1_WID             = S.ORG_SCD1_WID,
         T.BBG_CUSTOMER_COUNT       = S.BBG_CUSTOMER_COUNT,
         T.BBG_SERVICE_SATISFACTION = S.BBG_SERVICE_SATISFACTION,
         T.DATASOURCE_NUM_ID        = S.DATASOURCE_NUM_ID,
         T.INTEGRATION_ID           = S.INTEGRATION_ID,
         T.W_INSERT_DT              = S.W_INSERT_DT,
         T.W_UPDATE_DT              = S.W_UPDATE_DT
WHEN NOT MATCHED THEN
  INSERT
    (T.ROW_WID,
     T.PROD_WID,
     T.PROD_SCD1_WID,
     T.ORG_WID,
     T.ORG_DH_WID,
     T.ORG_SCD1_WID,
     T.DT_WID,
     T.BBG_ITEM_LOC_WID,
     T.BBG_CUSTOMER_COUNT,
     T.BBG_SERVICE_SATISFACTION,
     T.DATASOURCE_NUM_ID,
     T.INTEGRATION_ID,
     T.W_INSERT_DT,
     T.W_UPDATE_DT)
  VALUES
    (RADM.BBG_RA_CUST_IT_LC_DY_F_SEQ.NEXTVAL,
     S.PROD_WID,
     S.PROD_SCD1_WID,
     S.ORG_WID,
     S.ORG_DH_WID,
     S.ORG_SCD1_WID,
     S.DT_WID,
     S.BBG_ITEM_LOC_WID,
     S.BBG_CUSTOMER_COUNT,
     S.BBG_SERVICE_SATISFACTION,
     S.DATASOURCE_NUM_ID,
     S.INTEGRATION_ID,
     S.W_INSERT_DT,
     S.W_UPDATE_DT)
