SELECT R.DAY DAYS,
       R.SUPP_SALES_COST REF_NET_SSC,
       S1.SUPP_SALES_COST RA_NET_SSC,
       R.SUPP_SALES_COST - S1.SUPP_SALES_COST DIFF1,
       R.SUPP_SALES_AMT REF_NET_SSA,
       S1.SUPP_SALES_AMT RA_NET_SSA,
       R.SUPP_SALES_AMT - S1.SUPP_SALES_AMT DIFF2,
       R.BBG_REFERENCE_FO1 REF_SSA,
       S1.BBG_REFERENCE_FO1 RA_SSA,
       R.BBG_REFERENCE_FO1 - S1.BBG_REFERENCE_FO1 DIFF3
  FROM (SELECT /*+PARALLEL(T,20)*/
         SUBSTR(TO_CHAR(T.DAY_DT, 'YYYYMMDD'), 1, 8) DAY,
         SUM(T.SUPP_SALES_COST) SUPP_SALES_COST,
         SUM(T.SUPP_SALES_AMT) SUPP_SALES_AMT,
         SUM(T.BBG_REFERENCE_FO1) BBG_REFERENCE_FO1
          FROM RADM.BBG_RA_SUPP_SLS_REF T
         WHERE T.DAY_DT BETWEEN DATE '2012-01-01' AND DATE '2013-05-07'
         GROUP BY SUBSTR(TO_CHAR(T.DAY_DT, 'YYYYMMDD'), 1, 8)
         ORDER BY SUBSTR(TO_CHAR(T.DAY_DT, 'YYYYMMDD'), 1, 8)) R
  FULL JOIN (SELECT /*+PARALLEL(SD,20)*/
              SUBSTR(TO_CHAR(SD.DT_WID), 2, 8) DAY,
              SUM(SD.SUPP_SALES_COST) SUPP_SALES_COST,
              SUM(SD.SUPP_SALES_AMT) SUPP_SALES_AMT,
              SUM(SD.BBG_REFERENCE_FO1) BBG_REFERENCE_FO1
               FROM RADM.BBG_RA_SUPP_SALES_IT_LC_DY_F SD
              WHERE SUBSTR(TO_CHAR(SD.DT_WID), 2, 8) BETWEEN '20120101' AND
                    '20130507'
              GROUP BY SUBSTR(TO_CHAR(SD.DT_WID), 2, 8)) S1
    ON S1.DAY = R.DAY
 order by r.day;
