--维度数据检查
SELECT 'BBG_RA_ITEM_LOC_D',COUNT(*)  FROM BBG_RA_ITEM_LOC_D  T  WHERE TRUNC(T.SRC_EFF_FROM_DT)=DATE '2013-06-27'  AND TRUNC(T.EFFECTIVE_TO_DT)=DATE '2100-01-01'
UNION ALL
SELECT 'BBG_RA_ITEM_LOC_DS',COUNT(*)  FROM BBG_RA_ITEM_LOC_DS  T 
UNION ALL                                                                                                          
SELECT 'BBG_RA_ITEM_LOC_SUPP_D',COUNT(*)  FROM BBG_RA_ITEM_LOC_SUPP_D  T  WHERE TRUNC(T.SRC_EFF_FROM_DT)=DATE '2013-06-27'  AND TRUNC(T.EFFECTIVE_TO_DT)=DATE '2100-01-01'
UNION ALL
SELECT 'BBG_RA_ITEM_LOC_SUPP_DS',COUNT(*)  FROM BBG_RA_ITEM_LOC_SUPP_DS  T   
UNION ALL
SELECT 'BBG_RA_SUPPLIER_INCOME_TYPE_D',COUNT(*)  FROM BBG_RA_SUPPLIER_INCOME_TYPE_D  T  WHERE TRUNC(T.SRC_EFF_FROM_DT)=DATE '2013-06-27'  AND TRUNC(T.EFFECTIVE_TO_DT)=DATE '2100-01-01'
UNION ALL
SELECT 'BBG_RA_SUPPLIER_INCOME_TYPE_DS',COUNT(*)  FROM BBG_RA_SUPPLIER_INCOME_TYPE_DS  T    
UNION ALL
SELECT 'BBG_RA_CONTRACT_TYPE_D',COUNT(*)  FROM BBG_RA_CONTRACT_TYPE_D  T  WHERE TRUNC(T.SRC_EFF_FROM_DT)=DATE '2013-06-27'  AND TRUNC(T.EFFECTIVE_TO_DT)=DATE '2100-01-01'
UNION ALL
SELECT 'BBG_RA_CONTRACT_TYPE_DS',COUNT(*)  FROM BBG_RA_CONTRACT_TYPE_DS  T  
UNION ALL
SELECT 'BBG_RA_RETAIL_TYPE_D',COUNT(*)  FROM BBG_RA_RETAIL_TYPE_D  T  WHERE TRUNC(T.SRC_EFF_FROM_DT)=DATE '2013-06-27'  AND TRUNC(T.EFFECTIVE_TO_DT)=DATE '2100-01-01'
UNION ALL
SELECT 'BBG_RA_RETAIL_TYPE_DS',COUNT(*)  FROM BBG_RA_RETAIL_TYPE_DS  T 
UNION ALL
SELECT 'BBG_RA_AJUSTMENT_REASON_D',COUNT(*)  FROM BBG_RA_AJUSTMENT_REASON_D  T  WHERE TRUNC(T.SRC_EFF_FROM_DT)=DATE '2013-06-27'  AND TRUNC(T.EFFECTIVE_TO_DT)=DATE '2100-01-01'
UNION ALL
SELECT 'BBG_RA_AJUSTMENT_REASON_DS',COUNT(*)  FROM BBG_RA_AJUSTMENT_REASON_DS  T                                                                                                                                  
UNION ALL
SELECT 'W_PRODUCT_D',COUNT(*)  FROM W_PRODUCT_D  T  WHERE TRUNC(T.Src_Eff_From_Dt)=DATE '2013-06-27' 
UNION ALL
SELECT 'W_PRODUCT_DS',COUNT(*)  FROM W_PRODUCT_DS  T    
UNION ALL
--门店组织表，采用全量传送，所以屏蔽日期条件
SELECT 'W_INT_ORG_D',COUNT(*)  FROM W_INT_ORG_D  T  --WHERE TRUNC(T.Src_Eff_From_Dt)=DATE '2013-06-27' 
UNION ALL
SELECT 'W_INT_ORG_DS',COUNT(*)  FROM W_INT_ORG_DS  T                                                                                                 
UNION ALL
--供应商表，采用全量传送，所以屏蔽日期条件
SELECT 'W_PARTY_ORG_D',COUNT(*)  FROM W_PARTY_ORG_D  T  --WHERE TRUNC(T.Effective_From_Dt)=DATE '2013-06-27' 
UNION ALL
SELECT 'W_PARTY_ORG_DS',COUNT(*)  FROM W_PARTY_ORG_DS  T                                                                                                      
UNION ALL
--促销类型，采用全量传送，中间表没有Effective_From_Dt、EFFECTIVE_TO_DT字段，只传送当前有效的促销类型,
--W_RTL_PROMO_D表中的促销类型如果在W_RTL_PROMO_DS表中找不到记录，则在W_RTL_PROMO_D置称无效，字段EFFECTIVE_TO_DT=SYSDATE-1
SELECT 'W_RTL_PROMO_D',COUNT(*)  FROM W_RTL_PROMO_D  T  WHERE /*TRUNC(T.Effective_From_Dt)=DATE '2013-06-27' AND*/ TRUNC(T.EFFECTIVE_TO_DT)=DATE '2100-01-01'
UNION ALL
SELECT 'W_RTL_PROMO_DS',COUNT(*)  FROM W_RTL_PROMO_DS  T 
UNION ALL
SELECT 'W_RTL_SEASON_D',COUNT(*)  FROM W_RTL_SEASON_D  T  --WHERE TRUNC(T.Effective_From_Dt)=DATE '2013-06-27' AND TRUNC(T.EFFECTIVE_TO_DT)=DATE '2100-01-01'
UNION ALL
SELECT 'W_RTL_SEASON_DS',COUNT(*)  FROM W_RTL_SEASON_DS  T ;



