SELECT * FROM ALL_ALL_TABLES T WHERE T.table_name LIKE '%SLSPK%';
W_RTL_SLSPK_IT_WK_SN_A nodata
W_RTL_SLSPK_IT_WK_A nodata
W_RTL_SLSPK_IT_LC_WK_A nodata
W_RTL_SLSPK_IT_LC_DY_SN_A nodata
W_RTL_SLSPK_IT_LC_DY_FS nodata
W_RTL_SLSPK_IT_LC_DY_F havedata
W_RTL_SLSPK_IT_DY_SN_A nodata
W_RTL_SLSPK_IT_DY_A havedata
W_RTL_SLSPK_IT_LC_WK_SN_A nodata
;
W_RTL_SLSPK_IT_DY_A
W_RTL_SLSPK_IT_DY_TMP
W_RTL_SLSPK_IT_LC_DY_TMP
W_RTL_SLSPK_IT_LC_DY_FS
W_RTL_SLSPK_TRX_COMPCOST_TMP
W_RTL_SLSPK_TRX_COST_TMP
W_RTL_SLSPK_TRX_TMP
W_RTL_SLS_TRX_TMP
--检查数据
SELECT * FROM W_RTL_SLSPK_IT_LC_DY_F T 
WHERE T.DT_WID='120131212000' AND T.INTEGRATION_ID LIKE '%100850715%' 
--AND T.INTEGRATION_ID LIKE '%120008%'
;
SELECT * FROM W_RTL_SLSPK_IT_DY_A T --汇总表
WHERE T.DT_WID='120131212000' AND T.INTEGRATION_ID LIKE '%100850715%';
SELECT * FROM W_RTL_SLSPK_IT_LC_DY_FS T
WHERE T.PACK_NUM='100850715';

--打包商品从销售开始导入
TRUNCATE TABLE RA_RMS.BBG_XTERN_RDWT;
TRUNCATE TABLE RA_RMS.C_LOAD_DATES;
--从BBG_XTERN_RDWT_HIST载入12月12日销售
INSERT INTO RA_RMS.BBG_XTERN_RDWT
SELECT * FROM RA_RMS.BBG_XTERN_RDWT_HIST WHERE BUSINESS_DT= '20131212';
--修改BBG_RA_ITEM_LOC_SOH_V日期条件
RA_RMS.BBG_RA_ITEM_LOC_SOH_V;
--检查W_RTL_SLSPK_TRX_TMP表是否有数据
--如果W_RTL_SLSPK_IT_LC_DY_FS的数据是正确的,那么可以跳过SDE步骤
SELECT * FROM RA_RMS.W_RTL_SLSPK_TRX_TMP;
SELECT * FROM RA_RMS.W_RTL_SLSPK_TRX_COST_TMP;
SELECT * FROM RA_RMS.W_RTL_SLSPK_TRX_COMPCOST_TMP;
SELECT * FROM W_RTL_SLSPK_IT_LC_DY_FS@RMS_RA;
SELECT * FROM RABATCHER.W_RTL_SLSPK_IT_LC_DY_TMP@RMS_RA;
--删除12月12日的打包商品销售记录
DELETE W_RTL_SLSPK_IT_LC_DY_F@RMS_RA T WHERE T.DT_WID='120131212000';
DELETE W_RTL_SLSPK_IT_DY_A@RMS_RA T WHERE T.DT_WID='120131212000';

TRUNCATE TABLE RADM.C_LOAD_DATES;

--运行sil\plp部分,检查数据
--sil:BBG_SIL_RetailSalesPackFact
--plp: in UC4 Workflow name:PF.PLP_SALES_PACK
SELECT * FROM  W_RTL_SLSPK_IT_LC_DY_F@RMS_RA T WHERE T.DT_WID='120131212000';
SELECT * FROM  W_RTL_SLSPK_IT_DY_A@RMS_RA T WHERE T.DT_WID='120131212000';


