SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS;
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F T WHERE T.DT_WID=120140917000;
SELECT * FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP;

TRUNCATE TABLE RADM.C_LOAD_DATES;

SELECT * FROM RADM.BBG_RA_SLSFC_DP_LC_DY_FS_V T WHERE T.DAY_DT=DATE'2014-09-17';
SELECT * FROM RADM.BBG_RA_SLSFC_DP_LC_DY_FS;
SELECT * FROM RABATCHER.BBG_RA_SLSFC_DP_LC_DY_TMP;

SELECT * FROM RADM.BBG_RA_INVADJ_IT_LC_DY_FS;
SELECT * FROM RADM.BBG_RA_INVADJ_IT_LC_DY_F T WHERE T.DT_WID='120140917000';


SELECT * FROM RADM.BBG_RA_INVTSF_IT_LC_DY_FS;
SELECT * FROM RADM.BBG_RA_INVTSF_IT_LC_DY_F T WHERE T.DT_WID='120140917000';

SELECT * FROM RADM.BBG_RA_RTV_IT_LC_DY_FS;
SELECT * FROM RADM.BBG_RA_RTV_IT_LC_SUPP_DY_F T WHERE T.DT_WID='120140917000';

SELECT * FROM RADM.BBG_RA_SUPP_INV_IT_LC_DY_F T;
SELECT * FROM RABATCHER.BBG_RA_SUPP_INV_IT_LC_DY_TMP;

SELECT * FROM RABATCHER.BBG_RA_SUPP_SLS_IT_LC_DY_TMP; 
SELECT * FROM RADM.BBG_RA_SUPP_SALES_IT_LC_DY_F T WHERE T.DT_WID=120140917000;

SELECT * FROM RADM.BBG_RA_WHOLE_SALES_FS;
SELECT * FROM RADM.BBG_RA_WHOLE_SALES_F  T WHERE T.DT_WID=120140917000;

SELECT * FROM RADM.W_RTL_SUPPCM_IT_LC_DY_FS;
SELECT * FROM RADM.W_RTL_SUPPCM_IT_LC_DY_F T WHERE T.BBG_REFERENCE_DO3=DATE'2014-09-17';

SELECT * FROM RABATCHER.W_RTL_INV_IT_LC_DY_TMP;

SELECT * FROM RABATCHER.W_RTL_NCOST_IT_LC_DY_TMP;

SELECT * FROM RABATCHER.W_RTL_PRICE_IT_LC_DY_TMP;
SELECT * FROM RADM.W_RTL_PRICE_IT_LC_DY_FS;
SELECT * FROM RADM.W_RTL_PRICE_IT_LC_DY_F;

SELECT * FROM RADM.W_RTL_MKDN_IT_LC_DY_FS;
SELECT * FROM RADM.W_RTL_MKDN_IT_LC_DY_F T WHERE T.DT_WID=120140918000;
