--1.
DELETE RADM.W_RTL_SLS_DP_LC_DY_A T WHERE T.DT_WID = 120150318000;
COMMIT;
DELETE RADM.W_RTL_SLS_CL_LC_DY_A T WHERE T.DT_WID = 120150318000;
COMMIT;
--2.
UPDATE RABATCHER.W_INT_ORG_DH_RTL_TMP T
   SET T.EFFECTIVE_FROM_DT = DATE '2013-05-07'
 WHERE EXISTS
 (SELECT 1
          FROM (SELECT B.ORG_NUM, MIN(B.EFFECTIVE_FROM_DT) EFFECTIVE_FROM_DT
                  FROM RABATCHER.W_INT_ORG_DH_RTL_TMP B
                 GROUP BY B.ORG_NUM) A
         WHERE T.ORG_NUM = A.ORG_NUM
           AND T.EFFECTIVE_FROM_DT = A.EFFECTIVE_FROM_DT);
--3.
CALL FIX_W_RTL_SLS_TRX_IT_LC_DY_TMP(120150318000);

SELECT COUNT(1)
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F T
 WHERE T.DT_WID = 120150318000;
SELECT COUNT(1) FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP;


 


SELECT SUM(T.SLS_AMT_LCL) SLS_AMT_LCL /*+PARALLEL(T,16)*/
  FROM W_RTL_SLS_CL_LC_DY_A T
 WHERE T.DT_WID = &FDTWID;

SELECT SUM(T.SLS_AMT_LCL) SLS_AMT_LCL /*+PARALLEL(T,16)*/
  FROM W_RTL_SLS_DP_LC_DY_A T
 WHERE T.DT_WID = &FDTWID;

SELECT SUM(T.SLS_AMT_LCL) SLS_AMT_LCL /*+PARALLEL(T,16)*/
  FROM W_RTL_SLS_IT_LC_DY_A T
 WHERE T.DT_WID = &FDTWID;

