--2013.05.08
--2013.07.31
--2013.08.03


--1.删除RA销售数据
CALL RADM.BBG_RA_DEL_SLS_DT(120130508000);
CALL RADM.BBG_RA_DEL_SLS_DT(120130731000);
CALL RADM.BBG_RA_DEL_SLS_DT(120130803000);
--2.清空BBG_XTERN_RDWT
TRUNCATE TABLE RA_RMS.BBG_XTERN_RDWT;

--3.从BBG_XTERN_RDWT_HIST插入BBG_XTERN_RDWT
INSERT INTO RA_RMS.BBG_XTERN_RDWT
  SELECT *
    FROM RA_RMS.BBG_XTERN_RDWT_HIST
   WHERE BUSINESS_DT IN ('20130508', '20130731', '20130803');
COMMIT;

--4.TRAN_DATA_HISTORY存入RMS
SELECT /*+PARALLEL(16)*/
 *
  FROM TRAN_DATA_HISTORY T
 WHERE T.TRAN_DATE IN
       (DATE '2013-05-08', DATE '2013-07-31', DATE '2013-08-03');

INSERT INTO /*+PARALLEL(16)*/
TRAN_DATA_HISTORY
  SELECT /*+PARALLEL(16)*/
   *
    FROM TRAN_DATA_HISTORY@RTKHIST T
   WHERE T.TRAN_DATE IN
         (DATE '2013-05-08', DATE '2013-07-31', DATE '2013-08-03');
COMMIT;

--5.清空ODI日志
TRUNCATE TABLE RA_RMS.C_LOAD_DATES;
TRUNCATE TABLE RADM.C_LOAD_DATES;

--6.清空TMP表
TRUNCATE TABLE RABATCHER.W_RTL_SLS_IT_DY_TMP;
TRUNCATE TABLE RABATCHER.W_RTL_SLS_IT_LC_DY_SN_TMP;
TRUNCATE TABLE RABATCHER.W_RTL_SLS_IT_LC_DY_TMP;
TRUNCATE TABLE RABATCHER.W_RTL_SLS_LC_DY_TMP;
TRUNCATE TABLE RABATCHER.W_RTL_SLS_SC_LC_DY_CUR_TMP;
TRUNCATE TABLE RABATCHER.W_RTL_SLS_SC_LC_DY_RC_TMP;
TRUNCATE TABLE RABATCHER.W_RTL_SLS_SC_LC_DY_TMP;
TRUNCATE TABLE RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP;

--7.修改BBG_RA_ITEM_LOC_SOH_V的日期为重导日期
SELECT * FROM RA_RMS.BBG_RA_ITEM_LOC_SOH_V;

--8.
SELECT /*+PARALLEL(16)*/ DISTINCT DAY_DT FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS;

--9.检查W_RTL_SLS_TRX_IT_LC_DY_TMP数据
SELECT DISTINCT T.DT_WID FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP T;



