--2016/10/28,2016/10/29,2016/10/30
--1.1 
SELECT *
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS A
 WHERE NOT EXISTS (SELECT /*+PARALLEL(16)*/
         1
          FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP B
         WHERE A.ORG_NUM = B.ORG_NUM
           AND A.PROD_IT_NUM = B.PROD_IT_NUM);

--1.2
SELECT *
  FROM BBG_RA_SLS_TRX_JL_V@RA_JL T
 WHERE T.DAY_DT = DATE '2016-10-29'
   AND NOT EXISTS (SELECT /*+PARALLEL(16)*/
         1
          FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F B,
               RADM.W_INT_ORG_D              O,
               RADM.W_PRODUCT_D              P
         WHERE B.ORG_WID = O.ROW_WID
           AND B.PROD_WID = P.ROW_WID
           AND O.ORG_NUM = T.ORG_NUM
           AND P.PROD_NUM = T.PROD_IT_NUM
           AND B.DT_WID = 120161029000);

--2.location list:120072,130003,130012,130033,139056,139164
TRUNCATE TABLE RADM.BBG_RA_ITEM_LOC_DS;
CALL BBG_JL_ITEM_LOC_NEW_PROC(120072);
CALL BBG_JL_ITEM_LOC_NEW_PROC(130003);
CALL BBG_JL_ITEM_LOC_NEW_PROC(130012);
CALL BBG_JL_ITEM_LOC_NEW_PROC(130033);
CALL BBG_JL_ITEM_LOC_NEW_PROC(139056);
CALL BBG_JL_ITEM_LOC_NEW_PROC(139164);

SELECT *
  FROM BBG_RA_ITEM_LOC_JL_V_ALL@RA_JL T
 WHERE T.ITEM = '2400070072530'
   AND T.LOC = '139056';
--3.item sales
--3.1
DELETE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T
 WHERE NVL(T.BBG_SERVICE_SATISFACTION, 0) <> 3.5;
COMMIT;
DELETE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T
 WHERE (T.ORG_NUM, T.PROD_IT_NUM) NOT IN
       (SELECT A.ORG_NUM, A.PROD_IT_NUM
          FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS A
         WHERE NOT EXISTS (SELECT /*+PARALLEL(16)*/
                 1
                  FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP B
                 WHERE A.ORG_NUM = B.ORG_NUM
                   AND A.PROD_IT_NUM = B.PROD_IT_NUM));
COMMIT;

--3.2
INSERT INTO RADM.W_RTL_SLS_TRX_IT_LC_DY_FS
  (SLS_TRX_ID,
   PROD_IT_NUM,
   ORG_NUM,
   DAY_DT,
   VOUCHER_ID,
   RTL_TYPE_CODE,
   MIN_NUM,
   EMPLOYEE_NUM,
   SLS_QTY,
   SLS_AMT_LCL,
   SLS_PROFIT_AMT_LCL,
   SLS_TAX_AMT_LCL,
   SLS_EMP_DISC_AMT_LCL,
   SLS_MANUAL_COUNT,
   SLS_SCAN_COUNT,
   RET_QTY,
   RET_AMT_LCL,
   RET_PROFIT_AMT_LCL,
   RET_TAX_AMT_LCL,
   RET_EMP_DISC_AMT_LCL,
   RET_MANUAL_COUNT,
   RET_SCAN_COUNT,
   REJECT_FLG,
   SLS_MANUAL_MKDN_AMT_LCL,
   SLS_MANUAL_MKUP_AMT_LCL,
   RET_MANUAL_MKDN_AMT_LCL,
   RET_MANUAL_MKUP_AMT_LCL,
   EXCHANGE_DT,
   AUX1_CHANGED_ON_DT,
   AUX2_CHANGED_ON_DT,
   AUX3_CHANGED_ON_DT,
   AUX4_CHANGED_ON_DT,
   CHANGED_BY_ID,
   CHANGED_ON_DT,
   CREATED_BY_ID,
   CREATED_ON_DT,
   DATASOURCE_NUM_ID,
   DELETE_FLG,
   DOC_CURR_CODE,
   ETL_THREAD_VAL,
   GLOBAL1_EXCHANGE_RATE,
   GLOBAL2_EXCHANGE_RATE,
   GLOBAL3_EXCHANGE_RATE,
   INTEGRATION_ID,
   LOC_CURR_CODE,
   LOC_EXCHANGE_RATE,
   TENANT_ID,
   X_CUSTOM,
   BBG_RETAIL_TYPE_ID,
   BBG_SERVICE_SATISFACTION,
   SRC_REF_NO1,
   SRC_REF_NO2,
   SRC_REF_NO3,
   SRC_REF_NO6,
   SRC_REF_NO7,
   SRC_REF_NO8,
   BBG_REFERENCE_DO1,
   BBG_REFERENCE_DO2,
   BBG_REFERENCE_DO3,
   BBG_REFERENCE_DO4,
   BBG_REFERENCE_DO5,
   BBG_REFERENCE_FO1,
   BBG_REFERENCE_FO2,
   BBG_REFERENCE_FO3,
   BBG_REFERENCE_FO4,
   BBG_REFERENCE_FO5,
   BBG_REFERENCE_FO6,
   BBG_REFERENCE_FO7,
   BBG_REFERENCE_FO8,
   BBG_REFERENCE_FO9,
   BBG_REFERENCE_FO10,
   HYK_NO)
  SELECT T.SLS_TRX_ID,
         T.PROD_IT_NUM,
         T.ORG_NUM,
         T.DAY_DT,
         -1 VOUCHER_ID,
         T.RTL_TYPE_CODE,
         T.MIN_NUM,
         -1 EMPLOYEE_NUM,
         T.SLS_QTY,
         T.SLS_AMT_LCL,
         T.SLS_PROFIT_AMT_LCL,
         T.SLS_TAX_AMT_LCL,
         T.SLS_EMP_DISC_AMT_LCL,
         T.SLS_MANUAL_COUNT,
         T.SLS_SCAN_COUNT,
         T.RET_QTY RET_QTY,
         T.RET_AMT_LCL RET_AMT_LCL,
         T.RET_PROFIT_AMT_LCL,
         T.RET_TAX_AMT_LCL RET_TAX_AMT_LCL,
         T.RET_EMP_DISC_AMT_LCL,
         T.RET_MANUAL_COUNT,
         T.RET_SCAN_COUNT,
         NULL REJECT_FLG,
         T.SLS_MANUAL_MKDN_AMT_LCL,
         T.SLS_MANUAL_MKUP_AMT_LCL,
         T.RET_MANUAL_MKDN_AMT_LCL,
         T.RET_MANUAL_MKUP_AMT_LCL,
         T.DAY_DT EXCHANGE_DT,
         NULL AUX1_CHANGED_ON_DT,
         NULL AUX2_CHANGED_ON_DT,
         NULL AUX3_CHANGED_ON_DT,
         NULL AUX4_CHANGED_ON_DT,
         -1 CHANGED_BY_ID,
         SYSDATE CHANGED_ON_DT,
         -1 CREATED_BY_ID,
         SYSDATE CREATED_ON_DT,
         1 DATASOURCE_NUM_ID,
         NULL DELETE_FLG,
         'CNY' DOC_CURR_CODE,
         (SELECT L.THREAD_VAL
            FROM RA_RMS.RA_RESTART_LOC@RA_RMS_DBLINK L
           WHERE T.ORG_NUM = L.DRIVER_VALUE
             AND L.SCENARIO_NAME = 'SDE_BBG_RETAIL_SALESTRANSACTIONFACT') ETL_THREAD_VAL,
         NULL GLOBAL1_EXCHANGE_RATE,
         NULL GLOBAL2_EXCHANGE_RATE,
         NULL GLOBAL3_EXCHANGE_RATE,
         T.SLS_TRX_ID || '~' || T.PROD_IT_NUM || '~-1~' ||
         TO_CHAR(T.DAY_DT, 'DD-MON-YY', 'NLS_DATE_LANGUAGE = American') INTEGRATION_ID,
         'CNY' LOC_CURR_CODE,
         NULL LOC_EXCHANGE_RATE,
         NULL TENANT_ID,
         NULL X_CUSTOM,
         T.BBG_RETAIL_TYPE_ID,
         3.5 BBG_SERVICE_SATISFACTION,
         NULL SRC_REF_NO1,
         NULL SRC_REF_NO2,
         NULL SRC_REF_NO3,
         T.PROD_IT_NUM SRC_REF_NO6,
         NULL SRC_REF_NO7,
         NULL SRC_REF_NO8,
         NULL BBG_REFERENCE_DO1,
         NULL BBG_REFERENCE_DO2,
         NULL BBG_REFERENCE_DO3,
         NULL BBG_REFERENCE_DO4,
         NULL BBG_REFERENCE_DO5,
         NULL BBG_REFERENCE_FO1,
         NULL BBG_REFERENCE_FO2,
         NULL BBG_REFERENCE_FO3,
         NULL BBG_REFERENCE_FO4,
         NULL BBG_REFERENCE_FO5,
         NULL BBG_REFERENCE_FO6,
         NULL BBG_REFERENCE_FO7,
         NULL BBG_REFERENCE_FO8,
         NULL BBG_REFERENCE_FO9,
         NULL BBG_REFERENCE_FO10,
         T.HYK_NO HYK_NO
    FROM (SELECT A.SLS_TRX_ID,
                 A.PROD_IT_NUM,
                 A.ORG_NUM,
                 A.DAY_DT,
                 A.VOUCHER_ID,
                 A.RTL_TYPE_CODE,
                 A.MIN_NUM,
                 A.SLS_QTY,
                 A.SLS_AMT_LCL,
                 A.SLS_PROFIT_AMT_LCL,
                 A.SLS_TAX_AMT_LCL,
                 A.SLS_EMP_DISC_AMT_LCL,
                 A.SLS_MANUAL_COUNT,
                 A.SLS_SCAN_COUNT,
                 -A.RET_QTY                 RET_QTY,
                 -A.RET_AMT_LCL             RET_AMT_LCL,
                 -A.RET_PROFIT_AMT_LCL      RET_PROFIT_AMT_LCL,
                 -A.RET_TAX_AMT_LCL         RET_TAX_AMT_LCL,
                 -A.RET_EMP_DISC_AMT_LCL    RET_EMP_DISC_AMT_LCL,
                 -A.RET_MANUAL_COUNT        RET_MANUAL_COUNT,
                 -A.RET_SCAN_COUNT          RET_SCAN_COUNT,
                 A.SLS_MANUAL_MKDN_AMT_LCL,
                 A.SLS_MANUAL_MKUP_AMT_LCL,
                 -A.RET_MANUAL_MKDN_AMT_LCL RET_MANUAL_MKDN_AMT_LCL,
                 -A.RET_MANUAL_MKUP_AMT_LCL RET_MANUAL_MKUP_AMT_LCL,
                 A.BBG_RETAIL_TYPE_ID,
                 A.HYK_NO
            FROM BBG_RA_SLS_TRX_JL_V@RA_JL A
           WHERE (A.ORG_NUM, A.PROD_IT_NUM) IN
                 (SELECT V.ORG_NUM, V.PROD_IT_NUM
                    FROM BBG_RA_SLS_TRX_JL_V@RA_JL V
                   WHERE V.DAY_DT = DATE '2016-10-29'
                     AND NOT EXISTS
                   (SELECT /*+PARALLEL(16)*/
                           1
                            FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F B,
                                 RADM.W_INT_ORG_D              O,
                                 RADM.W_PRODUCT_D              P
                           WHERE B.ORG_WID = O.ROW_WID
                             AND B.PROD_WID = P.ROW_WID
                             AND O.ORG_NUM = V.ORG_NUM
                             AND P.PROD_NUM = V.PROD_IT_NUM
                             AND B.DT_WID = 120161029000))
             AND A.DAY_DT = DATE '2016-10-29') T;
COMMIT;

--3.3.SIL
TRUNCATE TABLE RADM.C_LOAD_DATES;
SELECT * FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP;

--4.supp sales
--4.1
DELETE RADM.BBG_RA_SLS_IT_LC_DY_FS A
 WHERE (A.DAY_DT, A.ORG_NUM, A.PROD_IT_NUM) NOT IN
       (SELECT B.DAY_DT, B.ORG_NUM, B.PROD_IT_NUM
          FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS B);
COMMIT;
SELECT * FROM RADM.BBG_RA_SUPP_SALES_IT_LC_DY_F;

--4.2
INSERT INTO RADM.BBG_RA_SLS_IT_LC_DY_FS
  (DAY_DT,
   PROD_IT_NUM,
   ORG_NUM,
   SUPPLIER_NUM,
   SUPP_SALES_QTY,
   SUPP_SALES_COST,
   SUPP_SALES_AMT,
   CHANGED_BY_ID,
   CHANGED_ON_DT,
   CREATED_BY_ID,
   CREATED_ON_DT,
   DATASOURCE_NUM_ID,
   DELETE_FLG,
   ETL_THREAD_VAL,
   INTEGRATION_ID,
   AUX1_CHANGED_ON_DT,
   AUX2_CHANGED_ON_DT,
   AUX3_CHANGED_ON_DT,
   AUX4_CHANGED_ON_DT,
   DOC_CURR_CODE,
   GLOBAL1_EXCHANGE_RATE,
   GLOBAL2_EXCHANGE_RATE,
   GLOBAL3_EXCHANGE_RATE,
   LOC_CURR_CODE,
   LOC_EXCHANGE_RATE,
   TENANT_ID,
   X_CUSTOM,
   BBG_REFERENCE_DO1,
   BBG_REFERENCE_DO2,
   BBG_REFERENCE_DO3,
   BBG_REFERENCE_DO4,
   BBG_REFERENCE_DO5,
   BBG_REFERENCE_FO1,
   BBG_REFERENCE_FO2,
   BBG_REFERENCE_FO3,
   BBG_REFERENCE_FO4,
   BBG_REFERENCE_FO5,
   BBG_REFERENCE_FO6,
   BBG_REFERENCE_FO7,
   BBG_REFERENCE_FO8,
   BBG_REFERENCE_FO9,
   BBG_REFERENCE_FO10)
  SELECT T.DAY_DT,
         T.PROD_IT_NUM,
         T.ORG_NUM,
         T.SUPPLIER_NUM,
         T.SUPP_SALES_QTY,
         T.SUPP_SALES_COST,
         T.SUPP_SALES_AMT,
         -1 CHANGED_BY_ID,
         SYSDATE CHANGED_ON_DT,
         -1 CREATED_BY_ID,
         SYSDATE CREATED_ON_DT,
         1 DATASOURCE_NUM_ID,
         NULL DELETE_FLG,
         (SELECT L.THREAD_VAL
            FROM RA_RMS.RA_RESTART_LOC@RA_RMS_DBLINK L
           WHERE T.ORG_NUM = L.DRIVER_VALUE
             AND L.SCENARIO_NAME = 'SDE_BBG_RA_SUPP_SALES_IT_LC_DY_FS') ETL_THREAD_VAL,
         TO_CHAR(T.DAY_DT, 'DD-MON-YY', 'NLS_DATE_LANGUAGE = American') || '~' ||
         T.PROD_IT_NUM || '~' || T.ORG_NUM || '~' || T.SUPPLIER_NUM INTEGRATION_ID,
         NULL AUX1_CHANGED_ON_DT,
         NULL AUX2_CHANGED_ON_DT,
         NULL AUX3_CHANGED_ON_DT,
         NULL AUX4_CHANGED_ON_DT,
         'CNY' DOC_CURR_CODE,
         NULL GLOBAL1_EXCHANGE_RATE,
         NULL GLOBAL2_EXCHANGE_RATE,
         NULL GLOBAL3_EXCHANGE_RATE,
         'CNY' LOC_CURR_CODE,
         NULL LOC_EXCHANGE_RATE,
         NULL TENANT_ID,
         NULL X_CUSTOM,
         (SELECT IL.BUSINESS_MODE
            FROM RADM.BBG_RA_ITEM_LOC_D IL
           WHERE IL.ITEM = T.PROD_IT_NUM
             AND IL.LOC = T.ORG_NUM
             AND T.DAY_DT BETWEEN IL.EFFECTIVE_FROM_DT AND
                 IL.EFFECTIVE_TO_DT) BBG_REFERENCE_DO1,
         'JINLI' BBG_REFERENCE_DO2,
         NULL BBG_REFERENCE_DO3,
         NULL BBG_REFERENCE_DO4,
         NULL BBG_REFERENCE_DO5,
         T.BBG_REFERENCE_FO1 BBG_REFERENCE_FO1,
         NULL BBG_REFERENCE_FO2,
         NULL BBG_REFERENCE_FO3,
         NULL BBG_REFERENCE_FO4,
         NULL BBG_REFERENCE_FO5,
         NULL BBG_REFERENCE_FO6,
         NULL BBG_REFERENCE_FO7,
         NULL BBG_REFERENCE_FO8,
         NULL BBG_REFERENCE_FO9,
         NULL BBG_REFERENCE_FO10
    FROM RADM.BBG_RA_SUPP_JL_VIEW T
   WHERE T.DAY_DT = DATE '2016-10-28'
     AND (T.DAY_DT, T.ORG_NUM, T.PROD_IT_NUM) IN
         (SELECT B.DAY_DT, T.ORG_NUM, T.PROD_IT_NUM
            FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS B
           WHERE T.DAY_DT = B.DAY_DT
             AND T.ORG_NUM = B.ORG_NUM
             AND T.PROD_IT_NUM = B.PROD_IT_NUM);
COMMIT;

--4.3.SUPP SIL
TRUNCATE TABLE RADM.C_LOAD_DATES;
SELECT * FROM RABATCHER.BBG_RA_SUPP_SLS_IT_LC_DY_TMP;
--5.
