--1.
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS;
DELETE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T WHERE T.BBG_SERVICE_SATISFACTION=3.5;
COMMIT;
DELETE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T WHERE T.ORG_NUM<>120259;
COMMIT;
DELETE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T WHERE T.PROD_IT_NUM<>100357074;
COMMIT;
--5.
SELECT SUM(T.SLS_QTY - T.RET_QTY) QTY,
       SUM((T.SLS_AMT_LCL - T.SLS_TAX_AMT_LCL) -
           (T.RET_AMT_LCL - T.RET_TAX_AMT_LCL)),
       SUM((T.SLS_AMT_LCL - T.SLS_TAX_AMT_LCL - T.SLS_PROFIT_AMT_LCL) -
           (T.RET_AMT_LCL - T.RET_TAX_AMT_LCL - T.RET_PROFIT_AMT_LCL))
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T;
SELECT T.SLS_QTY,
       T.SLS_AMT_LCL,
       T.SLS_PROFIT_AMT_LCL,
       T.SLS_TAX_AMT_LCL,
       T.RET_QTY,
       T.RET_AMT_LCL,
       T.RET_PROFIT_AMT_LCL,
       T.RET_TAX_AMT_LCL
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T;
--6.
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS FOR UPDATE;
UPDATE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T
   SET T.SLS_QTY                 = 0,
       T.SLS_AMT_LCL             = 0,
       T.SLS_PROFIT_AMT_LCL      = 0,
       T.SLS_MANUAL_MKDN_AMT_LCL = 0,
       T.SLS_MANUAL_MKUP_AMT_LCL = 0,
       T.SLS_TAX_AMT_LCL         = 0,
       T.SLS_EMP_DISC_AMT_LCL    = 0,
       T.SLS_MANUAL_COUNT        = 0,
       T.SLS_SCAN_COUNT          = 0,
       T.RET_QTY                 = 0,
       T.RET_AMT_LCL             = 0,
       T.RET_PROFIT_AMT_LCL      = 160.8462,
       T.RET_MANUAL_MKDN_AMT_LCL = 0,
       T.RET_MANUAL_MKUP_AMT_LCL = 0,
       T.RET_TAX_AMT_LCL         = 0,
       T.RET_EMP_DISC_AMT_LCL    = 0,
       T.RET_MANUAL_COUNT        = 0,
       T.RET_SCAN_COUNT          = 0,
       T.SLS_COUPON_AMT_LCL      = 0,
       T.RET_COUPON_AMT_LCL      = 0,
       T.SLS_TAX_COUPON_AMT_LCL  = 0,
       T.RET_TAX_COUPON_AMT_LCL  = 0;
COMMIT;
--7.
TRUNCATE TABLE RADM.C_LOAD_DATES;

--8.
SELECT * FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP;
--9.

--10.
