--2016/10/31
--item:2400073040669 loc:139191,item:2400070010243 loc:130004
--1.1 
SELECT *
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS A
 WHERE NOT EXISTS (SELECT /*+PARALLEL(16)*/
         1
          FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP B
         WHERE A.ORG_NUM = B.ORG_NUM
           AND A.PROD_IT_NUM = B.PROD_IT_NUM);

--1.2
SELECT *
  FROM BBG_RA_SLS_TRX_JL_V@RA_JL T
 WHERE T.DAY_DT = DATE '2016-10-29'
   AND NOT EXISTS (SELECT /*+PARALLEL(16)*/
         1
          FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F B,
               RADM.W_INT_ORG_D              O,
               RADM.W_PRODUCT_D              P
         WHERE B.ORG_WID = O.ROW_WID
           AND B.PROD_WID = P.ROW_WID
           AND O.ORG_NUM = T.ORG_NUM
           AND P.PROD_NUM = T.PROD_IT_NUM
           AND B.DT_WID = 120161029000);

--2.location list:120072,130003,130012,130033,139056,139164
TRUNCATE TABLE RADM.BBG_RA_ITEM_LOC_DS;
CALL BBG_JL_ITEM_LOC_NEW_PROC(130004);
CALL BBG_JL_ITEM_LOC_NEW_PROC(139191);

SELECT *
  FROM BBG_RA_ITEM_LOC_JL_V_ALL@RA_JL T
 WHERE T.ITEM = '2400070072530'
   AND T.LOC = '139056';
--3.item sales
--3.1
DELETE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T
 WHERE NVL(T.BBG_SERVICE_SATISFACTION, 0) <> 3.5;
COMMIT;
DELETE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T
 WHERE (T.ORG_NUM, T.PROD_IT_NUM) NOT IN
       (SELECT A.ORG_NUM, A.PROD_IT_NUM
          FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS A
         WHERE NOT EXISTS (SELECT /*+PARALLEL(16)*/
                 1
                  FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP B
                 WHERE A.ORG_NUM = B.ORG_NUM
                   AND A.PROD_IT_NUM = B.PROD_IT_NUM));
COMMIT;

--3.2


--3.3.SIL
TRUNCATE TABLE RADM.C_LOAD_DATES;
SELECT * FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP;

--4.supp sales
--4.1
DELETE RADM.BBG_RA_SLS_IT_LC_DY_FS A
 WHERE (A.DAY_DT, A.ORG_NUM, A.PROD_IT_NUM) NOT IN
       (SELECT B.DAY_DT, B.ORG_NUM, B.PROD_IT_NUM
          FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS B);
COMMIT;

--4.2


--4.3.SUPP SIL
TRUNCATE TABLE RADM.C_LOAD_DATES;
SELECT * FROM RABATCHER.BBG_RA_SUPP_SLS_IT_LC_DY_TMP;
--5.
