--1.
SELECT *
  FROM TRAN_DATA_HISTORY T
 WHERE T.TRAN_DATE = DATE '2016-12-11'
   AND T.TRAN_CODE IN (1, 2, 3)
   AND T.ITEM = 102714629
   AND T.LOCATION = 120110;

SELECT *
  FROM RA_RMS.BBG_RA_ITEM_LOC_SOH_V T
 WHERE T.TRAN_DATE = DATE '2016-12-11'
   AND T.ITEM = 102714629
   AND T.LOCATION = 120110;

--2.
SELECT *
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T
 WHERE T.ORG_NUM = 120110
   AND T.PROD_IT_NUM = 102714629
   AND T.SLS_TRX_ID = 2034623001;
DELETE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T
 WHERE T.SLS_TRX_ID <> 2034623001
   OR T.PROD_IT_NUM <> 102714629;
COMMIT;
--3.
TRUNCATE TABLE RA_RMS.C_LOAD_DATES;

--4.
SELECT SUM(T.SLS_QTY - T.RET_QTY) QTY,
       SUM((T.SLS_AMT_LCL - T.SLS_TAX_AMT_LCL) -
           (T.RET_AMT_LCL - T.RET_TAX_AMT_LCL)),
       SUM((T.SLS_AMT_LCL - T.SLS_TAX_AMT_LCL - T.SLS_PROFIT_AMT_LCL) -
           (T.RET_AMT_LCL - T.RET_TAX_AMT_LCL - T.RET_PROFIT_AMT_LCL))
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T;
SELECT T.SLS_QTY,
       T.SLS_AMT_LCL,
       T.SLS_PROFIT_AMT_LCL,
       T.SLS_TAX_AMT_LCL,
       T.RET_QTY,
       T.RET_AMT_LCL,
       T.RET_PROFIT_AMT_LCL,
       T.RET_TAX_AMT_LCL
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T;
--5.
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS FOR UPDATE;
UPDATE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T
   SET T.SLS_QTY                 = 0,
       T.SLS_AMT_LCL             = 0,
       T.SLS_PROFIT_AMT_LCL      = 0,
       T.SLS_MANUAL_MKDN_AMT_LCL = 0,
       T.SLS_MANUAL_MKUP_AMT_LCL = 0,
       T.SLS_TAX_AMT_LCL         = 0,
       T.SLS_EMP_DISC_AMT_LCL    = 0,
       T.SLS_MANUAL_COUNT        = 0,
       T.SLS_SCAN_COUNT          = 0,
       T.RET_QTY                 = 0,
       T.RET_AMT_LCL             = 0,
       T.RET_PROFIT_AMT_LCL      = -11.1982,
       T.RET_MANUAL_MKDN_AMT_LCL = 0,
       T.RET_MANUAL_MKUP_AMT_LCL = 0,
       T.RET_TAX_AMT_LCL         = 0,
       T.RET_EMP_DISC_AMT_LCL    = 0,
       T.RET_MANUAL_COUNT        = 0,
       T.RET_SCAN_COUNT          = 0,
       T.SLS_COUPON_AMT_LCL      = 0,
       T.RET_COUPON_AMT_LCL      = 0,
       T.SLS_TAX_COUPON_AMT_LCL  = 0,
       T.RET_TAX_COUPON_AMT_LCL  = 0;
COMMIT;
--6.
TRUNCATE TABLE RADM.C_LOAD_DATES;

--7.
SELECT * FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP;
--8.

--9.
