--2016.7.3/2016.7.4二天金立销售在RA中缺失。
--1.
--删除商品销售汇总表
DELETE /*+PARALLEL(16)*/
RADM.W_RTL_SLS_TRX_IT_LC_DY_F A
 WHERE A.DT_WID = &DT_WID
   AND EXISTS (SELECT /*+PARALLEL(16)*/
         1
          FROM BBG_RA_SLS_TRX_JL_V@RA_JL B
         WHERE B.DAY_DT = &DAY_DT
           AND A.SLS_TRX_ID = B.SLS_TRX_ID);
COMMIT;

DELETE /*+PARALLEL(16)*/
RADM.W_RTL_SLS_CL_DY_CUR_A A
 WHERE A.DT_WID = &DT_WID
   AND EXISTS
 (SELECT /*+PARALLEL(16)*/
         1
          FROM RADM.W_PROD_CAT_DH B
         WHERE A.PROD_DH_WID = B.ROW_WID
           AND B.LVL7ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;

DELETE /*+PARALLEL(16)*/
RADM.W_RTL_SLS_CL_LC_DY_A A
 WHERE A.DT_WID = &DT_WID
   AND EXISTS
 (SELECT /*+PARALLEL(16)*/
         1
          FROM RADM.W_PROD_CAT_DH B
         WHERE A.PROD_DH_WID = B.ROW_WID
           AND B.LVL7ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;

DELETE /*+PARALLEL(16)*/
RADM.W_RTL_SLS_CL_LC_DY_CUR_A A
 WHERE A.DT_WID = &DT_WID
   AND EXISTS
 (SELECT /*+PARALLEL(16)*/
         1
          FROM RADM.W_PROD_CAT_DH B
         WHERE A.PROD_DH_WID = B.ROW_WID
           AND B.LVL7ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;

DELETE /*+PARALLEL(16)*/
RADM.W_RTL_SLS_DP_DY_CUR_A A
 WHERE A.DT_WID = &DT_WID
   AND EXISTS
 (SELECT /*+PARALLEL(16)*/
         1
          FROM RADM.W_PROD_CAT_DH B
         WHERE A.PROD_DH_WID = B.ROW_WID
           AND B.LVL7ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;

DELETE /*+PARALLEL(16)*/
RADM.W_RTL_SLS_DP_LC_DY_A A
 WHERE A.DT_WID = &DT_WID
   AND EXISTS
 (SELECT /*+PARALLEL(16)*/
         1
          FROM RADM.W_PROD_CAT_DH B
         WHERE A.PROD_DH_WID = B.ROW_WID
           AND B.LVL7ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;

DELETE /*+PARALLEL(16)*/
RADM.W_RTL_SLS_DP_LC_DY_CUR_A A
 WHERE A.DT_WID = &DT_WID
   AND EXISTS
 (SELECT /*+PARALLEL(16)*/
         1
          FROM RADM.W_PROD_CAT_DH B
         WHERE A.PROD_DH_WID = B.ROW_WID
           AND B.LVL7ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;

DELETE /*+PARALLEL(16)*/
RADM.W_RTL_SLS_IT_DY_A A
 WHERE A.DT_WID = &DT_WID
   AND EXISTS
 (SELECT /*+PARALLEL(16)*/
         1
          FROM RADM.W_PRODUCT_D C
         WHERE A.PROD_WID = C.ROW_WID
           AND SUBSTR(C.PROD_CAT5, 3, 2) IN (70, 71, 72, 73, 74, 77, 78, 79)
           AND C.PROD_NUM LIKE '24%');
COMMIT;

DELETE /*+PARALLEL(16)*/
RADM.W_RTL_SLS_IT_DY_SN_A A
 WHERE A.DT_WID = &DT_WID
   AND EXISTS
 (SELECT /*+PARALLEL(16)*/
         1
          FROM RADM.W_PRODUCT_D C
         WHERE A.PROD_WID = C.ROW_WID
           AND SUBSTR(C.PROD_CAT5, 3, 2) IN (70, 71, 72, 73, 74, 77, 78, 79)
           AND C.PROD_NUM LIKE '24%');
COMMIT;

DELETE /*+PARALLEL(16)*/
RADM.W_RTL_SLS_IT_LC_DY_A A
 WHERE A.DT_WID = &DT_WID
   AND EXISTS
 (SELECT /*+PARALLEL(16)*/
         1
          FROM RADM.W_PRODUCT_D C
         WHERE A.PROD_WID = C.ROW_WID
           AND SUBSTR(C.PROD_CAT5, 3, 2) IN (70, 71, 72, 73, 74, 77, 78, 79)
           AND C.PROD_NUM LIKE '24%');
COMMIT;

DELETE /*+PARALLEL(16)*/
RADM.W_RTL_SLS_IT_LC_DY_SN_A A
 WHERE A.DT_WID = &DT_WID
   AND EXISTS
 (SELECT /*+PARALLEL(16)*/
         1
          FROM RADM.W_PRODUCT_D C
         WHERE A.PROD_WID = C.ROW_WID
           AND SUBSTR(C.PROD_CAT5, 3, 2) IN (70, 71, 72, 73, 74, 77, 78, 79)
           AND C.PROD_NUM LIKE '24%');
COMMIT;

DELETE /*+PARALLEL(16)*/
RADM.W_RTL_SLS_SC_DY_A A
 WHERE A.DT_WID = &DT_WID
   AND EXISTS
 (SELECT /*+PARALLEL(16)*/
         1
          FROM RADM.W_PROD_CAT_DH B
         WHERE A.PROD_DH_WID = B.ROW_WID
           AND B.LVL7ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;

DELETE /*+PARALLEL(16)*/
RADM.W_RTL_SLS_SC_DY_CUR_A A
 WHERE A.DT_WID = &DT_WID
   AND EXISTS
 (SELECT /*+PARALLEL(16)*/
         1
          FROM RADM.W_PROD_CAT_DH B
         WHERE A.PROD_DH_WID = B.ROW_WID
           AND B.LVL7ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;

DELETE /*+PARALLEL(16)*/
RADM.W_RTL_SLS_SC_LC_DY_A A
 WHERE A.DT_WID = &DT_WID
   AND EXISTS
 (SELECT /*+PARALLEL(16)*/
         1
          FROM RADM.W_PROD_CAT_DH B
         WHERE A.PROD_DH_WID = B.ROW_WID
           AND B.LVL7ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;

DELETE /*+PARALLEL(16)*/
RADM.W_RTL_SLS_SC_LC_DY_CUR_A A
 WHERE A.DT_WID = &DT_WID
   AND EXISTS
 (SELECT /*+PARALLEL(16)*/
         1
          FROM RADM.W_PROD_CAT_DH B
         WHERE A.PROD_DH_WID = B.ROW_WID
           AND B.LVL7ANC_PRODCAT_ID IN (70, 71, 72, 73, 74, 77, 78, 79));
COMMIT;
--2.
TRUNCATE TABLE RADM.C_LOAD_DATES;
TRUNCATE TABLE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS;
INSERT INTO RADM.W_RTL_SLS_TRX_IT_LC_DY_FS
  (SLS_TRX_ID,
   PROD_IT_NUM,
   ORG_NUM,
   DAY_DT,
   VOUCHER_ID,
   RTL_TYPE_CODE,
   MIN_NUM,
   EMPLOYEE_NUM,
   SLS_QTY,
   SLS_AMT_LCL,
   SLS_PROFIT_AMT_LCL,
   SLS_TAX_AMT_LCL,
   SLS_EMP_DISC_AMT_LCL,
   SLS_MANUAL_COUNT,
   SLS_SCAN_COUNT,
   RET_QTY,
   RET_AMT_LCL,
   RET_PROFIT_AMT_LCL,
   RET_TAX_AMT_LCL,
   RET_EMP_DISC_AMT_LCL,
   RET_MANUAL_COUNT,
   RET_SCAN_COUNT,
   REJECT_FLG,
   SLS_MANUAL_MKDN_AMT_LCL,
   SLS_MANUAL_MKUP_AMT_LCL,
   RET_MANUAL_MKDN_AMT_LCL,
   RET_MANUAL_MKUP_AMT_LCL,
   EXCHANGE_DT,
   AUX1_CHANGED_ON_DT,
   AUX2_CHANGED_ON_DT,
   AUX3_CHANGED_ON_DT,
   AUX4_CHANGED_ON_DT,
   CHANGED_BY_ID,
   CHANGED_ON_DT,
   CREATED_BY_ID,
   CREATED_ON_DT,
   DATASOURCE_NUM_ID,
   DELETE_FLG,
   DOC_CURR_CODE,
   ETL_THREAD_VAL,
   GLOBAL1_EXCHANGE_RATE,
   GLOBAL2_EXCHANGE_RATE,
   GLOBAL3_EXCHANGE_RATE,
   INTEGRATION_ID,
   LOC_CURR_CODE,
   LOC_EXCHANGE_RATE,
   TENANT_ID,
   X_CUSTOM,
   BBG_RETAIL_TYPE_ID,
   BBG_SERVICE_SATISFACTION,
   SRC_REF_NO1,
   SRC_REF_NO2,
   SRC_REF_NO3,
   SRC_REF_NO6,
   SRC_REF_NO7,
   SRC_REF_NO8,
   BBG_REFERENCE_DO1,
   BBG_REFERENCE_DO2,
   BBG_REFERENCE_DO3,
   BBG_REFERENCE_DO4,
   BBG_REFERENCE_DO5,
   BBG_REFERENCE_FO1,
   BBG_REFERENCE_FO2,
   BBG_REFERENCE_FO3,
   BBG_REFERENCE_FO4,
   BBG_REFERENCE_FO5,
   BBG_REFERENCE_FO6,
   BBG_REFERENCE_FO7,
   BBG_REFERENCE_FO8,
   BBG_REFERENCE_FO9,
   BBG_REFERENCE_FO10,
   HYK_NO)
  SELECT T.SLS_TRX_ID,
         T.PROD_IT_NUM,
         T.ORG_NUM,
         T.DAY_DT,
         -1 VOUCHER_ID,
         T.RTL_TYPE_CODE,
         T.MIN_NUM,
         -1 EMPLOYEE_NUM,
         T.SLS_QTY,
         T.SLS_AMT_LCL,
         T.SLS_PROFIT_AMT_LCL,
         T.SLS_TAX_AMT_LCL,
         T.SLS_EMP_DISC_AMT_LCL,
         T.SLS_MANUAL_COUNT,
         T.SLS_SCAN_COUNT,
         T.RET_QTY RET_QTY,
         T.RET_AMT_LCL RET_AMT_LCL,
         T.RET_PROFIT_AMT_LCL,
         T.RET_TAX_AMT_LCL RET_TAX_AMT_LCL,
         T.RET_EMP_DISC_AMT_LCL,
         T.RET_MANUAL_COUNT,
         T.RET_SCAN_COUNT,
         NULL REJECT_FLG,
         T.SLS_MANUAL_MKDN_AMT_LCL,
         T.SLS_MANUAL_MKUP_AMT_LCL,
         T.RET_MANUAL_MKDN_AMT_LCL,
         T.RET_MANUAL_MKUP_AMT_LCL,
         T.DAY_DT EXCHANGE_DT,
         NULL AUX1_CHANGED_ON_DT,
         NULL AUX2_CHANGED_ON_DT,
         NULL AUX3_CHANGED_ON_DT,
         NULL AUX4_CHANGED_ON_DT,
         -1 CHANGED_BY_ID,
         SYSDATE CHANGED_ON_DT,
         -1 CREATED_BY_ID,
         SYSDATE CREATED_ON_DT,
         1 DATASOURCE_NUM_ID,
         NULL DELETE_FLG,
         'CNY' DOC_CURR_CODE,
         (SELECT L.THREAD_VAL
            FROM RA_RMS.RA_RESTART_LOC@RA_RMS_DBLINK L
           WHERE T.ORG_NUM = L.DRIVER_VALUE
             AND L.SCENARIO_NAME = 'SDE_BBG_RETAIL_SALESTRANSACTIONFACT') ETL_THREAD_VAL,
         NULL GLOBAL1_EXCHANGE_RATE,
         NULL GLOBAL2_EXCHANGE_RATE,
         NULL GLOBAL3_EXCHANGE_RATE,
         T.SLS_TRX_ID || '~' || T.PROD_IT_NUM || '~-1~' ||
         TO_CHAR(T.DAY_DT, 'DD-MON-YY', 'NLS_DATE_LANGUAGE = American') INTEGRATION_ID,
         'CNY' LOC_CURR_CODE,
         NULL LOC_EXCHANGE_RATE,
         NULL TENANT_ID,
         NULL X_CUSTOM,
         T.BBG_RETAIL_TYPE_ID,
         3.5 BBG_SERVICE_SATISFACTION,
         NULL SRC_REF_NO1,
         NULL SRC_REF_NO2,
         NULL SRC_REF_NO3,
         T.PROD_IT_NUM SRC_REF_NO6,
         NULL SRC_REF_NO7,
         NULL SRC_REF_NO8,
         NULL BBG_REFERENCE_DO1,
         NULL BBG_REFERENCE_DO2,
         NULL BBG_REFERENCE_DO3,
         NULL BBG_REFERENCE_DO4,
         NULL BBG_REFERENCE_DO5,
         NULL BBG_REFERENCE_FO1,
         NULL BBG_REFERENCE_FO2,
         NULL BBG_REFERENCE_FO3,
         NULL BBG_REFERENCE_FO4,
         NULL BBG_REFERENCE_FO5,
         NULL BBG_REFERENCE_FO6,
         NULL BBG_REFERENCE_FO7,
         NULL BBG_REFERENCE_FO8,
         NULL BBG_REFERENCE_FO9,
         NULL BBG_REFERENCE_FO10,
         T.HYK_NO HYK_NO
    FROM (SELECT SLS_TRX_ID,
                 PROD_IT_NUM,
                 ORG_NUM,
                 DAY_DT,
                 VOUCHER_ID,
                 RTL_TYPE_CODE,
                 MIN_NUM,
                 SLS_QTY,
                 SLS_AMT_LCL,
                 SLS_PROFIT_AMT_LCL,
                 SLS_TAX_AMT_LCL,
                 SLS_EMP_DISC_AMT_LCL,
                 SLS_MANUAL_COUNT,
                 SLS_SCAN_COUNT,
                 -RET_QTY                 RET_QTY,
                 -RET_AMT_LCL             RET_AMT_LCL,
                 -RET_PROFIT_AMT_LCL      RET_PROFIT_AMT_LCL,
                 -RET_TAX_AMT_LCL         RET_TAX_AMT_LCL,
                 -RET_EMP_DISC_AMT_LCL    RET_EMP_DISC_AMT_LCL,
                 -RET_MANUAL_COUNT        RET_MANUAL_COUNT,
                 -RET_SCAN_COUNT          RET_SCAN_COUNT,
                 SLS_MANUAL_MKDN_AMT_LCL,
                 SLS_MANUAL_MKUP_AMT_LCL,
                 -RET_MANUAL_MKDN_AMT_LCL RET_MANUAL_MKDN_AMT_LCL,
                 -RET_MANUAL_MKUP_AMT_LCL RET_MANUAL_MKUP_AMT_LCL,
                 BBG_RETAIL_TYPE_ID,
                 HYK_NO
            FROM BBG_RA_SLS_TRX_JL_V@RA_JL
           WHERE DAY_DT IN (DATE '2016-07-03', DATE '2016-07-04')) T;
COMMIT;

--3.
--Master_SIL_BBG_Retail_SalesTransactionFact
SELECT * FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP;
--4.
--UC4 PLP_SALES_TRANSACTION
