--1.
SELECT *
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS A
 WHERE NOT EXISTS (SELECT 1
          FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP B
         WHERE A.ORG_NUM = B.ORG_NUM
           AND A.PROD_IT_NUM = B.PROD_IT_NUM);
					 
--2.
SELECT * FROM RA_RMS.BBG_XTERN_RDWT T WHERE T.BUSINESS_DT=20161128 AND T.LOCATION='0000120092';
SELECT * FROM RA_RMS.BBG_XTERN_RDWT_BAK T WHERE T.BUSINESS_DT=20161129;

--3.
SELECT * FROM TRAN_DATA_HISTORY T WHERE T.TRAN_DATE=DATE'2016-11-28' AND T.TRAN_CODE IN (1,2,3) AND T.LOCATION=120092;
--4.
TRUNCATE TABLE RA_RMS.BBG_XTERN_RDWT_BAK;
INSERT INTO RA_RMS.BBG_XTERN_RDWT_BAK
SELECT * FROM RA_RMS.BBG_XTERN_RDWT;
COMMIT;
DELETE RA_RMS.BBG_XTERN_RDWT T WHERE T.BUSINESS_DT=20161129;
COMMIT;
--5.
TRUNCATE TABLE RA_RMS.C_LOAD_DATES;
--6.
SELECT * FROM RA_RMS.BBG_RA_ITEM_LOC_SOH_V;
--7.
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS;
DELETE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T WHERE T.DAY_DT=DATE'2016-11-29';
COMMIT;
--8.
TRUNCATE TABLE RADM.C_LOAD_DATES;
--9.
SELECT * FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP;
--10.

--11.

--12.

--13.

