--2016.10.18 loc:139056 dept:70 item:2400070072496
--***********************************************************
--SALES
--***********************************************************
--1.
TRUNCATE TABLE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK;
INSERT INTO RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS;
COMMIT;

TRUNCATE TABLE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS;
INSERT INTO RADM.W_RTL_SLS_TRX_IT_LC_DY_FS
SELECT *
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK T
 WHERE T.PROD_IT_NUM = '2400070072496'
   AND T.ORG_NUM = '139056';
COMMIT;

SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS;

--2.SIL
SELECT * FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP;

--3.PLP_SALES


--***********************************************************
--SUPP SALES
--***********************************************************
--1.
TRUNCATE TABLE RADM.BBG_RA_SLS_IT_LC_DY_FS_BAK;
INSERT INTO RADM.BBG_RA_SLS_IT_LC_DY_FS_BAK
SELECT * FROM RADM.BBG_RA_SLS_IT_LC_DY_FS;
COMMIT;

TRUNCATE TABLE RADM.BBG_RA_SLS_IT_LC_DY_FS;
INSERT INTO RADM.BBG_RA_SLS_IT_LC_DY_FS
SELECT * FROM RADM.BBG_RA_SLS_IT_LC_DY_FS_BAK T WHERE T.ORG_NUM='139056' AND T.PROD_IT_NUM='2400070072496';
COMMIT;

SELECT * FROM RADM.BBG_RA_SLS_IT_LC_DY_FS;

--2.SUPP SIL
SELECT * FROM RABATCHER.BBG_RA_SUPP_SLS_IT_LC_DY_TMP;
--3.
 
