--1.缺失清单,原因：部分item-loc维度缺失。造成部分销售未导入RA.
SELECT DISTINCT A.PROD_IT_NUM, A.ORG_NUM
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS A
 WHERE NOT EXISTS (SELECT 1
          FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP B
         WHERE A.PROD_IT_NUM = B.PROD_IT_NUM
           AND A.ORG_NUM = B.ORG_NUM)
   AND A.BBG_SERVICE_SATISFACTION = 3.5;

--2.
DELETE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T
 WHERE NVL(T.BBG_SERVICE_SATISFACTION, 0) <> 3.5;
COMMIT;

DROP TABLE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK;
CREATE TABLE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK AS
  SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS;

--3.
DELETE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T
 WHERE EXISTS (SELECT 1
          FROM (SELECT DISTINCT A.PROD_IT_NUM, A.ORG_NUM
                  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS A
                 WHERE EXISTS (SELECT 1
                          FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP B
                         WHERE A.PROD_IT_NUM = B.PROD_IT_NUM
                           AND A.ORG_NUM = B.ORG_NUM)
                   AND A.BBG_SERVICE_SATISFACTION = 3.5) C
         WHERE T.PROD_IT_NUM = C.PROD_IT_NUM
           AND T.ORG_NUM = C.ORG_NUM);

TRUNCATE TABLE RADM.C_LOAD_DATES;

