--昨日7075的销售还是划入7074销售。
/*
2400070071738
2400070071961
2400070071990
2400070071993
2400070071817
*/
--1.SDE_RetailItemDimension
TRUNCATE TABLE RA_RMS.C_LOAD_DATES;

SELECT * FROM RADM.W_PRODUCT_DS;
SELECT * FROM RADM.W_PRODUCT_ATTR_DS;
SELECT * FROM RADM.W_PRODUCT_DS_TL;

DELETE RADM.W_PRODUCT_DS T WHERE T.PROD_CAT5 <> '7~70~70~707~7074';
COMMIT;
DELETE FROM RADM.W_PRODUCT_ATTR_DS T
 WHERE NOT EXISTS
 (SELECT 1 FROM RADM.W_PRODUCT_DS P WHERE T.PROD_NUM = P.PROD_NUM);
COMMIT;
DELETE FROM RADM.W_PRODUCT_DS_TL T
 WHERE NOT EXISTS (SELECT 1
          FROM RADM.W_PRODUCT_DS P
         WHERE T.INTEGRATION_ID = P.PROD_NUM);
COMMIT;

--2.SIL_ItemDimension
TRUNCATE TABLE RADM.C_LOAD_DATES;
SELECT * FROM RADM.W_PRODUCT_D T WHERE T.PROD_NUM='2400070071738';

--3.PLP_RetailProductDimensionLkUpTemp
SELECT *
  FROM RABATCHER.W_PRODUCT_D_RTL_TMP T
 WHERE T.PROD_IT_NUM = '2400070071738';

--4.SALES_SDE
TRUNCATE TABLE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK;
INSERT INTO RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS;
COMMIT;

INSERT INTO RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK
  SELECT /*+PARALLEL(16)*/
   *
    FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS A
   WHERE NOT EXISTS (SELECT /*+PARALLEL(16)*/
           1
            FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP B
           WHERE A.SLS_TRX_ID = B.SLS_TRX_ID
             AND A.PROD_IT_NUM = B.PROD_IT_NUM);
COMMIT;

TRUNCATE TABLE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS;
INSERT INTO RADM.W_RTL_SLS_TRX_IT_LC_DY_FS
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK;
COMMIT;

--5.BBG_SIL_Retail_SalesTransactionFact
TRUNCATE TABLE RADM.C_LOAD_DATES;
SELECT * FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP;

--6.PLP_SALES_TRANSACTION

--7.SUPP_SALES
TRUNCATE TABLE RADM.BBG_RA_SLS_IT_LC_DY_FS_BAK;
INSERT INTO RADM.BBG_RA_SLS_IT_LC_DY_FS_BAK
SELECT * FROM RADM.BBG_RA_SLS_IT_LC_DY_FS;
COMMIT;

INSERT INTO RADM.BBG_RA_SLS_IT_LC_DY_FS_BAK
  SELECT /*+PARALLEL(16)*/
   *
    FROM RADM.BBG_RA_SLS_IT_LC_DY_FS A
   WHERE NOT EXISTS (SELECT /*+PARALLEL(16)*/
           1
            FROM RABATCHER.BBG_RA_SUPP_SLS_IT_LC_DY_TMP B
           WHERE A.SUPPLIER_NUM = B.SUPPLIER_NUM
             AND A.ORG_NUM = B.ORG_NUM
             AND A.PROD_IT_NUM = B.PROD_IT_NUM);
COMMIT;

TRUNCATE TABLE RADM.BBG_RA_SLS_IT_LC_DY_FS;
INSERT INTO RADM.BBG_RA_SLS_IT_LC_DY_FS
SELECT * FROM RADM.BBG_RA_SLS_IT_LC_DY_FS_BAK;
COMMIT;

--8.BBG_SIL_BBG_RA_SUPP_SALES_IT_LC_DY_F
SELECT * FROM RABATCHER.BBG_RA_SUPP_SLS_IT_LC_DY_TMP;

--9.BBG.CMX.RA.F20_SUPP_SALES

--10.MONTHS AGGREGATE



BBG_RA_SLS_IT_LC_DY_FS

SELECT * FROM BBG_RA_PRODUCT_JL_V@RA_JL A WHERE NOT EXISTS(SELECT 1 FROM RADM.W_PRODUCT_D P WHERE A.PROD_NUM=P.PROD_NUM);
SELECT * FROM BBG_RA_SLS_TRX_JL_V@RA_JL WHERE DAY_DT = &DAY_DT;
SELECT * FROM BBG_RA_PRODUCT_JL_V@RA_JL WHERE PROD_CAT5 LIKE '%7075%';

SELECT * FROM BBG_RA_PRODUCT_JL_V@RA_JL T WHERE T.SRC_EFF_FROM_DT=DATE'2016-03-31';

SELECT * FROM BBG_RA_PRODUCT_JL_V@RA_JL T WHERE T.PROD_NUM='2400070072003';

SELECT * FROM RADM.W_PRODUCT_D T WHERE T.PROD_NUM='2400070071738';
SELECT * FROM RABATCHER.W_PRODUCT_D_RTL_TMP T WHERE T.PROD_IT_NUM='2400070072003';
