--2016/10/24 item:103577259,loc:120236
--1.
SELECT *
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS A
 WHERE NOT EXISTS (SELECT 1
          FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP B
         WHERE A.ORG_NUM = B.ORG_NUM
           AND A.PROD_IT_NUM = B.PROD_IT_NUM);

SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T WHERE T.ORG_NUM='120236' AND T.PROD_IT_NUM='103577259';
SELECT * FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP T WHERE T.ORG_NUM='120236' AND T.PROD_IT_NUM='103577259';
SELECT /*+PARALLEL(16)*/ * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F T WHERE T.ORG_WID=560004 AND T.PROD_WID=8889440;
SELECT * FROM RADM.BBG_RA_SLS_IT_LC_DY_FS T WHERE T.ORG_NUM='120236' AND T.PROD_IT_NUM='103577259';
SELECT * FROM RABATCHER.BBG_RA_SUPP_SLS_IT_LC_DY_TMP T WHERE T.ORG_NUM='120236' AND T.PROD_IT_NUM='103577259';
SELECT /*+PARALLEL(16)*/ * FROM RADM.BBG_RA_SUPP_SALES_IT_LC_DY_F T WHERE T.ORG_WID=560004 AND T.PROD_WID=8889440;


--2.SALES
TRUNCATE TABLE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK;

INSERT INTO RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS;
COMMIT;

TRUNCATE TABLE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS;

INSERT INTO RADM.W_RTL_SLS_TRX_IT_LC_DY_FS
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK T WHERE T.ORG_NUM='120236' AND T.PROD_IT_NUM='103577259';
COMMIT; 

TRUNCATE TABLE RADM.C_LOAD_DATES;

--3.SUPP SALES
TRUNCATE TABLE RADM.BBG_RA_SLS_IT_LC_DY_FS_BAK;

INSERT INTO RADM.BBG_RA_SLS_IT_LC_DY_FS_BAK
SELECT * FROM RADM.BBG_RA_SLS_IT_LC_DY_FS;
COMMIT;

TRUNCATE TABLE RADM.BBG_RA_SLS_IT_LC_DY_FS;

INSERT INTO RADM.BBG_RA_SLS_IT_LC_DY_FS
SELECT * FROM RADM.BBG_RA_SLS_IT_LC_DY_FS_BAK T WHERE T.ORG_NUM='120236' AND T.PROD_IT_NUM='103577259';
COMMIT;



