--1.
TRUNCATE TABLE RA_RMS.BBG_XTERN_RDWT;
INSERT INTO RA_RMS.BBG_XTERN_RDWT
  SELECT /*+PARALLEL(16)*/
   *
    FROM RA_RMS.BBG_XTERN_RDWT_HIST T
   WHERE T.BUSINESS_DT = 20170101
     AND T.LOCATION IN ('0000120022', '0000120149', '0000120197');
COMMIT;
--2.
SELECT * FROM RA_RMS.BBG_RA_ITEM_LOC_SOH_V;
--3.
TRUNCATE TABLE RA_RMS.C_LOAD_DATES;
SELECT DISTINCT T.DAY_DT, T.ORG_NUM FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T;
DELETE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T WHERE T.DAY_DT = DATE '2017-01-02';
COMMIT;
--4.
TRUNCATE TABLE RADM.C_LOAD_DATES;
SELECT DISTINCT T.ORG_NUM FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP T;

--5.

--6.


SELECT * FROM RA_RMS.W_RTL_SLS_TRX_TMP;
SELECT T.LOCATION,COUNT(1)
  FROM TRAN_DATA_HISTORY T
 WHERE T.TRAN_DATE = DATE '2017-01-01'
   AND T.TRAN_CODE IN (1, 2, 3)
   GROUP BY T.LOCATION
   ORDER BY T.LOCATION;
