--1.2017-01-19
/*
120267 800030987
120191 800030987
*/
SELECT *
  FROM RA_RMS.BBG_XTERN_RDWT A
 WHERE NOT EXISTS (SELECT 1
          FROM W_RTL_SLS_TRX_IT_LC_DY_FS@RMS_RA B
         WHERE A.ITEM = B.PROD_IT_NUM
           AND TO_NUMBER(A.LOCATION) = B.ORG_NUM);

--2.
TRUNCATE TABLE RA_RMS.BBG_XTERN_RDWT;
INSERT INTO RA_RMS.BBG_XTERN_RDWT
  SELECT /*+PARALLEL(16)*/
   *
    FROM RA_RMS.BBG_XTERN_RDWT_HIST T
   WHERE T.BUSINESS_DT = 20170119
     AND T.ITEM = 800030987
     AND T.LOCATION IN ('0000120191', '0000120267');
COMMIT;

--3.
SELECT * FROM RA_RMS.BBG_RA_ITEM_LOC_SOH_V;
--4.
DELETE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T WHERE T.BBG_SERVICE_SATISFACTION=3.5;
COMMIT;
--5.
TRUNCATE TABLE RADM.C_LOAD_DATES;
SELECT * FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP;


--TMP
SELECT T.LOCATION, TO_NUMBER(T.LOCATION) FROM RA_RMS.BBG_XTERN_RDWT T;
SELECT * FROM W_RTL_SLS_TRX_IT_LC_DY_FS@RMS_RA;
