--2017-02-07,120254,76,100014581,-155.2564
--2017-02-07,120235,76,100318729,-7.61

--1.
TRUNCATE TABLE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK;
INSERT INTO RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS;
COMMIT;

TRUNCATE TABLE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS;
INSERT INTO RADM.W_RTL_SLS_TRX_IT_LC_DY_FS
  SELECT *
    FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK T
   WHERE T.ORG_NUM = 120235
     AND T.PROD_IT_NUM = 100318729;
COMMIT;

--2.
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS FOR UPDATE;
UPDATE RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T
   SET T.SLS_QTY                 = 0,
       T.SLS_AMT_LCL             = 0,
       T.SLS_PROFIT_AMT_LCL      = 0,
       T.SLS_MANUAL_MKDN_AMT_LCL = 0,
       T.SLS_MANUAL_MKUP_AMT_LCL = 0,
       T.SLS_TAX_AMT_LCL         = 0,
       T.SLS_EMP_DISC_AMT_LCL    = 0,
       T.SLS_MANUAL_COUNT        = 0,
       T.SLS_SCAN_COUNT          = 0,
       T.RET_QTY                 = 0,
       T.RET_AMT_LCL             = 0,
       T.RET_PROFIT_AMT_LCL      = -7.61,
       T.RET_MANUAL_MKDN_AMT_LCL = 0,
       T.RET_MANUAL_MKUP_AMT_LCL = 0,
       T.RET_TAX_AMT_LCL         = 0,
       T.RET_EMP_DISC_AMT_LCL    = 0,
       T.RET_MANUAL_COUNT        = 0,
       T.RET_SCAN_COUNT          = 0,
       T.SLS_COUPON_AMT_LCL      = 0,
       T.RET_COUPON_AMT_LCL      = 0,
       T.SLS_TAX_COUPON_AMT_LCL  = 0,
       T.RET_TAX_COUPON_AMT_LCL  = 0;
COMMIT;

--3.
TRUNCATE TABLE RADM.C_LOAD_DATES;
--4.
SELECT * FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP;
