--BBG_RA_SLS_IT_LC_DY_A
--BBG_RA_SLS_IT_LC_DY_A_HIST
--BBG_RA_SLS_IT_LC_DY_A_V

--1.
CREATE TABLE RADM.BBG_RA_SLS_IT_LC_DY_A_HIST AS
SELECT * FROM RADM.BBG_RA_SLS_IT_LC_DY_A WHERE 1=2;

--2.
CREATE OR REPLACE VIEW RADM.BBG_RA_SLS_IT_LC_DY_A_V AS
SELECT * FROM RADM.BBG_RA_SLS_IT_LC_DY_A_HIST
UNION ALL
SELECT * FROM RADM.BBG_RA_SLS_IT_LC_DY_A;



