--BBG_RA_CUST_IT_LC_DY_F
--BBG_RA_CUST_IT_LC_DY_F_HIST
--BBG_RA_CUST_IT_LC_DY_F_V

--1.
CREATE TABLE RADM.BBG_RA_CUST_IT_LC_DY_F_HIST AS
SELECT * FROM RADM.BBG_RA_CUST_IT_LC_DY_F WHERE 1=2;

--2.
CREATE OR REPLACE VIEW RADM.BBG_RA_CUST_IT_LC_DY_F_V AS
SELECT * FROM RADM.BBG_RA_CUST_IT_LC_DY_F_HIST
UNION ALL
SELECT * FROM RADM.BBG_RA_CUST_IT_LC_DY_F;
