--W_RTL_NCOST_IT_DY_A
--W_RTL_NCOST_IT_DY_A_HIST
--W_RTL_NCOST_IT_DY_A_V

--1.
CREATE TABLE RADM.W_RTL_NCOST_IT_DY_A_HIST AS
SELECT * FROM RADM.W_RTL_NCOST_IT_DY_A WHERE 1=2;

--2.
CREATE OR REPLACE VIEW RADM.W_RTL_NCOST_IT_DY_A_V AS
SELECT * FROM RADM.W_RTL_NCOST_IT_DY_A_HIST
UNION ALL
SELECT * FROM RADM.W_RTL_NCOST_IT_DY_A;



