--新建虚拟门店：９９３３８，９９３３９
--测试内容：９９３３８门店与１２０００１门店合并成一个门店，并且采用１２０００１的SCD1_WID
SELECT * FROM RADM.W_INT_ORG_DH T;
SELECT * FROM RADM.W_RTL_ORG_FIN_D;
SELECT * FROM RADM.W_INT_ORG_ATTR_D;
SELECT * FROM RADM.W_INT_ORG_D;
SELECT * FROM RADM.W_INT_ORG_D_TL;

--A.当虚拟门店传入RA系统之后,修改门店的失效日期---------------------------------------------------------
--W_INT_ORG_DH
UPDATE RADM.W_INT_ORG_DH T
   SET T.EFFECTIVE_TO_DT = DATE '2100-01-01'
 WHERE T.ORG_HIER9_NUM IN (99338);
COMMIT;
--W_INT_ORG_ATTR_D 
UPDATE RADM.W_INT_ORG_ATTR_D T
   SET T.EFFECTIVE_TO_DT = DATE '2100-01-01'
 WHERE T.INTEGRATION_ID IN (99338);
COMMIT;
--W_INT_ORG_D 
UPDATE RADM.W_INT_ORG_D T
   SET T.EFFECTIVE_TO_DT = DATE '2100-01-01'
 WHERE T.ORG_NUM IN (99338);
COMMIT;

--B.当正式门店资料传入RA系统之后,把二个门店信息合并--------------------------------------------------------
--W_INT_ORG_ATTR_D
DELETE RADM.W_INT_ORG_ATTR_D D WHERE D.INTEGRATION_ID = '99338';
COMMIT;

--W_INT_ORG_D
DELETE RADM.W_INT_ORG_D D WHERE D.ORG_NUM = '99338';
COMMIT;

--W_INT_ORG_D_TL
DELETE RADM.W_INT_ORG_D_TL D WHERE D.INTEGRATION_ID='99338'
COMMIT;

--W_INT_ORG_DH
UPDATE RADM.W_INT_ORG_DH DH
   SET (DH.ORG_HIER9_NUM,
        DH.ORG_HIER10_NUM,
        DH.ORG_HIER11_NUM,
        DH.ORG_HIER12_NUM,
        DH.ORG_HIER13_NUM,
        DH.ORG_TOP_NUM,
        DH.SCD1_WID,
        DH.RETAIL_FLG,
        DH.INV_ORG_FLG,
        DH.EFFECTIVE_TO_DT,
        DH.INTEGRATION_ID,
        DH.W_UPDATE_DT) =
       (SELECT O.ORG_HIER9_NUM,
               O.ORG_HIER10_NUM,
               O.ORG_HIER11_NUM,
               O.ORG_HIER12_NUM,
               O.ORG_HIER13_NUM,
               O.ORG_TOP_NUM,
               O.SCD1_WID,
               O.RETAIL_FLG,
               O.INV_ORG_FLG,
               O.EFFECTIVE_FROM_DT - 1,
               O.INTEGRATION_ID,
               SYSDATE
          FROM RADM.W_INT_ORG_DH O
         WHERE O.ORG_HIER9_NUM = '120001' --正式门店编码
           AND SYSDATE BETWEEN O.EFFECTIVE_FROM_DT AND O.EFFECTIVE_TO_DT)
 WHERE DH.ORG_HIER9_NUM = '99338' --虚拟门店编码
   AND SYSDATE BETWEEN DH.EFFECTIVE_FROM_DT AND DH.EFFECTIVE_TO_DT;
COMMIT;

--C.销售预算FACT处理----------------------------------------------------------------------------------
--检查销售预算源表是否调整
SELECT * FROM RADM.BBG_RA_SLSFC_DP_LC_DY_FS_V T;

--修改之前的销售预算表数据
UPDATE RADM.BBG_RA_SLSFC_DP_LC_DY_F F
   SET (F.ORG_WID, F.ORG_SCD1_WID) =
       (SELECT O.ROW_WID, O.SCD1_WID
          FROM RADM.W_INT_ORG_D O
         WHERE O.ORG_NUM = '120001')
 WHERE F.INTEGRATION_ID LIKE '%99338%';



--tmp SQL---------------------------------------------------------------------------------------------
SELECT * FROM RADM.BBG_RA_SLSFC_DP_LC_DY_F T WHERE T.INTEGRATION_ID LIKE '%120001%';

SELECT * FROM RADM.W_INT_ORG_DH;
SELECT * FROM RADM.W_INT_ORG_DHS;

SELECT * FROM RABATCHER.ODI_SQ_W_INT_ORG_DH;

SELECT STG.INTEGRATION_ID,
       STG.DATASOURCE_NUM_ID,
       STG.SCD1_WID,
       RANK() OVER(ORDER BY STG.INTEGRATION_ID, STG.DATASOURCE_NUM_ID)
  FROM RADM.W_INT_ORG_DH STG;

BBG_RA_SLSFC_DP_LC_DY_FS_V;

SELECT * FROM RADM.W_INT_ORG_DH T WHERE T.ORG_HIER9_NUM IN (99338, 120001);

SELECT *
  FROM RADM.W_INT_ORG_ATTR_D T
 WHERE T.INTEGRATION_ID IN (99338, 120001);
SELECT * FROM RADM.W_INT_ORG_D T WHERE T.ORG_NUM IN (99338, 120001);

SELECT * FROM RADM.W_INT_ORG_D T WHERE T.ORG_NUM IN (99338, 120001) FOR UPDATE;

SELECT * FROM RADM.W_INT_ORG_D_TL;
