----------------------------------------------------------------------------------

--因为需要按经营属性(经销\代销)分别计算周转天数,
--所以从BBG_RA_ITEM_LOC_D表BUSINESS_MODE(经营属性)得到数据
--汇总三条路径:
--A.类别:中类cl->大类dp->品类(分部)dv
--B.地理:门店大类->门店->区域
--C.供应商
--周转天数=(上月期末库存成本+本月期末库存成本)/(本月销售成本/本月天数)
--源表:W_RTL_SLS_IT_LC_DY_TMP关联商品类别表,然后汇总出class级别的到天的表,然后再创建按月汇总的物化试图
--W_RTL_SLS_IT_LC_DY_TMP-->BBG_RA_SLS_CL_BM_DY_TMP-->BBG_RA_SLS_CL_BM_DY_A-->BBG_RA_SLS_CL_BM_MN_A
--                      -->BBG_RA_SLS_DP_BM_DY_TMP-->BBG_RA_SLS_DP_BM_DY_A-->BBG_RA_SLS_DP_BM_MN_A
--                      -->BBG_RA_SLS_DV_BM_DY_TMP-->BBG_RA_SLS_DV_BM_DY_A-->BBG_RA_SLS_DV_BM_MN_A
--                                               
--INTEGRATION_ID:类别~日期~RTL_TYPE_WID~BBG_RETAIL_TYPE_WID

--MATERIALIZED VIEW YJ_TOTAL_SLS_IT_LC_MN_TMP 销售临时汇总表
--RADM.BBG_RA_SLS_CL_BM_DY_A:中类天汇总销售表
--RADM.BBG_RA_SLS_DP_BM_DY_A:大类天汇总销售表
--RABATCHER.BBG_RA_SLS_CL_BM_DY_TMP:中类天汇总销售表
--RABATCHER.BBG_RA_SLS_DP_BM_DY_TMP:大类天汇总销售表
-----------------------------------------------------------------------------------

----------1.销售
--源表,通过BBG_RA_ITEM_LOC_WID关联BBG_RA_ITEM_LOC_D表BUSINESS_MODE,计划由每日完运行
SELECT * FROM RABATCHER.W_RTL_SLS_IT_LC_DY_TMP;
--中类
--参考表(包含地点):
SELECT * FROM W_RTL_SLS_CL_LC_MN_A;

---------------------------------------------------------------------------------------
--历史数据倒入
--历史数据从W_RTL_SLS_IT_LC_DY_A导入W_RTL_SLS_CL_MN_A
SELECT * FROM BBG_RA_ITEM_LOC_D;
SELECT * FROM RADM.W_RTL_SLS_IT_LC_DY_A; --源表
SELECT * FROM W_RTL_SLS_CL_MN_A; --目标表
SELECT * FROM W_PROD_CAT_DH; --商品类别表:LVL5ANC_PRODCAT_ID 中类

--插入语句BBG_RA_SLS_CL_BM_MN_A
INSERT INTO BBG_RA_SLS_CL_BM_MN_A
	(PROD_DH_WID,
	 MN_WID,
	 RTL_TYPE_WID,
	 BUSINESS_MODE,
	 SLS_QTY,
	 SLS_AMT_LCL,
	 SLS_PROFIT_AMT_LCL,
	 SLS_TAX_AMT_LCL,
	 SLS_EMP_DISC_AMT_LCL,
	 SLS_MANUAL_MKDN_AMT_LCL,
	 SLS_MANUAL_MKUP_AMT_LCL,
	 RET_QTY,
	 RET_AMT_LCL,
	 RET_PROFIT_AMT_LCL,
	 RET_TAX_AMT_LCL,
	 RET_EMP_DISC_AMT_LCL,
	 RET_MANUAL_MKDN_AMT_LCL,
	 RET_MANUAL_MKUP_AMT_LCL,
	 SLS_MANUAL_COUNT,
	 SLS_SCAN_COUNT,
	 RET_MANUAL_COUNT,
	 RET_SCAN_COUNT,
	 INTEGRATION_ID,
	 GLOBAL1_EXCHANGE_RATE,
	 GLOBAL2_EXCHANGE_RATE,
	 GLOBAL3_EXCHANGE_RATE,
	 LOC_EXCHANGE_RATE,
	 BBG_RETAIL_TYPE_WID,
	 BBG_CUSTOMER_COUNT,
	 BBG_SERVICE_SATISFACTION,
	 BBG_REFERENCE_DO1,
	 BBG_REFERENCE_DO2,
	 BBG_REFERENCE_DO3,
	 BBG_REFERENCE_DO4,
	 BBG_REFERENCE_DO5,
	 BBG_REFERENCE_FO1,
	 BBG_REFERENCE_FO2,
	 BBG_REFERENCE_FO3,
	 BBG_REFERENCE_FO4,
	 BBG_REFERENCE_FO5,
	 BBG_REFERENCE_FO6,
	 BBG_REFERENCE_FO7,
	 BBG_REFERENCE_FO8,
	 BBG_REFERENCE_FO9,
	 BBG_REFERENCE_FO10)
	SELECT /*RADM.BBG_RA_SLS_CL_BM_MN_A_SEQ.NEXTVAL,*/
	 A.*
		FROM (SELECT C.PROD_CL_WID PROD_DH_WID,
								 S.MN_WID,
								 S.RTL_TYPE_WID,
								 IL.BUSINESS_MODE,
								 SUM(S.SLS_QTY) SLS_QTY,
								 SUM(S.SLS_AMT_LCL) SLS_AMT_LCL,
								 SUM(S.SLS_PROFIT_AMT_LCL) SLS_PROFIT_AMT_LCL,
								 SUM(S.SLS_TAX_AMT_LCL) SLS_TAX_AMT_LCL,
								 SUM(S.SLS_EMP_DISC_AMT_LCL) SLS_EMP_DISC_AMT_LCL,
								 SUM(S.SLS_MANUAL_MKDN_AMT_LCL) SLS_MANUAL_MKDN_AMT_LCL,
								 SUM(S.SLS_MANUAL_MKUP_AMT_LCL) SLS_MANUAL_MKUP_AMT_LCL,
								 SUM(S.RET_QTY) RET_QTY,
								 SUM(S.RET_AMT_LCL) RET_AMT_LCL,
								 SUM(S.RET_PROFIT_AMT_LCL) RET_PROFIT_AMT_LCL,
								 SUM(S.RET_TAX_AMT_LCL) RET_TAX_AMT_LCL,
								 SUM(S.RET_EMP_DISC_AMT_LCL) RET_EMP_DISC_AMT_LCL,
								 SUM(S.RET_MANUAL_MKDN_AMT_LCL) RET_MANUAL_MKDN_AMT_LCL,
								 SUM(S.RET_MANUAL_MKUP_AMT_LCL) RET_MANUAL_MKUP_AMT_LCL,
								 SUM(S.SLS_MANUAL_COUNT) SLS_MANUAL_COUNT,
								 SUM(S.SLS_SCAN_COUNT) SLS_SCAN_COUNT,
								 SUM(S.RET_MANUAL_COUNT) RET_MANUAL_COUNT,
								 SUM(S.RET_SCAN_COUNT) RET_SCAN_COUNT,
								 C.PROD_CL_NUM || '~' || S.MN_WID || '~' || CASE
									 WHEN S.RTL_TYPE_WID = 1 THEN
										'P'
									 WHEN S.RTL_TYPE_WID = 4 THEN
										'R'
								 END || '~' || IL.BUSINESS_MODE INTEGRATION_ID,
								 NULL GLOBAL1_EXCHANGE_RATE,
								 NULL GLOBAL2_EXCHANGE_RATE,
								 NULL GLOBAL4_EXCHANGE_RATE,
								 1 LOC_EXCHANGE_RATE,
								 S.BBG_RETAIL_TYPE_WID,
								 SUM(S.BBG_CUSTOMER_COUNT) BBG_CUSTOMER_COUNT,
								 SUM(S.BBG_SERVICE_SATISFACTION) BBG_SERVICE_SATISFACTION,
								 NULL BBG_REFERENCE_DO1,
								 NULL BBG_REFERENCE_DO2,
								 NULL BBG_REFERENCE_DO3,
								 NULL BBG_REFERENCE_DO4,
								 NULL BBG_REFERENCE_DO5,
								 SUM(S.BBG_REFERENCE_FO1) BBG_REFERENCE_FO1,
								 SUM(S.BBG_REFERENCE_FO2) BBG_REFERENCE_FO2,
								 NULL BBG_REFERENCE_FO3,
								 NULL BBG_REFERENCE_FO4,
								 NULL BBG_REFERENCE_FO5,
								 NULL BBG_REFERENCE_FO6,
								 NULL BBG_REFERENCE_FO7,
								 NULL BBG_REFERENCE_FO8,
								 NULL BBG_REFERENCE_FO9,
								 NULL BBG_REFERENCE_FO10
						FROM (SELECT * FROM YJ_TOTAL_SLS_IT_LC_MN_TMP) S,
								 RADM.BBG_RA_ITEM_LOC_D IL,
								 RABATCHER.W_PRODUCT_D_RTL_TMP C
					 WHERE S.BBG_ITEM_LOC_WID = IL.ROW_WID
						 AND C.PROD_IT_WID = S.PROD_WID
						 AND S.MN_WID <= '201311'
					 GROUP BY S.MN_WID,
										S.RTL_TYPE_WID,
										IL.BUSINESS_MODE,
										S.BBG_RETAIL_TYPE_WID,
										C.PROD_CL_WID,
										C.PROD_CL_NUM) A;
COMMIT;

--插入语句BBG_RA_SLS_DP_BM_MN_A
INSERT INTO BBG_RA_SLS_DP_BM_MN_A
	(PROD_DH_WID,
	 MN_WID,
	 RTL_TYPE_WID,
	 BUSINESS_MODE,
	 SLS_QTY,
	 SLS_AMT_LCL,
	 SLS_PROFIT_AMT_LCL,
	 SLS_TAX_AMT_LCL,
	 SLS_EMP_DISC_AMT_LCL,
	 SLS_MANUAL_MKDN_AMT_LCL,
	 SLS_MANUAL_MKUP_AMT_LCL,
	 RET_QTY,
	 RET_AMT_LCL,
	 RET_PROFIT_AMT_LCL,
	 RET_TAX_AMT_LCL,
	 RET_EMP_DISC_AMT_LCL,
	 RET_MANUAL_MKDN_AMT_LCL,
	 RET_MANUAL_MKUP_AMT_LCL,
	 SLS_MANUAL_COUNT,
	 SLS_SCAN_COUNT,
	 RET_MANUAL_COUNT,
	 RET_SCAN_COUNT,
	 INTEGRATION_ID,
	 GLOBAL1_EXCHANGE_RATE,
	 GLOBAL2_EXCHANGE_RATE,
	 GLOBAL3_EXCHANGE_RATE,
	 LOC_EXCHANGE_RATE,
	 BBG_RETAIL_TYPE_WID,
	 BBG_CUSTOMER_COUNT,
	 BBG_SERVICE_SATISFACTION,
	 BBG_REFERENCE_DO1,
	 BBG_REFERENCE_DO2,
	 BBG_REFERENCE_DO3,
	 BBG_REFERENCE_DO4,
	 BBG_REFERENCE_DO5,
	 BBG_REFERENCE_FO1,
	 BBG_REFERENCE_FO2,
	 BBG_REFERENCE_FO3,
	 BBG_REFERENCE_FO4,
	 BBG_REFERENCE_FO5,
	 BBG_REFERENCE_FO6,
	 BBG_REFERENCE_FO7,
	 BBG_REFERENCE_FO8,
	 BBG_REFERENCE_FO9,
	 BBG_REFERENCE_FO10)
	SELECT /*RADM.BBG_RA_SLS_CL_BM_MN_A_SEQ.NEXTVAL,*/
	 A.*
		FROM (SELECT C.PROD_DP_WID PROD_DH_WID,
								 S.MN_WID,
								 S.RTL_TYPE_WID,
								 IL.BUSINESS_MODE,
								 SUM(S.SLS_QTY) SLS_QTY,
								 SUM(S.SLS_AMT_LCL) SLS_AMT_LCL,
								 SUM(S.SLS_PROFIT_AMT_LCL) SLS_PROFIT_AMT_LCL,
								 SUM(S.SLS_TAX_AMT_LCL) SLS_TAX_AMT_LCL,
								 SUM(S.SLS_EMP_DISC_AMT_LCL) SLS_EMP_DISC_AMT_LCL,
								 SUM(S.SLS_MANUAL_MKDN_AMT_LCL) SLS_MANUAL_MKDN_AMT_LCL,
								 SUM(S.SLS_MANUAL_MKUP_AMT_LCL) SLS_MANUAL_MKUP_AMT_LCL,
								 SUM(S.RET_QTY) RET_QTY,
								 SUM(S.RET_AMT_LCL) RET_AMT_LCL,
								 SUM(S.RET_PROFIT_AMT_LCL) RET_PROFIT_AMT_LCL,
								 SUM(S.RET_TAX_AMT_LCL) RET_TAX_AMT_LCL,
								 SUM(S.RET_EMP_DISC_AMT_LCL) RET_EMP_DISC_AMT_LCL,
								 SUM(S.RET_MANUAL_MKDN_AMT_LCL) RET_MANUAL_MKDN_AMT_LCL,
								 SUM(S.RET_MANUAL_MKUP_AMT_LCL) RET_MANUAL_MKUP_AMT_LCL,
								 SUM(S.SLS_MANUAL_COUNT) SLS_MANUAL_COUNT,
								 SUM(S.SLS_SCAN_COUNT) SLS_SCAN_COUNT,
								 SUM(S.RET_MANUAL_COUNT) RET_MANUAL_COUNT,
								 SUM(S.RET_SCAN_COUNT) RET_SCAN_COUNT,
								 C.PROD_DP_NUM || '~' || S.MN_WID || '~' || CASE
									 WHEN S.RTL_TYPE_WID = 1 THEN
										'P'
									 WHEN S.RTL_TYPE_WID = 4 THEN
										'R'
								 END || '~' || IL.BUSINESS_MODE INTEGRATION_ID,
								 NULL GLOBAL1_EXCHANGE_RATE,
								 NULL GLOBAL2_EXCHANGE_RATE,
								 NULL GLOBAL4_EXCHANGE_RATE,
								 1 LOC_EXCHANGE_RATE,
								 S.BBG_RETAIL_TYPE_WID,
								 SUM(S.BBG_CUSTOMER_COUNT) BBG_CUSTOMER_COUNT,
								 SUM(S.BBG_SERVICE_SATISFACTION) BBG_SERVICE_SATISFACTION,
								 NULL BBG_REFERENCE_DO1,
								 NULL BBG_REFERENCE_DO2,
								 NULL BBG_REFERENCE_DO3,
								 NULL BBG_REFERENCE_DO4,
								 NULL BBG_REFERENCE_DO5,
								 SUM(S.BBG_REFERENCE_FO1) BBG_REFERENCE_FO1,
								 SUM(S.BBG_REFERENCE_FO2) BBG_REFERENCE_FO2,
								 NULL BBG_REFERENCE_FO3,
								 NULL BBG_REFERENCE_FO4,
								 NULL BBG_REFERENCE_FO5,
								 NULL BBG_REFERENCE_FO6,
								 NULL BBG_REFERENCE_FO7,
								 NULL BBG_REFERENCE_FO8,
								 NULL BBG_REFERENCE_FO9,
								 NULL BBG_REFERENCE_FO10
						FROM (SELECT * FROM YJ_TOTAL_SLS_IT_LC_MN_TMP) S,
								 RADM.BBG_RA_ITEM_LOC_D IL,
								 RABATCHER.W_PRODUCT_D_RTL_TMP C
					 WHERE S.BBG_ITEM_LOC_WID = IL.ROW_WID
						 AND C.PROD_IT_WID = S.PROD_WID
						 AND S.MN_WID <= '201311'
					 GROUP BY S.MN_WID,
										S.RTL_TYPE_WID,
										IL.BUSINESS_MODE,
										S.BBG_RETAIL_TYPE_WID,
										C.PROD_DP_WID,
										C.PROD_DP_NUM) A;
COMMIT;

--*****************************************************************************************************************
--插入接口信息到RADM.C_ODI_PARAM表
SELECT MAX(ROW_WID) FROM RADM.C_ODI_PARAM;
SELECT *
	FROM RADM.C_ODI_PARAM T
 WHERE T.SCENARIO_NAME LIKE '%PLP_BBG_RETAILSALESBMITCLDPDVDYAGGREGATE%' FOR UPDATE;

--每日晚运行数据从W_RTL_SLS_IT_LC_DY_TMP导入
SELECT * FROM BBG_RA_ITEM_LOC_D;

SELECT * FROM RABATCHER.W_RTL_SLS_IT_LC_DY_TMP;

--查询语句
SELECT *
	FROM RABATCHER.W_RTL_SLS_IT_LC_DY_TMP T, BBG_RA_ITEM_LOC_D D
 WHERE T.PROD_IT_NUM = D.ITEM
	 AND T.ORG_NUM = D.LOC

--2.库存
	SELECT * FROM W_RTL_INV_IT_LC_DY_F;


select * from BBG_RA_SLS_CL_BM_MN_A t;
SELECT * FROM RABATCHER.W_RTL_SLS_IT_LC_DY_TMP;
SELECT DISTINCT T.PR_NUM FROM RABATCHER.W_RTL_SLS_IT_LC_DY_TMP T;
SELECT * FROM W_MCAL_DAY_D;
