SELECT * FROM ITEM_SUPP_COUNTRY WHERE ITEM='900001530' AND SUPPLIER='19000216';
SELECT * FROM CMX_ITEM_SUPP_COUNTRY WHERE ITEM='900001530' AND SUPPLIER='19000216';

SELECT COUNT(*) FROM ITEM_SUPP_COUNTRY;
SELECT COUNT(*) FROM CMX_ITEM_SUPP_COUNTRY;

SELECT COUNT(*) FROM CMX_ITEM_LOC_INFO;
SELECT COUNT(*) FROM ITEM_LOC;
SELECT * FROM BBG_RA_ITEM_LOC_SUPP_D_V;

SELECT * FROM ITEM_LOC;--主供应商
SELECT * FROM CMX_I
SELECT * FROM ITEM_MASTER;
SELECT * FROM BARCODE_V;--主条码
SELECT * FROM DEPS;
SELECT * FROM ITEM_LOC WHERE ITEM='800215659';
SELECT * FROM CMX_ITEM_SUPP_COUNTRY_LOC;
SELECT * FROM CMX_CODE_DETAIL WHERE CODE_TYPE = 'LDMD';
SELECT * FROM ITEM_LOC;
SELECT * FROM STORE;
SELECT SUBSTR(S.DISTRICT,1,3) FROM STORE S;
SELECT * FROM STORE S WHERE SUBSTR(S.DISTRICT,1,3) in( '109');
SELECT * FROM vm_cmx_itemsupploc_status--赛龙告诉的可订货标志
SELECT * FROM BBG_RA_ITEM_LOC_SUPP_D_V--odi传过去的可订货标志



SELECT IL.LOC,IM.DEPT,IL.ITEM,IL.LOCAL_ITEM_DESC,BARCODE.barcode,IM.CREATE_DATETIME,CD.CODE_DESC,ISC.UNIT_COST,IL.UNIT_RETAIL
FROM ITEM_LOC IL,
     ITEM_MASTER IM,
     BARCODE_V BARCODE,
     CMX_ITEM_SUPP_COUNTRY_LOC ISCL,
     ITEM_SUPP_COUNTRY ISC,
     (SELECT CODE,CODE_DESC FROM CMX_CODE_DETAIL WHERE CODE_TYPE = 'LDMD') CD
WHERE IL.ITEM=IM.ITEM AND IL.ITEM=BARCODE.item 
AND ISCL.ITEM=IL.ITEM AND ISCL.LOC=IL.LOC AND ISCL.SUPPLIER=IL.PRIMARY_SUPP AND ISCL.ITEM=IM.ITEM 
AND ISC.ITEM=IL.ITEM AND ISC.SUPPLIER=IL.PRIMARY_SUPP 
AND ISCL.LOGISTICS_DELIVERY_MODEL=CD.CODE
AND IM.TRAN_LEVEL=2
AND EXISTS(SELECT 1 FROM vm_cmx_itemsupploc_status ISIL 
                   WHERE ISIL.ITEM=IL.ITEM AND ISIL.SUPPLIER=IL.PRIMARY_SUPP AND ISIL.LOC=IL.LOC AND ISIL.ORDERABLE_IND='Y')
AND EXISTS(SELECT 1 FROM STORE S WHERE S.STORE=IL.LOC AND SUBSTR(S.DISTRICT,1,3) = '109')
ORDER BY IL.LOC,IM.DEPT,IL.ITEM;



SELECT IL.LOC,IM.DEPT,IL.ITEM,IL.LOCAL_ITEM_DESC,BARCODE.barcode,IM.CREATE_DATETIME,CD.CODE_DESC,ISC.UNIT_COST,IL.UNIT_RETAIL
FROM ITEM_LOC IL,
     ITEM_MASTER IM,
     BARCODE_V BARCODE,
     CMX_ITEM_SUPP_COUNTRY_LOC ISCL,
     ITEM_SUPP_COUNTRY ISC,
     (SELECT CODE,CODE_DESC FROM CMX_CODE_DETAIL WHERE CODE_TYPE = 'LDMD') CD
WHERE IL.ITEM=IM.ITEM AND IL.ITEM=BARCODE.item 
AND ISCL.ITEM=IL.ITEM AND ISCL.LOC=IL.LOC AND ISCL.SUPPLIER=IL.PRIMARY_SUPP AND ISCL.ITEM=IM.ITEM 
AND ISC.ITEM=IL.ITEM AND ISC.SUPPLIER=IL.PRIMARY_SUPP 
AND ISCL.LOGISTICS_DELIVERY_MODEL=CD.CODE
AND IM.TRAN_LEVEL=2
AND EXISTS(SELECT 1 FROM vm_cmx_itemsupploc_status ISIL 
                   WHERE ISIL.ITEM=IL.ITEM AND ISIL.SUPPLIER=IL.PRIMARY_SUPP AND ISIL.LOC=IL.LOC AND ISIL.ORDERABLE_IND='Y')
AND IL.LOC='120127'
ORDER BY IL.LOC,IM.DEPT,IL.ITEM;
