SELECT * FROM ALL_ALL_TABLES WHERE TABLE_NAME LIKE '%SUPP%INV%'

SELECT * FROM BBG_RA_ITEM_LOC_D WHERE ITEM=800022240 AND LOC=120055;
SELECT * FROM BBG_RA_ITEM_LOC_SUPP_D WHERE ITEM=800022240 AND LOC=120055;
SELECT * FROM W_PRODUCT_D;

SELECT
   0 s_0,
   "Retail As-Was"."BBG Item Loc Supp"."Desc Chinese" s_1,
   "Retail As-Was"."Item As Was"."Item" s_2,
   "Retail As-Was"."Organization As Was"."Loc" s_3
FROM "Retail As-Was"
WHERE
(("Item As Was"."Item" = '800022240-金爱丽120g加州牛排') AND ("Organization As Was"."Loc" = '120055-贺嘉土店'))
ORDER BY 1, 3 ASC NULLS LAST, 4 ASC NULLS LAST, 2 ASC NULLS LAST
FETCH FIRST 10000000 ROWS ONLY

--物流模式
SELECT * FROM BBG_RA_ITEM_LOC_SUPP_D WHERE ITEM=100056677 AND LOC=120055;

SELECT * FROM RABATCHER. 

Fact_W_RTL_INV_SC_MN_CUR_A

SELECT * FROM W_RTL_INV_SC_MN_CUR_A;
SELECT * FROM W_RTL_INV_IT_LC_DY_F T WHERE T.ORG_WID=57 AND T.PROD_WID='781355' ;
SELECT * FROM W_INT_ORG_D T WHERE T.ORG_NUM='120055';
SELECT * FROM W_PRODUCT_D T WHERE T.PROD_NUM = '100056677'; 

SELECT * FROM BBG_RA_SUPP_INV_SC_MN_CUR_A;
SELECT * FROM BBG_RA_SUPP_INV_IT_LC_DY_F T WHERE T.PROD_WID='781355' AND T.ORG_WID=57
