--删除2013-10-10之前的数据
DELETE BBG_RA_CUST_LC_DY_A T WHERE T.DT_WID < '120131010000';

--BBG_XTERN_RDWT_HIST取历史数据
INSERT INTO RA_RMS.BBG_XTERN_RDWT
  SELECT *
    FROM RA_RMS.BBG_XTERN_RDWT_HIST
   WHERE BUSINESS_DT BETWEEN '20131001' AND '20131009';

--清除日志
TRUNCATE TABLE RA_RMS.C_LOAD_DATES;

--来客数建立物化视图
CREATE MATERIALIZED VIEW RADM.BBG_RA_CUST_LC_DY_HIST_FV AS
  SELECT '1' || BUSINESS_DT || '000' DT_WID,
         SUBSTR(LOCATION, 5, 6) ORG_NUM,
         COUNT(TRANSACTION_HEADER_NO) BBG_CUSTOMER_COUNT
    FROM (SELECT T.BUSINESS_DT,
                 T.LOCATION,
                 T.TRANSACTION_HEADER_NO,
                 MAX(T.REASON_CD)
            FROM RA_RMS.BBG_XTERN_RDWT_HIST@RA_RMS_DBLINK T
           WHERE T.BUSINESS_DT BETWEEN '20130508' AND '20131009'
           GROUP BY T.BUSINESS_DT, T.LOCATION, T.TRANSACTION_HEADER_NO)
   GROUP BY BUSINESS_DT, LOCATION
   ORDER BY '1' || BUSINESS_DT || '000', SUBSTR(LOCATION, 5, 6);

DROP MATERIALIZED VIEW RADM.BBG_RA_CUST_LC_DY_HIST_FV;

--直接插入BBG_RA_CUST_LC_DY_A(2013年5月8日~~2013年10月9日)
INSERT INTO RADM.BBG_RA_CUST_LC_DY_A
  (ROW_WID,
   ORG_WID,
   ORG_DH_WID,
   ORG_SCD1_WID,
   DT_WID,
   DATASOURCE_NUM_ID,
   INTEGRATION_ID,
   W_INSERT_DT,
   W_UPDATE_DT,
   BBG_CUSTOMER_COUNT)
  SELECT BBG_RA_CUST_LC_DY_A_SEQ.NEXTVAL,
         D.ORG_WID,
         DH.ORG_LC_WID,
         DH.ORG_SCD1_WID,
         HIST.DT_WID,
         1,
         HIST.ORG_NUM || '~' ||
         TO_CHAR(W_MCAL_DAY_D.MCAL_DAY_DT,
                 'DD-MON-YY',
                 'NLS_DATE_LANGUAGE = American') INTEGRATION_ID,
         SYSDATE,
         SYSDATE,
         HIST.BBG_CUSTOMER_COUNT
    FROM RADM.BBG_RA_CUST_LC_DY_HIST_FV HIST,
         RABATCHER.W_INT_ORG_D_RTL_TMP  D,
         RABATCHER.W_INT_ORG_DH_RTL_TMP DH,
         RADM.W_MCAL_DAY_D
   WHERE HIST.ORG_NUM = D.ORG_NUM
     AND HIST.ORG_NUM = DH.ORG_NUM
     AND HIST.DT_WID = W_MCAL_DAY_D.ROW_WID;

--************************************************************************************************************************
--2013年5月8日之前的来客数统计
--创建物化视图(表名和之前的不变)
--DT_WID,ORG_NUM,BBG_CUSTOMER_COUNT
--SALEDETAIL小票号通过SD0106和SD0109
CREATE MATERIALIZED VIEW RADM.BBG_RA_CUST_LC_DY_HIST_FV AS
  SELECT DT_WID, ORG_NUM, COUNT(BBG_TRX_ID) BBG_CUSTOMER_COUNT
    FROM (SELECT DISTINCT '1' || SD.SD0101 || '000' DT_WID,
                          SUBSTR(SD.SHOPID, 2, 2) || SUBSTR(SD.SHOPID, 1, 1) ||
                          SUBSTR(SD.SHOPID, 4, 3) ORG_NUM,
                          SD.SD0109 || SD.SD0106 BBG_TRX_ID
            FROM RADM.SALEDETAIL SD
           WHERE SD.SD0101 BETWEEN '20120101' AND '20130507')
   GROUP BY DT_WID, ORG_NUM
   ORDER BY DT_WID, ORG_NUM;

--按记帐日期取值----------------------------------------------------------------------------------------------------------
DROP MATERIALIZED VIEW RADM.BBG_RA_CUST_LC_DY_HIST_FV;
CREATE MATERIALIZED VIEW RADM.BBG_RA_CUST_LC_DY_HIST_FV AS
  SELECT DT_WID, ORG_NUM, COUNT(BBG_TRX_ID) BBG_CUSTOMER_COUNT
    FROM (SELECT DISTINCT '1' || TO_CHAR(SC.SDATE,'YYYYMMDD') || '000' DT_WID,
                          SUBSTR(SD.SHOPID, 2, 2) || SUBSTR(SD.SHOPID, 1, 1) ||
                          SUBSTR(SD.SHOPID, 4, 3) ORG_NUM,
                          SD.SD0109 || SD.SD0106 BBG_TRX_ID
            FROM RADM.SALEDETAIL SD, RADM.SALECOST SC
           WHERE SD.SHEETID = SC.SHEETID
             AND SC.SDATE BETWEEN DATE'2012-01-01' AND DATE'2013-05-07')
   GROUP BY DT_WID, ORG_NUM
   ORDER BY DT_WID, ORG_NUM;
----------------------------------------------------------------------
--删除BBG_RA_CUST_LC_DY_A的2012-01-01~~2013-05-07
DELETE RADM.BBG_RA_CUST_LC_DY_A T WHERE T.DT_WID BETWEEN '120120101000' AND '120130507000';
--直接插入BBG_RA_CUST_LC_DY_A(2012年6月1日~~2013年5月7日)
INSERT INTO RADM.BBG_RA_CUST_LC_DY_A
  (ROW_WID,
   ORG_WID,
   ORG_DH_WID,
   ORG_SCD1_WID,
   DT_WID,
   DATASOURCE_NUM_ID,
   INTEGRATION_ID,
   W_INSERT_DT,
   W_UPDATE_DT,
   BBG_CUSTOMER_COUNT)
  SELECT BBG_RA_CUST_LC_DY_A_SEQ.NEXTVAL,
         D.ORG_WID,
         DH.ORG_LC_WID,
         DH.ORG_SCD1_WID,
         HIST.DT_WID,
         1,
         HIST.ORG_NUM || '~' ||
         TO_CHAR(W_MCAL_DAY_D.MCAL_DAY_DT,
                 'DD-MON-YY',
                 'NLS_DATE_LANGUAGE = American') INTEGRATION_ID,
         SYSDATE,
         SYSDATE,
         HIST.BBG_CUSTOMER_COUNT
    FROM RADM.BBG_RA_CUST_LC_DY_HIST_FV HIST,
         RABATCHER.W_INT_ORG_D_RTL_TMP  D,
         RABATCHER.W_INT_ORG_DH_RTL_TMP DH,
         RADM.W_MCAL_DAY_D
   WHERE HIST.ORG_NUM = D.ORG_NUM
     AND HIST.ORG_NUM = DH.ORG_NUM
     AND HIST.DT_WID = W_MCAL_DAY_D.ROW_WID
		 --130024修改过维度,需要剔出
		 AND DH.ORG_LC_WID<>'140008';

SELECT * FROM RADM.SALEDETAIL;

SELECT /*BBG_RA_CUST_LC_DY_A_SEQ.NEXTVAL,*/
 D.ORG_WID,
 DH.ORG_CH_WID,
 DH.ORG_SCD1_WID,
 HIST.DT_WID,
 1,
 HIST.ORG_NUM || '~' ||
 TO_CHAR(W_MCAL_DAY_D.MCAL_DAY_DT,
         'DD-MON-YY',
         'NLS_DATE_LANGUAGE = American') INTEGRATION_ID,
 SYSDATE,
 SYSDATE,
 HIST.BBG_CUSTOMER_COUNT
  FROM RADM.BBG_RA_CUST_LC_DY_HIST_FV HIST,
       RABATCHER.W_INT_ORG_D_RTL_TMP  D,
       RABATCHER.W_INT_ORG_DH_RTL_TMP DH,
       RADM.W_MCAL_DAY_D
 WHERE HIST.ORG_NUM = D.ORG_NUM
   AND HIST.ORG_NUM = DH.ORG_NUM
   AND HIST.DT_WID = W_MCAL_DAY_D.ROW_WID;
