--RMS
CREATE TABLE RMSHIST.W_RTL_SLS_TRX_IT_LC_DY_FS_0507 AS
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_0507@RMS_RA;

CREATE TABLE RMSHIST.W_RTL_SLS_TRX_IT_LC_DY_FS_0901 AS
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_0901@RMS_RA;

CREATE TABLE RMSHIST.W_RTL_SLS_TRX_IT_LC_DY_FS_0904 AS
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_0904@RMS_RA;

CREATE TABLE RMSHIST.W_RTL_SLS_TRX_IT_LC_DY_FS_0908 AS
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_0908@RMS_RA;

CREATE TABLE RMSHIST.W_RTL_SLS_TRX_IT_LC_DY_FS_0910 AS
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_0910@RMS_RA;

CREATE TABLE RMSHIST.W_RTL_SLS_TRX_IT_LC_DY_FS_0912 AS
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_0912@RMS_RA;

CREATE TABLE RMSHIST.W_RTL_SLS_TRX_IT_LC_DY_FS_0914 AS
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_0914@RMS_RA;

CREATE TABLE RMSHIST.W_RTL_SLS_TRX_IT_LC_DY_FS_0930 AS
SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_0930@RMS_RA;

SELECT * FROM RMSHIST.W_RTL_SLS_TRX_IT_LC_DY_FS_0930;

--RADM
DROP TABLE W_RTL_SLS_TRX_IT_LC_DY_FS_0507;
DROP TABLE W_RTL_SLS_TRX_IT_LC_DY_FS_0901;
DROP TABLE W_RTL_SLS_TRX_IT_LC_DY_FS_0904;
DROP TABLE W_RTL_SLS_TRX_IT_LC_DY_FS_0908;
DROP TABLE W_RTL_SLS_TRX_IT_LC_DY_FS_0910;
DROP TABLE W_RTL_SLS_TRX_IT_LC_DY_FS_0912;
DROP TABLE W_RTL_SLS_TRX_IT_LC_DY_FS_0914;
DROP TABLE W_RTL_SLS_TRX_IT_LC_DY_FS_0930;
