--销售物化视图
CREATE MATERIALIZED VIEW RADM.YJ_SLS_IT_LC_MN_V
AS
  SELECT
    T.ORG_WID,
    T.PROD_WID,
    SUM((T.SLS_AMT_LCL - T.RET_AMT_LCL) - (T.SLS_TAX_AMT_LCL - T.RET_TAX_AMT_LCL)) SLS_AMT
  FROM W_RTL_SLS_IT_LC_DY_A T
  WHERE T.DT_WID BETWEEN '120130901000' AND '120130930000'
  GROUP BY T.ORG_WID, T.PROD_WID;
--库存物化视图
CREATE MATERIALIZED VIEW RADM.YJ_SOH_COST_AVG_V
AS
  SELECT
    T.ORG_WID,
    T.PROD_WID,
    SUM(T.INV_SOH_QTY)          INV_SOH_QTY,
    SUM(T.INV_SOH_COST_AMT_LCL) INV_SOH_COST
  FROM W_RTL_INV_IT_LC_DY_FV T
  WHERE T.DT_WID IN ('120130831000', '120130930000')
  GROUP BY T.ORG_WID, T.PROD_WID;

DROP MATERIALIZED VIEW RADM.YJ_SOH_COST_AVG_V;
--*********
--门店商品周转天数
CREATE MATERIALIZED VIEW yj_zhouzhuang
AS
  SELECT
    ORG.ORG_NUM,
    ORG_NAME.ORG_NAME,
    DH.LVL4ANC_PRODCAT_ID,
    D2.C1,
    PROD_NUM.PROD_NUM,
    PROD_NAME.PRODUCT_NAME,
    NOWINV.INV_SOH_QTY,
    NOWINV.INV_SOH_COST_AMT_LCL,
    DECODE(SLS.SLS_AMT, 0, 99999, (INV.INV_SOH_COST / 2) / (SLS.SLS_AMT / 30))
  FROM
    --INV
    YJ_SOH_COST_AVG_V INV,
    W_RTL_INV_IT_LC_DY_FV NOWINV,
    --SLS
    YJ_SLS_IT_LC_MN_V SLS,
    W_INT_ORG_D ORG,
    W_PROD_CAT_DH DH INNER JOIN (SELECT
                                   T16687.DOMAIN_MEMBER_NAME AS c1,
                                   T16687.DOMAIN_MEMBER_CODE AS c2,
                                   T16687.DATASOURCE_NUM_ID  AS c3
                                 FROM
                                   W_DOMAIN_MEMBER_LKP_TL T16687 /* Lookup_W_DOMAIN_MEMBER_LKP_TL */
                                 WHERE (T16687.DOMAIN_CODE = 'MCAT' AND T16687.DOMAIN_TYPE_CODE = 'S' AND
                                        T16687.LANGUAGE_CODE = 'ZHS')
                                ) D2 ON concat(concat(concat(concat(concat(concat('SBC', '~'), DH.LVL6ANC_PRODCAT_ID),
                                                                    '~'), DH.LVL5ANC_PRODCAT_ID), '~'),
                                               DH.LVL4ANC_PRODCAT_ID) = D2.c2 AND DH.DATASOURCE_NUM_ID = D2.c3
    ,
    --W_INT_ORG_DH ORGDH,

    --商品编码
    (SELECT T.*
     FROM W_PRODUCT_D T,
       W_PRODUCT_ATTR_D A
     WHERE T.SCD1_WID = A.SCD1_WID
           AND A.PRODUCT_ATTR12_NAME = A.PRODUCT_ATTR11_NAME) PROD_NUM,
    --商品名称
    (SELECT
       DATASOURCE_NUM_ID,
       INTEGRATION_ID,
       PRODUCT_NAME
     FROM W_PRODUCT_D_TL
     WHERE LANGUAGE_CODE = 'ZHS') PROD_NAME,
    --网点名称
    (SELECT
       DATASOURCE_NUM_ID,
       INTEGRATION_ID,
       ORG_DESCR,
       ORG_NAME,
       LANGUAGE_CODE
     FROM W_INT_ORG_D_TL
     WHERE LANGUAGE_CODE = 'ZHS') ORG_NAME
  WHERE INV.PROD_WID = PROD_NUM.ROW_WID
        AND INV.ORG_WID = ORG.ROW_WID
        AND NOWINV.PROD_WID = PROD_NUM.ROW_WID
        AND NOWINV.ORG_WID = ORG.ROW_WID
        AND NOWINV.DT_WID = '120130930000'
        AND SLS.PROD_WID = PROD_NUM.ROW_WID
        AND SLS.ORG_WID = ORG.ROW_WID
        AND PROD_NUM.DATASOURCE_NUM_ID = PROD_NAME.DATASOURCE_NUM_ID
        AND PROD_NUM.INTEGRATION_ID = PROD_NAME.INTEGRATION_ID
        AND ORG_NAME.INTEGRATION_ID = ORG.INTEGRATION_ID
        AND ORG_NAME.DATASOURCE_NUM_ID = ORG.DATASOURCE_NUM_ID
        AND PROD_NUM.PROD_CAT5_WID_AS_WAS = DH.ROW_WID
--ORDER BY ORG.ORG_NUM,DH.LVL4ANC_PRODCAT_ID,PROD_NUM.PROD_NUM


--GROUP BY DH.LVL5ANC_PRODCAT_ID,D2.C1,PROD_NUM.PROD_NUM,PROD_NAME.PRODUCT_NAME,ORG.ORG_NUM,ORG_NAME.ORG_NAME
;

--------------------------------------------------------------------------------------------------------------	
--有库存无销售(9.1有库存,9.1-9.31无销售)
SELECT
  ORG.ORG_NUM,
  ORG_NAME.ORG_NAME,
  DH.LVL4ANC_PRODCAT_ID,
  D2.C1,
  PROD_NUM.PROD_NUM,
  PROD_NAME.PRODUCT_NAME,
  NOWINV.INV_SOH_QTY,
  NOWINV.INV_SOH_COST_AMT_LCL
FROM
  --INV
  YJ_SOH_COST_AVG_V INV,
  W_RTL_INV_IT_LC_DY_FV NOWINV,
  --SLS
  YJ_SLS_IT_LC_MN_V SLS,
  W_INT_ORG_D ORG,
  W_PROD_CAT_DH DH INNER JOIN (SELECT
                                 T16687.DOMAIN_MEMBER_NAME AS c1,
                                 T16687.DOMAIN_MEMBER_CODE AS c2,
                                 T16687.DATASOURCE_NUM_ID  AS c3
                               FROM
                                 W_DOMAIN_MEMBER_LKP_TL T16687 /* Lookup_W_DOMAIN_MEMBER_LKP_TL */
                               WHERE (T16687.DOMAIN_CODE = 'MCAT' AND T16687.DOMAIN_TYPE_CODE = 'S' AND
                                      T16687.LANGUAGE_CODE = 'ZHS')
                              ) D2 ON concat(concat(
                                                 concat(concat(concat(concat('SBC', '~'), DH.LVL6ANC_PRODCAT_ID), '~'),
                                                        DH.LVL5ANC_PRODCAT_ID), '~'), DH.LVL4ANC_PRODCAT_ID) = D2.c2 AND
                                      DH.DATASOURCE_NUM_ID = D2.c3
  ,
  --W_INT_ORG_DH ORGDH,

  --商品编码
  (SELECT T.*
   FROM W_PRODUCT_D T,
     W_PRODUCT_ATTR_D A
   WHERE T.SCD1_WID = A.SCD1_WID
         AND A.PRODUCT_ATTR12_NAME = A.PRODUCT_ATTR11_NAME) PROD_NUM,
  --商品名称
  (SELECT
     DATASOURCE_NUM_ID,
     INTEGRATION_ID,
     PRODUCT_NAME
   FROM W_PRODUCT_D_TL
   WHERE LANGUAGE_CODE = 'ZHS') PROD_NAME,
  --网点名称
  (SELECT
     DATASOURCE_NUM_ID,
     INTEGRATION_ID,
     ORG_DESCR,
     ORG_NAME,
     LANGUAGE_CODE
   FROM W_INT_ORG_D_TL
   WHERE LANGUAGE_CODE = 'ZHS') ORG_NAME
WHERE INV.PROD_WID = PROD_NUM.ROW_WID
      AND INV.ORG_WID = ORG.ROW_WID
      AND NOWINV.PROD_WID = PROD_NUM.ROW_WID
      AND NOWINV.ORG_WID = ORG.ROW_WID
      AND NOWINV.DT_WID = '120130901000'
      AND NOWINV.INV_SOH_QTY > 0--有库存
      AND SLS.PROD_WID = PROD_NUM.ROW_WID
      AND SLS.ORG_WID = ORG.ROW_WID
      AND SLS.SLS_AMT = 0--无销售
      AND PROD_NUM.DATASOURCE_NUM_ID = PROD_NAME.DATASOURCE_NUM_ID
      AND PROD_NUM.INTEGRATION_ID = PROD_NAME.INTEGRATION_ID
      AND ORG_NAME.INTEGRATION_ID = ORG.INTEGRATION_ID
      AND ORG_NAME.DATASOURCE_NUM_ID = ORG.DATASOURCE_NUM_ID
      AND PROD_NUM.PROD_CAT5_WID_AS_WAS = DH.ROW_WID
--ORDER BY ORG.ORG_NUM,DH.LVL4ANC_PRODCAT_ID,PROD_NUM.PROD_NUM


--GROUP BY DH.LVL5ANC_PRODCAT_ID,D2.C1,PROD_NUM.PROD_NUM,PROD_NAME.PRODUCT_NAME,ORG.ORG_NUM,ORG_NAME.ORG_NAME
;
--------------------------------------------------------------------------------------------------------------
--9.1~9.15无库存,8月份有销售
--库存物化视图
CREATE MATERIALIZED VIEW RADM.YJ_SOH_COST_AVG_V1
AS
  SELECT
    T.ORG_WID,
    T.PROD_WID,
    SUM(T.INV_SOH_QTY)          INV_SOH_QTY,
    SUM(T.INV_SOH_COST_AMT_LCL) INV_SOH_COST
  FROM W_RTL_INV_IT_LC_DY_FV T
  WHERE T.DT_WID BETWEEN '120130901000' AND '120130915000'
  GROUP BY T.ORG_WID, T.PROD_WID;

--销售物化视图
CREATE MATERIALIZED VIEW RADM.YJ_SLS_IT_LC_MN_V1
AS
  SELECT
    T.ORG_WID,
    T.PROD_WID,
    SUM(T.SLS_QTY - T.RET_QTY)                                                     SLS_QTY,
    SUM((T.SLS_AMT_LCL - T.RET_AMT_LCL) - (T.SLS_TAX_AMT_LCL - T.RET_TAX_AMT_LCL)) SLS_AMT
  FROM W_RTL_SLS_IT_LC_DY_A T
  WHERE T.DT_WID BETWEEN '120130801000' AND '120130831000'
  GROUP BY T.ORG_WID, T.PROD_WID;
--*********
SELECT
  ORG.ORG_NUM,
  ORG_NAME.ORG_NAME,
  DH.LVL4ANC_PRODCAT_ID,
  D2.C1,
  PROD_NUM.PROD_NUM,
  PROD_NAME.PRODUCT_NAME,
  SLS.SLS_QTY,
  SLS.SLS_AMT
FROM
  --INV
  YJ_SOH_COST_AVG_V1 INV,
  --W_RTL_INV_IT_LC_DY_FV NOWINV,
  --SLS
  YJ_SLS_IT_LC_MN_V1 SLS,
  W_INT_ORG_D ORG,
  W_PROD_CAT_DH DH INNER JOIN (SELECT
                                 T16687.DOMAIN_MEMBER_NAME AS c1,
                                 T16687.DOMAIN_MEMBER_CODE AS c2,
                                 T16687.DATASOURCE_NUM_ID  AS c3
                               FROM
                                 W_DOMAIN_MEMBER_LKP_TL T16687 /* Lookup_W_DOMAIN_MEMBER_LKP_TL */
                               WHERE (T16687.DOMAIN_CODE = 'MCAT' AND T16687.DOMAIN_TYPE_CODE = 'S' AND
                                      T16687.LANGUAGE_CODE = 'ZHS')
                              ) D2 ON concat(concat(
                                                 concat(concat(concat(concat('SBC', '~'), DH.LVL6ANC_PRODCAT_ID), '~'),
                                                        DH.LVL5ANC_PRODCAT_ID), '~'), DH.LVL4ANC_PRODCAT_ID) = D2.c2 AND
                                      DH.DATASOURCE_NUM_ID = D2.c3
  ,
  --W_INT_ORG_DH ORGDH,

  --商品编码
  (SELECT T.*
   FROM W_PRODUCT_D T,
     W_PRODUCT_ATTR_D A
   WHERE T.SCD1_WID = A.SCD1_WID
         AND A.PRODUCT_ATTR12_NAME = A.PRODUCT_ATTR11_NAME) PROD_NUM,
  --商品名称
  (SELECT
     DATASOURCE_NUM_ID,
     INTEGRATION_ID,
     PRODUCT_NAME
   FROM W_PRODUCT_D_TL
   WHERE LANGUAGE_CODE = 'ZHS') PROD_NAME,
  --网点名称
  (SELECT
     DATASOURCE_NUM_ID,
     INTEGRATION_ID,
     ORG_DESCR,
     ORG_NAME,
     LANGUAGE_CODE
   FROM W_INT_ORG_D_TL
   WHERE LANGUAGE_CODE = 'ZHS') ORG_NAME
WHERE INV.PROD_WID = PROD_NUM.ROW_WID
      AND INV.ORG_WID = ORG.ROW_WID
      /*AND NOWINV.PROD_WID=PROD_NUM.ROW_WID
      AND NOWINV.ORG_WID=ORG.ROW_WID
      AND NOWINV.DT_WID='120130901000'*/
      AND INV.INV_SOH_QTY = 0--无库存
      AND SLS.PROD_WID = PROD_NUM.ROW_WID
      AND SLS.ORG_WID = ORG.ROW_WID
      AND SLS.SLS_AMT > 0--有销售
      AND PROD_NUM.DATASOURCE_NUM_ID = PROD_NAME.DATASOURCE_NUM_ID
      AND PROD_NUM.INTEGRATION_ID = PROD_NAME.INTEGRATION_ID
      AND ORG_NAME.INTEGRATION_ID = ORG.INTEGRATION_ID
      AND ORG_NAME.DATASOURCE_NUM_ID = ORG.DATASOURCE_NUM_ID
      AND PROD_NUM.PROD_CAT5_WID_AS_WAS = DH.ROW_WID
--ORDER BY ORG.ORG_NUM,DH.LVL4ANC_PRODCAT_ID,PROD_NUM.PROD_NUM


--GROUP BY DH.LVL5ANC_PRODCAT_ID,D2.C1,PROD_NUM.PROD_NUM,PROD_NAME.PRODUCT_NAME,ORG.ORG_NUM,ORG_NAME.ORG_NAME
;
-------------------------------------------------------------------------------------------------------
SELECT
  sls_amt,
  DECODE(SLS_AMT, 0, 'zero', sls_amt)
FROM YJ_SLS_IT_LC_MN_V;
SELECT *
FROM W_PROD_CAT_DH;
SELECT *
FROM W_RTL_SLS_IT_LC_DY_A;
SELECT
  T.ORG_WID,
  T.PROD_WID,
  T.DT_WID,
  T.INV_SOH_QTY,
  T.INV_SOH_COST_AMT_LCL
FROM W_RTL_INV_IT_LC_DY_FV T
WHERE T.DT_WID IN ('120130831000', '120130930000');
--商品编码
SELECT *
FROM W_PRODUCT_D_TL;
SELECT *
FROM W_PRODUCT_D;
SELECT *
FROM W_PRODUCT_ATTR_D;
(SELECT T.*
 FROM W_PRODUCT_D T,
   W_PRODUCT_ATTR_D A
 WHERE T.SCD1_WID =
       A.SCD1_WID
       AND A.PRODUCT_ATTR12_NAME =
           A.PRODUCT_ATTR11_NAME)
--商品名称																																			 
SELECT
  DATASOURCE_NUM_ID,
  INTEGRATION_ID,
  PRODUCT_DESCR,
  PRODUCT_NAME,
  LANGUAGE_CODE
FROM W_PRODUCT_D_TL
WHERE LANGUAGE_CODE = 'ZHS'
--网点名称
SELECT
  DATASOURCE_NUM_ID,
  INTEGRATION_ID,
  ORG_DESCR,
  ORG_NAME,
  LANGUAGE_CODE
FROM W_INT_ORG_D_TL
WHERE LANGUAGE_CODE = 'ZHS'
