/*杨进，上次提到的从RA系统中统计item_loc在10月31号数据的工作还请你做一下。
结构如下：
商品编码、父商品编码、地点、地点类型、状态、主供应商编码、系统当前日期、创建日期。在RA重取这个数据后可放到RMS系统中的BBG_ITEM_LOC_LASTMONTH表里。*/


--取数据
CREATE TABLE RMS.BBG_ITEM_LOC_LASTMONTH
AS
SELECT S.ITEM,S.ITEM_PARENT,S.LOC,S.LOC_TYPE,T.REF_NO1, S.PRIMARY_SUPP,DATE'2013-10-31' CREATE_DATETIME,DATE'2013-10-31' CURRENT_DATETIME
FROM RADM.BBG_RA_ITEM_LOC_D@RMS_RA T,
     RA_RMS.ITEM_LOC_SOH_20131031 S
WHERE T.ITEM=S.ITEM 
  AND T.LOC=S.LOC
	AND T.EFFECTIVE_FROM_DT<=DATE'2013-10-31' 
	AND T.EFFECTIVE_TO_DT>=DATE'2013-10-31';

--验证是否有重复
SELECT * FROM RMS.BBG_ITEM_LOC_LASTMONTH;
SELECT COUNT(*) FROM RMS.BBG_ITEM_LOC_LASTMONTH;
SELECT ITEM,LOC,PRIMARY_SUPP,COUNT(*) FROM RMS.BBG_ITEM_LOC_LASTMONTH GROUP BY ITEM,LOC,PRIMARY_SUPP HAVING COUNT(*)>1;
SELECT COUNT(*) FROM RA_RMS.ITEM_LOC_SOH_20131031;

--目标表
SELECT * FROM RMS.BBG_ITEM_LOC_LASTMONTH@RA_RMS_DBLINK;

--TMP
SELECT * FROM BBG_RA_ITEM_LOC_D;
SELECT DISTINCT REF_NO1 FROM BBG_RA_ITEM_LOC_D;
SELECT * FROM BBG_RA_ITEM_LOC_D T WHERE T.EFFECTIVE_FROM_DT<=DATE'2013-10-31' AND T.EFFECTIVE_TO_DT>=DATE'2013-10-31';
SELECT * FROM BBG_RA_ITEM_LOC_D T WHERE T.ITEM='900381078' AND T.LOC='120162';
SELECT T.* FROM BBG_RA_ITEM_LOC_SUPP_D T ;
SELECT * FROM BBG_RA_ITEM_LOC_SUPP_D_V@RA_RMS_DBLINK;
SELECT * FROM BBG_RA_ITEM_LOC_D_V@RA_RMS_DBLINK;
SELECT * FROM ITEM_LOC@RA_RMS_DBLINK;
SELECT * FROM CMX_ITEM_LOC_INFO@RA_RMS_DBLINK;
SELECT DISTINCT T.STATUS FROM ITEM_LOC@RA_RMS_DBLINK T;
SELECT DISTINCT T.REF_NO1 FROM CMX_ITEM_LOC_INFO@RA_RMS_DBLINK T;
SELECT * FROM BBG_RA_ITEM_LOC_D T;
SELECT * FROM RA_RMS.ITEM_LOC_SOH_20131031@RA_RMS_DBLINK S;
