--销售交易流水
SELECT * FROM W_RTL_SLS_TRX_IT_LC_DY_FS;
--从销售取的视图
SELECT * FROM BBG_RA_CUST_IT_LC_DY_FV;
select * from rabatcher.w_product_d_rtl_tmp;
BBG_RA_CUST_SC_LC_DY_FV
SELECT * FROM BBG_RA_CUST_IT_LC_DY_F;
SELECT * FROM BBG_RA_CUST_SC_LC_DY_A;
SELECT * FROM BBG_RA_CUST_CL_LC_DY_A;
SELECT * FROM BBG_RA_CUST_DP_LC_DY_A;
SELECT * FROM BBG_RA_CUST_GP_LC_DY_A;
SELECT * FROM BBG_RA_CUST_DV_LC_DY_A;
SELECT * FROM W_PROD_CAT_DH;

SELECT ROW_WID ITEM,ORG_WID ORG_NUM,BBG_CUSTOMER_COUNT,BBG_SERVICE_SATISFACTION  FROM BBG_RA_CUST_IT_LC_DY_F;


SELECT T.SLS_TRX_ID,T.PROD_IT_NUM
FROM W_RTL_SLS_TRX_IT_LC_DY_FS T
WHERE DAY_DT = DATE'2013-07-18'
GROUP BY T.SLS_TRX_ID,T.PROD_IT_NUM
HAVING COUNT(*)>1;

--一张小票中如果一个商品有多条记录，只算一个来客数。
--BBG_RA_CUST_IT_LC_DY_FV-->BBG_RA_CUST_IT_LC_DY_FS
SELECT  SLS_TRX_ID FROM W_RTL_SLS_TRX_IT_LC_DY_FS T
WHERE T.PROD_IT_NUM = 800217596 AND ORG_NUM = 120020;

SELECT * FROM BBG_RA_CUST_IT_LC_DY_FV T
WHERE T.DAY_DT = DATE'2013-07-18' AND ORG_NUM = 120020
AND T.PROD_IT_NUM=800217596

--BBG_RA_CUST_IT_LC_DY_FS-->BBG_RA_CUST_IT_LC_DY_TMP
SELECT * FROM BBG_RA_CUST_IT_LC_DY_FS;
SELECT * FROM RABATCHER.BBG_RA_CUST_IT_LC_DY_TMP;
SELECT * FROM RADM.W_PRODUCT_D;
SELECT * FROM RADM.W_INT_ORG_D;

SELECT DISTINCT DAY_DT FROM BBG_RA_CUST_IT_LC_DY_FS;
SELECT DISTINCT DAY_DT FROM RABATCHER.BBG_RA_CUST_IT_LC_DY_TMP;

SELECT * 
FROM RADM.BBG_RA_CUST_IT_LC_DY_FS FS,RABATCHER.BBG_RA_CUST_IT_LC_DY_TMP TMP,RADM.W_PRODUCT_D PRO,RADM.W_INT_ORG_D ORG
WHERE FS.ORG_NUM=ORG.ORG_NUM AND FS.PROD_IT_NUM=PRO.PROD_NUM AND TMP.ORG_WID=ORG.ROW_WID AND TMP.PROD_IT_WID=PRO.ROW_WID
AND FS.DAY_DT = TMP.DAY_DT AND FS.DAY_DT = DATE'2013-07-23'
AND (FS.BBG_CUSTOMER_COUNT<>TMP.BBG_CUSTOMER_COUNT OR ROUND(FS.BBG_SERVICE_SATISFACTION,4)<>ROUND(TMP.BBG_SERVICE_SATISFACTION,4));


------小票数历史数据重导
SELECT * FROM BBG_RA_CUST_IT_LC_DY_F;
SELECT * FROM BBG_RA_CUST_SC_LC_DY_A;
SELECT * FROM BBG_RA_CUST_CL_LC_DY_A;
SELECT * FROM BBG_RA_CUST_DP_LC_DY_A;
SELECT * FROM BBG_RA_CUST_GP_LC_DY_A;
SELECT * FROM BBG_RA_CUST_DV_LC_DY_A;

SELECT DISTINCT DT_WID FROM BBG_RA_CUST_IT_LC_DY_F;
SELECT DISTINCT DT_WID FROM BBG_RA_CUST_SC_LC_DY_A;
SELECT DISTINCT DT_WID FROM BBG_RA_CUST_CL_LC_DY_A;
SELECT DISTINCT DT_WID FROM BBG_RA_CUST_DP_LC_DY_A;
SELECT DISTINCT DT_WID FROM BBG_RA_CUST_GP_LC_DY_A;
SELECT DISTINCT DT_WID FROM BBG_RA_CUST_DV_LC_DY_A;

DELETE BBG_RA_CUST_IT_LC_DY_F WHERE DT_WID<'120130723000'; 
DELETE BBG_RA_CUST_SC_LC_DY_A WHERE DT_WID<'120130723000';
DELETE BBG_RA_CUST_CL_LC_DY_A WHERE DT_WID<'120130723000';
DELETE BBG_RA_CUST_DP_LC_DY_A WHERE DT_WID<'120130723000';
DELETE BBG_RA_CUST_GP_LC_DY_A WHERE DT_WID<'120130723000';
DELETE BBG_RA_CUST_DV_LC_DY_A WHERE DT_WID<'120130723000';

SELECT DISTINCT DAY_DT FROM BBG_RA_CUST_IT_LC_DY_FV;
--*****************************************************************************************************************************************************
-------小票增加门店来客数统计表
--创建源表视图：BBG_RA_CUST_LC_DY_FV
CREATE OR REPLACE VIEW BBG_RA_CUST_LC_DY_FV AS
SELECT ORG_NUM,
       DAY_DT,
       COUNT(DISTINCT SLS_TRX_ID) BBG_CUSTOMER_COUNT,
       AVG(BBG_SERVICE_SATISFACTION) BBG_SERVICE_SATISFACTION
  FROM (SELECT ORG_NUM,
               SLS_TRX_ID,
               DAY_DT,
               AVG(BBG_SERVICE_SATISFACTION) BBG_SERVICE_SATISFACTION
          FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS T
         GROUP BY ORG_NUM, SLS_TRX_ID, DAY_DT)
 GROUP BY ORG_NUM, DAY_DT;
 
--创建目标表：BBG_RA_CUST_LC_DY_A
CREATE TABLE "RADM"."BBG_RA_CUST_LC_DY_A" 
   (  "ROW_WID" NUMBER(10,0) NOT NULL ENABLE, 
  "ORG_WID" NUMBER(10,0) NOT NULL ENABLE, 
  "ORG_DH_WID" NUMBER(10,0) NOT NULL ENABLE, 
  "ORG_SCD1_WID" NUMBER(10,0) NOT NULL ENABLE, 
  "DT_WID" NUMBER(15,0) NOT NULL ENABLE, 
  "DATASOURCE_NUM_ID" NUMBER(10,0) NOT NULL ENABLE, 
  "INTEGRATION_ID" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
  "W_INSERT_DT" DATE, 
  "W_UPDATE_DT" DATE, 
  "BBG_CUSTOMER_COUNT" NUMBER(20,4), 
  "BBG_SERVICE_SATISFACTION" NUMBER(20,4), 
  "BBG_REFERENCE_DO1" VARCHAR2(250), 
  "BBG_REFERENCE_DO2" VARCHAR2(250), 
  "BBG_REFERENCE_DO3" VARCHAR2(250), 
  "BBG_REFERENCE_DO4" VARCHAR2(250), 
  "BBG_REFERENCE_DO5" VARCHAR2(250), 
  "BBG_REFERENCE_FO1" NUMBER(20,4), 
  "BBG_REFERENCE_FO2" NUMBER(20,4), 
  "BBG_REFERENCE_FO3" NUMBER(20,4), 
  "BBG_REFERENCE_FO4" NUMBER(20,4), 
  "BBG_REFERENCE_FO5" NUMBER(20,4), 
  "BBG_REFERENCE_FO6" NUMBER(20,4), 
  "BBG_REFERENCE_FO7" NUMBER(20,4), 
  "BBG_REFERENCE_FO8" NUMBER(20,4), 
  "BBG_REFERENCE_FO9" NUMBER(20,4), 
  "BBG_REFERENCE_FO10" NUMBER(20,4), 
   CONSTRAINT "PK_BBG_RA_CUST_LC_DY_A" PRIMARY KEY ( "ORG_WID", "DT_WID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RETAIL_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RETAIL_DATA" ;
  CREATE UNIQUE INDEX "RADM"."PK_BBG_RA_CUST_LC_DY_A" ON "RADM"."BBG_RA_CUST_LC_DY_A" ( "ORG_WID", "DT_WID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RETAIL_DATA" ;
  ALTER TABLE "RADM"."BBG_RA_CUST_LC_DY_A" ADD CONSTRAINT "PK_BBG_RA_CUST_LC_DY_A" PRIMARY KEY ( "ORG_WID", "DT_WID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RETAIL_DATA"  ENABLE;
  ALTER TABLE "RADM"."BBG_RA_CUST_LC_DY_A" MODIFY ("INTEGRATION_ID" NOT NULL ENABLE);
  ALTER TABLE "RADM"."BBG_RA_CUST_LC_DY_A" MODIFY ("DATASOURCE_NUM_ID" NOT NULL ENABLE);
  ALTER TABLE "RADM"."BBG_RA_CUST_LC_DY_A" MODIFY ("DT_WID" NOT NULL ENABLE);
  ALTER TABLE "RADM"."BBG_RA_CUST_LC_DY_A" MODIFY ("ORG_SCD1_WID" NOT NULL ENABLE);
  ALTER TABLE "RADM"."BBG_RA_CUST_LC_DY_A" MODIFY ("ORG_DH_WID" NOT NULL ENABLE);
  ALTER TABLE "RADM"."BBG_RA_CUST_LC_DY_A" MODIFY ("ORG_WID" NOT NULL ENABLE);
  ALTER TABLE "RADM"."BBG_RA_CUST_LC_DY_A" MODIFY ("ROW_WID" NOT NULL ENABLE);
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_CUSTOMER_COUNT" IS '客流量';
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_SERVICE_SATISFACTION" IS '客户满意分数';
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_REFERENCE_DO1" IS 'Dimension扩展1';
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_REFERENCE_DO2" IS 'Dimension扩展2';
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_REFERENCE_DO3" IS 'Dimension扩展3';
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_REFERENCE_DO4" IS 'Dimension扩展4';
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_REFERENCE_DO5" IS 'Dimension扩展5';
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_REFERENCE_FO1" IS 'FACT扩展1';
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_REFERENCE_FO2" IS 'FACT扩展2';
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_REFERENCE_FO3" IS 'FACT扩展3';
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_REFERENCE_FO4" IS 'FACT扩展4';
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_REFERENCE_FO5" IS 'FACT扩展5';
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_REFERENCE_FO6" IS 'FACT扩展6';
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_REFERENCE_FO7" IS 'FACT扩展7';
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_REFERENCE_FO8" IS 'FACT扩展8';
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_REFERENCE_FO9" IS 'FACT扩展9';
   COMMENT ON COLUMN "RADM"."BBG_RA_CUST_LC_DY_A"."BBG_REFERENCE_FO10" IS 'FACT扩展10';
  GRANT UPDATE ON "RADM"."BBG_RA_CUST_LC_DY_A" TO "RABATCHER";
  GRANT SELECT ON "RADM"."BBG_RA_CUST_LC_DY_A" TO "RABATCHER";
  GRANT INSERT ON "RADM"."BBG_RA_CUST_LC_DY_A" TO "RABATCHER";
  GRANT DELETE ON "RADM"."BBG_RA_CUST_LC_DY_A" TO "RABATCHER";
  
--创建FS表：BBG_RA_CUST_LC_DY_FS
CREATE TABLE "RADM"."BBG_RA_CUST_LC_DY_FS" 
   (	"ORG_NUM" VARCHAR2(80 CHAR),  
	"DAY_DT" DATE, 
	"BBG_CUSTOMER_COUNT" NUMBER, 
	"BBG_SERVICE_SATISFACTION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RETAIL_DATA" ;
  
--创建TMP表
-- Create table
ALTER TABLE RABATCHER.BBG_RA_CUST_LC_DY_TMP DROP COLUMN bbg_item_loc_wid;

create table RABATCHER.BBG_RA_CUST_LC_DY_TMP
(
  org_wid                  NUMBER(10),
  org_scd1_wid             NUMBER(10),
/*  prod_it_wid              NUMBER(10),
  prod_scd1_wid            NUMBER(10),*/
  org_lc_wid               NUMBER(10),
  org_ds_wid               NUMBER(10),
  org_rg_wid               NUMBER(10),
  org_ar_wid               NUMBER(10),
  org_ch_wid               NUMBER(10),
/*  prod_dv_wid              NUMBER(10),
  prod_gp_wid              NUMBER(10),
  prod_dp_wid              NUMBER(10),
  prod_cl_wid              NUMBER(10),
  prod_sc_wid              NUMBER(10),*/
  dt_wid                   NUMBER(15),
  wk_wid                   NUMBER(15),
  pr_wid                   NUMBER(15),
  qt_wid                   NUMBER(10),
  day_dt                   DATE,
  wk_num                   VARCHAR2(6),
  pr_num                   VARCHAR2(6),
  qt_num                   VARCHAR2(5),
  org_num                  VARCHAR2(30),
  org_ds_num               VARCHAR2(30),
  org_rg_num               VARCHAR2(30),
  org_ar_num               VARCHAR2(30),
  org_ch_num               VARCHAR2(30),
/*  prod_it_num              VARCHAR2(30),
  prod_sc_num              VARCHAR2(30),
  prod_cl_num              VARCHAR2(30),
  prod_dp_num              VARCHAR2(30),
  prod_gp_num              VARCHAR2(30),
  prod_dv_num              VARCHAR2(30),*/
  datasource_num_id        NUMBER(10),
  integration_id           VARCHAR2(80 CHAR) not null,
  w_insert_dt              DATE,
  w_update_dt              DATE,
/*  bbg_item_loc_wid         NUMBER(10) not null,*/
  bbg_customer_count       NUMBER(20,4),
  bbg_service_satisfaction NUMBER(20,4),
  bbg_reference_do1        VARCHAR2(250),
  bbg_reference_do2        VARCHAR2(250),
  bbg_reference_do3        VARCHAR2(250),
  bbg_reference_do4        VARCHAR2(250),
  bbg_reference_do5        VARCHAR2(250),
  bbg_reference_fo1        NUMBER(20,4),
  bbg_reference_fo2        NUMBER(20,4),
  bbg_reference_fo3        NUMBER(20,4),
  bbg_reference_fo4        NUMBER(20,4),
  bbg_reference_fo5        NUMBER(20,4),
  bbg_reference_fo6        NUMBER(20,4),
  bbg_reference_fo7        NUMBER(20,4),
  bbg_reference_fo8        NUMBER(20,4),
  bbg_reference_fo9        NUMBER(20,4),
  bbg_reference_fo10       NUMBER(20,4)
)
tablespace RETAIL_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
  

-- Create sequence 
create sequence BBG_RA_CUST_LC_DY_A_SEQ
minvalue 1
maxvalue 9999999999999999999999999999
start with 1
increment by 1
cache 20;

DROP sequence BBG_RA_CUST_LC_DY_F_SEQ;

SELECT * FROM BBG_RA_CUST_LC_DY_FV;
SELECT * FROM BBG_RA_CUST_LC_DY_A;
SELECT * FROM BBG_RA_CUST_LC_DY_FS;
SELECT * FROM RABATCHER.BBG_RA_CUST_LC_DY_TMP;

  


 
 


