
--日均库存额A
SELECT IM.DEPT,IM.CLASS,INV.ORG_NUM LOC,INFO.BUSINESS_MODE,SUM(INV.INV_SOH_COST_AMT_LCL_MN_AVG) SOH_COST
FROM W_RTL_INV_IT_LC_MN_AVG2_FV@RMS_RA INV,ITEM_MASTER IM,CMX_ITEM_LOC_INFO INFO
WHERE INV.PROD_NUM(+)=IM.ITEM AND INFO.ITEM(+)=IM.ITEM AND INFO.LOC=INV.ORG_NUM
AND INV.MONTH='201307' AND INV.ORG_NUM>'120000' AND INFO.BUSINESS_MODE IN ('JX','DX')
GROUP BY IM.DEPT,IM.CLASS,INV.ORG_NUM,INFO.BUSINESS_MODE;


--日均销售成本B
SELECT IM.DEPT,IM.CLASS,TDH.LOCATION LOC,INFO.BUSINESS_MODE,SUM(TDH.TOTAL_COST)/30 SALE_COST
FROM TRAN_DATA_HISTORY TDH,ITEM_MASTER IM,CMX_ITEM_LOC_INFO INFO
WHERE TDH.ITEM(+)=IM.ITEM AND INFO.ITEM(+)=IM.ITEM AND INFO.LOC=TDH.LOCATION AND TDH.TRAN_CODE IN (1,3)
AND TDH.TRAN_DATE BETWEEN DATE'2013-07-01' AND DATE'2013-07-31' AND INFO.BUSINESS_MODE IN ('JX','DX')
GROUP BY IM.DEPT,IM.CLASS,TDH.LOCATION,INFO.BUSINESS_MODE;

--DC日均库存额C
--关联WH表REDIST_WH_IND=Y的为生鲜仓库,需要排除.
SELECT IM.DEPT,IM.CLASS,IL.LOC,INFO.BUSINESS_MODE,SUM(DCINV.INV_SOH_COST_AMT_LCL_MN_AVG) DC_SOH_COST
FROM ITEM_MASTER IM,(SELECT ITEM,LOC,SOURCE_WH 
                       FROM ITEM_LOC 
                      WHERE SOURCE_METHOD='W')IL,CMX_ITEM_LOC_INFO INFO,W_RTL_INV_IT_LC_MN_AVG2_FV@RMS_RA DCINV
WHERE IM.ITEM=IL.ITEM(+) AND IL.LOC=INFO.LOC AND IM.ITEM=INFO.ITEM(+) AND DCINV.ORG_NUM=IL.SOURCE_WH AND DCINV.PROD_NUM(+)=IM.ITEM
AND DCINV.MONTH='201307' AND IL.LOC>'120000' AND INFO.BUSINESS_MODE IN ('JX','DX')
AND EXISTS(SELECT 1 FROM WH WHERE WH.WH=DCINV.ORG_NUM AND WH.REDIST_WH_IND='N')--排除DC生鲜仓的库存
GROUP BY IM.DEPT,IM.CLASS,IL.LOC,INFO.BUSINESS_MODE;



/*IM.ITEM=IL.ITEM
IL.LOC=INFO.LOC
IL.ITEM=INFO.ITEM
DCINV.ORG_NUM=IL.SOURCE_WH
DCINV.PROD_NUM=IM.ITEM*/

--合并
--Turnover Report周转报表
--关联WH表REDIST_WH_IND=Y的为生鲜仓库,需要排除.
CREATE MATERIALIZED VIEW YJ_TURNOVER_REPORT AS   
SELECT A.DEPT,A.CLASS,A.LOC,A.BUSINESS_MODE,A.SOH_COST,B.SALE_COST,C.DC_SOH_COST
FROM (SELECT IM.DEPT,IM.CLASS,INV.ORG_NUM LOC,INFO.BUSINESS_MODE,SUM(INV.INV_SOH_COST_AMT_LCL_MN_AVG) SOH_COST
        FROM W_RTL_INV_IT_LC_MN_AVG2_FV@RMS_RA INV,ITEM_MASTER IM,CMX_ITEM_LOC_INFO INFO
       WHERE INV.PROD_NUM(+)=IM.ITEM AND INFO.ITEM(+)=IM.ITEM AND INFO.LOC=INV.ORG_NUM
         AND INV.MONTH='201307' AND INV.ORG_NUM>'120000' AND INFO.BUSINESS_MODE IN ('JX','DX')
    GROUP BY IM.DEPT,IM.CLASS,INV.ORG_NUM,INFO.BUSINESS_MODE)A,
    
(SELECT IM.DEPT,IM.CLASS,TDH.LOCATION LOC,INFO.BUSINESS_MODE,SUM(TDH.TOTAL_COST)/30 SALE_COST
   FROM TRAN_DATA_HISTORY TDH,ITEM_MASTER IM,CMX_ITEM_LOC_INFO INFO
  WHERE TDH.ITEM(+)=IM.ITEM AND INFO.ITEM(+)=IM.ITEM AND INFO.LOC=TDH.LOCATION AND TDH.TRAN_CODE IN (1,3)
    AND TDH.TRAN_DATE BETWEEN DATE'2013-07-01' AND DATE'2013-07-31' AND INFO.BUSINESS_MODE IN ('JX','DX')
GROUP BY IM.DEPT,IM.CLASS,TDH.LOCATION,INFO.BUSINESS_MODE)B,

(SELECT IM.DEPT,IM.CLASS,IL.LOC,INFO.BUSINESS_MODE,SUM(DCINV.INV_SOH_COST_AMT_LCL_MN_AVG) DC_SOH_COST
   FROM ITEM_MASTER IM,(SELECT ITEM,LOC,SOURCE_WH 
                       FROM ITEM_LOC 
                      WHERE SOURCE_METHOD='W')IL,CMX_ITEM_LOC_INFO INFO,W_RTL_INV_IT_LC_MN_AVG2_FV@RMS_RA DCINV
  WHERE IM.ITEM=IL.ITEM(+) AND IL.LOC=INFO.LOC AND IM.ITEM=INFO.ITEM(+) AND DCINV.ORG_NUM=IL.SOURCE_WH AND DCINV.PROD_NUM(+)=IM.ITEM
    AND DCINV.MONTH='201307' AND IL.LOC>'120000' AND INFO.BUSINESS_MODE IN ('JX','DX')
    AND EXISTS(SELECT 1 FROM WH WHERE WH.WH=DCINV.ORG_NUM AND WH.REDIST_WH_IND='N')--排除DC生鲜仓的库存
GROUP BY IM.DEPT,IM.CLASS,IL.LOC,INFO.BUSINESS_MODE)C
WHERE A.DEPT=B.DEPT AND A.CLASS=B.CLASS AND A.LOC=B.LOC AND A.BUSINESS_MODE=B.BUSINESS_MODE AND 
      A.DEPT=C.DEPT AND A.CLASS=C.CLASS AND A.LOC=C.LOC AND A.BUSINESS_MODE=C.BUSINESS_MODE
      
----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------      
--出报表格式
SELECT  C.DEPT,C.CLASS,C.LOC,
        SUM(A.SOH_COST)/*+SUM(A.DC_SOH_COST)*/                                代销日均库存额,
        SUM(A.SALE_COST)                                                  代销日销成本,
        SUM(A.DC_SOH_COST)                                                代销DC日均库存额,
        DECODE(SUM(A.SALE_COST),0,0,SUM(A.SOH_COST)+SUM(A.DC_SOH_COST)/SUM(A.SALE_COST))     周转,
        DECODE(SUM(A.SALE_COST),0,0,SUM(A.SOH_COST)/SUM(A.SALE_COST))  不含DC周转,
-----------------       
        SUM(B.SOH_COST)/*+SUM(B.DC_SOH_COST)*/                                经销日均库存额,
        SUM(B.SALE_COST)                                                  经销日销成本,
        SUM(B.DC_SOH_COST)                                                经销DC日均库存额,
        DECODE(SUM(B.SALE_COST),0,0,SUM(B.SOH_COST)+SUM(A.DC_SOH_COST)/SUM(B.SALE_COST))     周转,
        DECODE(SUM(B.SALE_COST),0,0,SUM(B.SOH_COST)/SUM(B.SALE_COST))  不含DC周转,
-----------------
       SUM(C.SOH_COST)/*+SUM(C.DC_SOH_COST)*/                                 合计日均库存额,
       SUM(C.SALE_COST)                                                   合计日销成本,
       SUM(C.DC_SOH_COST)                                                 合计DC日均库存额,
       DECODE(SUM(C.SALE_COST),0,0,SUM(C.SOH_COST)+SUM(A.DC_SOH_COST)/SUM(C.SALE_COST))      周转,
       DECODE(SUM(C.SALE_COST),0,0,SUM(C.SOH_COST)/SUM(C.SALE_COST))   不含DC周转
       
FROM 
--DX
(SELECT A.DEPT,A.CLASS,A.LOC,A.BUSINESS_MODE,A.SOH_COST,B.SALE_COST,C.DC_SOH_COST
   FROM (SELECT IM.DEPT,IM.CLASS,INV.ORG_NUM LOC,INFO.BUSINESS_MODE,SUM(INV.INV_SOH_COST_AMT_LCL_MN_AVG) SOH_COST
           FROM W_RTL_INV_IT_LC_MN_AVG2_FV@RMS_RA INV,ITEM_MASTER IM,CMX_ITEM_LOC_INFO INFO
          WHERE INV.PROD_NUM(+)=IM.ITEM AND INFO.ITEM(+)=IM.ITEM AND INFO.LOC=INV.ORG_NUM
            AND INV.MONTH='201307' AND INV.ORG_NUM>'120000' AND INFO.BUSINESS_MODE = 'DX'
       GROUP BY IM.DEPT,IM.CLASS,INV.ORG_NUM,INFO.BUSINESS_MODE)A,
    
(SELECT IM.DEPT,IM.CLASS,TDH.LOCATION LOC,INFO.BUSINESS_MODE,SUM(TDH.TOTAL_COST)/30 SALE_COST
   FROM TRAN_DATA_HISTORY TDH,ITEM_MASTER IM,CMX_ITEM_LOC_INFO INFO
  WHERE TDH.ITEM(+)=IM.ITEM AND INFO.ITEM(+)=IM.ITEM AND INFO.LOC=TDH.LOCATION AND TDH.TRAN_CODE IN (1,3) 
    AND TDH.TRAN_DATE BETWEEN DATE'2013-07-01' AND DATE'2013-07-31' AND INFO.BUSINESS_MODE ='DX'
GROUP BY IM.DEPT,IM.CLASS,TDH.LOCATION,INFO.BUSINESS_MODE)B,

(SELECT IM.DEPT,IM.CLASS,IL.LOC,INFO.BUSINESS_MODE,SUM(DCINV.INV_SOH_COST_AMT_LCL_MN_AVG) DC_SOH_COST
   FROM ITEM_MASTER IM,(SELECT ITEM,LOC,SOURCE_WH 
                       FROM ITEM_LOC 
                      WHERE SOURCE_METHOD='W')IL,CMX_ITEM_LOC_INFO INFO,W_RTL_INV_IT_LC_MN_AVG2_FV@RMS_RA DCINV
  WHERE IM.ITEM=IL.ITEM(+) AND IL.LOC=INFO.LOC AND IM.ITEM=INFO.ITEM(+) AND DCINV.ORG_NUM=IL.SOURCE_WH AND DCINV.PROD_NUM(+)=IM.ITEM
    AND DCINV.MONTH='201307' AND IL.LOC>'120000' AND INFO.BUSINESS_MODE = 'DX'
    AND EXISTS(SELECT 1 FROM WH WHERE WH.WH=DCINV.ORG_NUM AND WH.REDIST_WH_IND='N')--排除DC生鲜仓的库存
GROUP BY IM.DEPT,IM.CLASS,IL.LOC,INFO.BUSINESS_MODE)C
WHERE A.DEPT=B.DEPT AND A.CLASS=B.CLASS AND A.LOC=B.LOC AND A.BUSINESS_MODE=B.BUSINESS_MODE AND 
      A.DEPT=C.DEPT AND A.CLASS=C.CLASS AND A.LOC=C.LOC AND A.BUSINESS_MODE=C.BUSINESS_MODE)A,
--JX
(SELECT A.DEPT,A.CLASS,A.LOC,A.BUSINESS_MODE,A.SOH_COST,B.SALE_COST,C.DC_SOH_COST
   FROM (SELECT IM.DEPT,IM.CLASS,INV.ORG_NUM LOC,INFO.BUSINESS_MODE,SUM(INV.INV_SOH_COST_AMT_LCL_MN_AVG) SOH_COST
           FROM W_RTL_INV_IT_LC_MN_AVG2_FV@RMS_RA INV,ITEM_MASTER IM,CMX_ITEM_LOC_INFO INFO
          WHERE INV.PROD_NUM(+)=IM.ITEM AND INFO.ITEM(+)=IM.ITEM AND INFO.LOC=INV.ORG_NUM
            AND INV.MONTH='201307' AND INV.ORG_NUM>'120000' AND INFO.BUSINESS_MODE ='JX'
       GROUP BY IM.DEPT,IM.CLASS,INV.ORG_NUM,INFO.BUSINESS_MODE)A,
    
(SELECT IM.DEPT,IM.CLASS,TDH.LOCATION LOC,INFO.BUSINESS_MODE,SUM(TDH.TOTAL_COST)/30 SALE_COST
   FROM TRAN_DATA_HISTORY TDH,ITEM_MASTER IM,CMX_ITEM_LOC_INFO INFO
  WHERE TDH.ITEM(+)=IM.ITEM AND INFO.ITEM(+)=IM.ITEM AND INFO.LOC=TDH.LOCATION AND TDH.TRAN_CODE IN (1,3) 
    AND TDH.TRAN_DATE BETWEEN DATE'2013-07-01' AND DATE'2013-07-31' AND INFO.BUSINESS_MODE ='JX'
GROUP BY IM.DEPT,IM.CLASS,TDH.LOCATION,INFO.BUSINESS_MODE)B,

(SELECT IM.DEPT,IM.CLASS,IL.LOC,INFO.BUSINESS_MODE,SUM(DCINV.INV_SOH_COST_AMT_LCL_MN_AVG) DC_SOH_COST
   FROM ITEM_MASTER IM,(SELECT ITEM,LOC,SOURCE_WH 
                          FROM ITEM_LOC 
                         WHERE SOURCE_METHOD='W')IL,CMX_ITEM_LOC_INFO INFO,W_RTL_INV_IT_LC_MN_AVG2_FV@RMS_RA DCINV
  WHERE IM.ITEM=IL.ITEM(+) AND IL.LOC=INFO.LOC AND IM.ITEM=INFO.ITEM(+) AND DCINV.ORG_NUM=IL.SOURCE_WH AND DCINV.PROD_NUM(+)=IM.ITEM
    AND DCINV.MONTH='201307' AND IL.LOC>'120000' AND INFO.BUSINESS_MODE ='JX'
    AND EXISTS(SELECT 1 FROM WH WHERE WH.WH=DCINV.ORG_NUM AND WH.REDIST_WH_IND='N')--排除DC生鲜仓的库存
GROUP BY IM.DEPT,IM.CLASS,IL.LOC,INFO.BUSINESS_MODE)C
WHERE A.DEPT=B.DEPT AND A.CLASS=B.CLASS AND A.LOC=B.LOC AND A.BUSINESS_MODE=B.BUSINESS_MODE AND 
      A.DEPT=C.DEPT AND A.CLASS=C.CLASS AND A.LOC=C.LOC AND A.BUSINESS_MODE=C.BUSINESS_MODE)B,
--合计     
(SELECT A.DEPT,A.CLASS,A.LOC,A.BUSINESS_MODE,A.SOH_COST,B.SALE_COST,C.DC_SOH_COST
   FROM (SELECT IM.DEPT,IM.CLASS,INV.ORG_NUM LOC,INFO.BUSINESS_MODE,SUM(INV.INV_SOH_COST_AMT_LCL_MN_AVG) SOH_COST
           FROM W_RTL_INV_IT_LC_MN_AVG2_FV@RMS_RA INV,ITEM_MASTER IM,CMX_ITEM_LOC_INFO INFO
          WHERE INV.PROD_NUM(+)=IM.ITEM AND INFO.ITEM(+)=IM.ITEM AND INFO.LOC=INV.ORG_NUM
            AND INV.MONTH='201307' AND INV.ORG_NUM>'120000' AND INFO.BUSINESS_MODE IN ('JX','DX')
       GROUP BY IM.DEPT,IM.CLASS,INV.ORG_NUM,INFO.BUSINESS_MODE)A,
    
(SELECT IM.DEPT,IM.CLASS,TDH.LOCATION LOC,INFO.BUSINESS_MODE,SUM(TDH.TOTAL_COST)/30 SALE_COST
   FROM TRAN_DATA_HISTORY TDH,ITEM_MASTER IM,CMX_ITEM_LOC_INFO INFO
  WHERE TDH.ITEM(+)=IM.ITEM AND INFO.ITEM(+)=IM.ITEM AND INFO.LOC=TDH.LOCATION AND TDH.TRAN_CODE IN (1,3) 
    AND TDH.TRAN_DATE BETWEEN DATE'2013-07-01' AND DATE'2013-07-31' AND INFO.BUSINESS_MODE IN ('JX','DX')
GROUP BY IM.DEPT,IM.CLASS,TDH.LOCATION,INFO.BUSINESS_MODE)B,

(SELECT IM.DEPT,IM.CLASS,IL.LOC,INFO.BUSINESS_MODE,SUM(DCINV.INV_SOH_COST_AMT_LCL_MN_AVG) DC_SOH_COST
   FROM ITEM_MASTER IM,(SELECT ITEM,LOC,SOURCE_WH 
                          FROM ITEM_LOC 
                         WHERE SOURCE_METHOD='W')IL,CMX_ITEM_LOC_INFO INFO,W_RTL_INV_IT_LC_MN_AVG2_FV@RMS_RA DCINV
  WHERE IM.ITEM=IL.ITEM(+) AND IL.LOC=INFO.LOC AND IM.ITEM=INFO.ITEM(+) AND DCINV.ORG_NUM=IL.SOURCE_WH AND DCINV.PROD_NUM(+)=IM.ITEM
    AND DCINV.MONTH='201307' AND IL.LOC>'120000' AND INFO.BUSINESS_MODE IN ('JX','DX')
    AND EXISTS(SELECT 1 FROM WH WHERE WH.WH=DCINV.ORG_NUM AND WH.REDIST_WH_IND='N')--排除DC生鲜仓的库存
GROUP BY IM.DEPT,IM.CLASS,IL.LOC,INFO.BUSINESS_MODE)C
WHERE A.DEPT=B.DEPT AND A.CLASS=B.CLASS AND A.LOC=B.LOC AND A.BUSINESS_MODE=B.BUSINESS_MODE AND 
      A.DEPT=C.DEPT AND A.CLASS=C.CLASS AND A.LOC=C.LOC AND A.BUSINESS_MODE=C.BUSINESS_MODE)C
      
WHERE /*B.DEPT=C.DEPT AND B.CLASS=C.CLASS AND B.LOC=C.LOC
  AND A.DEPT=C.DEPT AND A.CLASS=C.CLASS AND A.LOC=C.LOC*/
      C.DEPT=B.DEPT(+) AND C.CLASS=B.CLASS(+) AND C.LOC=B.LOC(+)
  AND C.DEPT=A.DEPT(+) AND C.CLASS=A.CLASS(+) AND C.LOC=A.LOC(+)
 
GROUP BY C.DEPT,C.CLASS,C.LOC
ORDER BY C.DEPT,C.CLASS,C.LOC

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------
949089464.72715

SELECT COUNT(*) FROM ITEM_LOC WHERE SOURCE_METHOD='W';
SELECT COUNT(*) FROM CMX_ITEM_LOC_INFO;
SELECT COUNT(*) FROM ITEM_MASTER;

SELECT * FROM TRAN_DATA_HISTORY;
SELECT * FROM ITEM_LOC_SOH;
SELECT * FROM ITEM_MASTER;
SELECT * FROM DEPS --大类
SELECT * FROM W_RTL_INV_IT_LC_MN_AVG2_FV@RMS_RA ;
--SELECT * FROM ITEM_LOC_INFOR_V;
SELECT * FROM ITEM_LOC WHERE SOURCE_METHOD='W'; --SOURCE_WH商品仓库
SELECT ITEM,SOURCE_WH FROM ITEM_LOC WHERE SOURCE_METHOD='W';
SELECT * FROM ITEM_LOC T WHERE T.LOC=118001;
SELECT count(*) FROM ITEM_LOC WHERE SOURCE_WH IS NOT NULL;
SELECT * FROM STORE ORDER BY STORE;
SELECT distinct loc FROM ITEM_LOC;
SELECT DISTINCT ORG_NUM FROM W_RTL_INV_IT_LC_MN_AVG2_FV@RMS_RA;
SELECT * FROM CMX_ITEM_LOC_INFO;


SELECT DISTINCT 'COUNT',
       CASE WHEN T.BUSINESS_MODE='JX' THEN  COUNT(*)  END JXC,
         CASE WHEN T.BUSINESS_MODE='DX' THEN  COUNT(*)  END DXC
FROM CMX_ITEM_LOC_INFO T
WHERE T.BUSINESS_MODE IN ('JX','DX')
GROUP BY T.BUSINESS_MODE;

SELECT DECODE(T.BUSINESS_MODE,'JX',COUNT(1),T.BUSINESS_MODE,'DX',COUNT(1))
FROM CMX_ITEM_LOC_INFO T
GROUP BY T.BUSINESS_MODE

SELECT DISTINCT T.BUSINESS_MODE
FROM CMX_ITEM_LOC_INFO T

SELECT SUM(INV_SOH_COST_AMT_LCL_MN),SUM(INV_SOH_COST_AMT_LCL_MN_AVG) FROM W_RTL_INV_IT_LC_MN_AVG2_FV@RMS_RA WHERE MONTH='201307'
AND ORG_NUM >=120000;

CREATE GLOBAL TEMPORARY TABLE YJ_STORE

SELECT IM.DEPT,IM.CLASS,INV.ORG_NUM,
       CASE WHEN INFO.BUSINESS_MODE='JX' THEN SUM(INV.INV_SOH_COST_AMT_LCL_MN_AVG) END JX日均库存额,
       CASE WHEN INFO.BUSINESS_MODE='JX' THEN SUM(TDH.TOTAL_COST)/30 END JX日销成本,
       CASE WHEN INFO.BUSINESS_MODE='JX' THEN SUM(DCINV.INV_SOH_COST_AMT_LCL_MN_AVG) END JX_DC日均库存额,
       CASE WHEN INFO.BUSINESS_MODE='JX' THEN (SUM(INV.INV_SOH_COST_AMT_LCL_MN_AVG)+SUM(DCINV.INV_SOH_COST_AMT_LCL_MN_AVG))/(SUM(TDH.TOTAL_COST)/30) END JX周转,
       CASE WHEN INFO.BUSINESS_MODE='JX' THEN SUM(INV.INV_SOH_COST_AMT_LCL_MN_AVG)/(SUM(TDH.TOTAL_COST)/30) END JX不含DC周转,
       CASE WHEN INFO.BUSINESS_MODE='DX' THEN SUM(INV.INV_SOH_COST_AMT_LCL_MN_AVG) END DX日均库存额,
       CASE WHEN INFO.BUSINESS_MODE='DX' THEN SUM(TDH.TOTAL_COST)/30 END DX日销成本,
       CASE WHEN INFO.BUSINESS_MODE='DX' THEN SUM(DCINV.INV_SOH_COST_AMT_LCL_MN_AVG) END DX_DC日均库存额,
       CASE WHEN INFO.BUSINESS_MODE='DX' THEN (SUM(INV.INV_SOH_COST_AMT_LCL_MN_AVG)+SUM(DCINV.INV_SOH_COST_AMT_LCL_MN_AVG))/(SUM(TDH.TOTAL_COST)/30) END DX周转,
       CASE WHEN INFO.BUSINESS_MODE='DX' THEN SUM(INV.INV_SOH_COST_AMT_LCL_MN_AVG)/(SUM(TDH.TOTAL_COST)/30) END DX不含DC周转
FROM W_RTL_INV_IT_LC_MN_AVG2_FV@RMS_RA INV,--门店库存
     TRAN_DATA_HISTORY TDH,
     ITEM_MASTER IM,
     (SELECT ITEM,LOC,SOURCE_WH FROM ITEM_LOC WHERE SOURCE_WH IS NOT NULL ) IL,--关联仓库
     W_RTL_INV_IT_LC_MN_AVG2_FV@RMS_RA DCINV ,--DC库存
     CMX_ITEM_LOC_INFO INFO --经营属性
WHERE INV.PROD_NUM=IM.ITEM AND IM.ITEM=TDH.ITEM AND TDH.LOCATION=INV.ORG_NUM 
AND IL.SOURCE_WH=DCINV.ORG_NUM AND INV.ORG_NUM=IL.LOC AND INV.PROD_NUM=IL.ITEM 
AND INFO.ITEM=INV.PROD_NUM AND INFO.LOC=INV.ORG_NUM
AND INV.MONTH='201307'
AND DCINV.MONTH='201307'
--AND TDH.TRAN_DATE = DATE'2013-07-01' 
AND TDH.TOTAL_COST<>0
AND TDH.TRAN_DATE BETWEEN DATE'2013-07-01' AND DATE'2013-07-31'
AND TDH.TRAN_CODE IN (1,3)
AND INV.ORG_NUM >120000
GROUP BY IM.DEPT,IM.CLASS,INV.ORG_NUM,INFO.BUSINESS_MODE
---------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------

