SELECT *
  FROM W_RTL_SLS_TRX_IT_LC_DY_FS T
 WHERE NOT EXISTS
 (SELECT 1
          FROM (SELECT FS.*
                  FROM W_RTL_SLS_TRX_IT_LC_DY_FS FS, BBG_RA_ITEM_LOC_D IL
                 WHERE FS.PROD_IT_NUM = IL.ITEM
                   AND FS.ORG_NUM = IL.LOC
                   AND FS.DAY_DT BETWEEN IL.EFFECTIVE_FROM_DT and
                       IL.EFFECTIVE_TO_DT) A
         WHERE T.PROD_IT_NUM = A.PROD_IT_NUM
           AND T.ORG_NUM = A.ORG_NUM
           AND T.DAY_DT = A.DAY_DT);

SELECT *
  FROM BBG_RA_ITEM_LOC_D D
 WHERE D.ITEM = '800026625'
   AND D.LOC = '120185';
2013 / 5 / 1

  SELECT *
    FROM W_RTL_SLS_TRX_IT_LC_DY_FS T
   WHERE (T.PROD_IT_NUM, T.ORG_NUM) NOT IN
         (SELECT D.ITEM, D.LOC FROM BBG_RA_ITEM_LOC_D D);

SELECT *
  FROM W_RTL_SLS_TRX_IT_LC_DY_FS T
 WHERE NOT EXISTS
 (SELECT 1
          FROM BBG_RA_ITEM_LOC_D D
         WHERE T.PROD_IT_NUM = D.ITEM
           AND T.ORG_NUM = D.LOC
           AND T.DAY_DT BETWEEN D.EFFECTIVE_FROM_DT AND D.EFFECTIVE_TO_DT);

SELECT *
  FROM W_RTL_SLS_TRX_IT_LC_DY_FS T
 WHERE NOT EXISTS (SELECT 1
          FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP D
         WHERE T.PROD_IT_NUM = D.PROD_IT_NUM
           AND T.ORG_NUM = D.ORG_NUM);

SELECT *
  FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP
       
        SELECT T.DAY_DT, SUM(T.SLS_QTY), SUM(T.SLS_AMT_LCL)
          FROM W_RTL_SLS_TRX_IT_LC_DY_FS T
        /*WHERE T.DAY_DT BETWEEN DATE'2013-05-07' AND DATE'2013-05-07'*/
         GROUP BY T.DAY_DT
         ORDER BY T.DAY_DT;


SELECT T.Dt_Wid, SUM(T.SLS_QTY), SUM(T.SLS_AMT_LCL)
  FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP T
/*WHERE T.Dt_Wid BETWEEN 120130507000 AND 120130507000*/
 GROUP BY T.Dt_Wid;
--销售插入tmp后有重复的记录
CREATE TABLE YJ_ITEM_LOC_CF AS
  SELECT T.ORG_NUM,
         T.PROD_IT_NUM,
         T.SLS_QTY,
         T.SLS_AMT_LCL,
         T.DAY_DT,
         COUNT(*) CNT
    FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP T
   GROUP BY T.ORG_NUM, T.PROD_IT_NUM, T.SLS_QTY, T.SLS_AMT_LCL, T.DAY_DT
  HAVING COUNT(*) > 1
   ORDER BY COUNT(*) DESC
            
             SELECT *
               FROM RABATCHER.W_RTL_SLS_TRX_IT_LC_DY_TMP T
              WHERE T.ORG_NUM = '120170'
                AND T.PROD_IT_NUM = '800034518'
                AND T.DAY_DT = DATE '2013-05-03';

SELECT *
  FROM W_RTL_SLS_TRX_IT_LC_DY_FS T
 WHERE T.ORG_NUM = '120170'
   AND T.PROD_IT_NUM = '800034518'
   AND T.DAY_DT = DATE '2013-05-03';

SELECT *
  FROM BBG_RA_ITEM_LOC_D T
 WHERE T.ITEM = '800237079'
   AND T.LOC = '120127';

SELECT *
  FROM BBG_RA_ITEM_LOC_D D
 WHERE D.W_INSERT_DT = DATE '2013-01-01'
   AND W_UPDATE_DT = DATE '2013-01-01'
   AND D.CURRENT_FLG = 'N';
--开始日期和结束日期重复
SELECT D.ITEM, D.LOC, D.EFFECTIVE_FROM_DT, D.EFFECTIVE_TO_DT, COUNT(*)
  FROM BBG_RA_ITEM_LOC_D D
 WHERE D.CURRENT_FLG = 'N' --AND D.ITEM='800237079' AND D.LOC='120127'
 GROUP BY D.ITEM, D.LOC, D.EFFECTIVE_FROM_DT, D.EFFECTIVE_TO_DT
HAVING COUNT(*) > 1
 ORDER BY COUNT(*);
--删除日期条件重复的记录
DELETE FROM BBG_RA_ITEM_LOC_D A
 WHERE (A.ITEM, A.LOC, A.EFFECTIVE_FROM_DT, A.EFFECTIVE_TO_DT) IN
       (
        --日期重复的记录
        SELECT D.ITEM, D.LOC, D.EFFECTIVE_FROM_DT, D.EFFECTIVE_TO_DT
          FROM BBG_RA_ITEM_LOC_D D
         WHERE D.CURRENT_FLG = 'N' --AND D.ITEM='800237079' AND D.LOC='120127'
         GROUP BY D.ITEM, D.LOC, D.EFFECTIVE_FROM_DT, D.EFFECTIVE_TO_DT
        HAVING COUNT(*) > 1)
      --
   AND A.ROW_WID NOT IN
       (SELECT MIN(B.ROW_WID)
          FROM BBG_RA_ITEM_LOC_D B
         WHERE B.CURRENT_FLG = 'N' --AND B.ITEM='800237079' AND B.LOC='120127'
         GROUP BY B.ITEM, B.LOC, B.EFFECTIVE_FROM_DT, B.EFFECTIVE_TO_DT
        HAVING COUNT(*) > 1);
--例子
SELECT *
  FROM BBG_RA_ITEM_LOC_D T
 WHERE T.ITEM = '800237079'
   AND T.LOC = '120127'
 ORDER BY T.EFFECTIVE_FROM_DT, T.EFFECTIVE_TO_DT;
SELECT *
  FROM BBG_RA_ITEM_LOC_D T
 WHERE T.ITEM = '800195695'
   AND T.LOC = '120158'
 ORDER BY T.EFFECTIVE_FROM_DT, T.EFFECTIVE_TO_DT
   FOR UPDATE;
--查找最多cnt的例子
SELECT T.ITEM, T.LOC
  FROM BBG_RA_ITEM_LOC_D T
 GROUP BY T.ITEM, T.LOC
HAVING COUNT(*) > 1
 ORDER BY COUNT(*) DESC;
--检查同一ITEM_LOC,EFFECTIVE_FROM_DT重复
CREATE TABLE BBG_RA_ITEM_LOC_D_EFFECTIVE_FC AS
  SELECT T.ITEM, T.LOC, T.EFFECTIVE_FROM_DT, COUNT(*) CNT
    FROM BBG_RA_ITEM_LOC_D T
   WHERE T.CURRENT_FLG = 'N'
   GROUP BY T.ITEM, T.LOC, T.EFFECTIVE_FROM_DT
  HAVING COUNT(*) > 1
   ORDER BY COUNT(*) DESC;
--处理EFFECTIVE_FROM_DT重复
SELECT * FROM BBG_RA_ITEM_LOC_D_EFFECTIVE_FC;

UPDATE BBG_RA_ITEM_LOC_D B
   SET B.EFFECTIVE_FROM_DT = DATE '2011-01-01'
 WHERE EXISTS (SELECT C.ROW_WID
          FROM (SELECT A.ITEM, A.LOC, MAX(A.ROW_WID) ROW_WID
                  FROM BBG_RA_ITEM_LOC_D A
                 WHERE (A.ITEM, A.LOC, A.EFFECTIVE_FROM_DT) IN
                       (SELECT C.ITEM, C.LOC, C.EFFECTIVE_FROM_DT
                          FROM BBG_RA_ITEM_LOC_D_EFFECTIVE_FC C)
                   AND A.CURRENT_FLG = 'N'
                --AND A.ITEM='800041570' AND A.LOC='120190'
                 GROUP BY A.ITEM, A.LOC) C
         WHERE B.ROW_WID = C.ROW_WID);
--日期effective_to_dt重复
CREATE TABLE BBG_RA_ITEM_LOC_D_YJ_CF AS
  SELECT T.ITEM, T.LOC, T.EFFECTIVE_TO_DT
    FROM BBG_RA_ITEM_LOC_D T
   GROUP BY T.ITEM, T.LOC, T.EFFECTIVE_TO_DT
  HAVING COUNT(*) > 1;
--查找全部为N的记录
SELECT *
  FROM BBG_RA_ITEM_LOC_D a
 WHERE not EXISTS (SELECT T.ITEM, T.LOC
          FROM BBG_RA_ITEM_LOC_D T
         WHERE T.CURRENT_FLG = 'Y'
           and a.item = t.item
           and a.loc = t.loc);

SELECT A.ITEM, A.LOC
  FROM BBG_RA_ITEM_LOC_D a
 WHERE not EXISTS (SELECT T.ITEM, T.LOC
          FROM BBG_RA_ITEM_LOC_D T
         WHERE T.CURRENT_FLG = 'Y'
           and a.item = t.item
           and a.loc = t.loc)
 GROUP BY A.ITEM, A.LOC
HAVING COUNT(*) > 1;

--建立测试表测试
CREATE TABLE BBG_RA_ITEM_LOC_D_TEST AS
  SELECT *
    FROM BBG_RA_ITEM_LOC_D T
   WHERE T.ITEM = '800237079'
     AND T.LOC = '120127'
   ORDER BY T.EFFECTIVE_FROM_DT, T.EFFECTIVE_TO_DT;
SELECT * FROM BBG_RA_ITEM_LOC_D_TEST FOR UPDATE;
--update effective_TO_DT
UPDATE BBG_RA_ITEM_LOC_D T
   SET T.EFFECTIVE_TO_DT =
       (SELECT NVL(B.NEW_EFFECTIVE_TO_DT, T.EFFECTIVE_TO_DT)
          FROM (SELECT ROW_WID,
                       LEAD(Effective_From_DT) Over(Partition By Item, Loc Order By Effective_From_DT) - 1 NEW_EFFECTIVE_TO_DT
                  FROM BBG_RA_ITEM_LOC_D) B
         WHERE T.ROW_WID = B.ROW_WID)
 WHERE T.CURRENT_FLG = 'N';

--使用储存过程
begin
  -- Call the procedure
  up_it_lc_d_eff_to_dt_yj;
end;

--储存过程使用的语句
SELECT T.ITEM, T.LOC
  FROM BBG_RA_ITEM_LOC_D T
 GROUP BY T.ITEM, T.LOC, T.EFFECTIVE_TO_DT
HAVING COUNT(*) > 1;
