--NBO应开通门店数
SELECT ILD.ITEM,COUNT(*) NBO_COUNT_STORE
FROM BBG_RA_ITEM_LOC_D ILD
WHERE ILD.CURRENT_FLG='Y' AND ILD.NBO='Y'
AND ILD.LOC>120000
GROUP BY ILD.ITEM;

--NBO停购门店数
SELECT ILD.ITEM,COUNT(ILD.NBO) NBO_NOORDER_COUNT_STORE
FROM BBG_RA_ITEM_LOC_D ILD
WHERE EXISTS(SELECT 1 FROM BBG_RA_ITEM_LOC_SUPP_D ILSD WHERE ILD.ITEM=ILSD.ITEM AND ILD.LOC=ILSD.LOC AND ILSD.REF_NO2='N' )
AND ILD.CURRENT_FLG='Y'
AND ILD.NBO='Y'
GROUP BY ILD.ITEM;

--NBO有库存门店数
SELECT ILD.ITEM,COUNT(ILD.NBO) NBO_INV_COUNT_STORE
FROM BBG_RA_ITEM_LOC_D ILD
WHERE EXISTS(SELECT 1 FROM W_RTL_INV_IT_LC_G INV WHERE INV.PROD_IT_NUM=ILD.ITEM AND INV.ORG_NUM=ILD.LOC AND INV.INV_SOH_QTY>0 )
AND ILD.CURRENT_FLG='Y' 
AND ILD.NBO='Y' 
GROUP BY ILD.ITEM;

--NBO有货门店数
SELECT ILD.ITEM,COUNT(ILD.NBO) NBO_INV3_COUNT_STORE
FROM BBG_RA_ITEM_LOC_D ILD
WHERE EXISTS(SELECT 1 
               FROM cmx_sale_history@ra_rms_dblink sale,W_RTL_INV_IT_LC_G INV 
              WHERE SALE.ITEM=INV.PROD_IT_NUM AND SALE.LOC=INV.ORG_NUM
                AND INV.PROD_IT_NUM=ILD.ITEM AND INV.ORG_NUM=ILD.LOC AND INV.INV_SOH_QTY>SALE.FOUR_WEEK_SALE*3 )
AND ILD.CURRENT_FLG='Y' 
AND ILD.NBO='Y' 
GROUP BY ILD.ITEM;

--创建固化视图   按商品汇总
CREATE MATERIALIZED VIEW BBG_RA_NBOItemCountOfStore_A AS
SELECT A.ITEM,'1'||TO_CHAR(SYSDATE-1,'YYYYMMDD')||'000' DT_WID,A.NBO_COUNT_STORE,B.NBO_NOORDER_COUNT_STORE,C.NBO_INV_COUNT_STORE,D.NBO_INV3_COUNT_STORE
FROM (--NBO应开通门店数
SELECT ILD.ITEM,COUNT(*) NBO_COUNT_STORE
FROM BBG_RA_ITEM_LOC_D ILD
WHERE ILD.CURRENT_FLG='Y' AND ILD.NBO='Y'
AND ILD.LOC>120000
GROUP BY ILD.ITEM)A,
(--NBO停购门店数
SELECT ILD.ITEM,COUNT(ILD.NBO) NBO_NOORDER_COUNT_STORE
FROM BBG_RA_ITEM_LOC_D ILD
WHERE EXISTS(SELECT 1 FROM BBG_RA_ITEM_LOC_SUPP_D ILSD WHERE ILD.ITEM=ILSD.ITEM AND ILD.LOC=ILSD.LOC AND ILSD.REF_NO2='N' )
AND ILD.CURRENT_FLG='Y'
AND ILD.NBO='Y'
GROUP BY ILD.ITEM)B,
(--NBO有库存门店数
SELECT ILD.ITEM,COUNT(ILD.NBO) NBO_INV_COUNT_STORE
FROM BBG_RA_ITEM_LOC_D ILD
WHERE EXISTS(SELECT 1 FROM W_RTL_INV_IT_LC_G INV WHERE INV.PROD_IT_NUM=ILD.ITEM AND INV.ORG_NUM=ILD.LOC AND INV.INV_SOH_QTY>0 )
AND ILD.CURRENT_FLG='Y' 
AND ILD.NBO='Y' 
GROUP BY ILD.ITEM)C,
(--NBO有货门店数
SELECT ILD.ITEM,COUNT(ILD.NBO) NBO_INV3_COUNT_STORE
FROM BBG_RA_ITEM_LOC_D ILD
WHERE EXISTS(SELECT 1 
               FROM cmx_sale_history@ra_rms_dblink sale,W_RTL_INV_IT_LC_G INV 
              WHERE SALE.ITEM=INV.PROD_IT_NUM AND SALE.LOC=INV.ORG_NUM
                AND INV.PROD_IT_NUM=ILD.ITEM AND INV.ORG_NUM=ILD.LOC AND INV.INV_SOH_QTY>SALE.FOUR_WEEK_SALE*3 )
AND ILD.CURRENT_FLG='Y' 
AND ILD.NBO='Y' 
GROUP BY ILD.ITEM)D
WHERE A.ITEM=B.ITEM(+) AND A.ITEM=C.ITEM(+) AND A.ITEM=D.ITEM(+) ;
-------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------
--门店应开通SKU
SELECT ILD.LOC,COUNT(*) NBO_SKU
FROM BBG_RA_ITEM_LOC_D ILD
WHERE ILD.CURRENT_FLG='Y' AND ILD.NBO='Y'
AND ILD.LOC>120000
GROUP BY ILD.LOC;

--门店停购SKU
SELECT ILD.LOC,COUNT(ILD.NBO) NBO_NOORDER_SKU
FROM BBG_RA_ITEM_LOC_D ILD
WHERE EXISTS(SELECT 1 FROM BBG_RA_ITEM_LOC_SUPP_D ILSD WHERE ILD.ITEM=ILSD.ITEM AND ILD.LOC=ILSD.LOC AND ILSD.REF_NO2='N' )
AND ILD.CURRENT_FLG='Y'
AND ILD.NBO='Y'
GROUP BY ILD.LOC;

--门店有货SKU
SELECT ILD.LOC,COUNT(ILD.NBO) NBO_INV_SKU
FROM BBG_RA_ITEM_LOC_D ILD
WHERE EXISTS(SELECT 1 FROM W_RTL_INV_IT_LC_G INV WHERE INV.PROD_IT_NUM=ILD.ITEM AND INV.ORG_NUM=ILD.LOC AND INV.INV_SOH_QTY>0 )
AND ILD.CURRENT_FLG='Y' 
AND ILD.NBO='Y' 
GROUP BY ILD.LOC;

--创建固化视图   按门店汇总
CREATE MATERIALIZED VIEW BBG_RA_NBOStoreCountOfItem_A as
SELECT A.LOC,'1'||TO_CHAR(SYSDATE-1,'YYYYMMDD')||'000' DT_WID,A.NBO_SKU,B.NBO_NOORDER_SKU,C.NBO_INV_SKU
FROM (--门店应开通SKU
SELECT ILD.LOC,COUNT(*) NBO_SKU
FROM BBG_RA_ITEM_LOC_D ILD
WHERE ILD.CURRENT_FLG='Y' AND ILD.NBO='Y'
AND ILD.LOC>120000
GROUP BY ILD.LOC)A,
(--门店停购SKU
SELECT ILD.LOC,COUNT(ILD.NBO) NBO_NOORDER_SKU
FROM BBG_RA_ITEM_LOC_D ILD
WHERE EXISTS(SELECT 1 FROM BBG_RA_ITEM_LOC_SUPP_D ILSD WHERE ILD.ITEM=ILSD.ITEM AND ILD.LOC=ILSD.LOC AND ILSD.REF_NO2='N' )
AND ILD.CURRENT_FLG='Y'
AND ILD.NBO='Y'
GROUP BY ILD.LOC)B,
(--门店有货SKU
SELECT ILD.LOC,COUNT(ILD.NBO) NBO_INV_SKU
FROM BBG_RA_ITEM_LOC_D ILD
WHERE EXISTS(SELECT 1 FROM W_RTL_INV_IT_LC_G INV WHERE INV.PROD_IT_NUM=ILD.ITEM AND INV.ORG_NUM=ILD.LOC AND INV.INV_SOH_QTY>0 )
AND ILD.CURRENT_FLG='Y' 
AND ILD.NBO='Y' 
GROUP BY ILD.LOC)C
WHERE A.LOC=B.LOC(+) AND A.LOC=C.LOC(+);

SELECT * FROM BBG_RA_NBOItemCountOfStore_A;
SELECT * FROM BBG_RA_NBOStoreCountOfItem_A;
-------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------
--按大类汇总  BBG_RA_NBOSKU_DP_DY_A
--有库存SKU
--在BBG_RA_NBOITEMCOUNTOFSTORE_A表基础上取Y/N标志
SELECT ITEM PROD_NUM,DT_WID,
       CASE WHEN NBO_COUNT_STORE>0 THEN 1 ELSE 0 END NBO_FLG,
       CASE WHEN NBO_NOORDER_COUNT_STORE>0 THEN 1 ELSE 0 END NBO_NOORDER_FLG,
       CASE WHEN NBO_INV_COUNT_STORE>0 THEN 1 ELSE 0 END NBO_INV_FLG,
       CASE WHEN NBO_INV3_COUNT_STORE>0 THEN 1 ELSE 0 END NBO_INV3_FLG  
FROM BBG_RA_NBOITEMCOUNTOFSTORE_A;

select distinct cast(T955085.LVL4ANC_PRODCAT_ID as  INTEGER  ) as DP_NUM,
               T14449.PROD_NUM as PROD_NUM,
               T14449.PROD_CAT5_WID_AS_WAS
          from 
               (SELECT T.*
  FROM W_PRODUCT_D T, W_PRODUCT_ATTR_D A
 WHERE T.SCD1_WID = A.SCD1_WID
   AND A.PRODUCT_ATTR12_NAME = A.PRODUCT_ATTR11_NAME) T14449,
               W_PROD_CAT_DH T955085 /* Dim_W_PROD_CAT_DH_As_Was */ 
          where  ( T14449.PROD_CAT5_WID_AS_WAS = T955085.ROW_WID );
--创建固化视图
CREATE MATERIALIZED VIEW RADM.BBG_RA_NBOSKU_DP_DY_A AS
SELECT DP.DP_NUM,NBO.DT_WID,DP.PROD_DH_WID,
SUM(NBO.NBO_FLG) NBO_SKU,SUM(NBO.NBO_NOORDER_FLG) NBO_NOORDER_SKU,SUM(NBO.NBO_INV_FLG) NBO_INV_SKU,SUM(NBO.NBO_INV3_FLG) NBO_INV3_SKU--,COUNT(DP.PROD_NUM)
FROM (SELECT ITEM PROD_NUM,DT_WID,
       CASE WHEN NBO_COUNT_STORE>0 THEN 1 ELSE 0 END NBO_FLG,
       CASE WHEN NBO_NOORDER_COUNT_STORE>0 THEN 1 ELSE 0 END NBO_NOORDER_FLG,
       CASE WHEN NBO_INV_COUNT_STORE>0 THEN 1 ELSE 0 END NBO_INV_FLG,
       CASE WHEN NBO_INV3_COUNT_STORE>0 THEN 1 ELSE 0 END NBO_INV3_FLG  
FROM BBG_RA_NBOITEMCOUNTOFSTORE_A)NBO,--NBO标志表
(select distinct cast(T955085.LVL6ANC_PRODCAT_ID as  INTEGER  ) as DP_NUM,
               T14449.PROD_NUM as PROD_NUM,
               DEPT.ROW_WID PROD_DH_WID
          from 
               (SELECT T.*
  FROM W_PRODUCT_D T, W_PRODUCT_ATTR_D A
 WHERE T.SCD1_WID = A.SCD1_WID
   AND A.PRODUCT_ATTR12_NAME = A.PRODUCT_ATTR11_NAME) T14449,
               W_PROD_CAT_DH T955085 ,/* Dim_W_PROD_CAT_DH_As_Was */ 
               W_PROD_CAT_DH DEPT
          where  ( T14449.PROD_CAT5_WID_AS_WAS = T955085.ROW_WID )
          AND DEPT.LEVEL_NAME='DEPT' AND DEPT.LVL6ANC_PRODCAT_ID=T955085.LVL6ANC_PRODCAT_ID)DP--大类商品对照表
WHERE NBO.PROD_NUM=DP.PROD_NUM(+) AND DP.DP_NUM IS NOT NULL
GROUP BY DP.DP_NUM,NBO.DT_WID,DP.PROD_DH_WID;
----------------------------------------------------------------------------------------------------------------------------

SELECT * FROM BBG_RA_NBOSKU_DP_DY_A;

DROP MATERIALIZED VIEW RADM.BBG_RA_NBOSKU_DP_DY_A




SELECT * FROM BBG_RA_ITEM_LOC_D;
SELECT * FROM W_PRODUCT_D;
SELECT * FROM ITEM_MASTER@RA_RMS_DBLINK;
SELECT * FROM CMX_ITEM_LOC_INFO@RA_RMS_DBLINK;
SELECT * FROM W_PROD_CAT_DH;
SELECT * FROM BBG_RA_ITEM_LOC_D;
SELECT * FROM W_PRODUCT_D;
SELECT * FROM BBG_RA_NBOITEMCOUNTOFSTORE_A T
WHERE  EXISTS(select distinct cast(T955085.LVL4ANC_PRODCAT_ID as  INTEGER  ) as DP_NUM,
               T14449.PROD_NUM as PROD_NUM,
               T14449.PROD_CAT5_WID_AS_WAS
          from 
               (SELECT T.*
  FROM W_PRODUCT_D T, W_PRODUCT_ATTR_D A
 WHERE T.SCD1_WID = A.SCD1_WID
   AND A.PRODUCT_ATTR12_NAME = A.PRODUCT_ATTR11_NAME) T14449,
               W_PROD_CAT_DH T955085 /* Dim_W_PROD_CAT_DH_As_Was */ 
          where  ( T14449.PROD_CAT5_WID_AS_WAS = T955085.ROW_WID ) 
          AND T14449.PROD_NUM=T.ITEM );
--添加中文说明

VALUEOF(NQ_SESSION.CN_Retail_As-Was_BBG_NBO_Item_Count_by_Loc)--门店的NBO商品数统计Stores statistics for the number of NBO product
VALUEOF(NQ_SESSION.CN_Retail_As-Was_BBG_NBO_Item_Count_by_Loc_NBO_INV_SKU)--有货SKU
VALUEOF(NQ_SESSION.CN_Retail_As-Was_BBG_NBO_Item_Count_by_Loc_NBO_NOORDER_SKU)--停购SKU
VALUEOF(NQ_SESSION.CN_Retail_As-Was_BBG_NBO_Item_Count_by_Loc_NBO_SKU)--应开通SKU

VALUEOF(NQ_SESSION.CD_Retail_As-Was_BBG_NBO_Item_Count_by_Loc)


VALUEOF(NQ_SESSION.CN_Retail_As-Was_BBG_NBO_Loc_Count_by_Item)--NBO商品的门店数统计NBO product statistics for the number of stores
VALUEOF(NQ_SESSION.CN_Retail_As-Was_BBG_NBO_Loc_Count_by_Item_NBO_COUNT_STORE)--应开通门店数
VALUEOF(NQ_SESSION.CN_Retail_As-Was_BBG_NBO_Loc_Count_by_Item_NBO_INV3_COUNT_STORE)--有货门店数
VALUEOF(NQ_SESSION.CN_Retail_As-Was_BBG_NBO_Loc_Count_by_Item_NBO_INV_COUNT_STORE)--有库存门店数
VALUEOF(NQ_SESSION.CN_Retail_As-Was_BBG_NBO_Loc_Count_by_Item_NBO_NOORDER_COUNT_STORE)--停购门店数
---------------------------------------------------------------------------------------------------------------------------------------
VALUEOF(NQ_SESSION.CN_Retail_As-Was_BBG_NBO_Item_Count_by_Dept)--NBO商品的大类数统计NBO
VALUEOF(NQ_SESSION.CN_Retail_As-Was_BBG_NBO_Item_Count_by_Dept_NBO_INV3_SKU)--有货SKU
VALUEOF(NQ_SESSION.CN_Retail_As-Was_BBG_NBO_Item_Count_by_Dept_NBO_INV_SKU)--有库存SKU
VALUEOF(NQ_SESSION.CN_Retail_As-Was_BBG_NBO_Item_Count_by_Dept_NBO_NOORDER_SKU)--停购SKU
VALUEOF(NQ_SESSION.CN_Retail_As-Was_BBG_NBO_Item_Count_by_Dept_NBO_SKU)--NBO SKU


SELECT * FROM w_localized_string_g G WHERE G.MSG_NUM LIKE '%Retail_As-Was_BBG_NBO%' and lang_id='zh-cn' FOR UPDATE ;

SELECT * FROM w_localized_string_g G WHERE G.MSG_TEXT LIKE '->报告期初拥有%' and lang_id='zh-cn' FOR UPDATE ;

CD_Retail_As-Was_Inventory_Position

SELECT * FROM w_localized_string_g G WHERE G.MSG_NUM LIKE '%CD_Retail_As-Was_BBG_NBO_Item_Count_by_Loc%';
SELECT * FROM w_localized_string_g G WHERE G.MSG_NUM LIKE '%CD_Retail_As-Was_BBG_NBO_Loc_Count_by_Item%';



/*DROP MATERIALIZED VIEW BBG_RA_NBOItemCountOfStore_A;
DROP MATERIALIZED VIEW BBG_RA_NBOStoreCountOfItem_A;*/
-----------------------------------------------------------------------------------------------------------------------------
SELECT COUNT(*) FROM BBG_RA_ITEM_LOC_D T WHERE T.CURRENT_FLG='Y' AND T.NBO='Y';--265442
SELECT COUNT(*) FROM BBG_RA_ITEM_LOC_SUPP_D T WHERE T.REF_NO2='Y';--5759935
SELECT * FROM BBG_RA_ITEM_LOC_D T WHERE T.CURRENT_FLG='Y' AND T.NBO='Y' AND T.ITEM='800026955';
SELECT * FROM BBG_RA_ITEM_LOC_SUPP_D T WHERE T.REF_NO2='Y' AND T.ITEM='800026955';
SELECT * FROM cmx_sale_history@ra_rms_dblink;
--SELECT * FROM ALL_TABLES WHERE TABLE_NAME LIKE '%SLS%IT%LC%'
SELECT T.ITEM,T.LOC,COUNT(*) FROM cmx_sale_history@ra_rms_dblink T
GROUP BY T.ITEM,T.LOC
HAVING COUNT(*)>1;
SELECT  FROM W_RTL_INV_IT_LC_G
SELECT * FROM W_PRODUCT_D_TL WHERE INTEGRATION_ID='800369366';
SELECT * FROM W_PRODUCT_D WHERE INTEGRATION_ID='800369366';
SELECT * FROM W_RTL_INV_IT_LC_G WHERE PROD_IT_NUM='800026528';
SELECT * FROM w_Rtl_Inv_It_Lc_Dy_f
SELECT * FROM w_Rtl_Inv_It_Lc_Dy_fv
SELECT * FROM W_RTL_INV_IT_LC_G;--最后一天库存
w_Rtl_Inv_It_Lc_Dy_f
SELECT * FROM W_RTL_INV_IT_LC_G WHERE PROD_IT_NUM='800326893';
SELECT * FROM BBG_RA_ITEM_LOC_D T WHERE T.CURRENT_FLG='Y' AND T.NBO='Y' AND T.ITEM='800026528';
SELECT * FROM BBG_RA_ITEM_LOC_SUPP_D T WHERE T.ITEM='800026528' AND T.REF_NO2='N';
SELECT COUNT(*) FROM BBG_RA_ITEM_LOC_D WHERE NBO IS  NULL;
SELECT COUNT(*) FROM BBG_RA_ITEM_LOC_D WHERE CURRENT_FLG='Y' AND NBO IS NOT NULL; 
SELECT COUNT(*) FROM BBG_RA_ITEM_LOC_D WHERE NBO IS NOT NULL;
SELECT * FROM BBG_RA_ITEM_LOC_D;
SELECT * FROM BBG_RA_ITEM_LOC_SUPP_D;

SELECT * FROM BBG_RA_ITEM_LOC_D WHERE ITEM='700002461';
SELECT * FROM CMX_ITEM_LOC_INFO@RA_RMS_DBLINK WHERE ITEM='700002461';

SELECT COUNT(*) FROM CMX_ITEM_LOC_INFO@RA_RMS_DBLINK WHERE NBO IS NULL;

--订货状态:BBG_RA_ITEM_LOC_SUPP_D.REF_N02
SELECT T.ITEM,T.LOC
FROM BBG_RA_ITEM_LOC_SUPP_D T 
WHERE T.CURRENT_FLG='Y' AND T.REF_NO2='Y'
GROUP BY  T.ITEM,T.LOC
HAVING COUNT(T.SUPPLIER)>1 ;

1	800410944	120162
2	800035199	120162
3	800391519	120001
4	800044541	120001
5	800067067	120140
6	800029550	120153
7	800024889	120138
8	800027465	120138


SELECT * FROM BBG_RA_ITEM_LOC_SUPP_D T WHERE T.ITEM='800410944' AND T.LOC='120162'



