--删除BBG_RA_SLSTOT_LC_DY_A数据
DELETE RADM.BBG_RA_CUST_LC_DY_A T
 WHERE T.DT_WID BETWEEN 120130101000 AND 120130507000;
COMMIT;
--建立临时表
CREATE TABLE RADM.JIN_SALEDETAIL_TRX AS
SELECT SAD.SD0101, SAD.SHOPID, SAD.SD0106, SAD.SD0109, SUM(AMT) AMT
  FROM RADM.SALEDETAIL SAD
 WHERE SAD.SD0101 BETWEEN 20130101 AND 20130507
 GROUP BY SAD.SD0101, SAD.SHOPID, SAD.SD0106, SAD.SD0109;
--创建门店来客数视图--2013.5.8之前
CREATE MATERIALIZED VIEW RADM.BBG_RA_CUST_LC_DY_HIST_FV AS
  SELECT HIS.DT_WID, HIS.ORG_NUM, COUNT(HIS.SLS_TRX_ID) BBG_CUSTOMER_COUNT
    FROM (SELECT SD.SD0101 || SD.SHOPID || SD.SD0109 || SD.SD0106 SLS_TRX_ID,
                 '1' || SD.SD0101 || '000' DT_WID,
                 ORG.ORG_NUM
            FROM RADM.JIN_SALEDETAIL_TRX SD,
                 RABATCHER.W_INT_ORG_D_RTL_TMP ORG
           WHERE SUBSTR(SD.SHOPID, 2, 2) || SUBSTR(SD.SHOPID, 1, 1) ||
                 SUBSTR(SD.SHOPID, 4, 3) = ORG.ORG_NUM
             AND SD.SD0101 BETWEEN 20130101 AND 20130507) HIS
   GROUP BY HIS.DT_WID, HIS.ORG_NUM;
	 
	 
--创建门店来客数视图--2013.5.8之后
CREATE MATERIALIZED VIEW RADM.BBG_RA_CUST_LC_DY_HIST_FV AS
  SELECT DT_WID, ORG_NUM, COUNT(SLS_TRX_ID) BBG_CUSTOMER_COUNT
    FROM (SELECT DISTINCT T.DT_WID, G.ORG_NUM, T.SLS_TRX_ID
            FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F T,
                 RABATCHER.W_INT_ORG_D_RTL_TMP G
           WHERE T.ORG_WID = G.ORG_WID
             AND T.DT_WID BETWEEN 120140116000 AND 120140116000)
   GROUP BY DT_WID, ORG_NUM
   ORDER BY DT_WID, ORG_NUM;
	 
DROP MATERIALIZED VIEW RADM.BBG_RA_CUST_LC_DY_HIST_FV;

SELECT * FROM RADM.BBG_RA_CUST_LC_DY_HIST_FV;

--MERGE BBG_RA_CUST_LC_DY_A表 
MERGE /*+APPEND*/
INTO RADM.BBG_RA_CUST_LC_DY_A T
USING (SELECT /*+APPEND*/
        D.ORG_WID,
        DH.ORG_LC_WID,
        DH.ORG_SCD1_WID,
        HIST.DT_WID,
        HIST.ORG_NUM || '~' ||
        TO_CHAR(W_MCAL_DAY_D.MCAL_DAY_DT,
                'DD-MON-YY',
                'NLS_DATE_LANGUAGE = American') INTEGRATION_ID,
        HIST.BBG_CUSTOMER_COUNT
         FROM RADM.BBG_RA_CUST_LC_DY_HIST_FV HIST,
              RABATCHER.W_INT_ORG_D_RTL_TMP  D,
              RABATCHER.W_INT_ORG_DH_RTL_TMP DH,
              RADM.W_MCAL_DAY_D
        WHERE HIST.ORG_NUM = D.ORG_NUM
          AND D.ORG_SCD1_WID = DH.ORG_SCD1_WID
          AND HIST.DT_WID = W_MCAL_DAY_D.ROW_WID
             --门店区域变更后加上此条件
          AND TO_DATE(SUBSTR(HIST.DT_WID, 2, 8), 'YYYYMMDD') BETWEEN
              DH.EFFECTIVE_FROM_DT AND DH.EFFECTIVE_TO_DT
          /*AND DH.CURRENT_FLG = 'Y'*/) S
ON (T.DT_WID = S.DT_WID AND T.ORG_WID = S.ORG_WID /*AND T.ORG_DH_WID = S.ORG_LC_WID AND T.ORG_SCD1_WID = S.ORG_SCD1_WID*/
)
WHEN MATCHED THEN
  UPDATE
     SET T.Bbg_Customer_Count = S.BBG_CUSTOMER_COUNT,
         T.W_UPDATE_DT        = SYSDATE
WHEN NOT MATCHED THEN
  INSERT
    (T.ROW_WID,
     T.ORG_WID,
     T.ORG_DH_WID,
     T.ORG_SCD1_WID,
     T.DT_WID,
     T.DATASOURCE_NUM_ID,
     T.INTEGRATION_ID,
     T.W_INSERT_DT,
     T.W_UPDATE_DT,
     T.BBG_CUSTOMER_COUNT,
     T.BBG_SERVICE_SATISFACTION)
  VALUES
    (RADM.BBG_RA_CUST_LC_DY_A_SEQ.NEXTVAL,
     S.ORG_WID,
     S.ORG_LC_WID,
     S.ORG_SCD1_WID,
     S.DT_WID,
     1,
     S.INTEGRATION_ID,
     SYSDATE,
     SYSDATE,
     S.BBG_CUSTOMER_COUNT,
     NULL);


