--1.客流
SELECT * FROM BBG_RA_CUST_LC_DY_A T ORDER BY DT_WID;
DROP MATERIALIZED VIEW RADM.BBG_RA_CUST_LC_DY_HIST_FV;
--海波龙系统从2011年1月开始取数
--创建物化视图(表名和之前的不变)
--DT_WID,ORG_NUM,BBG_CUSTOMER_COUNT
--SALEDETAIL小票号通过SD0106和SD0109
CREATE MATERIALIZED VIEW RADM.BBG_RA_CUST_LC_DY_HIST_FV AS
	SELECT DT_WID, ORG_NUM, COUNT(BBG_TRX_ID) BBG_CUSTOMER_COUNT
		FROM (SELECT DISTINCT '1' || SD.SD0101 || '000' DT_WID,
													SUBSTR(SD.SHOPID, 2, 2) || SUBSTR(SD.SHOPID, 1, 1) ||
													SUBSTR(SD.SHOPID, 4, 3) ORG_NUM,
													SD.SD0109 || SD.SD0106 BBG_TRX_ID
						FROM RADM.SALEDETAIL SD
					 WHERE SD.SD0101 BETWEEN '20110101' AND '20111231')
	 GROUP BY DT_WID, ORG_NUM
	 ORDER BY DT_WID, ORG_NUM;

--直接插入BBG_RA_CUST_LC_DY_A(2011年1月1日~~2012年12月31日)
INSERT INTO RADM.BBG_RA_CUST_LC_DY_A
	(ROW_WID,
	 ORG_WID,
	 ORG_DH_WID,
	 ORG_SCD1_WID,
	 DT_WID,
	 DATASOURCE_NUM_ID,
	 INTEGRATION_ID,
	 W_INSERT_DT,
	 W_UPDATE_DT,
	 BBG_CUSTOMER_COUNT)
	SELECT BBG_RA_CUST_LC_DY_A_SEQ.NEXTVAL,
				 D.ORG_WID,
				 DH.ORG_LC_WID,
				 DH.ORG_SCD1_WID,
				 HIST.DT_WID,
				 1,
				 HIST.ORG_NUM || '~' ||
				 TO_CHAR(W_MCAL_DAY_D.MCAL_DAY_DT,
								 'DD-MON-YY',
								 'NLS_DATE_LANGUAGE = American') INTEGRATION_ID,
				 SYSDATE,
				 SYSDATE,
				 HIST.BBG_CUSTOMER_COUNT
		FROM RADM.BBG_RA_CUST_LC_DY_HIST_FV HIST,
				 RABATCHER.W_INT_ORG_D_RTL_TMP  D,
				 RABATCHER.W_INT_ORG_DH_RTL_TMP DH,
				 RADM.W_MCAL_DAY_D
	 WHERE HIST.ORG_NUM = D.ORG_NUM
		 AND HIST.ORG_NUM = DH.ORG_NUM
		 AND HIST.DT_WID = W_MCAL_DAY_D.ROW_WID;

--客流SQL：
SELECT '' PKEY,
			 ORG.ORG_NUM SHPCODE,
			 '客流' ACCOUNT_CODE,
			 '' BRANCH_CODE,
			 '' SEG01_CODE,
			 '' SEG02_CODE,
			 '' SEG03_CODE,
			 A.YEAR,
			 A.PERIOD,
			 A.BUSINESSDATA,
			 SYSDATE MODIFYTIME
	FROM (SELECT SUBSTR(A.DT_WID, 2, 4) YEAR,
							 SUBSTR(A.DT_WID, 6, 2) PERIOD,
							 A.ORG_WID,
							 SUM(A.BBG_CUSTOMER_COUNT) BUSINESSDATA
					FROM BBG_RA_CUST_LC_DY_A A
				 GROUP BY SUBSTR(A.DT_WID, 2, 4), SUBSTR(A.DT_WID, 6, 2), A.ORG_WID) A,
			 W_INT_ORG_D ORG
 WHERE ORG.ROW_WID(+) = A.ORG_WID
 ORDER BY A.YEAR, A.PERIOD, ORG.ORG_NUM;

----------------------------------------------------------------------------------------------------------- 
--2.平均客单(含税)   
--平均客单SQL   
SELECT '' PKEY,
			 ORG.ORG_NUM SHPCODE,
			 '平均客单' ACCOUNT_CODE,
			 '' BRANCH_CODE,
			 '' SEG01_CODE,
			 '' SEG02_CODE,
			 '' SEG03_CODE,
			 SLS.YEAR,
			 SLS.PERIOD,
			 SLS.AMT / CUST.CNT BUSINESSDATA,
			 SYSDATE MODIFYTIME
	FROM (SELECT SUBSTR(A.DT_WID, 2, 4) YEAR,
							 SUBSTR(A.DT_WID, 6, 2) PERIOD,
							 A.ORG_WID,
							 SUM(A.BBG_CUSTOMER_COUNT) CNT
					FROM BBG_RA_CUST_LC_DY_A A
				 GROUP BY SUBSTR(A.DT_WID, 2, 4), SUBSTR(A.DT_WID, 6, 2), A.ORG_WID) CUST,
			 (SELECT SUBSTR(S.MN_WID, 1, 4) YEAR,
							 SUBSTR(S.MN_WID, 5, 2) PERIOD,
							 S.ORG_WID,
							 SUM(S.SLS_AMT_LCL - S.RET_AMT_LCL) AMT
					FROM W_RTL_SLS_LC_MN_A S
				 GROUP BY SUBSTR(S.MN_WID, 1, 4), SUBSTR(S.MN_WID, 5, 2), S.ORG_WID) SLS,
			 W_INT_ORG_D ORG
 WHERE ORG.ROW_WID(+) = CUST.ORG_WID
	 AND SLS.ORG_WID(+) = CUST.ORG_WID
	 AND SLS.YEAR = CUST.YEAR
	 AND SLS.PERIOD = CUST.PERIOD
 ORDER BY SLS.YEAR, SLS.PERIOD, ORG.ORG_NUM;

----------------------------------------------------------------------------------------------------------------------------
--3.大类客流
--说明:SALEDETAIL.SD0102为商品编码,800000000+则为item_master.item,融通系统的商品信息表为GOODS
--大类客流和大类客单分二部分取数:历史的(2011.01.01~2013.05.07)由SALEDETAIL取数,新系统(2013.05.08之后)
--saledetail取大类来客数,直接使用cateid前二位做大类编码(物化视图)
CREATE MATERIALIZED VIEW RADM.BBG_RA_CUST_LC_DP_MN_HIST_V AS
	SELECT B.ORG_NUM, B.DAY, B.DP_NUM, COUNT(B.BBG_TRX_ID) CUST
		FROM (SELECT A.ORG_NUM, SUBSTR(A.DAY, 1, 6) DAY, A.DP_NUM, A.BBG_TRX_ID
						FROM (SELECT DISTINCT SUBSTR(S.SHOPID, 2, 2) ||
																	SUBSTR(S.SHOPID, 1, 1) ||
																	SUBSTR(S.SHOPID, 4, 3) ORG_NUM,
																	S.SD0101 DAY,
																	SUBSTR(S.CATEID, 1, 2) DP_NUM,
																	S.SD0109 || S.SD0106 BBG_TRX_ID
										FROM RADM.SALEDETAIL S
									 WHERE S.SD0101 BETWEEN '20110101' AND '20130507') A) B
	 GROUP BY B.ORG_NUM, B.DAY, B.DP_NUM;
--大类客流SQL
SELECT PKEY,
			 SHPCODE,
			 ACCOUNT_CODE,
			 BRANCH_CODE,
			 SEG01_CODE,
			 SEG02_CODE,
			 SEG03_CODE,
			 YEAR,
			 PERIOD,
			 SUM(BUSINESSDATA),
			 MODIFYTIME
	FROM (
				--SALEDETAIL取数(历史数据)
				SELECT '' PKEY,
								A.ORG_NUM SHPCODE,
								'大类客流' ACCOUNT_CODE,
								A.DP_NUM BRANCH_CODE,
								'' SEG01_CODE,
								'' SEG02_CODE,
								'' SEG03_CODE,
								SUBSTR(A.DAY, 1, 4) YEAR,
								SUBSTR(A.DAY, 5, 2) PERIOD,
								A.CUST BUSINESSDATA,
								SYSDATE MODIFYTIME
					FROM RADM.BBG_RA_CUST_LC_DP_MN_HIST_V A
				UNION ALL
				--BBG_RA_CUST_DP_LC_DY_A取数(新系统数据)
				SELECT '' PKEY,
								B.ORG_NUM SHPCODE,
								'大类客流' ACCOUNT_CODE,
								B.LVL6ANC_PRODCAT_ID BRANCH_CODE,
								'' SEG01_CODE,
								'' SEG02_CODE,
								'' SEG03_CODE,
								SUBSTR(B.DT, 1, 4) YEAR,
								SUBSTR(B.DT, 5, 2) PERIOD,
								B.CUST BUSINESSDATA,
								SYSDATE MODIFYTIME
					FROM (SELECT ORG.ORG_NUM, CATE.LVL6ANC_PRODCAT_ID, A.DT, A.CUST
									 FROM (SELECT T.ORG_WID,
																T.PROD_DH_WID,
																SUBSTR(T.DT_WID, 2, 6) DT,
																SUM(T.BBG_CUSTOMER_COUNT) CUST
													 FROM RADM.BBG_RA_CUST_DP_LC_DY_A T
													GROUP BY T.ORG_WID,
																	 T.PROD_DH_WID,
																	 SUBSTR(T.DT_WID, 2, 6)) A,
												W_INT_ORG_D ORG,
												W_PROD_CAT_DH CATE
									WHERE A.ORG_WID = ORG.ROW_WID
										AND A.PROD_DH_WID = CATE.ROW_WID
										AND CATE.LEVEL_NAME = 'DEPT') B) TOTAL
 GROUP BY PKEY,
					SHPCODE,
					ACCOUNT_CODE,
					BRANCH_CODE,
					SEG01_CODE,
					SEG02_CODE,
					SEG03_CODE,
					YEAR,
					PERIOD,
					MODIFYTIME
 ORDER BY YEAR, PERIOD, SHPCODE, BRANCH_CODE;

--4.
--大类平均客单SQL
SELECT '' PKEY,
			 SLS.ORG_NUM SHPCODE,
			 '大类平均客单' ACCOUNT_CODE,
			 SLS.DP_NUM BRANCH_CODE,
			 '' SEG01_CODE,
			 '' SEG02_CODE,
			 '' SEG03_CODE,
			 SLS.YEAR,
			 SLS.PERIOD,
			 SLS.AMT / CUST.CUST BUSINESSDATA,
			 SYSDATE MODIFYTIME
	FROM (SELECT TAL.ORG_NUM,
							 SUBSTR(TAL.DAY, 1, 4) YEAR,
							 SUBSTR(TAL.DAY, 5, 2) PERIOD,
							 TAL.DP_NUM,
							 SUM(TAL.CUST) CUST
					FROM (SELECT V.ORG_NUM, V.DAY, V.DP_NUM, V.CUST
									FROM RADM.BBG_RA_CUST_LC_DP_MN_HIST_V V
								UNION ALL
								SELECT ORG.ORG_NUM,
											 A.DAY,
											 CATE.LVL6ANC_PRODCAT_ID DP_NUM,
											 A.CUST
									FROM (SELECT T.ORG_WID,
															 T.PROD_DH_WID,
															 SUBSTR(T.DT_WID, 2, 6) DAY,
															 SUM(T.BBG_CUSTOMER_COUNT) CUST
													FROM RADM.BBG_RA_CUST_DP_LC_DY_A T
												 GROUP BY T.ORG_WID,
																	T.PROD_DH_WID,
																	SUBSTR(T.DT_WID, 2, 6)) A,
											 W_INT_ORG_D ORG,
											 W_PROD_CAT_DH CATE
								 WHERE A.ORG_WID = ORG.ROW_WID
									 AND A.PROD_DH_WID = CATE.ROW_WID
									 AND CATE.LEVEL_NAME = 'DEPT') TAL
				 GROUP BY TAL.ORG_NUM, TAL.DAY, TAL.DP_NUM) CUST, --大类来客
			 (SELECT SUBSTR(S.MN_WID, 1, 4) YEAR,
							 SUBSTR(S.MN_WID, 5, 2) PERIOD,
							 ORG.ORG_NUM,
							 CAT.LVL6ANC_PRODCAT_ID DP_NUM,
							 SUM(S.SLS_AMT_LCL - S.RET_AMT_LCL) AMT
					FROM W_RTL_SLS_DP_LC_MN_A S, W_INT_ORG_D ORG, W_PROD_CAT_DH CAT
				 WHERE S.ORG_WID = ORG.ROW_WID
					 AND S.PROD_DH_WID = CAT.ROW_WID
					 AND CAT.LEVEL_NAME = 'DEPT'
				 GROUP BY SUBSTR(S.MN_WID, 1, 4),
									SUBSTR(S.MN_WID, 5, 2),
									ORG.ORG_NUM,
									CAT.LVL6ANC_PRODCAT_ID) SLS --大类销售
 WHERE CUST.ORG_NUM = SLS.ORG_NUM
	 AND CUST.YEAR = SLS.YEAR
	 AND CUST.PERIOD = SLS.PERIOD
	 AND SLS.DP_NUM = CUST.DP_NUM
 ORDER BY SLS.YEAR, SLS.PERIOD, SLS.ORG_NUM, SLS.DP_NUM;

--现系统中大类来客数算法.
SELECT * FROM BBG_RA_CUST_DP_LC_DY_FV;

SELECT * FROM BBG_RA_CUST_DP_LC_DY_A T ORDER BY T.DT_WID;
SELECT * FROM RADM.SALEDETAIL T;
SELECT * FROM rabatcher.W_PRODUCT_D_RTL_TMP;
--
--历史来客数
SELECT * FROM RADM.BBG_RA_CUST_LC_DP_MN_HIST_V;
--新系统来客数
SELECT ORG.ORG_NUM, A.DAY, CATE.LVL6ANC_PRODCAT_ID DP_NUM, A.CUST
	FROM (SELECT T.ORG_WID,
							 T.PROD_DH_WID,
							 SUBSTR(T.DT_WID, 2, 6) DAY,
							 SUM(T.BBG_CUSTOMER_COUNT) CUST
					FROM RADM.BBG_RA_CUST_DP_LC_DY_A T
				 GROUP BY T.ORG_WID, T.PROD_DH_WID, SUBSTR(T.DT_WID, 2, 6)) A,
			 W_INT_ORG_D ORG,
			 W_PROD_CAT_DH CATE
 WHERE A.ORG_WID = ORG.ROW_WID
	 AND A.PROD_DH_WID = CATE.ROW_WID
	 AND CATE.LEVEL_NAME = 'DEPT';
--
SELECT TAL.ORG_NUM, TAL.DAY, TAL.DP_NUM, SUM(TAL.CUST) CUST
	FROM (SELECT V.ORG_NUM, V.DAY, V.DP_NUM, V.CUST
					FROM RADM.BBG_RA_CUST_LC_DP_MN_HIST_V V
				UNION ALL
				--新系统来客数
				SELECT ORG.ORG_NUM, A.DAY, CATE.LVL6ANC_PRODCAT_ID DP_NUM, A.CUST
					FROM (SELECT T.ORG_WID,
											 T.PROD_DH_WID,
											 SUBSTR(T.DT_WID, 2, 6) DAY,
											 SUM(T.BBG_CUSTOMER_COUNT) CUST
									FROM RADM.BBG_RA_CUST_DP_LC_DY_A T
								 GROUP BY T.ORG_WID, T.PROD_DH_WID, SUBSTR(T.DT_WID, 2, 6)) A,
							 W_INT_ORG_D ORG,
							 W_PROD_CAT_DH CATE
				 WHERE A.ORG_WID = ORG.ROW_WID
					 AND A.PROD_DH_WID = CATE.ROW_WID
					 AND CATE.LEVEL_NAME = 'DEPT') TAL
 GROUP BY TAL.ORG_NUM, TAL.DAY, TAL.DP_NUM;
--销售
SELECT SUBSTR(S.MN_WID, 1, 4) YEAR,
			 SUBSTR(S.MN_WID, 5, 2) PERIOD,
			 S.ORG_WID,
			 S.PROD_DH_WID,
			 SUM(S.SLS_AMT_LCL - S.RET_AMT_LCL) AMT
	FROM W_RTL_SLS_DP_LC_MN_A S
 GROUP BY SUBSTR(S.MN_WID, 1, 4),
					SUBSTR(S.MN_WID, 5, 2),
					S.ORG_WID,
					S.PROD_DH_WID;

SELECT * FROM W_RTL_SLS_DP_LC_MN_A T ORDER BY T.MN_WID;
