--插入W_PRODUCT_DS中间表之后，执行SIL_ItemDimension
INSERT INTO W_PRODUCT_DS 
(PRODUCT_TYPE_CODE,UOM_CODE,SRC_EFF_FROM_DT,DATASOURCE_NUM_ID,INTEGRATION_ID,PROD_CAT5,PACK_FLG,PROD_CAT5_AS_WAS,PROD_NUM,BBG_ITEM_BRAND,BBG_ITEM_UOM_DESC)
SELECT ITEM.ITEM_NUMBER_TYPE,ITEM.STANDARD_UOM,DATE'2013-09-02',1/*DATASOURCE_NUM_ID*/,
ITEM.ITEM,DIVISION.DIVISION||'~'||GROUPS.GROUP_NO||'~'||ITEM.DEPT||'~'||ITEM.CLASS||'~'||ITEM.SUBCLASS, /*PROD_CAT5*/
ITEM.PACK_IND,/*PACK_FLG*/ 
DIVISION.DIVISION||'~'||GROUPS.GROUP_NO||'~'||ITEM.DEPT||'~'||ITEM.CLASS||'~'||ITEM.SUBCLASS,/*PROD_CAT5_AS_WAS*/
ITEM.ITEM /*PROD_NUM*/,
BBG_RA_ITEM_CUSTOM_V.BBG_ITEM_BRAND /*BBG_ITEM_BRAND*/,
UOM_CLASS.UOM_DESC /*BBG_ITEM_UOM_DESC*/
FROM ITEM_MASTER@RA_RMS_DBLINK ITEM,
     DIVISION@RA_RMS_DBLINK DIVISION,
     GROUPS@RA_RMS_DBLINK GROUPS,
     BBG_RA_ITEM_CUSTOM_V@RA_RMS_DBLINK BBG_RA_ITEM_CUSTOM_V,
     UOM_CLASS@RA_RMS_DBLINK UOM_CLASS,
     DEPS@RA_RMS_DBLINK DEPS
WHERE GROUPS.DIVISION=DIVISION.DIVISION
 AND ITEM.STANDARD_UOM=UOM_CLASS.UOM
 AND DEPS.GROUP_NO=GROUPS.GROUP_NO
 AND ITEM.DEPT=DEPS.DEPT
 AND ITEM.ITEM=BBG_RA_ITEM_CUSTOM_V.ITEM
 AND ITEM.STATUS='A'
/* AND (ITEM.PACK_IND='N' OR (ITEM.PACK_IND='Y' AND NOT EXISTS (SELECT 'X'
            FROM QUALIFY(V_PACKSKU_QTY) V_PACKSKU1,QUALIFY(ITEM_MASTER) IM1
            WHERE V_PACKSKU1.PACK_NO = ITEM.ITEM 
            AND V_PACKSKU1.ITEM = IM1.ITEM
            AND IM1.ITEM_XFORM_IND = 'Y'
            AND ROWNUM = 1)))*/
 AND ITEM.ITEM_XFORM_IND!='Y'
 --AND ITEM.ITEM like '1006%'
 AND NOT EXISTS(SELECT 1 FROM W_PRODUCT_D T WHERE T.PROD_NUM=ITEM.ITEM /*AND T.PROD_NUM LIKE '1006%'*/);


SELECT COUNT(*) FROM W_PRODUCT_DS 
TRUNCATE TABLE W_PRODUCT_DS;

SELECT * FROM W_RTL_SLS_TRX_IT_LC_DY_FS;
SELECT * FROM RABATCHER.W_RTL_SLS_IT_LC_DY_TMP;
SELECT * FROM W_RTL_SLS_TRX_IT_LC_DY_F;

SELECT * FROM RA_RMS.BBG_XTERN_RDWT@RA_RMS_DBLINK WHERE BUSINESS_DT=DATE'2013-09-02' ;
SELECT * FROM RA_RMS.BBG_XTERN_RDWT_HIST@RA_RMS_DBLINK WHERE BUSINESS_DT='20130902' ;


TRUNCATE TABLE RADM.C_LOAD_DATES;









 


