--门店来客数视图--BBG_XTERN_RDWT_HIST
CREATE MATERIALIZED VIEW RADM.BBG_RA_CUST_LC_DY_HIST_FV AS
  SELECT '1' || BUSINESS_DT || '000' DT_WID,
         SUBSTR(LOCATION, 5, 6) ORG_NUM,
         COUNT(TRANSACTION_HEADER_NO) BBG_CUSTOMER_COUNT
    FROM (SELECT T.BUSINESS_DT,
                 T.LOCATION,
                 T.TRANSACTION_HEADER_NO,
                 MAX(T.REASON_CD)
            FROM RA_RMS.BBG_XTERN_RDWT_HIST@RA_RMS_DBLINK T
           WHERE T.BUSINESS_DT BETWEEN '20131201' AND '20140131'
           GROUP BY T.BUSINESS_DT, T.LOCATION, T.TRANSACTION_HEADER_NO)
   GROUP BY BUSINESS_DT, LOCATION
   ORDER BY '1' || BUSINESS_DT || '000', SUBSTR(LOCATION, 5, 6);
	 
--门店来客数视图--W_RTL_SLS_TRX_IT_LC_DY_F 有问题
CREATE MATERIALIZED VIEW RADM.BBG_RA_CUST_LC_DY_HIST_FV AS
  SELECT DT_WID, ORG_NUM, COUNT(TRANSACTION_HEADER_NO) BBG_CUSTOMER_COUNT
    FROM (SELECT T.DT_WID, G.ORG_NUM, T.SLS_TRX_ID, 1 TRANSACTION_HEADER_NO
            FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F T,
                 RABATCHER.W_INT_ORG_D_RTL_TMP G
           WHERE T.ORG_WID = G.ORG_WID
             AND T.DT_WID BETWEEN 120131201000 AND 120140131000)
   GROUP BY DT_WID, ORG_NUM
   ORDER BY DT_WID, ORG_NUM;
	 
--门店来客数视图--2013.5.8之前
CREATE MATERIALIZED VIEW RADM.BBG_RA_CUST_LC_DY_HIST_FV AS
SELECT HIS.DT_WID, HIS.ORG_NUM, COUNT(HIS.SLS_TRX_ID) BBG_CUSTOMER_COUNT
  FROM (SELECT SD.SD0101 || SD.SHOPID || SD.SD0109 || SD.SD0106 SLS_TRX_ID,
               '1' || SD.SD0101 || '000' DT_WID,
               ORG.ORG_NUM
          FROM (SELECT SAD.SD0101, SAD.SHOPID, SAD.SD0106, SAD.SD0109
                  FROM RADM.SALEDETAIL SAD
                 WHERE SAD.SD0101 BETWEEN 20130101 AND 20130507) SD,
               RABATCHER.W_INT_ORG_D_RTL_TMP ORG
         WHERE SUBSTR(SD.SHOPID, 2, 2) || SUBSTR(SD.SHOPID, 1, 1) ||
               SUBSTR(SD.SHOPID, 4, 3) = ORG.ORG_NUM
           AND SD.SD0101 BETWEEN 20130101 AND 20130507) HIS
 GROUP BY HIS.DT_WID, HIS.ORG_NUM;
	 
DROP MATERIALIZED VIEW RADM.BBG_RA_CUST_LC_DY_HIST_FV;

SELECT * FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F T;
SELECT T.DT_WID, SUM(T.BBG_CUSTOMER_COUNT)
  FROM BBG_RA_CUST_LC_DY_HIST_FV T
 WHERE SUBSTR(T.DT_WID, 2, 6) = 201312
 GROUP BY T.DT_WID;
 
 SELECT * FROM RADM.SALEDETAIL ;
