/*
HYXFJL表字段说明:
XFJLID:消费记录ID
SHDM:
MDID:门店ID
SKTNO:收款台NO
JLBH:
DJLX:
XFJLID_OLD:
HYID:会员ID
HYID_FQ:
HYID_TQ:
SKYDM:收款员代码
XFSJ:消费时间
JZRQ:记账日期
CRMJZRQ:CRM记账日期
SCSJ:
XSSL:
JE:金额
ZK:
ZK_HY:
JFDYDBH:
CZJE:
JF:
BJ_HTBSK:
XFRQ_FQ:
JFBS:
*/

--检查已经导入的日期数据
SELECT MAX(DT_WID) FROM BBG_RA_VIPSLS_LC_DY_A;
SELECT MAX(XFSJ) FROM RADM.BBG_RA_VIPSLS_LC_DY_FV;
select max(jzrq) from HYXFJL t;

select distinct dt_wid
	from BBG_RA_VIPSLS_LC_DY_A t
 where t.dt_wid > '1' || to_char(sysdate - 20, 'YYYYMMDD') || '000'
 ORDER BY DT_WID;
select distinct XFSJ
	from BBG_RA_VIPSLS_LC_DY_FV t
 where t.XFSJ > sysdate - 20
 ORDER BY XFSJ;
select distinct dt_wid
	from BBG_RA_VIPSLS_LC_DY_FV2 t
 where t.dt_wid > '1' || to_char(sysdate - 20, 'YYYYMMDD') || '000'
 ORDER BY DT_WID;
select distinct CRMjzrq from HYXFJL t where t.CRMjzrq > sysdate - 10 ORDER BY CRMjzrq;
--由HYXFJL表汇总出会员销售金额和来客数BBG_RA_VIPSLS_LC_DY_FV
CREATE MATERIALIZED VIEW RADM.BBG_RA_VIPSLS_LC_DY_FV REFRESH FORCE ON DEMAND START
	WITH TO_DATE(CONCAT(TO_CHAR(SYSDATE,
	 'DD-MM-YYYY'),
	 ' 04:30:00'),
	 'DD-MM-YYYY HH24:MI:SS') NEXT TO_DATE(CONCAT(TO_CHAR(SYSDATE + 1,
	 'DD-MM-YYYY'),
	 ' 04:30:00'),
	 'DD-MM-YYYY HH24:MI:SS') AS
	SELECT T.MDID,
				 TO_DATE(TO_CHAR(T.CRMJZRQ, 'YYYY-MM-DD'), 'YYYY-MM-DD') XFSJ,
				 SUM(T.JE) JE,
				 COUNT(*) BBG_CUSTOMER_COUNT
		FROM RADM.HYXFJL T
	 WHERE TO_DATE(TO_CHAR(T.JZRQ, 'YYYY-MM-DD'), 'YYYY-MM-DD') >
				 TO_DATE(TO_CHAR(SYSDATE - 10, 'YYYY-MM-DD'), 'YYYY-MM-DD')
	 GROUP BY T.MDID, TO_DATE(TO_CHAR(T.CRMJZRQ, 'YYYY-MM-DD'), 'YYYY-MM-DD');

DROP MATERIALIZED VIEW RADM.BBG_RA_VIPSLS_LC_DY_FV;

--关联mddy表，转换org_num 视图BBG_RA_VIPSLS_LC_DY_FV2
CREATE OR REPLACE VIEW BBG_RA_VIPSLS_LC_DY_FV2 AS
	SELECT '1' || TO_CHAR(FV.XFSJ, 'YYYYMMDD') || '000' DT_WID,
				 SUBSTR(MD.MDDM, 3, 6) ORG_NUM,
				 FV.JE VIP_SALES_AMT,
				 FV.BBG_CUSTOMER_COUNT VIP_CUSTOMER_COUNT
		FROM BBG_RA_VIPSLS_LC_DY_FV FV, MDDY MD
	 WHERE FV.MDID = MD.MDID
		 AND MD.SHDM = 'CS'
	 ORDER BY '1' || TO_CHAR(FV.XFSJ, 'YYYYMMDD') || '000',
						SUBSTR(MD.MDDM, 3, 6);

--创建会员销售汇总表
CREATE TABLE "RADM"."BBG_RA_VIPSLS_LC_DY_A"("ROW_WID" NUMBER(10, 0)
																						NOT NULL ENABLE,
																						"ORG_WID" NUMBER(10, 0)
																						NOT NULL ENABLE,
																						"ORG_DH_WID" NUMBER(10, 0)
																						NOT NULL ENABLE,
																						"ORG_SCD1_WID" NUMBER(10, 0)
																						NOT NULL ENABLE,
																						"DT_WID" NUMBER(15, 0) NOT NULL
																						ENABLE,
																						"W_INSERT_DT" DATE,
																						"W_UPDATE_DT" DATE,
																						"VIP_SALES_AMT" NUMBER(35, 20),
																						"VIP_CUSTOMER_COUNT"
																						NUMBER(20, 4),
																						"BBG_REFERENCE_DO1"
																						VARCHAR2(250),
																						"BBG_REFERENCE_DO2"
																						VARCHAR2(250),
																						"BBG_REFERENCE_DO3"
																						VARCHAR2(250),
																						"BBG_REFERENCE_FO1"
																						NUMBER(20, 4),
																						"BBG_REFERENCE_FO2"
																						NUMBER(20, 4),
																						"BBG_REFERENCE_FO3"
																						NUMBER(20, 4)) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 65536 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE
																																																																																																																																													DEFAULT
																																																																																																																																													CELL_FLASH_CACHE
																																																																																																																																													DEFAULT) TABLESPACE "RETAIL_DATA";

--创建序列用于BBG_RA_VIPSLS_LC_DY_A表
create sequence BBG_RA_VIPSLS_LC_DY_A_SEQ increment by 1 start
	with 1 maxvalue 999999999;
DROP SEQUENCE BBG_RA_VIPSLS_LC_DY_A_SEQ;
--会员汇总数据插入BBG_RA_VIPSLS_LC_DY_A
INSERT INTO RADM.BBG_RA_VIPSLS_LC_DY_A
	(ROW_WID,
	 ORG_WID,
	 ORG_DH_WID,
	 ORG_SCD1_WID,
	 DT_WID,
	 W_INSERT_DT,
	 W_UPDATE_DT,
	 VIP_SALES_AMT,
	 VIP_CUSTOMER_COUNT)
	SELECT BBG_RA_VIPSLS_LC_DY_A_SEQ.NEXTVAL,
				 D.ORG_WID,
				 DH.ORG_LC_WID,
				 DH.ORG_SCD1_WID,
				 VPS.DT_WID,
				 SYSDATE,
				 SYSDATE,
				 VPS.VIP_SALES_AMT,
				 VPS.VIP_CUSTOMER_COUNT
		FROM RADM.BBG_RA_VIPSLS_LC_DY_FV2   VPS,
				 RABATCHER.W_INT_ORG_D_RTL_TMP  D,
				 RABATCHER.W_INT_ORG_DH_RTL_TMP DH,
				 RADM.W_MCAL_DAY_D
	 WHERE VPS.ORG_NUM = D.ORG_NUM
		 AND VPS.ORG_NUM = DH.ORG_NUM
		 AND VPS.DT_WID = W_MCAL_DAY_D.ROW_WID;

--
SELECT * FROM BBG_RA_VIPSLS_LC_DY_FV2;
SELECT * FROM BBG_RA_VIPSLS_LC_DY_A;
--MERGE插入数据
MERGE /*+APPEND*/
INTO RADM.BBG_RA_VIPSLS_LC_DY_A T
USING (SELECT /*+APPEND*/
				FV2.DT_WID,
				D.ORG_WID,
				DH.ORG_LC_WID,
				DH.ORG_SCD1_WID,
				FV2.VIP_SALES_AMT,
				FV2.VIP_CUSTOMER_COUNT
				 FROM RADM.BBG_RA_VIPSLS_LC_DY_FV2   FV2,
							RABATCHER.W_INT_ORG_D_RTL_TMP  D,
							RABATCHER.W_INT_ORG_DH_RTL_TMP DH
				WHERE FV2.ORG_NUM = D.ORG_NUM
					AND FV2.ORG_NUM = DH.ORG_NUM
					AND FV2.DT_WID > '1' || TO_CHAR(SYSDATE - 7, 'YYYYMMDD') || '000' --插入日期控制
			 ) S
ON (T.DT_WID = S.DT_WID AND T.ORG_WID = S.ORG_WID AND T.ORG_DH_WID = S.ORG_LC_WID AND T.ORG_SCD1_WID = S.ORG_SCD1_WID)
WHEN MATCHED THEN
	UPDATE
		 SET T.VIP_SALES_AMT      = S.VIP_SALES_AMT,
				 T.VIP_CUSTOMER_COUNT = S.VIP_CUSTOMER_COUNT,
				 T.W_UPDATE_DT        = SYSDATE
WHEN NOT MATCHED THEN
	INSERT
		(T.ROW_WID,
		 T.ORG_WID,
		 T.ORG_DH_WID,
		 T.ORG_SCD1_WID,
		 T.DT_WID,
		 T.W_INSERT_DT,
		 T.W_UPDATE_DT,
		 T.VIP_SALES_AMT,
		 T.VIP_CUSTOMER_COUNT,
		 T.BBG_REFERENCE_DO1,
		 T.BBG_REFERENCE_DO2,
		 T.BBG_REFERENCE_DO3,
		 T.BBG_REFERENCE_FO1,
		 T.BBG_REFERENCE_FO2,
		 T.BBG_REFERENCE_FO3)
	VALUES
		(RADM.BBG_RA_VIPSLS_LC_DY_A_SEQ.NEXTVAL,
		 S.ORG_WID,
		 S.ORG_LC_WID,
		 S.ORG_SCD1_WID,
		 S.DT_WID,
		 SYSDATE,
		 SYSDATE,
		 S.VIP_SALES_AMT,
		 S.VIP_CUSTOMER_COUNT,
		 NULL,
		 NULL,
		 NULL,
		 NULL,
		 NULL,
		 NULL);
		 
--****************************************************************************************************
--会员来客数及销售金额重新处理
--****************************************************************************************************
--清除RADM.BBG_RA_VIPSLS_LC_DY_A指定日期数据
DELETE RADM.BBG_RA_VIPSLS_LC_DY_A T WHERE T.DT_WID BETWEEN 120140801000 AND 120140824000;
COMMIT;
--
DROP MATERIALIZED VIEW RADM.BBG_RA_VIPSLS_LC_DY_FV_FIX;

DROP VIEW RADM.BBG_RA_VIPSLS_LC_DY_FV_FIX2;
--
CREATE MATERIALIZED VIEW RADM.BBG_RA_VIPSLS_LC_DY_FV_FIX AS
	SELECT T.MDID,
				 TO_DATE(TO_CHAR(T.CRMJZRQ, 'YYYY-MM-DD'), 'YYYY-MM-DD') XFSJ,
				 SUM(T.JE) JE,
				 COUNT(*) BBG_CUSTOMER_COUNT
		FROM RADM.HYXFJL T
	 WHERE TO_DATE(TO_CHAR(T.JZRQ, 'YYYY-MM-DD'), 'YYYY-MM-DD') BETWEEN DATE'2014-08-01' AND DATE'2014-08-24'
	 GROUP BY T.MDID, TO_DATE(TO_CHAR(T.CRMJZRQ, 'YYYY-MM-DD'), 'YYYY-MM-DD');
--关联mddy表，转换org_num 视图BBG_RA_VIPSLS_LC_DY_FV2
CREATE OR REPLACE VIEW RADM.BBG_RA_VIPSLS_LC_DY_FV_FIX2 AS
	SELECT '1' || TO_CHAR(FV.XFSJ, 'YYYYMMDD') || '000' DT_WID,
				 SUBSTR(MD.MDDM, 3, 6) ORG_NUM,
				 FV.JE VIP_SALES_AMT,
				 FV.BBG_CUSTOMER_COUNT VIP_CUSTOMER_COUNT
		FROM BBG_RA_VIPSLS_LC_DY_FV_FIX FV, MDDY MD
	 WHERE FV.MDID = MD.MDID
		 AND MD.SHDM = 'CS'
	 ORDER BY '1' || TO_CHAR(FV.XFSJ, 'YYYYMMDD') || '000',
						SUBSTR(MD.MDDM, 3, 6);

--MERGE重新插入数据
MERGE /*+APPEND*/
INTO RADM.BBG_RA_VIPSLS_LC_DY_A T
USING (SELECT /*+APPEND*/
				FV2.DT_WID,
				D.ORG_WID,
				DH.ORG_LC_WID,
				DH.ORG_SCD1_WID,
				FV2.VIP_SALES_AMT,
				FV2.VIP_CUSTOMER_COUNT
				 FROM RADM.BBG_RA_VIPSLS_LC_DY_FV_FIX2   FV2,
							RABATCHER.W_INT_ORG_D_RTL_TMP  D,
							RABATCHER.W_INT_ORG_DH_RTL_TMP DH
				WHERE FV2.ORG_NUM = D.ORG_NUM
					AND D.ORG_SCD1_WID = DH.ORG_SCD1_WID
					AND TO_DATE(SUBSTR(FV2.DT_WID,2,8),'YYYYMMDD') BETWEEN DH.EFFECTIVE_FROM_DT AND DH.EFFECTIVE_TO_DT
					/*AND FV2.DT_WID > '1' || TO_CHAR(SYSDATE - 7, 'YYYYMMDD') || '000' --插入日期控制*/
			 ) S
ON (T.DT_WID = S.DT_WID AND T.ORG_WID = S.ORG_WID AND T.ORG_DH_WID = S.ORG_LC_WID AND T.ORG_SCD1_WID = S.ORG_SCD1_WID)
WHEN MATCHED THEN
	UPDATE
		 SET T.VIP_SALES_AMT      = S.VIP_SALES_AMT,
				 T.VIP_CUSTOMER_COUNT = S.VIP_CUSTOMER_COUNT,
				 T.W_UPDATE_DT        = SYSDATE
WHEN NOT MATCHED THEN
	INSERT
		(T.ROW_WID,
		 T.ORG_WID,
		 T.ORG_DH_WID,
		 T.ORG_SCD1_WID,
		 T.DT_WID,
		 T.W_INSERT_DT,
		 T.W_UPDATE_DT,
		 T.VIP_SALES_AMT,
		 T.VIP_CUSTOMER_COUNT,
		 T.BBG_REFERENCE_DO1,
		 T.BBG_REFERENCE_DO2,
		 T.BBG_REFERENCE_DO3,
		 T.BBG_REFERENCE_FO1,
		 T.BBG_REFERENCE_FO2,
		 T.BBG_REFERENCE_FO3)
	VALUES
		(RADM.BBG_RA_VIPSLS_LC_DY_A_SEQ.NEXTVAL,
		 S.ORG_WID,
		 S.ORG_LC_WID,
		 S.ORG_SCD1_WID,
		 S.DT_WID,
		 SYSDATE,
		 SYSDATE,
		 S.VIP_SALES_AMT,
		 S.VIP_CUSTOMER_COUNT,
		 NULL,
		 NULL,
		 NULL,
		 NULL,
		 NULL,
		 NULL);

------------------------------------------------
SELECT * FROM BBG_RA_VIPSLS_LC_DY_A;
SELECT MAX(DT_WID) FROM BBG_RA_VIPSLS_LC_DY_A;
SELECT MAX(XFSJ) FROM RADM.HYXFJL;

SELECT * FROM BBG_RA_SLS_LC_DY_A;
SELECT * FROM BBG_RA_VIPSLS_LC_DY_FV2;
SELECT * FROM MDDY;
SELECT '1' || TO_CHAR(FV.XFSJ, 'YYYYMMDD') || '000' DT_WID,
			 SUBSTR(MD.MDDM, 3, 7) ORG_NUM,
			 FV.JE VIP_SALES_AMT,
			 FV.BBG_CUSTOMER_COUNT VIP_CUSTOMER_COUNT
	FROM BBG_RA_VIPSLS_LC_DY_FV FV, MDDY MD
 WHERE FV.MDID = FV.MDID
	 AND MD.SHDM = 'CS';

SELECT SUBSTR(MD.MDDM, 3, 6), MD.* FROM MDDY MD WHERE MD.SHDM = 'CS';

SELECT TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD'), 'YYYY-MM-DD') FROM DUAL;
SELECT * FROM RADM.HYXFJL T;
SELECT MAX() FROM BBG_RA_VIPSLS_LC_DY_A
