SELECT T.ITEM, SUM(T.STOCK_ON_HAND * T.UNIT_COST) TOTAL_COST
	FROM RA_RMS.ITEM_LOC_SOH_20131001 T
 WHERE T.STOCK_ON_HAND < 0
 GROUP BY T.ITEM;

SELECT T.ITEM, SUM(T.STOCK_ON_HAND * T.UNIT_COST) TOTAL_COST
	FROM RA_RMS.ITEM_LOC_SOH_20131001 T
 WHERE T.STOCK_ON_HAND >= 0
 GROUP BY T.ITEM;

SELECT IM.DEPT, SUM(A.TOTAL_COST) COST1, SUM(B.TOTAL_COST) COST2
	FROM ITEM_MASTER IM,
			 (SELECT T.ITEM, SUM(T.STOCK_ON_HAND * T.UNIT_COST) TOTAL_COST
					FROM RA_RMS.ITEM_LOC_SOH_20131130 T
				 WHERE T.STOCK_ON_HAND < 0
				 GROUP BY T.ITEM) A,
			 (SELECT T.ITEM, SUM(T.STOCK_ON_HAND * T.UNIT_COST) TOTAL_COST
					FROM RA_RMS.ITEM_LOC_SOH_20131130 T
				 WHERE T.STOCK_ON_HAND >= 0
				 GROUP BY T.ITEM) B
 WHERE IM.ITEM = A.ITEM
	 AND IM.ITEM = B.ITEM
 GROUP BY IM.DEPT
 ORDER BY IM.DEPT;

SELECT * FROM ITEM_MASTER;

SELECT * FROM RA_RMS.ITEM_LOC_SOH_20131001 T;
