SELECT /*+PARALLEL(H,20) (G,20)*/
 H.HYK_NO, H.HY_NAME, G.PHONE
  FROM RADM.HYK_HYXX H, RADM.HYK_GRXX G
 WHERE H.HYID = G.HYID
   AND H.YXQ > DATE '2014-09-10'
   AND EXISTS (SELECT /*+PARALLEL(T,20)*/
         1
          FROM RADM.HYK_GRXX T
					WHERE T.HYID=H.HYID
         GROUP BY G.PHONE
        HAVING COUNT(*) > 1);
				
SELECT /*+PARALLEL(H,20) (G,20)*/
 H.HYK_NO, H.HY_NAME, G.SJHM
  FROM RADM.HYK_HYXX H, RADM.HYK_GRXX G
 WHERE H.HYID = G.HYID
   AND H.YXQ > DATE '2014-09-10'
   AND EXISTS (SELECT /*+PARALLEL(T,20)*/
         1
          FROM RADM.HYK_GRXX T
					WHERE T.HYID=H.HYID
         GROUP BY G.SJHM
        HAVING COUNT(*) > 1);

SELECT * FROM RADM.Hyk_Grxx;
SELECT * FROM RADM.HYK_HYXX; 
