--1
TRUNCATE TABLE RADM.W_RTL_PRICE_IT_LC_DY_FS;
TRUNCATE TABLE RADM.C_LOAD_DATES;
--2
CREATE TABLE RADM.JIN_PRICE_ITEM_LOC_TMP(ITEM VARCHAR2(20),LOC VARCHAR2(20) );
SELECT * FROM RADM.JIN_PRICE_ITEM_LOC_TMP FOR UPDATE;
--3
INSERT INTO RADM.W_RTL_PRICE_IT_LC_DY_FS
  SELECT *
    FROM RADM.W_RTL_PRICE_IT_LC_DY_FS_140912 T
   WHERE SUBSTR(T.PROD_IT_NUM, 9, 1) = 0
     AND EXISTS (SELECT 1
            FROM RADM.JIN_PRICE_ITEM_LOC_TMP P
           WHERE T.PROD_IT_NUM = P.ITEM
             AND T.ORG_NUM = P.LOC);
COMMIT;

select * from ra_rms.ra_restart_loc t where t.SCENARIO_NAME = 'SDE_BBG_RETAILPRICEFACT';
SELECT * FROM ra_rms.C_ODI_PARAM t where t.Integration_Id = 'SDE_BBG_RETAILPRICEFACT~001~LOC_NUM_OF_THREAD' FOR UPDATE;

