--RAPXDB测试库数据同步，from BBG_PROD_RDW
--注意！！！！：登录RADM测试库运行
--RABATCHER.W_PRODUCT_D_RTL_TMP
TRUNCATE TABLE RABATCHER.W_PRODUCT_D_RTL_TMP;
INSERT INTO RABATCHER.W_PRODUCT_D_RTL_TMP
SELECT * FROM RABATCHER.W_PRODUCT_D_RTL_TMP@RA_PRD;
--RABATCHER.W_INT_ORG_D_RTL_TMP
TRUNCATE TABLE RABATCHER.W_INT_ORG_D_RTL_TMP;
INSERT INTO RABATCHER.W_INT_ORG_D_RTL_TMP
SELECT * FROM RABATCHER.W_INT_ORG_D_RTL_TMP@RA_PRD;
