SELECT T.ROW_WID,
       T.ORG_HIER11_NUM,
       T.EFFECTIVE_FROM_DT,
       T.EFFECTIVE_TO_DT,
       T.CURRENT_FLG,
       T.INTEGRATION_ID
  FROM RADM.W_INT_ORG_DH T
 WHERE EXISTS
 (SELECT 1
          FROM RADM.W_INT_ORG_DH D
         GROUP BY D.INTEGRATION_ID
        HAVING COUNT(*) > 1 AND T.INTEGRATION_ID = D.INTEGRATION_ID)
 ORDER BY T.INTEGRATION_ID
   FOR UPDATE;

--
SELECT DISTINCT T.DT_WID, T.ORG_WID, T.ORG_DH_WID, T.ORG_SCD1_WID
  FROM RADM.W_RTL_SLS_LC_DY_A T
 WHERE T.ORG_WID = 198
 ORDER BY T.DT_WID;

SELECT * FROM RADM.W_INT_ORG_D;
