SELECT STI.ITEM,
       STI.STORE,
       SUM(NVL(STI.QTY, 0)) QTY,
       COUNT(1) TRAN_COUNT,
       SUM(NVL(STI.QTY, 0) * NVL(STI.UNIT_RETAIL, 0) -
           NVL(DISC.DISC_AMT, 0)) TOTAL_RETAIL
  FROM SA_TRAN_ITEM STI,
       SA_TRAN_HEAD H,
       SA_STORE_DAY D,
       (SELECT TRAN_SEQ_NO,
               ITEM_SEQ_NO,
               STORE,
               DAY,
               SUM(NVL(STD.QTY, 0) * NVL(STD.UNIT_DISCOUNT_AMT, 0)) DISC_AMT
          FROM SA_TRAN_DISC STD
         GROUP BY TRAN_SEQ_NO, ITEM_SEQ_NO, STORE, DAY) DISC
 WHERE STI.TRAN_SEQ_NO = H.TRAN_SEQ_NO
   AND STI.STORE = H.STORE
   AND STI.DAY = H.DAY
   AND H.STORE_DAY_SEQ_NO = D.STORE_DAY_SEQ_NO
   AND D.BUSINESS_DATE = DATE '2014-08-28'
   AND STI.TRAN_SEQ_NO = DISC.TRAN_SEQ_NO(+)
   AND STI.ITEM_SEQ_NO = DISC.ITEM_SEQ_NO(+)
   AND STI.STORE = DISC.STORE(+)
   AND STI.DAY = DISC.DAY(+)
   AND STI.ITEM = 101507100
   AND D.STORE = 120033
 GROUP BY STI.ITEM, STI.STORE
