--1
SELECT JIN_PKG.GETAREA(4) FROM DUAL;
--2
DECLARE
  TYPE CUR_OUT IS REF CURSOR;
  RESULTS_OUT CUR_OUT;
BEGIN
  -- CALL THE PROCEDURE
  JIN_PKG.P_CK_IT_INV_DAY_ERROR(RESULTS_OUT);
END;
--3
DECLARE
  TYPE CUR_OUT IS REF CURSOR;
  RESULTS_OUT CUR_OUT;
BEGIN
  -- CALL THE PROCEDURE
  JIN_PKG.P_CK_SUPP_SLS_FIX_RESULT(RESULTS_OUT);
END;
--4
DECLARE
  TYPE CUR_OUT IS REF CURSOR;
  RESULTS_OUT CUR_OUT;
BEGIN
  -- CALL THE PROCEDURE
  JIN_PKG.P_CK_SUPP_SLS_FIX_RESULT(RESULTS_OUT);
END;
