UPDATE W_MCAL_DAY_D T
   SET T.CAL_WEEK_START_DT =
       (SELECT MIN(A.MCAL_DAY_DT)
          FROM W_MCAL_DAY_D A
         WHERE T.CAL_WEEK_NAME = A.CAL_WEEK_NAME
         GROUP BY T.CAL_WEEK_NAME);
COMMIT;

UPDATE W_MCAL_DAY_D T
   SET T.CAL_WEEK_END_DT =
       (SELECT MAX(A.MCAL_DAY_DT)
          FROM W_MCAL_DAY_D A
         WHERE T.CAL_WEEK_NAME = A.CAL_WEEK_NAME
         GROUP BY T.CAL_WEEK_NAME);
COMMIT;

select T.ROW_WID,
       T.MCAL_DAY_DT,
       T.CAL_WEEK_NAME,
       T.CAL_WEEK_START_DT,
       T.CAL_WEEK_END_DT,
       T.*
  from W_MCAL_DAY_D t
 ORDER BY T.ROW_WID;
SELECT * FROM W_RTL_SLS_IT_LC_DY_A;
SELECT * FROM W_RTL_SLS_IT_LC_WK_A;

SELECT T.CAL_WEEK_NAME, MIN(T.MCAL_DAY_DT), MAX(T.MCAL_DAY_DT)
  FROM W_MCAL_DAY_D T
 GROUP BY T.CAL_WEEK_NAME;
