/*
v_cmx_cost_vat_item  进项税


v_cmx_sale_vat_item  销项税
*/

SELECT * FROM 
(

---月，地点，供应商，商品--销售
SELECT --TO_CHAR(SDATE, 'YYYYMM') MONTH,
       to_number(SUBSTR(SHOPID, 2, 2) || '0' || SUBSTR(SHOPID, 4, 3)) LOC,
       to_number(VENDERID) SUPPLIER,
       to_char(GOODSID + 800000000) ITEM,
       SUM(QTY) SALEQTY,
       SUM(COSTVALUE) COSTVALUE,
       SUM(SALEVALUE) SALEVALUE
  FROM SALECOST@RMS_RA CH, SALECOSTITEM@RMS_RA CL
 WHERE CH.SHEETID = CL.SHEETID
 GROUP BY /*TO_CHAR(SDATE, 'YYYYMM'),*/ SHOPID, VENDERID, GOODSID    ---融通销售20130101-20130507
 
 UNION ALL
 
SELECT --TO_CHAR(SS.ORIGIN_SALES_DATE, 'yyyymm') MONTH,
       STORE LOC,
       SUPPLIER,
       ITEM,
       SUM(QTY) SALEQTY,
       SUM(TOTAL_COST * (100 + SS.COST_VAT_RATE) / 100) COSTVALUE,
       SUM(SS.TOTAL_RETAIL) SALEVALUE
  FROM CMX_SUPP_SALES SS WHERE ss.ORIGIN_SALES_DATE<=DATE'2013-12-31'
 GROUP BY /*TO_CHAR(SS.ORIGIN_SALES_DATE, 'yyyymm'),*/ STORE, SUPPLIER, ITEM
 
 ) A,ITEM_LOC C WHERE C.ITEM=A.ITEM AND C.LOC=A.LOC AND C.STATUS='A'
