--TRAN_CODE=82已经接入RA，TRAN_CODE=83未接入RA，与王勇昱沟通，TRAN_CODE=83的金额等于0的，不接入RA
--TRAN_CODE=83的数据，UNITS有正有负。
--RMS数据源
SELECT * FROM RMS.BBG_RA_WHOLE_SALES_FV;
--
SELECT * FROM RADM.BBG_RA_WHOLE_SALES_F;

SELECT T.TRAN_DATE DAY_DT,
         T.ITEM,
         T.LOCATION LOC,
         NVL(SUM(T.TOTAL_RETAIL), 0) BBG_WHOLE_SALES_AMOUNT,
         NVL(SUM(T.UNITS), 0) BBG_WHOLE_SALES_QTY,
         NVL(SUM(T.TOTAL_COST), 0) BBG_WHOLE_SALES_COST,
         '' BBG_REFERENCE_DO1,
         '' BBG_REFERENCE_DO2,
         '' BBG_REFERENCE_DO3,
         '' BBG_REFERENCE_DO4,
         '' BBG_REFERENCE_DO5,
         NULL BBG_REFERENCE_FO1,
         NULL BBG_REFERENCE_FO2,
         NULL BBG_REFERENCE_FO3,
         NULL BBG_REFERENCE_FO4,
         NULL BBG_REFERENCE_FO5,
         NULL BBG_REFERENCE_FO6,
         NULL BBG_REFERENCE_FO7,
         NULL BBG_REFERENCE_FO8,
         NULL BBG_REFERENCE_FO9,
         NULL BBG_REFERENCE_FO10
    FROM RMS.IF_TRAN_DATA T
   WHERE T.TRAN_CODE = 82
   GROUP BY T.TRAN_DATE, T.ITEM, T.LOCATION;
	 
SELECT * FROM RMS.IF_TRAN_DATA T WHERE T.TRAN_CODE IN (82,83);
SELECT * FROM RMS.TRAN_DATA_HISTORY T WHERE T.TRAN_CODE IN (82,83) /*AND T.TRAN_DATE=DATE'2014-09-13'*/;
