SELECT SUM(T.SUPP_SALES_QTY), SUM(T.SUPP_SALES_COST)
  FROM RADM.BBG_RA_SLS_IT_DY_A T
 WHERE T.DT_WID BETWEEN 120120701000 AND 120120731000;

SELECT SUM(T.SUPP_SALES_QTY), SUM(T.SUPP_SALES_COST)
  FROM RADM.BBG_RA_SLS_IT_DY_A T
 WHERE T.DT_WID BETWEEN 120120801000 AND 120120831000;
 
 SELECT SUM(T.SUPP_SALES_QTY), SUM(T.SUPP_SALES_COST)
  FROM RADM.BBG_RA_SLS_SC_DY_A T
 WHERE T.DT_WID BETWEEN 120120801000 AND 120120831000;
 
  SELECT SUM(T.SUPP_SALES_QTY), SUM(T.SUPP_SALES_COST)
  FROM RADM.BBG_RA_SLS_SC_MN_A T
 WHERE T.MN_WID = 201208;
 
 RADM.BBG_RA_SLS_SC_DY_A

SELECT SUM(T.SUPP_SALES_QTY), SUM(T.SUPP_SALES_COST)
  FROM RADM.BBG_RA_SLS_IT_DY_A T
 WHERE T.DT_WID BETWEEN 120120901000 AND 120120930000;

SELECT *
  FROM RADM.BBG_RA_SLS_SC_DY_A t
 WHERE T.DT_WID BETWEEN 120120801000 AND 120120831000;

SELECT * FROM RADM.BBG_RA_SLS_SC_DY_A t;
SELECT * FROM RADM.BBG_RA_SLS_SC_LC_DY_A t;

--BBG_RA_SLS_SC_DY_A

INSERT INTO RADM.BBG_RA_SLS_SC_DY_A
  (ROW_WID,
   PROD_DH_WID,
   DT_WID,
   SUPPLIER_WID,
   DATASOURCE_NUM_ID,
   DELETE_FLG,
   ETL_PROC_WID,
   INTEGRATION_ID,
   TENANT_ID,
   W_INSERT_DT,
   W_UPDATE_DT,
   X_CUSTOM,
   SUPP_SALES_QTY,
   SUPP_SALES_COST,
   SUPP_SALES_AMT,
   BBG_REFERENCE_DO1,
   BBG_REFERENCE_DO2,
   BBG_REFERENCE_DO3,
   BBG_REFERENCE_DO4,
   BBG_REFERENCE_DO5,
   BBG_REFERENCE_FO1,
   BBG_REFERENCE_FO2,
   BBG_REFERENCE_FO3,
   BBG_REFERENCE_FO4,
   BBG_REFERENCE_FO5,
   BBG_REFERENCE_FO6,
   BBG_REFERENCE_FO7,
   BBG_REFERENCE_FO8,
   BBG_REFERENCE_FO9,
   BBG_REFERENCE_FO10)
  SELECT BBG_RA_SLS_SC_DY_A_SEQ.NEXTVAL,
         A.PROD_DH_WID,
         A.DT_WID,
         A.SUPPLIER_WID,
         A.DATASOURCE_NUM_ID,
         A.DELETE_FLG,
         A.ETL_PROC_WID,
         A.INTEGRATION_ID,
         A.TENANT_ID,
         A.W_INSERT_DT,
         A.W_UPDATE_DT,
         A.X_CUSTOM,
         A.SUPP_SALES_QTY,
         A.SUPP_SALES_COST,
         A.SUPP_SALES_AMT,
         A.BBG_REFERENCE_DO1,
         A.BBG_REFERENCE_DO2,
         A.BBG_REFERENCE_DO3,
         A.BBG_REFERENCE_DO4,
         A.BBG_REFERENCE_DO5,
         A.BBG_REFERENCE_FO1,
         A.BBG_REFERENCE_FO2,
         A.BBG_REFERENCE_FO3,
         A.BBG_REFERENCE_FO4,
         A.BBG_REFERENCE_FO5,
         A.BBG_REFERENCE_FO6,
         A.BBG_REFERENCE_FO7,
         A.BBG_REFERENCE_FO8,
         A.BBG_REFERENCE_FO9,
         A.BBG_REFERENCE_FO10
    FROM (SELECT T.PROD_DH_WID,
                 T.DT_WID,
                 T.SUPPLIER_WID,
                 SUM(T.SUPP_SALES_QTY) SUPP_SALES_QTY,
                 SUM(T.SUPP_SALES_COST) SUPP_SALES_COST,
                 SUM(T.SUPP_SALES_AMT) SUPP_SALES_AMT,
                 T.DATASOURCE_NUM_ID,
                 T.DELETE_FLG,
                 T.DOC_CURR_CODE,
                 T.ETL_PROC_WID,
                 T.GLOBAL1_EXCHANGE_RATE,
                 T.GLOBAL2_EXCHANGE_RATE,
                 T.GLOBAL3_EXCHANGE_RATE,
                 SUBSTR(T.INTEGRATION_ID, 1, 5) ||
                 SUBSTR(T.INTEGRATION_ID, 13, 30) INTEGRATION_ID,
                 T.LOC_CURR_CODE,
                 T.LOC_EXCHANGE_RATE,
                 T.TENANT_ID,
								 SYSDATE W_INSERT_DT,
								 SYSDATE W_UPDATE_DT,
                 T.X_CUSTOM,
                 SUM(T.BBG_REFERENCE_DO1) BBG_REFERENCE_DO1,
                 SUM(T.BBG_REFERENCE_DO2) BBG_REFERENCE_DO2,
                 SUM(T.BBG_REFERENCE_DO3) BBG_REFERENCE_DO3,
                 SUM(T.BBG_REFERENCE_DO4) BBG_REFERENCE_DO4,
                 SUM(T.BBG_REFERENCE_DO5) BBG_REFERENCE_DO5,
                 SUM(T.BBG_REFERENCE_FO1) BBG_REFERENCE_FO1,
                 SUM(T.BBG_REFERENCE_FO2) BBG_REFERENCE_FO2,
                 SUM(T.BBG_REFERENCE_FO3) BBG_REFERENCE_FO3,
                 SUM(T.BBG_REFERENCE_FO4) BBG_REFERENCE_FO4,
                 SUM(T.BBG_REFERENCE_FO5) BBG_REFERENCE_FO5,
                 SUM(T.BBG_REFERENCE_FO6) BBG_REFERENCE_FO6,
                 SUM(T.BBG_REFERENCE_FO7) BBG_REFERENCE_FO7,
                 SUM(T.BBG_REFERENCE_FO8) BBG_REFERENCE_FO8,
                 SUM(T.BBG_REFERENCE_FO9) BBG_REFERENCE_FO9,
                 SUM(T.BBG_REFERENCE_FO10) BBG_REFERENCE_FO10
            FROM RADM.BBG_RA_SLS_SC_LC_DY_A T
           WHERE T.DT_WID BETWEEN 120120801000 AND 120120831000
           GROUP BY T.PROD_DH_WID,
                    T.DT_WID,
                    T.SUPPLIER_WID,
                    T.DATASOURCE_NUM_ID,
                    T.DELETE_FLG,
                    T.DOC_CURR_CODE,
                    T.ETL_PROC_WID,
                    T.GLOBAL1_EXCHANGE_RATE,
                    T.GLOBAL2_EXCHANGE_RATE,
                    T.GLOBAL3_EXCHANGE_RATE,
                    SUBSTR(T.INTEGRATION_ID, 1, 5) ||
                    SUBSTR(T.INTEGRATION_ID, 13, 30),
                    T.LOC_CURR_CODE,
                    T.LOC_EXCHANGE_RATE,
                    T.TENANT_ID,
                    T.X_CUSTOM) A;

--BBG_RA_SLS_IT_DY_A

INSERT INTO RADM.BBG_RA_SLS_IT_DY_A
  (ROW_WID,
   PROD_WID,
   PROD_SCD1_WID,
   DT_WID,
   DATASOURCE_NUM_ID,
   DELETE_FLG,
   ETL_PROC_WID,
   INTEGRATION_ID,
   TENANT_ID,
   W_INSERT_DT,
   W_UPDATE_DT,
   X_CUSTOM,
   SUPPLIER_WID,
   SUPP_SALES_QTY,
   SUPP_SALES_COST,
   SUPP_SALES_AMT,
   BBG_REFERENCE_DO1,
   BBG_REFERENCE_DO2,
   BBG_REFERENCE_DO3,
   BBG_REFERENCE_DO4,
   BBG_REFERENCE_DO5,
   BBG_REFERENCE_FO1,
   BBG_REFERENCE_FO2,
   BBG_REFERENCE_FO3,
   BBG_REFERENCE_FO4,
   BBG_REFERENCE_FO5,
   BBG_REFERENCE_FO6,
   BBG_REFERENCE_FO7,
   BBG_REFERENCE_FO8,
   BBG_REFERENCE_FO9,
   BBG_REFERENCE_FO10)
  SELECT BBG_RA_SLS_IT_DY_A_SEQ.NEXTVAL,
         A.PROD_WID,
         A.PROD_SCD1_WID,
         A.DT_WID,
         A.DATASOURCE_NUM_ID,
         A.DELETE_FLG,
         A.ETL_PROC_WID,
         A.INTEGRATION_ID,
         A.TENANT_ID,
         A.W_INSERT_DT,
         A.W_UPDATE_DT,
         A.X_CUSTOM,
         A.SUPPLIER_WID,
         A.SUPP_SALES_QTY,
         A.SUPP_SALES_COST,
         A.SUPP_SALES_AMT,
         A.BBG_REFERENCE_DO1,
         A.BBG_REFERENCE_DO2,
         A.BBG_REFERENCE_DO3,
         A.BBG_REFERENCE_DO4,
         A.BBG_REFERENCE_DO5,
         A.BBG_REFERENCE_FO1,
         A.BBG_REFERENCE_FO2,
         A.BBG_REFERENCE_FO3,
         A.BBG_REFERENCE_FO4,
         A.BBG_REFERENCE_FO5,
         A.BBG_REFERENCE_FO6,
         A.BBG_REFERENCE_FO7,
         A.BBG_REFERENCE_FO8,
         A.BBG_REFERENCE_FO9,
         A.BBG_REFERENCE_FO10
    FROM (SELECT T.PROD_WID,
                 T.PROD_SCD1_WID,
                 T.DT_WID,
                 T.DATASOURCE_NUM_ID,
                 T.DELETE_FLG,
                 T.ETL_PROC_WID,
                 SUBSTR(T.INTEGRATION_ID, 1, 9) ||
                 SUBSTR(T.INTEGRATION_ID, 17, 19) INTEGRATION_ID,
                 T.TENANT_ID,
                 SYSDATE W_INSERT_DT,
                 SYSDATE W_UPDATE_DT,
                 T.X_CUSTOM,
                 T.SUPPLIER_WID,
                 SUM(T.SUPP_SALES_QTY) SUPP_SALES_QTY,
                 SUM(T.SUPP_SALES_COST) SUPP_SALES_COST,
                 SUM(T.SUPP_SALES_AMT) SUPP_SALES_AMT,
                 SUM(T.BBG_REFERENCE_DO1) BBG_REFERENCE_DO1,
                 SUM(T.BBG_REFERENCE_DO2) BBG_REFERENCE_DO2,
                 SUM(T.BBG_REFERENCE_DO3) BBG_REFERENCE_DO3,
                 SUM(T.BBG_REFERENCE_DO4) BBG_REFERENCE_DO4,
                 SUM(T.BBG_REFERENCE_DO5) BBG_REFERENCE_DO5,
                 SUM(T.BBG_REFERENCE_FO1) BBG_REFERENCE_FO1,
                 SUM(T.BBG_REFERENCE_FO2) BBG_REFERENCE_FO2,
                 SUM(T.BBG_REFERENCE_FO3) BBG_REFERENCE_FO3,
                 SUM(T.BBG_REFERENCE_FO4) BBG_REFERENCE_FO4,
                 SUM(T.BBG_REFERENCE_FO5) BBG_REFERENCE_FO5,
                 SUM(T.BBG_REFERENCE_FO6) BBG_REFERENCE_FO6,
                 SUM(T.BBG_REFERENCE_FO7) BBG_REFERENCE_FO7,
                 SUM(T.BBG_REFERENCE_FO8) BBG_REFERENCE_FO8,
                 SUM(T.BBG_REFERENCE_FO9) BBG_REFERENCE_FO9,
                 SUM(T.BBG_REFERENCE_FO10) BBG_REFERENCE_FO10
            FROM RADM.BBG_RA_SLS_IT_LC_DY_A T
           WHERE T.DT_WID BETWEEN 120120801000 AND 120120831000
           GROUP BY T.PROD_WID,
                    T.PROD_SCD1_WID,
                    T.DT_WID,
                    T.DATASOURCE_NUM_ID,
                    T.DELETE_FLG,
                    T.ETL_PROC_WID,
                    SUBSTR(T.INTEGRATION_ID, 1, 9) ||
                    SUBSTR(T.INTEGRATION_ID, 17, 19),
                    T.TENANT_ID,
                    SYSDATE,
                    SYSDATE,
                    T.X_CUSTOM,
                    T.SUPPLIER_WID) A;
