SELECT TRX.SUBCLASS 品类,
			 TO_CHAR(TRX.BUSINESS_DATE, 'YYYYMM') 月份,
			 SUM(TRX.QTY) 购买数量,
			 COUNT(TRX.SLS_TRX_ID) 购买次数,
			 SUM(TRX.AMT) / COUNT(TRX.SLS_TRX_ID) 平均客单,
			 SUM(TRX.AMT) AMT,
			 SUM(TRX.DISAMT) / COUNT(TRX.SLS_TRX_ID) 平均优惠金额,
			 SUM(TRX.DISAMT) 优惠金额合计
	FROM (SELECT ST.TRAN_SEQ_NO SLS_TRX_ID,
							 ST.SUBCLASS,
							 SD.BUSINESS_DATE,
							 SUM(ST.QTY * (ST.UNIT_RETAIL - NVL(STD.UNIT_DISCOUNT_AMT, 0))) AMT,
							 SUM(STD.UNIT_DISCOUNT_AMT) DISAMT,
							 SUM(ST.QTY) QTY
					FROM SA_TRAN_ITEM ST,
							 SA_TRAN_HEAD SH,
							 SA_STORE_DAY SD,
							 SA_TRAN_DISC STD
				 WHERE ST.STORE = SH.STORE
					 AND ST.DAY = SH.DAY
					 AND ST.TRAN_SEQ_NO = SH.TRAN_SEQ_NO
					 AND SH.STORE_DAY_SEQ_NO = SD.STORE_DAY_SEQ_NO
					 AND SH.STORE = SD.STORE
					 AND SH.DAY = SD.DAY
					 AND ST.STORE = STD.STORE(+)
					 AND ST.DAY = STD.DAY(+)
					 AND ST.TRAN_SEQ_NO = STD.TRAN_SEQ_NO(+)
					 AND ST.ITEM_SEQ_NO = STD.ITEM_SEQ_NO(+)
					 AND SD.BUSINESS_DATE BETWEEN DATE '2013-05-08' AND DATE
				 '2013-12-31' --销售日期
					 AND ST.SUBCLASS IN ('2232', '2242', '2243', '2252') --红酒小类
					 AND EXISTS
				 (SELECT VIP.JZRQ, M.MDDM, VIP.SKTNO, VIP.JLBH
									FROM MDDY@RMS_RA M, YJ_HYK_BIRTHDAY_SLS_2013@RMS_RA VIP
								 WHERE M.MDID = VIP.MDID
									 AND VIP.JZRQ = SD.BUSINESS_DATE --日期
									 AND SUBSTR(M.MDDM, 3, 6) = TO_CHAR(ST.STORE) --门店
									 AND VIP.SKTNO = SH.REGISTER --机台号
									 AND VIP.JLBH = SH.TRAN_NO --小票号
								)
				 GROUP BY ST.TRAN_SEQ_NO, ST.SUBCLASS, SD.BUSINESS_DATE) TRX
 GROUP BY TRX.SUBCLASS, TO_CHAR(TRX.BUSINESS_DATE, 'YYYYMM');

--会员生日消费记录-----------------------------------------------------------------------
SELECT H.JZRQ, --消费日期
			 SUBSTR(M.MDDM, 2, 6), --门店 
			 H.SKTNO, --机台号
			 H.JLBH --小票号
	FROM RADM.HYXFJL H, RADM.MDDY M, RADM.HYK_GRXX GR
 WHERE H.MDID = M.MDID
	 AND H.HYID = GR.HYID
	 AND TO_CHAR(H.JZRQ, 'MMDD') = TO_CHAR(GR.CSRQ, 'MMDD')
	 AND H.JZRQ BETWEEN DATE '2013-05-08' AND DATE '2013-12-31';
--优化
SELECT VIP.JZRQ, M.MDDM, VIP.SKTNO, VIP.JLBH
	FROM MDDY M, YJ_HYK_BIRTHDAY_SLS_2013 VIP
 WHERE M.MDID = VIP.MDID;

CREATE MATERIALIZED VIEW YJ_HYK_BIRTHDAY_SLS_2013 AS
	SELECT H.JZRQ, --消费日期
				 H.MDID, --门店 
				 H.SKTNO, --机台号
				 H.JLBH --小票号
		FROM RADM.HYXFJL H, RADM.HYK_GRXX GR
	 WHERE H.HYID = GR.HYID
		 AND TO_CHAR(H.JZRQ, 'MMDD') = TO_CHAR(GR.CSRQ, 'MMDD')
		 AND H.JZRQ BETWEEN DATE '2013-01-01' AND DATE '2013-12-31';

SELECT COUNT(*) FROM YJ_HYK_BIRTHDAY_SLS_2013;
