SELECT SUP1.SUPPLIER 一级供应商,
			 SUP1.SUP_NAME 一级供应商名称,
			 SUP2.SUPPLIER 二级供应商,
			 SUP2.SUP_NAME 二级供应商名称,
			 CO.CONTRACT_NO 二级合同编码,
			 SUBSTR(SUP2.SUPPLIER, 1, 2) 合同大类,
			 (SELECT UV.UDA_VALUE_DESC
					FROM UDA_VALUES UV
				 WHERE UV.UDA_ID = 3
					 AND UV.UDA_VALUE = CO.BRAND_CODE) 经营主要品牌,
			 (SELECT CD.CODE_DESC
					FROM CMX_CODE_DETAIL CD
				 WHERE CD.CODE = CO.CONTRACT_TYPE
					 AND CD.CODE_TYPE = 'BSTP'
					 AND CD.LANG = 8) 合同类型,
			 CASE
				 WHEN CO.STATUS = 'C' THEN
					'终止'
				 WHEN CO.STATUS = 'A' THEN
					'正在执行'
				 WHEN CO.STATUS = 'S' THEN
					'录入'
				 WHEN CO.STATUS = 'I' THEN
					'提交'
				 ELSE
					NULL
			 END AS 合同状态,
			 (SELECT TH.TERMS_DESC
					FROM TERMS_HEAD TH
				 WHERE TH.TERMS_CODE = SUP2.TERMS) 方式,
			 R.COST_CODE,
			 (SELECT CCO.COST_NAME
					FROM CMX_CONTRACT_OPTIONS CCO
				 WHERE CCO.COST_CODE = R.COST_CODE) 费用名称,
			 R.AMOUNT 费用金额
	FROM CMX_CONTRACT_RESULT R,
			 SUPS SUP1,
			 SUPS SUP2,
			 CMX_CONTRACT CO,
			 (SELECT C.SUPPLIER,
							 MAX(C.CONTRACT_ID) CONTRACT_ID,
							 MAX(C.CONTRACT_NO) CONTRACT_NO
					FROM CMX_CONTRACT C
				 WHERE C.YEAR = '2013'
				 GROUP BY C.SUPPLIER) CO1
 WHERE R.CONTRACT_ID(+) = CO1.CONTRACT_ID
	 AND R.CONTRACT_NO(+) = CO1.CONTRACT_NO
	 AND R.SUPPLIER(+) = CO1.SUPPLIER
	 AND SUP2.SUPPLIER_PARENT = SUP1.SUPPLIER
	 AND CO1.SUPPLIER = SUP2.SUPPLIER(+)
	 AND CO.CONTRACT_ID = CO1.CONTRACT_ID
	 AND CO.CONTRACT_NO = CO1.CONTRACT_NO
	 AND CO.SUPPLIER = CO1.SUPPLIER;

SELECT * FROM CMX_CONTRACT_OPTIONS;
