--查找不在BBG_RA_ITEM_LOC_D维度中的商品地点
SELECT DISTINCT V.ITEM, V.ORG_NUM
  FROM RADM.BBG_RA_INV_REF_V V
 WHERE NOT EXISTS
 (SELECT 1
          FROM RADM.BBG_RA_ITEM_LOC_D D
         WHERE V.ITEM = D.ITEM
           AND V.ORG_NUM = D.LOC
           AND V.DAY_DT BETWEEN D.EFFECTIVE_FROM_DT AND D.EFFECTIVE_TO_DT);

--INSERT INTO BBG_RA_ITEM_LOC_D
INSERT INTO BBG_RA_ITEM_LOC_D
  (ROW_WID,
   ITEM,
   LOC,
   BUSINESS_MODE,
   NEW_ITEM_FLAG,
   REF_NO1,
   REF_NO2,
   SRC_EFF_FROM_DT,
   EFFECTIVE_FROM_DT,
   EFFECTIVE_TO_DT,
   CURRENT_FLG,
   W_INSERT_DT,
   W_UPDATE_DT,
   DATASOURCE_NUM_ID,
   ETL_PROC_WID,
   INTEGRATION_ID)
  SELECT RADM.RA_SIL_ITEM_LOC_D_SEQ.NEXTVAL ROW_WID,
         V.ITEM,
         V.ORG_NUM LOC,
         'JX' BUSINESS_MODE,
         'N' NEW_ITEM_FLAG,
         'A' REF_NO1,
         V.ORG_NUM REF_NO2,
         DATE '2012-01-01' SRC_EFF_FROM_DT,
         DATE '2012-01-01' EFFECTIVE_FROM_DT,
         DATE '2013-05-07' EFFECTIVE_TO_DT,
         'N' CURRENT_FLG,
         SYSDATE W_INSERT_DT,
         SYSDATE W_UPDATE_DT,
         1 DATASOURCE_NUM_ID,
         100 ETL_PROC_WID,
         V.ITEM || '~' || V.ORG_NUM INTEGRATION_ID
    FROM RADM.BBG_RA_INV_REF_V V
   WHERE NOT EXISTS
   (SELECT 1
            FROM RADM.BBG_RA_ITEM_LOC_D D
           WHERE V.ITEM = D.ITEM
             AND V.ORG_NUM = D.LOC
             AND V.DAY_DT BETWEEN D.EFFECTIVE_FROM_DT AND D.EFFECTIVE_TO_DT);

-- update BBG_RA_ITEM_LOC_D EFFECTIVE_FROM_DT-------------------------------------------------------------
UPDATE BBG_RA_ITEM_LOC_D D
   SET D.EFFECTIVE_FROM_DT = DATE '2012-01-01'
 WHERE
--查找不在BBG_RA_ITEM_LOC_D维度中的商品地点
 EXISTS (SELECT DISTINCT V.ITEM, V.ORG_NUM
    FROM RADM.BBG_RA_INV_REF_V V
   WHERE NOT EXISTS (SELECT 1
            FROM RADM.BBG_RA_ITEM_LOC_D D
           WHERE V.ITEM = D.ITEM
             AND V.ORG_NUM = D.LOC
             AND V.DAY_DT BETWEEN D.EFFECTIVE_FROM_DT AND
                 D.EFFECTIVE_TO_DT)
     AND V.ITEM = D.ITEM
     AND V.ORG_NUM = D.LOC)
--找出最早的EFFECTIVE_FROM_DT记录
 AND EXISTS
 (SELECT 1
    FROM (SELECT A.ITEM, A.LOC, MIN(A.EFFECTIVE_FROM_DT) EFFECTIVE_FROM_DT
            FROM RADM.BBG_RA_ITEM_LOC_D A
           GROUP BY A.ITEM, A.LOC) B
   WHERE B.ITEM = D.ITEM
     AND B.LOC = D.LOC
     AND B.EFFECTIVE_FROM_DT = D.EFFECTIVE_FROM_DT)
/* AND D.ITEM = 800299900
AND D.LOC = 120156*/
;
---------------------------------------------------------------------------------------------------------
SELECT T.ITEM, T.LOC, COUNT(*)
  FROM RADM.BBG_RA_ITEM_LOC_D T
 GROUP BY T.ITEM, T.LOC
HAVING COUNT(*) > 1
 ORDER BY COUNT(*) DESC;

SELECT *
  FROM RADM.BBG_RA_ITEM_LOC_D T
 WHERE T.ITEM = 800034931
   AND T.LOC = 120030;
SELECT *
  FROM RMS.CMX_ITEM_LOC_INFO@RA_RMS_DBLINK T
 WHERE T.ITEM = 800053825
   AND T.LOC = 120011;
