--A.全司销售创建视图封装金额段
-- VIEW NAME:   RADM.BBG_RA_SLS_SEQ_DY_LC_FV 
SELECT /*+PARALLEL(T,20)*/
 *
  FROM RADM.BBG_RA_SLS_SEQ_DY_LC_FV T
 WHERE T.DT_WID = 120141111000;

--B.全司-hyper-mart 12-超市
SELECT /*+PARALLEL(S,20) PARALLEL(O,20)*/
 SUBSTR(S.DT_WID, 2, 6) MONTH,
 S.SEQ,
 COUNT(S.SLS_TRX_ID) CNT,
 SUM(S.SLS_AMT) SLS_AMT
  FROM RADM.BBG_RA_SLS_SEQ_DY_LC_FV S, RADM.W_INT_ORG_DH O
 WHERE S.ORG_SCD1_WID = O.SCD1_WID
   AND O.ORG_HIER13_NUM = 12
   AND S.DT_WID BETWEEN 120140101000 AND 120141130000
 GROUP BY SUBSTR(S.DT_WID, 2, 6), S.SEQ
 ORDER BY SUBSTR(S.DT_WID, 2, 6), S.SEQ;

--C.全司-super-mart 11-大卖场
SELECT /*+PARALLEL(S,20) PARALLEL(O,20)*/
 SUBSTR(S.DT_WID, 2, 6) MONTH,
 S.SEQ,
 COUNT(S.SLS_TRX_ID) CNT,
 SUM(S.SLS_AMT) SLS_AMT
  FROM RADM.BBG_RA_SLS_SEQ_DY_LC_FV S, RADM.W_INT_ORG_DH O
 WHERE S.ORG_SCD1_WID = O.SCD1_WID
   AND O.ORG_HIER13_NUM = 11
   AND S.DT_WID BETWEEN 120140101000 AND 120141130000
 GROUP BY SUBSTR(S.DT_WID, 2, 6), S.SEQ
 ORDER BY SUBSTR(S.DT_WID, 2, 6), S.SEQ;

--D.会员销售金额段视图
-- VIEW NAME:   RADM.BBG_RA_SLS_VIP_SEQ_DY_LC_FV
SELECT *
  FROM RADM.BBG_RA_SLS_VIP_SEQ_DY_LC_FV T
 WHERE T.JZRQ = DATE '2014-11-11';

--E.会员-hyper-mart 12-超市 
SELECT /*+PARALLEL(S,20) PARALLEL(O,20)*/
 SUBSTR(TO_CHAR(S.JZRQ, 'YYYYMMDD'), 1, 6) MONTH,
 S.SEQ,
 COUNT(S.SLS_TRX_ID) CNT,
 SUM(S.VIP_SLS_AMT) VIP_SLS_AMT
  FROM RADM.BBG_RA_SLS_VIP_SEQ_DY_LC_FV S,
       (select DISTINCT T.ORG_HIER13_NUM, T.ORG_HIER9_NUM
          from W_INT_ORG_DH t) O
 WHERE S.LOC = O.ORG_HIER9_NUM
   AND O.ORG_HIER13_NUM = 12
   AND S.JZRQ BETWEEN DATE '2014-01-01' AND DATE '2014-11-30'
 GROUP BY SUBSTR(TO_CHAR(S.JZRQ, 'YYYYMMDD'), 1, 6), S.SEQ
 ORDER BY SUBSTR(TO_CHAR(S.JZRQ, 'YYYYMMDD'), 1, 6), S.SEQ;
--F.会员-super-mart 11-大卖场
SELECT /*+PARALLEL(S,20) PARALLEL(O,20)*/
 SUBSTR(TO_CHAR(S.JZRQ, 'YYYYMMDD'), 1, 6) MONTH,
 S.SEQ,
 COUNT(S.SLS_TRX_ID) CNT,
 SUM(S.VIP_SLS_AMT) VIP_SLS_AMT
  FROM RADM.BBG_RA_SLS_VIP_SEQ_DY_LC_FV S,
       (select DISTINCT T.ORG_HIER13_NUM, T.ORG_HIER9_NUM
          from W_INT_ORG_DH t) O
 WHERE S.LOC = O.ORG_HIER9_NUM
   AND O.ORG_HIER13_NUM = 11
   AND S.JZRQ BETWEEN DATE '2014-01-01' AND DATE '2014-11-30'
 GROUP BY SUBSTR(TO_CHAR(S.JZRQ, 'YYYYMMDD'), 1, 6), S.SEQ
 ORDER BY SUBSTR(TO_CHAR(S.JZRQ, 'YYYYMMDD'), 1, 6), S.SEQ;
------------------------------------------------------------------------------

