--2013年全年销售
DROP MATERIALIZED VIEW YJ_ITEM_LOC_SLS_2013;
CREATE MATERIALIZED VIEW YJ_ITEM_LOC_SLS_2013
AS
SELECT SUBSTR(A.DT_WID, 2, 4) YEAR,
			 D.PROD_NUM ITEM,
			 O.ORG_NUM LOC,
			 SUM(NVL(A.SLS_QTY, 0) - NVL(A.RET_QTY, 0)) SALESQTY,
			 SUM(NVL(A.SLS_AMT_LCL, 0) - NVL(A.RET_AMT_LCL, 0)) SALESAMT,
			 SUM((NVL(A.SLS_AMT_LCL, 0) - NVL(A.RET_AMT_LCL, 0)) -
			 (NVL(A.Sls_Tax_Amt_Lcl, 0) - NVL(A.Ret_Tax_Amt_Lcl, 0))) NOTAX_SALESAMT,
			 --SUM(NVL(A.BBG_REFERENCE_FO2, 0)) NOTAX_COSTAMT
			 SUM(((NVL(A.SLS_AMT_LCL, 0) - NVL(A.RET_AMT_LCL, 0)) -
			 (NVL(A.Sls_Tax_Amt_Lcl, 0) - NVL(A.Ret_Tax_Amt_Lcl, 0)))-NVL(A.SLS_PROFIT_AMT_LCL,0)) NOTAX_COSTAMT
	FROM W_RTL_SLS_IT_LC_DY_A A, W_PRODUCT_D D, W_INT_ORG_D O
 WHERE A.PROD_WID = D.ROW_WID
	 AND A.ORG_WID = O.ROW_WID
	 AND A.DT_WID BETWEEN '120130101000' AND '120131231000'
 GROUP BY SUBSTR(A.DT_WID, 2, 4), D.PROD_NUM, O.ORG_NUM;
 
--2013年全年销售_正常销售_RTL_TYPE_WID=4 
DROP MATERIALIZED VIEW YJ_ITEM_LOC_SLS_2013_R;
CREATE MATERIALIZED VIEW YJ_ITEM_LOC_SLS_2013_R
AS
SELECT SUBSTR(A.DT_WID, 2, 4) YEAR,
			 D.PROD_NUM ITEM,
			 O.ORG_NUM LOC,
			 SUM(NVL(A.SLS_QTY, 0) - NVL(A.RET_QTY, 0)) SALESQTY,
			 SUM(NVL(A.SLS_AMT_LCL, 0) - NVL(A.RET_AMT_LCL, 0)) SALESAMT,
			 SUM((NVL(A.SLS_AMT_LCL, 0) - NVL(A.RET_AMT_LCL, 0)) -
			 (NVL(A.Sls_Tax_Amt_Lcl, 0) - NVL(A.Ret_Tax_Amt_Lcl, 0))) NOTAX_SALESAMT,
			 --SUM(NVL(A.BBG_REFERENCE_FO2, 0)) NOTAX_COSTAMT
			 SUM(((NVL(A.SLS_AMT_LCL, 0) - NVL(A.RET_AMT_LCL, 0)) -
			 (NVL(A.Sls_Tax_Amt_Lcl, 0) - NVL(A.Ret_Tax_Amt_Lcl, 0)))-NVL(A.SLS_PROFIT_AMT_LCL,0)) NOTAX_COSTAMT
	FROM W_RTL_SLS_IT_LC_DY_A A, W_PRODUCT_D D, W_INT_ORG_D O
 WHERE A.PROD_WID = D.ROW_WID
	 AND A.ORG_WID = O.ROW_WID
	 AND A.DT_WID BETWEEN '120130101000' AND '120131231000'
	 AND A.RTL_TYPE_WID=4
 GROUP BY SUBSTR(A.DT_WID, 2, 4), D.PROD_NUM, O.ORG_NUM; 
 
--导出销售
--YJ_SUPP_SLS_20140106全部销售
--YJ_SUPP_SLS_20140106_R正常销售
DROP MATERIALIZED VIEW YJ_SUPP_SLS_20140106_R;
CREATE MATERIALIZED VIEW YJ_SUPP_SLS_20140106_R
AS
  select * from ksl_supplier_tmp a,(SELECT YJ.*, YJ.NOTAX_COSTAMT / (1 - VAT.VAT_RATE / 100) COSTAMT
           FROM YJ_ITEM_LOC_SLS_2013_R@RMS_RA YJ, V_CMX_COST_VAT_ITEM VAT
          WHERE YJ.ITEM = VAT.ITEM) b
          where A."门店编码"=b.loc(+)
          and A."主要条码"=B.ITEM(+);
