SELECT A.PROD_NUM, COUNT(*)
  FROM (SELECT DISTINCT T.PROD_NUM, T.SCD1_WID FROM RADM.W_PRODUCT_D T) A
 GROUP BY A.PROD_NUM
HAVING COUNT(*) > 1
 ORDER BY A.PROD_NUM;

SELECT T.PROD_NUM,
       T.INTEGRATION_ID,
       T.SCD1_WID,
       T.CURRENT_FLG,
       T.EFFECTIVE_FROM_DT,
       T.EFFECTIVE_TO_DT
  FROM RADM.W_PRODUCT_D T
	WHERE T.PROD_NUM='100029100';
