SELECT DISTINCT PROD_CAT5_AS_WAS
  FROM RADM.W_PRODUCT_D P
 WHERE PROD_CAT5_AS_WAS LIKE '2~17~17~175%';
SELECT *
  FROM RADM.W_PRODUCT_D P
 WHERE PROD_CAT5_AS_WAS LIKE '2~17~17~175%';
SELECT * FROM RADM.W_PRODUCT_DS_TL A WHERE A.INTEGRATION_ID = 101466651;
SELECT * FROM RADM.W_PRO;
SELECT SUBSTR(P.PROD_CAT5_AS_WAS, 13, 4) SUBCALSS,
       P.PROD_NUM,
       A.PRODUCT_NAME
  FROM RADM.W_PRODUCT_D P, RADM.W_PRODUCT_D_TL A
 WHERE P.DATASOURCE_NUM_ID = A.DATASOURCE_NUM_ID
   AND P.INTEGRATION_ID = A.INTEGRATION_ID
   AND A.LANGUAGE_CODE = 'ZHS'
   AND P.CURRENT_FLG = 'Y'
   AND P.PROD_CAT5_AS_WAS LIKE '2~17~17~175%';

SELECT IL.ITEM,COUNT(*)
  FROM RADM.BBG_RA_ITEM_LOC_D IL
 WHERE IL.CURRENT_FLG = 'Y'
   AND EXISTS (SELECT 1
          FROM RADM.W_PRODUCT_D P, RADM.W_PRODUCT_D_TL A
         WHERE P.DATASOURCE_NUM_ID = A.DATASOURCE_NUM_ID
           AND P.INTEGRATION_ID = A.INTEGRATION_ID
           AND A.LANGUAGE_CODE = 'ZHS'
           AND P.CURRENT_FLG = 'Y'
           AND P.PROD_CAT5_AS_WAS LIKE '2~17~17~175%'
           AND P.PROD_NUM = IL.ITEM)
					 GROUP BY IL.ITEM
					 ORDER BY IL.ITEM;
