DROP TABLE RADM.JIN_LXJ_TMP;

CREATE TABLE RMS.JIN_LXJ_TMP AS
SELECT * FROM RADM.JIN_LXJ_TMP@RMS_RA;

DROP TABLE RMS.JIN_LXJ_TMP;

CREATE TABLE ZFL.JIN_LXJ_TMP1 AS
SELECT * FROM RMS.JIN_LXJ_TMP@RTK;

DROP TABLE ZFL.JIN_LXJ_TMP;


--天/门店/大类/净销售数量/净销售额/净利润
--CREATE TABLE RADM.JIN_LXJ_TMP AS
SELECT /*+PARALLEL(T,20) PARALLEL(O,20) PARALLEL(P,20)*/ SUBSTR(T.DT_WID, 2, 8) DAY,
       O.ORG_NUM LOC,
       P.LVL6ANC_PRODCAT_ID DEPT,
			 SUM(T.SLS_QTY-T.RET_QTY) QTY,
       SUM((T.SLS_AMT_LCL - T.RET_AMT_LCL) -
           (T.SLS_TAX_AMT_LCL - T.RET_TAX_AMT_LCL)) AMT,
       SUM(T.SLS_PROFIT_AMT_LCL - T.RET_PROFIT_AMT_LCL) PROFIT
  FROM RADM.W_RTL_SLS_DP_LC_DY_A T,
       RADM.W_INT_ORG_D          O,
       RADM.W_PROD_CAT_DH        P
 WHERE T.ORG_WID = O.ROW_WID
   AND T.PROD_DH_WID = P.ROW_WID
   AND P.LEVEL_NAME = 'DEPT'
   AND T.DT_WID BETWEEN 120140101000 AND 120150326000
 GROUP BY SUBSTR(T.DT_WID, 2, 8), O.ORG_NUM, P.LVL6ANC_PRODCAT_ID
 ORDER BY SUBSTR(T.DT_WID, 2, 8), O.ORG_NUM, P.LVL6ANC_PRODCAT_ID;

--天/门店/大类/来客数
SELECT /*+PARALLEL(T,20) PARALLEL(O,20) PARALLEL(P,20)*/
 SUBSTR(T.DT_WID, 2, 8) DAY,
 O.ORG_NUM LOC,
 P.LVL6ANC_PRODCAT_ID DEPT,
 SUM(T.BBG_CUSTOMER_COUNT) BBG_CUSTOMER_COUNT
  FROM RADM.BBG_RA_CUST_DP_LC_DY_A T,
       RADM.W_INT_ORG_D            O,
       RADM.W_PROD_CAT_DH          P
 WHERE T.ORG_WID = O.ROW_WID
   AND T.PROD_DH_WID = P.ROW_WID
   AND P.LEVEL_NAME = 'DEPT'
   AND T.DT_WID BETWEEN 120140101000 AND 120150326000
 GROUP BY SUBSTR(T.DT_WID, 2, 8), O.ORG_NUM, P.LVL6ANC_PRODCAT_ID
 ORDER BY SUBSTR(T.DT_WID, 2, 8), O.ORG_NUM, P.LVL6ANC_PRODCAT_ID;

--来客数 from W_RTL_SLS_TRX_IT_LC_DY_F
CREATE TABLE RADM.JIN_LXJ1_TMP AS
SELECT /*+PARALLEL(S,20) PARALLEL(P,20) PARALLEL(O,20)*/
 O.ORG_NUM LOC,
 P.PROD_DP_NUM DEPT,
 COUNT(DISTINCT S.SLS_TRX_ID) BBG_CUST,
 TO_DATE(SUBSTR(S.DT_WID, 2, 8), 'YYYYMMDD') DAY
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F S,
       RABATCHER.W_PRODUCT_D_RTL_TMP P,
       RADM.W_INT_ORG_D              O
 WHERE S.PROD_WID = P.PROD_IT_WID
   AND S.ORG_WID = O.ROW_WID
   AND S.DT_WID BETWEEN 120140101000 AND 120150326000
 GROUP BY O.ORG_NUM,
          P.PROD_DP_NUM,
          TO_DATE(SUBSTR(S.DT_WID, 2, 8), 'YYYYMMDD');


--合并
CREATE TABLE RADM.JIN_LXJ_TMP AS
SELECT S.DAY, S.LOC, S.DEPT, S.QTY, S.AMT, C.BBG_CUSTOMER_COUNT
  FROM (SELECT /*+PARALLEL(T,20) PARALLEL(O,20) PARALLEL(P,20)*/
         SUBSTR(T.DT_WID, 2, 8) DAY,
         O.ORG_NUM LOC,
         P.LVL6ANC_PRODCAT_ID DEPT,
         SUM(T.SLS_QTY - T.RET_QTY) QTY,
         SUM((T.SLS_AMT_LCL - T.RET_AMT_LCL) -
             (T.SLS_TAX_AMT_LCL - T.RET_TAX_AMT_LCL)) AMT,
         SUM(T.SLS_PROFIT_AMT_LCL - T.RET_PROFIT_AMT_LCL) PROFIT
          FROM RADM.W_RTL_SLS_DP_LC_DY_A T,
               RADM.W_INT_ORG_D          O,
               RADM.W_PROD_CAT_DH        P
         WHERE T.ORG_WID = O.ROW_WID
           AND T.PROD_DH_WID = P.ROW_WID
           AND P.LEVEL_NAME = 'DEPT'
           AND T.DT_WID BETWEEN 120140101000 AND 120150326000
         GROUP BY SUBSTR(T.DT_WID, 2, 8), O.ORG_NUM, P.LVL6ANC_PRODCAT_ID
         ORDER BY SUBSTR(T.DT_WID, 2, 8), O.ORG_NUM, P.LVL6ANC_PRODCAT_ID) S,
       (SELECT /*+PARALLEL(T,20) PARALLEL(O,20) PARALLEL(P,20)*/
         SUBSTR(T.DT_WID, 2, 8) DAY,
         O.ORG_NUM LOC,
         P.LVL6ANC_PRODCAT_ID DEPT,
         SUM(T.BBG_CUSTOMER_COUNT) BBG_CUSTOMER_COUNT
          FROM RADM.BBG_RA_CUST_DP_LC_DY_A T,
               RADM.W_INT_ORG_D            O,
               RADM.W_PROD_CAT_DH          P
         WHERE T.ORG_WID = O.ROW_WID
           AND T.PROD_DH_WID = P.ROW_WID
           AND P.LEVEL_NAME = 'DEPT'
           AND T.DT_WID BETWEEN 120140101000 AND 120150326000
         GROUP BY SUBSTR(T.DT_WID, 2, 8), O.ORG_NUM, P.LVL6ANC_PRODCAT_ID
         ORDER BY SUBSTR(T.DT_WID, 2, 8), O.ORG_NUM, P.LVL6ANC_PRODCAT_ID) C
 WHERE S.DAY = C.DAY(+)
   AND S.LOC = C.LOC(+)
   AND S.DEPT = C.DEPT(+);

SELECT (T.SLS_AMT_LCL - T.RET_AMT_LCL) -
       (T.SLS_TAX_AMT_LCL - T.RET_TAX_AMT_LCL),
       T.SLS_AMT_LCL,
       T.RET_AMT_LCL,
       T.SLS_TAX_AMT_LCL,
       T.RET_TAX_AMT_LCL,
			 T.INTEGRATION_ID
  FROM RADM.W_RTL_SLS_DP_LC_DY_A T
 WHERE T.DT_WID BETWEEN 120140601000 AND 120150110000
   AND (T.SLS_AMT_LCL - T.RET_AMT_LCL) -
       (T.SLS_TAX_AMT_LCL - T.RET_TAX_AMT_LCL) = 0;
