SELECT A.ITEM, A.LOC, A.NBO, B.NBO
  FROM (SELECT * FROM CMX_ITEM_LOC_INFO@RA_RMS_DBLINK D WHERE D.NBO = 'Y') A,
       (SELECT *
          FROM RADM.BBG_RA_ITEM_LOC_D C
         WHERE C.CURRENT_FLG = 'Y'
           AND C.NBO = 'Y') B
 WHERE A.ITEM = B.ITEM(+)
   AND A.LOC = B.LOC(+)
   AND A.NBO <> B.NBO;

SELECT * FROM CMX_ITEM_LOC_INFO@RA_RMS_DBLINK A WHERE A.NBO = 'Y';

SELECT * FROM RADM.BBG_RA_ITEM_LOC_D B WHERE B.NBO = 'Y';

SELECT B.ITEM, B.LOC, COUNT(1)
  FROM RADM.BBG_RA_ITEM_LOC_D B
 WHERE B.CURRENT_FLG = 'Y'
 GROUP BY B.ITEM, B.LOC
HAVING COUNT(1) > 1;

SELECT *
  FROM RADM.BBG_RA_ITEM_LOC_D B
 WHERE B.ITEM = 800039482
   AND B.LOC = 120162;
