--原来客数
SELECT * FROM RADM.BBG_RA_CUST_DP_LC_DY_FV;
SELECT * FROM RADM.BBG_RA_CUST_CL_LC_DY_FV;
SELECT * FROM RADM.BBG_RA_CUST_SC_LC_DY_FV;
SELECT * FROM RADM.BBG_RA_CUST_DV_LC_DY_FV;
SELECT * FROM RADM.BBG_RA_CUST_GP_LC_DY_FV;
--
SELECT * FROM RADM.BBG_RA_CUST_LC_DY_A_TST;
SELECT * FROM RADM.BBG_RA_CUST_DP_LC_DY_A_TST;
SELECT * FROM RADM.BBG_RA_CUST_CL_LC_DY_A_TST;
SELECT * FROM RADM.BBG_RA_CUST_SC_LC_DY_A_TST;
--差异原因为:有部分商品曾经变更过类别,而原视图没有加是否有效条件

SELECT /*+PARALLEL(T,20) PARALLEL(S,20)*/
 *
  FROM RADM.BBG_RA_CUST_SC_LC_DY_A_TST T, RADM.BBG_RA_CUST_SC_LC_DY_A S
 WHERE T.DT_WID = S.DT_WID
   AND T.PROD_DH_WID = S.PROD_DH_WID
   AND T.ORG_WID = S.ORG_WID
   AND T.BBG_CUSTOMER_COUNT <> S.BBG_CUSTOMER_COUNT
   AND T.DT_WID = 120150210000;

SELECT *
  FROM RABATCHER.BBG_RA_CUST_SC_LC_DY_TMP T
 WHERE T.DT_WID = 120150210000
   AND T.ORG_NUM = '120056'
   AND T.PROD_SC_NUM = '2921';

SELECT DISTINCT T.SLS_TRX_ID
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK T
 WHERE T.ORG_NUM = '120056'
   AND EXISTS (SELECT 1
          FROM RABATCHER.W_PRODUCT_D_RTL_TMP P
         WHERE T.PROD_IT_NUM = P.PROD_IT_NUM
           AND P.PROD_SC_NUM = '2921');

SELECT /*+PARALLEL(T,20)*/
DISTINCT T.SLS_TRX_ID
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F T
 WHERE T.DT_WID = 120150210000
   AND EXISTS (SELECT /*+PARALLEL(O,20)*/
         1
          FROM RADM.W_INT_ORG_D O
         WHERE T.ORG_WID = O.ROW_WID
           AND O.ORG_NUM = '120056')
   AND EXISTS (SELECT /*+PARALLEL(P,20)*/
         1
          FROM RABATCHER.W_PRODUCT_D_RTL_TMP P
         WHERE T.PROD_WID = P.PROD_IT_WID
           AND P.PROD_SC_NUM = '2921');

SELECT *
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_FS_BAK T
 WHERE T.SLS_TRX_ID = '536711465           ';
SELECT /*+PARALLEL(T,20)*/ *
  FROM RADM.W_RTL_SLS_TRX_IT_LC_DY_F T
 WHERE T.SLS_TRX_ID = '536711465           '
   AND T.DT_WID = 120150210000;
	 
