SELECT * FROM V$SQL T WHERE T.SQL_ID='04dqjq9dy070j';
SELECT * FROM V$SQL T WHERE T.SQL_ID='1k05443q3vtc9';
SELECT * FROM V$SQL T WHERE T.SQL_ID='657dxv999w655';

--04dqjq9dy070j
merge   /*+ APPEND */  into  
 RADM.W_RTL_BCOST_IT_DY_A T 
 using  
   (
   Select  /*+ APPEND */ 
   W_RTL_BCOST_IT_DY_TMP.PROD_IT_WID  PROD_WID,
  W_RTL_BCOST_IT_DY_TMP.PROD_SCD1_WID  PROD_SCD1_WID,
  W_RTL_BCOST_IT_DY_TMP.DT_WID  DT_WID,
  W_RTL_BCOST_IT_DY_TMP.SUPPLIER_WID  SUPPLIER_WID,
  W_RTL_BCOST_IT_DY_TMP.BASE_COST_AMT_LCL  BASE_COST_AMT_LCL,
  W_RTL_BCOST_IT_DY_TMP.BASE_COST_AMT  BASE_COST_AMT,
  W_RTL_BCOST_IT_DY_TMP.BASE_COST_AMT_GLOBAL1  BASE_COST_AMT_GLOBAL1,
  W_RTL_BCOST_IT_DY_TMP.BASE_COST_AMT_GLOBAL2  BASE_COST_AMT_GLOBAL2,
  W_RTL_BCOST_IT_DY_TMP.BASE_COST_AMT_GLOBAL3  BASE_COST_AMT_GLOBAL3,
  W_RTL_BCOST_IT_DY_TMP.DATASOURCE_NUM_ID  DATASOURCE_NUM_ID,
  W_RTL_BCOST_IT_DY_TMP.DELETE_FLG  DELETE_FLG,
  100  ETL_PROC_WID,
  W_RTL_BCOST_IT_DY_TMP.PROD_IT_NUM||'~'||W_RTL_BCOST_IT_DY_TMP.DAY_DT||'~'||W_RTL_BCOST_IT_DY_TMP.SUPPLIER_NUM  INTEGRATION_ID,
  W_RTL_BCOST_IT_DY_TMP.TENANT_ID  TENANT_ID,
  SYSDATE  W_INSERT_DT,
  SYSDATE  W_UPDATE_DT,
  W_RTL_BCOST_IT_DY_TMP.X_CUSTOM  X_CUSTOM,
  W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_DO1  BBG_REFERENCE_DO1,
  W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_DO2  BBG_REFERENCE_DO2,
  W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_DO3  BBG_REFERENCE_DO3,
  W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_DO4  BBG_REFERENCE_DO4,
  W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_DO5  BBG_REFERENCE_DO5,
  W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO1  BBG_REFERENCE_FO1,
  W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO2  BBG_REFERENCE_FO2,
  W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO3  BBG_REFERENCE_FO3,
  W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO4  BBG_REFERENCE_FO4,
  W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO5  BBG_REFERENCE_FO5,
  W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO6  BBG_REFERENCE_FO6,
  W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO7  BBG_REFERENCE_FO7,
  W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO8  BBG_REFERENCE_FO8,
  W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO9  BBG_REFERENCE_FO9,
  W_RTL_BCOST_IT_DY_TMP.BBG_REFERENCE_FO10  BBG_REFERENCE_FO10
   
   From RABATCHER.W_RTL_BCOST_IT_DY_TMP   W_RTL_BCOST_IT_DY_TMP
        Where  (1=1)
  
  
  
  
   ) S
 on  (
     T.PROD_WID=S.PROD_WID
  and    T.PROD_SCD1_WID=S.PROD_SCD1_WID
  and    T.DT_WID=S.DT_WID
  and    T.SUPPLIER_WID=S.SUPPLIER_WID
   )
 when matched
 then update set
   T.BASE_COST_AMT_LCL = S.BASE_COST_AMT_LCL,
  T.BASE_COST_AMT = S.BASE_COST_AMT,
  T.BASE_COST_AMT_GLOBAL1 = S.BASE_COST_AMT_GLOBAL1,
  T.BASE_COST_AMT_GLOBAL2 = S.BASE_COST_AMT_GLOBAL2,
  T.BASE_COST_AMT_GLOBAL3 = S.BASE_COST_AMT_GLOBAL3,
  T.DATASOURCE_NUM_ID = S.DATASOURCE_NUM_ID,
  T.DELETE_FLG = S.DELETE_FLG,
  T.ETL_PROC_WID = S.ETL_PROC_WID,
  T.INTEGRATION_ID = S.INTEGRATION_ID,
  T.TENANT_ID = S.TENANT_ID,
  T.W_UPDATE_DT = S.W_UPDATE_DT,
  T.X_CUSTOM = S.X_CUSTOM,
  T.BBG_REFERENCE_DO1 = S.BBG_REFERENCE_DO1,
  T.BBG_REFERENCE_DO2 = S.BBG_REFERENCE_DO2,
  T.BBG_REFERENCE_DO3 = S.BBG_REFERENCE_DO3,
  T.BBG_REFERENCE_DO4 = S.BBG_REFERENCE_DO4,
  T.BBG_REFERENCE_DO5 = S.BBG_REFERENCE_DO5,
  T.BBG_REFERENCE_FO1 = S.BBG_REFERENCE_FO1,
  T.BBG_REFERENCE_FO2 = S.BBG_REFERENCE_FO2,
  T.BBG_REFERENCE_FO3 = S.BBG_REFERENCE_FO3,
  T.BBG_REFERENCE_FO4 = S.BBG_REFERENCE_FO4,
  T.BBG_REFERENCE_FO5 = S.BBG_REFERENCE_FO5,
  T.BBG_REFERENCE_FO6 = S.BBG_REFERENCE_FO6,
  T.BBG_REFERENCE_FO7 = S.BBG_REFERENCE_FO7,
  T.BBG_REFERENCE_FO8 = S.BBG_REFERENCE_FO8,
  T.BBG_REFERENCE_FO9 = S.BBG_REFERENCE_FO9,
  T.BBG_REFERENCE_FO10 = S.BBG_REFERENCE_FO10
   
  
 when not matched
 then insert
   (
   
    T.ROW_WID
                ,T.PROD_WID,
  T.PROD_SCD1_WID,
  T.DT_WID,
  T.SUPPLIER_WID,
  T.BASE_COST_AMT_LCL,
  T.BASE_COST_AMT,
  T.BASE_COST_AMT_GLOBAL1,
  T.BASE_COST_AMT_GLOBAL2,
  T.BASE_COST_AMT_GLOBAL3,
  T.DATASOURCE_NUM_ID,
  T.DELETE_FLG,
  T.ETL_PROC_WID,
  T.INTEGRATION_ID,
  T.TENANT_ID,
  T.W_INSERT_DT,
  T.W_UPDATE_DT,
  T.X_CUSTOM,
  T.BBG_REFERENCE_DO1,
  T.BBG_REFERENCE_DO2,
  T.BBG_REFERENCE_DO3,
  T.BBG_REFERENCE_DO4,
  T.BBG_REFERENCE_DO5,
  T.BBG_REFERENCE_FO1,
  T.BBG_REFERENCE_FO2,
  T.BBG_REFERENCE_FO3,
  T.BBG_REFERENCE_FO4,
  T.BBG_REFERENCE_FO5,
  T.BBG_REFERENCE_FO6,
  T.BBG_REFERENCE_FO7,
  T.BBG_REFERENCE_FO8,
  T.BBG_REFERENCE_FO9,
  T.BBG_REFERENCE_FO10
  
     
   )
 values
   (
  
    RADM.W_RTL_BCOST_IT_DY_A_SEQ.NEXTVAL
    ,S.PROD_WID,
  S.PROD_SCD1_WID,
  S.DT_WID,
  S.SUPPLIER_WID,
  S.BASE_COST_AMT_LCL,
  S.BASE_COST_AMT,
  S.BASE_COST_AMT_GLOBAL1,
  S.BASE_COST_AMT_GLOBAL2,
  S.BASE_COST_AMT_GLOBAL3,
  S.DATASOURCE_NUM_ID,
  S.DELETE_FLG,
  S.ETL_PROC_WID,
  S.INTEGRATION_ID,
  S.TENANT_ID,
  S.W_INSERT_DT,
  S.W_UPDATE_DT,
  S.X_CUSTOM,
  S.BBG_REFERENCE_DO1,
  S.BBG_REFERENCE_DO2,
  S.BBG_REFERENCE_DO3,
  S.BBG_REFERENCE_DO4,
  S.BBG_REFERENCE_DO5,
  S.BBG_REFERENCE_FO1,
	S.BBG_REFERENCE_FO2,
	S.BBG_REFERENCE_FO3,
	S.BBG_REFERENCE_FO4,
	S.BBG_REFERENCE_FO5,
	S.BBG_REFERENCE_FO6,
	S.BBG_REFERENCE_FO7,
	S.BBG_REFERENCE_FO8,
	S.BBG_REFERENCE_FO9,
	S.BBG_REFERENCE_FO10
	
 	
	);
--1k05443q3vtc9
merge   /*+ APPEND */  into  
 RADM.BBG_RA_CUST_IT_LC_DY_F T 
 using  
   (
   Select  /*+ APPEND */ 
   BBG_RA_CUST_IT_LC_DY_TMP.PROD_IT_WID  PROD_WID,
  BBG_RA_CUST_IT_LC_DY_TMP.PROD_SCD1_WID  PROD_SCD1_WID,
  BBG_RA_CUST_IT_LC_DY_TMP.ORG_WID  ORG_WID,
  BBG_RA_CUST_IT_LC_DY_TMP.ORG_LC_WID  ORG_DH_WID,
  BBG_RA_CUST_IT_LC_DY_TMP.ORG_SCD1_WID  ORG_SCD1_WID,
  BBG_RA_CUST_IT_LC_DY_TMP.DT_WID  DT_WID,
  BBG_RA_CUST_IT_LC_DY_TMP.BBG_ITEM_LOC_WID  BBG_ITEM_LOC_WID,
  BBG_RA_CUST_IT_LC_DY_TMP.BBG_CUSTOMER_COUNT  BBG_CUSTOMER_COUNT,
  BBG_RA_CUST_IT_LC_DY_TMP.BBG_SERVICE_SATISFACTION  BBG_SERVICE_SATISFACTION,
  BBG_RA_CUST_IT_LC_DY_TMP.DATASOURCE_NUM_ID  DATASOURCE_NUM_ID,
  BBG_RA_CUST_IT_LC_DY_TMP.INTEGRATION_ID  INTEGRATION_ID,
  BBG_RA_CUST_IT_LC_DY_TMP.W_INSERT_DT  W_INSERT_DT,
  BBG_RA_CUST_IT_LC_DY_TMP.W_UPDATE_DT  W_UPDATE_DT
   
   From RABATCHER.BBG_RA_CUST_IT_LC_DY_TMP   BBG_RA_CUST_IT_LC_DY_TMP
        Where  (1=1)
  
  
  
  
   ) S
 on  (
     T.PROD_WID=S.PROD_WID
  and    T.ORG_WID=S.ORG_WID
  and    T.DT_WID=S.DT_WID
  and    T.BBG_ITEM_LOC_WID=S.BBG_ITEM_LOC_WID
   )
 when matched
 then update set
   T.PROD_SCD1_WID = S.PROD_SCD1_WID,
  T.ORG_DH_WID = S.ORG_DH_WID,
  T.ORG_SCD1_WID = S.ORG_SCD1_WID,
  T.BBG_CUSTOMER_COUNT = S.BBG_CUSTOMER_COUNT,
  T.BBG_SERVICE_SATISFACTION = S.BBG_SERVICE_SATISFACTION,
  T.DATASOURCE_NUM_ID = S.DATASOURCE_NUM_ID,
  T.INTEGRATION_ID = S.INTEGRATION_ID,
  T.W_INSERT_DT = S.W_INSERT_DT,
  T.W_UPDATE_DT = S.W_UPDATE_DT
   
  
 when not matched
 then insert
   (
   
    T.ROW_WID
                ,T.PROD_WID,
  T.PROD_SCD1_WID,
  T.ORG_WID,
  T.ORG_DH_WID,
  T.ORG_SCD1_WID,
  T.DT_WID,
  T.BBG_ITEM_LOC_WID,
  T.BBG_CUSTOMER_COUNT,
  T.BBG_SERVICE_SATISFACTION,
  T.DATASOURCE_NUM_ID,
  T.INTEGRATION_ID,
  T.W_INSERT_DT,
  T.W_UPDATE_DT
  
     
   )
 values
   (
  
    RADM.BBG_RA_CUST_IT_LC_DY_F_SEQ.NEXTVAL
    ,S.PROD_WID,
  S.PROD_SCD1_WID,
	S.ORG_WID,
	S.ORG_DH_WID,
	S.ORG_SCD1_WID,
	S.DT_WID,
	S.BBG_ITEM_LOC_WID,
	S.BBG_CUSTOMER_COUNT,
	S.BBG_SERVICE_SATISFACTION,
	S.DATASOURCE_NUM_ID,
	S.INTEGRATION_ID,
	S.W_INSERT_DT,
	S.W_UPDATE_DT
	
 	
	);
--657dxv999w655
merge   /*+ APPEND */  into  
 RADM.BBG_RA_SLS_IT_LC_DY_A T 
 using  
   (
   Select  /*+ APPEND */ 
   BBG_RA_SUPP_SLS_IT_LC_DY_TMP.PROD_IT_WID  PROD_WID,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.PROD_SCD1_WID)  PROD_SCD1_WID,
  BBG_RA_SUPP_SLS_IT_LC_DY_TMP.ORG_WID  ORG_WID,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.ORG_SCD1_WID)  ORG_SCD1_WID,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.ORG_LC_WID)  ORG_DH_WID,
  BBG_RA_SUPP_SLS_IT_LC_DY_TMP.DT_WID  DT_WID,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.DATASOURCE_NUM_ID)  DATASOURCE_NUM_ID,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.DELETE_FLG)  DELETE_FLG,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.DOC_CURR_CODE)  DOC_CURR_CODE,
  100  ETL_PROC_WID,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.GLOBAL1_EXCHANGE_RATE)  GLOBAL1_EXCHANGE_RATE,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.GLOBAL2_EXCHANGE_RATE)  GLOBAL2_EXCHANGE_RATE,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.GLOBAL3_EXCHANGE_RATE)  GLOBAL3_EXCHANGE_RATE,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.PROD_IT_NUM||'~'|| BBG_RA_SUPP_SLS_IT_LC_DY_TMP.ORG_NUM  ||'~'|| BBG_RA_SUPP_SLS_IT_LC_DY_TMP.DAY_DT ||'~'||BBG_RA_SUPP_SLS_IT_LC_DY_TMP.SUPPLIER_NUM)  INTEGRATION_ID,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.LOC_CURR_CODE)  LOC_CURR_CODE,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.LOC_EXCHANGE_RATE)  LOC_EXCHANGE_RATE,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.TENANT_ID)  TENANT_ID,
  SYSDATE  W_INSERT_DT,
  SYSDATE  W_UPDATE_DT,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.X_CUSTOM)  X_CUSTOM,
  BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_ITEM_LOC_WID  BBG_ITEM_LOC_WID,
  BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_ITEM_LOC_SUPP_WID  BBG_ITEM_LOC_SUPP_WID,
  BBG_RA_SUPP_SLS_IT_LC_DY_TMP.SUPPLIER_WID  SUPPLIER_WID,
  BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_REFERENCE_DO1  BBG_REFERENCE_DO1,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_REFERENCE_DO2)  BBG_REFERENCE_DO2,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_REFERENCE_DO3)  BBG_REFERENCE_DO3,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_REFERENCE_DO4)  BBG_REFERENCE_DO4,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_REFERENCE_DO5)  BBG_REFERENCE_DO5,
  SUM(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_REFERENCE_FO1)  BBG_REFERENCE_FO1,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_REFERENCE_FO2)  BBG_REFERENCE_FO2,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_REFERENCE_FO3)  BBG_REFERENCE_FO3,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_REFERENCE_FO4)  BBG_REFERENCE_FO4,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_REFERENCE_FO5)  BBG_REFERENCE_FO5,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_REFERENCE_FO6)  BBG_REFERENCE_FO6,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_REFERENCE_FO7)  BBG_REFERENCE_FO7,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_REFERENCE_FO8)  BBG_REFERENCE_FO8,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_REFERENCE_FO9)  BBG_REFERENCE_FO9,
  MAX(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_REFERENCE_FO10)  BBG_REFERENCE_FO10
   ,SUM(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.SUPP_SALES_QTY)  SUPP_SALES_QTY,
  SUM(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.SUPP_SALES_COST)  SUPP_SALES_COST,
  SUM(BBG_RA_SUPP_SLS_IT_LC_DY_TMP.SUPP_SALES_AMT)  SUPP_SALES_AMT
   From RABATCHER.BBG_RA_SUPP_SLS_IT_LC_DY_TMP   BBG_RA_SUPP_SLS_IT_LC_DY_TMP
        Where  (1=1)
  
  
  Group By BBG_RA_SUPP_SLS_IT_LC_DY_TMP.PROD_IT_WID,
 BBG_RA_SUPP_SLS_IT_LC_DY_TMP.ORG_WID,
 BBG_RA_SUPP_SLS_IT_LC_DY_TMP.DT_WID,
 BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_ITEM_LOC_WID,
 BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_ITEM_LOC_SUPP_WID,
 BBG_RA_SUPP_SLS_IT_LC_DY_TMP.SUPPLIER_WID,
 BBG_RA_SUPP_SLS_IT_LC_DY_TMP.BBG_REFERENCE_DO1
  
   ) S
 on  (
     T.PROD_WID=S.PROD_WID
  and    T.ORG_WID=S.ORG_WID
  and    T.DT_WID=S.DT_WID
  and    T.BBG_ITEM_LOC_WID=S.BBG_ITEM_LOC_WID
  and    T.BBG_ITEM_LOC_SUPP_WID=S.BBG_ITEM_LOC_SUPP_WID
  and    T.SUPPLIER_WID=S.SUPPLIER_WID
  and    T.BBG_REFERENCE_DO1=S.BBG_REFERENCE_DO1
   )
 when matched
 then update set
   T.PROD_SCD1_WID = S.PROD_SCD1_WID,
  T.ORG_SCD1_WID = S.ORG_SCD1_WID,
  T.ORG_DH_WID = S.ORG_DH_WID,
  T.DATASOURCE_NUM_ID = S.DATASOURCE_NUM_ID,
  T.DELETE_FLG = S.DELETE_FLG,
  T.DOC_CURR_CODE = S.DOC_CURR_CODE,
  T.ETL_PROC_WID = S.ETL_PROC_WID,
  T.GLOBAL1_EXCHANGE_RATE = S.GLOBAL1_EXCHANGE_RATE,
  T.GLOBAL2_EXCHANGE_RATE = S.GLOBAL2_EXCHANGE_RATE,
  T.GLOBAL3_EXCHANGE_RATE = S.GLOBAL3_EXCHANGE_RATE,
  T.INTEGRATION_ID = S.INTEGRATION_ID,
  T.LOC_CURR_CODE = S.LOC_CURR_CODE,
  T.LOC_EXCHANGE_RATE = S.LOC_EXCHANGE_RATE,
  T.TENANT_ID = S.TENANT_ID,
  T.W_INSERT_DT = S.W_INSERT_DT,
  T.W_UPDATE_DT = S.W_UPDATE_DT,
  T.X_CUSTOM = S.X_CUSTOM,
  T.BBG_REFERENCE_DO2 = S.BBG_REFERENCE_DO2,
  T.BBG_REFERENCE_DO3 = S.BBG_REFERENCE_DO3,
  T.BBG_REFERENCE_DO4 = S.BBG_REFERENCE_DO4,
  T.BBG_REFERENCE_DO5 = S.BBG_REFERENCE_DO5,
  T.BBG_REFERENCE_FO1 = S.BBG_REFERENCE_FO1,
  T.BBG_REFERENCE_FO2 = S.BBG_REFERENCE_FO2,
  T.BBG_REFERENCE_FO3 = S.BBG_REFERENCE_FO3,
  T.BBG_REFERENCE_FO4 = S.BBG_REFERENCE_FO4,
  T.BBG_REFERENCE_FO5 = S.BBG_REFERENCE_FO5,
  T.BBG_REFERENCE_FO6 = S.BBG_REFERENCE_FO6,
  T.BBG_REFERENCE_FO7 = S.BBG_REFERENCE_FO7,
  T.BBG_REFERENCE_FO8 = S.BBG_REFERENCE_FO8,
  T.BBG_REFERENCE_FO9 = S.BBG_REFERENCE_FO9,
  T.BBG_REFERENCE_FO10 = S.BBG_REFERENCE_FO10
   ,T.SUPP_SALES_QTY = S.SUPP_SALES_QTY + T.SUPP_SALES_QTY,
  T.SUPP_SALES_COST = S.SUPP_SALES_COST + T.SUPP_SALES_COST,
  T.SUPP_SALES_AMT = S.SUPP_SALES_AMT + T.SUPP_SALES_AMT
  
 when not matched
 then insert
   (
   
    T.ROW_WID
                ,T.PROD_WID,
  T.PROD_SCD1_WID,
  T.ORG_WID,
  T.ORG_SCD1_WID,
  T.ORG_DH_WID,
  T.DT_WID,
  T.DATASOURCE_NUM_ID,
  T.DELETE_FLG,
  T.DOC_CURR_CODE,
  T.ETL_PROC_WID,
  T.GLOBAL1_EXCHANGE_RATE,
  T.GLOBAL2_EXCHANGE_RATE,
  T.GLOBAL3_EXCHANGE_RATE,
  T.INTEGRATION_ID,
  T.LOC_CURR_CODE,
  T.LOC_EXCHANGE_RATE,
  T.TENANT_ID,
  T.W_INSERT_DT,
  T.W_UPDATE_DT,
  T.X_CUSTOM,
  T.BBG_ITEM_LOC_WID,
  T.BBG_ITEM_LOC_SUPP_WID,
  T.SUPPLIER_WID,
  T.SUPP_SALES_QTY,
  T.SUPP_SALES_COST,
  T.SUPP_SALES_AMT,
  T.BBG_REFERENCE_DO1,
  T.BBG_REFERENCE_DO2,
  T.BBG_REFERENCE_DO3,
  T.BBG_REFERENCE_DO4,
  T.BBG_REFERENCE_DO5,
  T.BBG_REFERENCE_FO1,
  T.BBG_REFERENCE_FO2,
  T.BBG_REFERENCE_FO3,
  T.BBG_REFERENCE_FO4,
  T.BBG_REFERENCE_FO5,
  T.BBG_REFERENCE_FO6,
  T.BBG_REFERENCE_FO7,
  T.BBG_REFERENCE_FO8,
  T.BBG_REFERENCE_FO9,
  T.BBG_REFERENCE_FO10
  
     
   )
 values
   (
  
    RADM.BBG_RA_SLS_IT_LC_DY_A_SEQ.nextval
    ,S.PROD_WID,
  S.PROD_SCD1_WID,
  S.ORG_WID,
  S.ORG_SCD1_WID,
  S.ORG_DH_WID,
  S.DT_WID,
  S.DATASOURCE_NUM_ID,
  S.DELETE_FLG,
  S.DOC_CURR_CODE,
  S.ETL_PROC_WID,
  S.GLOBAL1_EXCHANGE_RATE,
  S.GLOBAL2_EXCHANGE_RATE,
  S.GLOBAL3_EXCHANGE_RATE,
  S.INTEGRATION_ID,
  S.LOC_CURR_CODE,
  S.LOC_EXCHANGE_RATE,
  S.TENANT_ID,
  S.W_INSERT_DT,
  S.W_UPDATE_DT,
  S.X_CUSTOM,
  S.BBG_ITEM_LOC_WID,
  S.BBG_ITEM_LOC_SUPP_WID,
  S.SUPPLIER_WID,
  S.SUPP_SALES_QTY,
  S.SUPP_SALES_COST,
  S.SUPP_SALES_AMT,
  S.BBG_REFERENCE_DO1,
  S.BBG_REFERENCE_DO2,
  S.BBG_REFERENCE_DO3,
  S.BBG_REFERENCE_DO4,
  S.BBG_REFERENCE_DO5,
	S.BBG_REFERENCE_FO1,
	S.BBG_REFERENCE_FO2,
	S.BBG_REFERENCE_FO3,
	S.BBG_REFERENCE_FO4,
	S.BBG_REFERENCE_FO5,
	S.BBG_REFERENCE_FO6,
	S.BBG_REFERENCE_FO7,
	S.BBG_REFERENCE_FO8,
	S.BBG_REFERENCE_FO9,
	S.BBG_REFERENCE_FO10
	
 	
	);
