SELECT SUBSTR(TO_CHAR(T.DAY_DT, 'YYYYMMDD'), 1, 6) MONTH,
       SUM(T.BBG_REFERENCE_FO1) BBG_REFERENCE_FO1,
       SUM(T.SUPP_SALES_AMT) SUPP_SALES_AMT,
       SUM(T.SUPP_SALES_COST) SUPP_SALES_COST
  FROM RADM.BBG_RA_SUPP_SLS_REF T
 WHERE T.SUPPLIER_NUM = 29001981
 GROUP BY SUBSTR(TO_CHAR(T.DAY_DT, 'YYYYMMDD'), 1, 6);
