SELECT TO_CHAR(TRUNC(T.TRAN_DATE), 'YYYYMM') MONTH,
       T.LOCATION,
       T.DEPT,
       SUM(T.UNITS) QTY,
       SUM(T.TOTAL_RETAIL) AMT
  FROM RA_RMS.TRAN_DATA_HISTORY_PACK_V T
 WHERE T.TRAN_CODE IN (1, 3)
   AND T.TRAN_DATE BETWEEN DATE '2014-01-01' AND DATE
 '2014-12-31'
      --AND T.DEPT IN ('29')
   AND T.LOCATION = '120056'
 GROUP BY T.LOCATION, TO_CHAR(TRUNC(T.TRAN_DATE), 'YYYYMM'), T.DEPT
 ORDER BY T.LOCATION, TO_CHAR(TRUNC(T.TRAN_DATE), 'YYYYMM'), T.DEPT;

--3183001.9523

SELECT * FROM TRAN_DATA_CODES;
