--SIL_RETAILPROMOTIONDIMENSION±¨´í
--ORA-00001: unique constraint (RADM.PK_W_RTL_PROMO_D) violated

DELETE RADM.W_RTL_PROMO_DS A
 WHERE NOT EXISTS (SELECT 1
          FROM RADM.W_RTL_PROMO_D B
         WHERE A.INTEGRATION_ID = B.INTEGRATION_ID
           AND A.DATASOURCE_NUM_ID = B.DATASOURCE_NUM_ID
           AND B.CURRENT_FLG = 'Y')
   AND EXISTS (SELECT 1
          FROM RADM.W_RTL_PROMO_D C
         WHERE A.PROMO_EVENT_ID = C.PROMO_EVENT_ID
           AND A.PROMO_PARENT_ID = C.PROMO_PARENT_ID
           AND A.PROMO_COMPONENT_ID = C.PROMO_COMPONENT_ID
           AND A.PROMO_DETAIL_ID = C.PROMO_DETAIL_ID
           AND A.PROMO_LEVEL = C.PROMO_LEVEL);
COMMIT;

TRUNCATE TABLE RADM.C_LOAD_DATES;