CREATE OR REPLACE VIEW RA_RMS.TRAN_DATA_HISTORY_PACK_V AS
SELECT T.TRAN_DATE,
       TO_CHAR(T.ITEM) ITEM,
       T.LOCATION,
       T.DEPT,
       T.TRAN_CODE,
       T.VAT_RATE,
       SUM(UNITS)/SUM(p.PACK_QTY) UNITS,
       SUM(TOTAL_RETAIL) TOTAL_RETAIL,
       SUM(TOTAL_COST) TOTAL_COST
  FROM ra_rms.bbg_ra_TRAN_DATA_HISTORY_v  T, ra_rms.packitem_v P
 WHERE  t.ITEM=p.PACK_NO
 GROUP BY T.TRAN_DATE,
          TO_CHAR(T.ITEM),
          T.LOCATION,
          T.DEPT,
          T.TRAN_CODE,
          T.VAT_RATE
UNION ALL
SELECT T.TRAN_DATE,
       T.ITEM,
       T.LOCATION,
       T.DEPT,
       T.TRAN_CODE,
       T.VAT_RATE,
       SUM(UNITS) TOTAL_QTY,
       SUM(TOTAL_RETAIL) TOTAL_RETAIL,
       SUM(TOTAL_COST) TOTAL_COST
  FROM RMS.TRAN_DATA_HISTORY T
 WHERE T.REF_NO_1 IS NULL
   AND T.TRAN_CODE IN (1 ,2, 3)
   --AND T.PGM_NAME='posupld'
 GROUP BY T.TRAN_DATE, T.ITEM, T.LOCATION, T.DEPT, T.TRAN_CODE, T.VAT_RATE
;
