UPDATE RADM.W_PRODUCT_D A
   SET A.BBG_ITEM_PLACE_OF_ORIGIN =
       (SELECT /*+PARALLEL(15)*/
         B.BBG_ITEM_PLACE_OF_ORIGIN
          FROM BBG_RA_ITEM_CUSTOM_V@RA_RMS_DBLINK B
         WHERE A.PROD_NUM = B.ITEM)
 WHERE A.BBG_ITEM_PLACE_OF_ORIGIN IS NULL
   AND EXISTS (SELECT /*+PARALLEL(15)*/
         1
          FROM BBG_RA_ITEM_CUSTOM_V@RA_RMS_DBLINK C
         WHERE A.PROD_NUM = C.ITEM);
COMMIT;

SELECT * FROM RADM.W_PRODUCT_D T WHERE T.PROD_NUM = '800229318';

SELECT * FROM BBG_RA_ITEM_CUSTOM_V@RA_RMS_DBLINK;

SELECT *
  FROM RADM.W_PRODUCT_D T
 WHERE T.BBG_ITEM_PLACE_OF_ORIGIN IS NULL
   AND LENGTH(T.PROD_NUM) = 9
 ORDER BY T.W_UPDATE_DT DESC;
