--1.
CREATE TABLE RADM.JIN_T_TMP AS
SELECT *
FROM DBA_OBJECTS T;

DELETE RADM.JIN_T_TMP T WHERE T.OBJECT_ID IS NULL;
COMMIT;

--2.
ALTER TABLE RADM.JIN_T_TMP ADD CONSTRAINT PK_JIN_T_TMP PRIMARY KEY (CREATED, OBJECT_ID);
CREATE INDEX I_JIN_T_TMP ON RADM.JIN_T_TMP(OBJECT_ID, STATUS);

--3.
BEGIN
	DBMS_REDEFINITION.CAN_REDEF_TABLE('RADM','JIN_T_TMP',DBMS_REDEFINITION.CONS_USE_PK);
END;
/

--4.
CREATE TABLE RADM.JIN_P_TMP  PARTITION BY RANGE (CREATED)
(PARTITION P1 VALUES LESS THAN (TO_DATE('2014-01-01', 'YYYY-MM-DD')),
 PARTITION P2 VALUES LESS THAN (TO_DATE('2015-01-01', 'YYYY-MM-DD')),
 PARTITION P3 VALUES LESS THAN (TO_DATE('2016-01-01', 'YYYY-MM-DD')),
 PARTITION P4 VALUES LESS THAN (MAXVALUE))
 AS SELECT *
FROM DBA_OBJECTS T WHERE 1=2;

--5.
BEGIN  
  DBMS_REDEFINITION.START_REDEF_TABLE(  
       UNAME => 'RADM',   
       ORIG_TABLE => 'JIN_T_TMP',  
       INT_TABLE => 'JIN_P_TMP',  
       COL_MAPPING => 'OWNER OWNER,
                       OBJECT_NAME OBJECT_NAME,
                       SUBOBJECT_NAME SUBOBJECT_NAME,
                       OBJECT_ID OBJECT_ID,
                       DATA_OBJECT_ID DATA_OBJECT_ID,
                       OBJECT_TYPE OBJECT_TYPE,
                       CREATED CREATED,
                       LAST_DDL_TIME LAST_DDL_TIME,
                       TIMESTAMP TIMESTAMP,
                       STATUS STATUS,
                       TEMPORARY TEMPORARY,
                       GENERATED GENERATED,
                       SECONDARY SECONDARY,
                       NAMESPACE NAMESPACE,
                       EDITION_NAME EDITION_NAME,
                       SHARING SHARING,
                       EDITIONABLE EDITIONABLE,
                       ORACLE_MAINTAINED ORACLE_MAINTAINED',  
       OPTIONS_FLAG => DBMS_REDEFINITION.CONS_USE_PK);  
END;  
/  

--6.
DECLARE  
num_errors PLS_INTEGER;  
BEGIN  
  DBMS_REDEFINITION.COPY_TABLE_DEPENDENTS('RADM', 'JIN_T_TMP','JIN_P_TMP',  
   DBMS_REDEFINITION.CONS_ORIG_PARAMS, TRUE, TRUE, TRUE, TRUE, num_errors);  
END;  
/ 

--7.
select object_name, base_table_name, ddl_txt from DBA_REDEFINITION_ERRORS;

--8.
BEGIN  
  DBMS_REDEFINITION.FINISH_REDEF_TABLE('RADM', 'JIN_T_TMP','JIN_P_TMP');  
END;  
/

--9.

SELECT * FROM RADM.JIN_P_TMP;


SELECT * FROM RADM.JIN_T_TMP;
SELECT * FROM RADM.JIN_P_TMP;

DROP TABLE RADM.JIN_T_TMP;
DROP TABLE RADM.JIN_P_TMP;
