TRUNCATE TABLE RA_RMS.W_RTL_SLS_TRX_TMP_A_BAK;
INSERT /*+PARALLEL(16)*/ INTO RA_RMS.W_RTL_SLS_TRX_TMP_A_BAK
  SELECT * FROM RA_RMS.W_RTL_SLS_TRX_TMP_A;
COMMIT;

SELECT T.DAY_DT,
       T.ORG_NUM,
       T.SLS_TRX_ID,
       T.IT_SEQ_NUM,
       T.PROD_IT_NUM,
       T.PROMO_TYPE,
       T.TRX_QTY,
       T.TRX_AMT,
       T.DISC_AMT
  FROM RA_RMS.W_RTL_SLS_TRX_TMP_A_BAK T
 WHERE T.ORG_NUM = 120001
   AND T.PROD_IT_NUM IN ('100440011', '100128853')
 ORDER BY T.SLS_TRX_ID, T.IT_SEQ_NUM, T.PROMO_TYPE;

SELECT *
  FROM (SELECT V.DAY_DT,
               V.SLS_TRX_ID,
               V.IT_SEQ_NUM,
               MAX(V.TRX_AMT) TRX_AMT
          FROM RA_RMS.W_RTL_SLS_TRX_TMP_A_BAK V
         WHERE V.PROMO_TYPE IN ('50', '51', '52')
         GROUP BY V.DAY_DT, V.SLS_TRX_ID, V.IT_SEQ_NUM) S
				 WHERE S.SLS_TRX_ID=1599557019
				 AND S.IT_SEQ_NUM=4;
				 

