--1.
CREATE TABLE RADM.W_MCAL_DAY_D_FUTURE AS
SELECT * FROM RADM.W_MCAL_DAY_D T 
WHERE 1=2;
COMMIT;
--2.
SELECT * FROM RADM.W_MCAL_DAY_D ORDER BY 1;
--3.

--4.


SELECT * FROM RADM.W_MCAL_DAY_DV ORDER BY 1;

SELECT * FROM ALL_ALL_TABLES T WHERE T.table_name LIKE '%MCAL%';

SELECT * FROM RADM.W_MCAL_DAY_D ORDER BY 1;
SELECT * FROM RADM.W_MCAL_PERIOD_D ORDER BY 1;
SELECT * FROM RADM.W_MCAL_CAL_D;
SELECT * FROM RADM.W_MCAL_CONTEXT_G;
SELECT * FROM RADM.W_MCAL_DAY_DS;
SELECT * FROM W_MCAL_PERIOD_TMP ORDER BY 1;
SELECT * FROM CALENDAR;
