SELECT T.TRAN_DATE,
       T.LOCATION,
       SUM(T.TOTAL_COST) TOTAL_COST,
       SUM(T.TOTAL_RETAIL_IN) TOTAL_RETAIL_IN,
       SUM(T.TOTAL_RETAIL) TOTAL_RETAIL,
       SUM(T.COUPON_AMT_IN) COUPON_AMT_IN,
       SUM(T.COUPON_AMT) COUPON_AMT
  FROM CMX.CMX_DY_ST_D_SALE_SUM_CP T
 WHERE T.TRAN_DATE = DATE '2016-06-30'
 GROUP BY T.TRAN_DATE, T.LOCATION
 ORDER BY 1, 2;

SELECT T.TRAN_DATE,
       T.DEPT,
       SUM(T.TOTAL_COST) TOTAL_COST,
       SUM(T.TOTAL_RETAIL_IN) TOTAL_RETAIL_IN,
       SUM(T.TOTAL_RETAIL) TOTAL_RETAIL,
       SUM(T.COUPON_AMT_IN) COUPON_AMT_IN,
       SUM(T.COUPON_AMT) COUPON_AMT
  FROM CMX.CMX_DY_ST_D_SALE_SUM_CP T
 WHERE T.TRAN_DATE = DATE '2016-06-30'
   AND T.LOCATION = 120001
 GROUP BY T.TRAN_DATE, T.DEPT
 ORDER BY 1, 2;

SELECT L.日期,
       L.门店编码,
       L.商品编码,
       SUM(L.含券销售金额) 含券销售金额,
       SUM(L.不含券销售金额) 不含券销售金额,
       SUM(L.券折扣金额) 券折扣金额
  FROM cmx_wang_coupon_sale_t l
 where l.日期 = date '2016-06-30'
   and l.门店编码 = 120001
 GROUP BY L.日期, L.门店编码, L.商品编码
 ORDER BY 1, 2, 3;


