--1.ra_rms.w_rtl_org_d_tmp add column org_unit_id

--2.SDE_RetailLocationDimensionStoreTempLoad 

--3.

--4.

--5.


truncate table radm.c_load_dates;
SELECT * FROM RADM.W_RTL_ORG_FIN_D;
SELECT * FROM RADM.W_INT_ORG_ATTR_DS;
SELECT * FROM RADM.W_INT_ORG_ATTR_D;
SELECT * FROM RADM.W_INT_ORG_DS;
SELECT * FROM RABATCHER.W_INT_ORG_ATTR_DS_TMP;

SELECT * FROM RADM.W_INT_ORG_D T WHERE T.ORG_NUM=120201;
SELECT * FROM RADM.W_INT_ORG_ATTR_D T WHERE T.SCD1_WID=1690;
SELECT * FROM RADM.W_RTL_ORG_FIN_D T WHERE T.TSF_ENTITY_ID=301002;

SELECT * FROM V$SQL T WHERE T.SQL_FULLTEXT LIKE '%W_RTL_ORG_FIN_D%2017-01-08%' ORDER BY T.LAST_LOAD_TIME DESC;
