SELECT TO_CHAR(SALET.SALES_DATE, 'YYYY-MM-DD') AS 日期,
       SALET.STORE AS 门店编码,
       MAX((SELECT STORE_NAME FROM STORE WHERE STORE = SALET.STORE)) AS 门店名称,
       AVG((SELECT SUPPLIER_PARENT FROM SUPS WHERE SUPPLIER = SALET.SUPPLIER)) AS 一级供应商编码,
       MAX((SELECT S2.SUP_NAME
             FROM SUPS S1, SUPS S2
            WHERE S1.SUPPLIER = SALET.SUPPLIER
              AND S2.SUPPLIER = S1.SUPPLIER_PARENT)) AS 一级供应商名称,
       SALET.SUPPLIER AS 二级供应商编码,
       MAX((SELECT SUP_NAME FROM SUPS WHERE SUPPLIER = SALET.SUPPLIER)) AS 二级供应商名称,
       AVG(IM.DEPT) AS 大类编码,
       MAX((SELECT DEPT_NAME FROM DEPS WHERE DEPT = IM.DEPT)) AS 大类名称,
       IM.CLASS AS 中类编码,
       MAX((SELECT CLASS_NAME FROM CLASS WHERE CLASS = IM.CLASS)) AS 中类名称,
       MAX((SELECT BUSINESS_MODE
             FROM CMX_ITEM_LOC_INFO
            WHERE ITEM = SALET.ITEM
              AND LOC = SALET.STORE)) AS 经营方式,
       SUM(SALET.QTY) AS 销售数量,
       SUM(SALET.TOTAL_COST) AS 销售成本,
       SUM(SALET.TOTAL_RETAIL) AS 销售金额
  FROM CMX_SUPP_SALES SALET, ITEM_MASTER IM
 WHERE SALET.SALES_DATE BETWEEN TO_DATE(&PM_BDATE, 'YYYY-MM-DD') AND
       TO_DATE(&PM_EDATE, 'YYYY-MM-DD')
   AND SALET.ITEM = IM.ITEM
   AND SALET.SUPPLIER = '29001970'
 GROUP BY SALET.STORE,
          SALET.SUPPLIER,
          IM.CLASS,
          TO_CHAR(SALET.SALES_DATE, 'YYYY-MM-DD')
 ORDER BY TO_CHAR(SALET.SALES_DATE, 'YYYY-MM-DD'),
          SALET.STORE,
          SALET.SUPPLIER,
					IM.CLASS;
