INSERT INTO RABATCHER.BBG_RA_FUND_IT_LC_SUPP_DY_TMP T
  (PROD_IT_NUM,
   PROD_SC_NUM,
   PROD_CL_NUM,
   PROD_DP_NUM,
   PROD_GP_NUM,
   PROD_DV_NUM,
   PROD_IT_WID,
   PROD_SCD1_WID,
   PROD_SC_WID,
   PROD_CL_WID,
   PROD_DP_WID,
   PROD_GP_WID,
   PROD_DV_WID,
   ORG_NUM,
   ORG_DS_NUM,
   ORG_RG_NUM,
   ORG_AR_NUM,
   ORG_CH_NUM,
   ORG_WID,
   ORG_SCD1_WID,
   ORG_LC_WID,
   ORG_DS_WID,
   ORG_RG_WID,
   ORG_AR_WID,
   ORG_CH_WID,
   SUPPLIER_NUM,
   SUPPLIER_WID,
   DAY_DT,
   DT_WID,
   BBG_ITEM_LOC_WID,
   BBG_ITEM_LOC_SUPP_WID,
   FUND_NO,
   PROMO_MIX_ID,
   PROMO_EVENT_DISPLAY_ID,
   PROMO_TYPE_ID,
   FUND_METHOD,
   FUND_SOURCE,
   COST_CODE,
   FUND_AMOUNT_IN,
   FUND_AMOUNT,
   ETL_THREAD_VAL,
   INTEGRATION_ID,
   W_INSERT_DT,
   W_UPDATE_DT,
   BBG_REFERENCE_DO1,
   BBG_REFERENCE_DO2,
   BBG_REFERENCE_DO3,
   BBG_REFERENCE_DO4,
   BBG_REFERENCE_DO5,
   BBG_REFERENCE_FO1,
   BBG_REFERENCE_FO2,
   BBG_REFERENCE_FO3,
   BBG_REFERENCE_FO4,
   BBG_REFERENCE_FO5,
   BBG_REFERENCE_FO6,
   BBG_REFERENCE_FO7,
   BBG_REFERENCE_FO8,
   BBG_REFERENCE_FO9,
   BBG_REFERENCE_FO10)
  SELECT W_PRODUCT_D_RTL_TMP.PROD_IT_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_SC_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_CL_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_DP_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_GP_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_DV_NUM,
         W_PRODUCT_D_RTL_TMP.PROD_IT_WID,
         W_PRODUCT_D_RTL_TMP.PROD_SCD1_WID,
         W_PRODUCT_D_RTL_TMP.PROD_SC_WID,
         W_PRODUCT_D_RTL_TMP.PROD_CL_WID,
         W_PRODUCT_D_RTL_TMP.PROD_DP_WID,
         W_PRODUCT_D_RTL_TMP.PROD_GP_WID,
         W_PRODUCT_D_RTL_TMP.PROD_DV_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_DS_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_RG_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_AR_NUM,
         W_INT_ORG_DH_RTL_TMP.ORG_CH_NUM,
         W_INT_ORG_D_RTL_TMP.ORG_WID,
         W_INT_ORG_D_RTL_TMP.ORG_SCD1_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_LC_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_DS_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_RG_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_AR_WID,
         W_INT_ORG_DH_RTL_TMP.ORG_CH_WID,
         W_PARTY_ORG_D.SUPPLIER_NUM,
         W_PARTY_ORG_D.ROW_WID,
         W_MCAL_DAY_D.MCAL_DAY_DT,
         W_MCAL_DAY_D.ROW_WID,
         BBG_RA_ITEM_LOC_D.ROW_WID,
         NVL(BBG_RA_ITEM_LOC_SUPP_D.ROW_WID, -1),
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.FUND_NO,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.PROMO_MIX_ID,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.PROMO_EVENT_DISPLAY_ID,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.PROMO_TYPE_ID,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.FUND_METHOD,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.FUND_SOURCE,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.COST_CODE,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.FUND_AMOUNT_IN,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.FUND_AMOUNT,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.ETL_THREAD_VAL,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.INTEGRATION_ID,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.W_INSERT_DT,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.W_UPDATE_DT,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.BBG_REFERENCE_DO1,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.BBG_REFERENCE_DO2,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.BBG_REFERENCE_DO3,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.BBG_REFERENCE_DO4,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.BBG_REFERENCE_DO5,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.BBG_REFERENCE_FO1,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.BBG_REFERENCE_FO2,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.BBG_REFERENCE_FO3,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.BBG_REFERENCE_FO4,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.BBG_REFERENCE_FO5,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.BBG_REFERENCE_FO6,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.BBG_REFERENCE_FO7,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.BBG_REFERENCE_FO8,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.BBG_REFERENCE_FO9,
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.BBG_REFERENCE_FO10
    FROM RADM.BBG_RA_FUND_IT_LC_SUPP_DY_FS BBG_RA_FUND_IT_LC_SUPP_DY_FS,
         RADM.BBG_RA_ITEM_LOC_SUPP_D       BBG_RA_ITEM_LOC_SUPP_D,
         RADM.BBG_RA_ITEM_LOC_D            BBG_RA_ITEM_LOC_D,
         RABATCHER.W_PRODUCT_D_RTL_TMP     W_PRODUCT_D_RTL_TMP,
         RABATCHER.W_INT_ORG_DH_RTL_TMP    W_INT_ORG_DH_RTL_TMP,
         RADM.W_MCAL_DAY_D                 W_MCAL_DAY_D,
         RABATCHER.W_INT_ORG_D_RTL_TMP     W_INT_ORG_D_RTL_TMP,
         RADM.W_PARTY_ORG_D                W_PARTY_ORG_D
   WHERE (1 = 1)
     AND (BBG_RA_ITEM_LOC_SUPP_D.ITEM(+) =
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.PROD_NUM AND
         BBG_RA_ITEM_LOC_SUPP_D.LOC(+) =
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.ORG_NUM AND
         BBG_RA_ITEM_LOC_SUPP_D.SUPPLIER(+) =
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.SUPPLIER_NUM AND
         (BBG_RA_FUND_IT_LC_SUPP_DY_FS.DAY_DT BETWEEN
         BBG_RA_ITEM_LOC_SUPP_D.EFFECTIVE_FROM_DT(+) AND
         BBG_RA_ITEM_LOC_SUPP_D.EFFECTIVE_TO_DT(+)))
     AND (BBG_RA_ITEM_LOC_D.ITEM = BBG_RA_FUND_IT_LC_SUPP_DY_FS.PROD_NUM AND
         BBG_RA_ITEM_LOC_D.LOC = BBG_RA_FUND_IT_LC_SUPP_DY_FS.ORG_NUM AND
         (BBG_RA_FUND_IT_LC_SUPP_DY_FS.DAY_DT BETWEEN
         BBG_RA_ITEM_LOC_D.EFFECTIVE_FROM_DT AND
         BBG_RA_ITEM_LOC_D.EFFECTIVE_TO_DT))
     AND (W_PRODUCT_D_RTL_TMP.PROD_IT_NUM =
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.PROD_NUM AND
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.DAY_DT BETWEEN
         W_PRODUCT_D_RTL_TMP.SRC_EFF_FROM_DT AND
         W_PRODUCT_D_RTL_TMP.SRC_EFF_TO_DT)
     AND (W_INT_ORG_DH_RTL_TMP.ORG_NUM =
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.ORG_NUM AND
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.DAY_DT BETWEEN
         W_INT_ORG_DH_RTL_TMP.EFFECTIVE_FROM_DT AND
         W_INT_ORG_DH_RTL_TMP.EFFECTIVE_TO_DT)
     AND (W_MCAL_DAY_D.MCAL_DAY_DT = BBG_RA_FUND_IT_LC_SUPP_DY_FS.DAY_DT)
     AND (W_INT_ORG_D_RTL_TMP.ORG_NUM =
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.ORG_NUM AND
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.DAY_DT BETWEEN
         W_INT_ORG_D_RTL_TMP.EFFECTIVE_FROM_DT AND
         W_INT_ORG_D_RTL_TMP.EFFECTIVE_TO_DT)
     AND (W_PARTY_ORG_D.SUPPLIER_NUM =
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.SUPPLIER_NUM AND
         BBG_RA_FUND_IT_LC_SUPP_DY_FS.DAY_DT BETWEEN
         W_PARTY_ORG_D.EFFECTIVE_FROM_DT AND W_PARTY_ORG_D.EFFECTIVE_TO_DT)
