--事实表：BBG_RA_INVADJ_IT_LC_DY_F
--中间表：BBG_RA_INVADJ_IT_LC_DY_FS
--原表：  BBG_RA_INVADJ_IT_LC_DY_FV
--接口名：YJ_BBG_SDE_BBG_RA_INVADJ_IT_LC_DY_FS
SELECT * FROM YJ_BBG_RA_INVADJ_IT_LC_DY_FS;
SELECT * FROM BBG_RA_INVADJ_IT_LC_DY_FS;

SELECT * FROM  C_ODI_PARAM


