W_RTL_SUPPCM_IT_LC_DY_FS

SELECT * FROM ALL_ALL_TABLES T WHERE T.table_name LIKE '%SUPPCM%';

RABATCHER  E$_W_RTL_SUPPCMUF_LC_DY_TMP
RABATCHER.E$_W_RTL_SUPPCM_IT_LC_DY_TMP
RABATCHER  W_RTL_SUPPCMUF_LC_DY_TMP
RABATCHER.W_RTL_SUPPCM_IT_LC_DY_TMP
RADM  BBG_RA_SUPPCM_REF
RADM  W_RTL_SUPPCMUF_LC_DY_F
RADM  W_RTL_SUPPCMUF_LC_DY_FS
RADM  W_RTL_SUPPCMUF_LC_WK_A
RADM	W_RTL_SUPPCM_IT_LC_DY_F
RADM	W_RTL_SUPPCM_IT_LC_DY_FS
RADM	W_RTL_SUPPCM_IT_LC_WK_A

SELECT * FROM BBG_RA_SUPPCM_REF;


