CREATE TABLE A (A INT,AMT INT);
CREATE TABLE B (B INT,AMT INT);

SELECT * FROM A;
SELECT * FROM B;

TRUNCATE TABLE A;
TRUNCATE TABLE B;

DROP TABLE A;
DROP TABLE B;

INSERT INTO A VALUES(1,10);
INSERT INTO A VALUES(2,15);
INSERT INTO A VALUES(3,20);
INSERT INTO B VALUES(1,8);
INSERT INTO B VALUES(2,8);
INSERT INTO B VALUES(4,9);

SELECT B.B,A.AMT+B.AMT AMT FROM A,B WHERE A.A(+)=B.B;

SELECT * FROM A,B WHERE A.A=B.B(+);

SELECT A,NVL(A.AMT,0)+NVL(B.AMT,0) FROM A,B WHERE A.A=B.B;

SELECT B,NVL(A.AMT,0)+NVL(B.AMT,0) AMT FROM A,B WHERE A.A(+)=B.B
UNION
SELECT A,NVL(A.AMT,0)+NVL(B.AMT,0) AMT FROM A,B WHERE A.A=B.B(+);

SELECT A,NVL(A.AMT,0)+NVL(B.AMT,0) AMT FROM A FULL JOIN B ON A.A=B.B;

SELECT * FROM A FULL OUTER JOIN B ON A.A=B.B;
