select * from BBG_RA_INVTSF_IT_LC_DY_F t;
SELECT SUBSTR(TSF.DT_WID, 2, 6),
       T.ORG_NUM,
       TL.ORG_NAME,
       SUM(TSF.TRANSFER_COST)
  FROM BBG_RA_INVTSF_IT_LC_DY_F TSF,
       W_INT_ORG_D              F,
       W_INT_ORG_D              T,
       W_INT_ORG_D_TL           TL
 WHERE TSF.ORG_WID = F.ROW_WID
   AND TSF.TO_ORG_WID = T.ROW_WID
   AND T.ORG_NUM = TL.INTEGRATION_ID
   AND TSF.TRANSFER_TYPE_ID = 2
   AND TSF.BBG_REFERENCE_DO1 = 'IN'
   AND TSF.DT_WID BETWEEN '120130101000' AND '120130507000'
 GROUP BY SUBSTR(TSF.DT_WID, 2, 6), T.ORG_NUM, TL.ORG_NAME;

SELECT * FROM W_INT_ORG_D_TL;
SELECT * FROM W_INT_ORG_D;
